console/local.go

@alecthomas Not sure if this is what you were looking for, but here's a shot at cleaning up the output on start-up for the console
```bash
ftl serve ./examples/echo ./examples/time
warn:agent: Starting FTL local agent on http://127.0.0.1:8892
info:agent:time: Starting
info:agent:time: Extracting schema
info:agent:echo: Starting
info:agent:echo: Extracting schema
info:agent:echo: Compiling FTL module...
info:agent:time: Compiling FTL module...
info:agent:echo: Online
info:agent:echo: Online
info:agent:time: Online
info:agent:time: Online
info:agent:time: Online
info:agent:echo: Online
info:agent: Starting console dev server
info:agent:echo: Terminated by signal terminated
info:agent:time: Terminated by signal terminated
warn:agent:echo: Module exited, restarting: context canceled …
```

Send npm output to debug logger

---

agent/agent.go
common/plugin/serve.go
drive-go/drive.go
drive-go/server.go
observability/metrics.go

In particular this allows the drive-go plugin to bind clients to the context, as well as initialise OTEL, before the plugin starts serving.

refactor: allow plugin constructor to extend Context

---

observability/client.go
observability/interceptor.go
observability/logger.go

- Removed leftover example code with sleeps in it.
- Create a dedicated OTEL logger defaulting to only log errors, with a flag to change the default.
- Disable exporting to OTEL by default, with a flag to enable it. This eliminates most of the logging during development.

fix: make OTEL less chatty in development

---

controlplane/controlplane.go

This is just so the Runner exporter doesn't spam errors.

feat: add stub OTEL server impl in ControlPlane

---

agent/agent.go
controlplane/controlplane.go
internal/rpc/context.go
internal/rpc/headers/headers.go
observability/interceptor.go

The callee is added to the request headers by the ControlPlane before forwarding to the Runner.

feat: propagate verb callee through request headers

---

go.mod
observability/interceptor.go
observability/server.go

Fixes #61
```json
{
"scope": {
"name": "ftl"
},
"metrics": [
{
"name": "call.request.count",
"sum": {
"dataPoints": [
{
"attributes": [
{
"key": "ftl.dest.module",
"value": {
"stringValue": "time"
}
},
{
"key": "ftl.dest.verb",
"value": {
"stringValue": "time"
}
},
{
"key": "ftl.source.module",
"value": {
"stringValue": "echo"
}
},
{
"key": "ftl.source.verb",
"value": {
"stringValue": "echo"
}
},
{
"key": "ftl.verb.ref",
"value": {
"stringValue": "echo.echo"
}
}
],
"startTimeUnixNano": "1686677838768290000",
"timeUnixNano": "1686677844461099000",
"asInt": "1"
},
{
"attributes": [
{
"key": "ftl.dest.module",
"value": {
"stringValue": "time"
}
},
{
"key": "ftl.dest.verb",
"value": {
"stringValue": "time"
}
},
{
"key": "ftl.source.module",
"value": {
"stringValue": "time"
}
},
{
"key": …
```

Use better source and dest attributes for metrics

---

Dockerfile.runner
bin/hermit.hcl
cmd/ftl/cmd_deploy.go
common/moduleconfig/config.go
common/plugin/serve.go
common/plugin/spawn.go
examples/echo-kotlin/src/main/kotlin/ftl/echo/Echo.kt
internal/rpc/rpc.go
kotlin-runtime/ftl-plugin/src/main/kotlin/xyz/block/ftl/gradle/FTLPlugin.kt
kotlin-runtime/src/main/kotlin/xyz/block/ftl/Context.kt
kotlin-runtime/src/test/kotlin/xyz/block/ftl/ContextTest.kt
kotlin-runtime/src/test/kotlin/xyz/block/ftl/registry/RegistryTest.kt
runner/runner.go
scripts/ftl-dev

Kotlin deploys!
Modified how `ftl deploy` works such that the files to deploy are defined in `ftl.toml`. The Kotlin build populates the config appropiately, then `ftl deploy ./build` correctly deploys everything required.
Also removed Caddy from ftl-dev because in some situations it would 503 for 10-20 seconds before reconnecting. This doesn't occur when connecting directly to controllers.

feat: Kotlin deploys working

---

examples/echo/echo.go
go-runtime/compile/generate/external_module.go

BEFORE:
```bash
LOG_LEVEL=trace ftl go deploy -S $PWD -d ./examples/echo -m ./examples/time
...
debug: # github.com/TBD54566975/ftl/examples/time
debug: _modules/time/main.go:12:8: undefined: time
ftl: error: exit status 1
```
AFTER:
```bash
LOG_LEVEL=trace ftl go deploy -S $PWD -d ./examples/echo -m ./examples/time
...
info: Compiling
info: Uploaded 4e90f1e9e46d17c2c714e5882621454d46d9b9b1df9ba6eb7f37c8d462d3f6c5:main
info: Created deployment D01H7BX317P1B3VSN9W6VNG7FRZ
```
```bash
ftl call echo.echo '{"name": "wes"}'
{"message":"Hello, wes!!! It is 2023-08-08 18:03:14.176409 -0700 PDT!"}
```

Fix go echo example

---

backend/controller/internal/dal/events.go
console/client/src/features/log/LogsPage.tsx

With the new event setup, we were previously only returning log events that had a `request_key`. But many of the log events happen outside of a request context. For example, a new deploy won't have an associated `request_key`.
This PR makes request_key optional so we can get logs with and without the key.

Return logs without a request key

---

backend/controller/controller.go
backend/controller/internal/dal/dal.go
backend/controller/internal/dal/dal_test.go

Fixes #236 
The previous change was made to create the key earlier which would allow us to log entries about the deploy during the creation process, before it was in the db. This PR retains that and fixes the reported bug.
This could be simplified but we'll lose the ability to log is some spots before the db call.
Still need to figure out how to log a message after the deployment has been replaced. Currently getting:
```bash
controller | info: Created deployment wes D01H809K9G09THVB5Z0HAMST7RZ
controller | info: Replace deployment for: D01H809K9G09THVB5Z0HAMST7RZ
controller | failed to insert log entry: {2023-08-16 16:14:02.341002 -0700 PDT m=+17.468284876 info map[deployment:D01H80A18Z366G9P1F0Y9PNK77C] Created deployment wes D01H809K9G09THVB5Z0HAMST7RZ <nil>} :: error: ERROR: null value …
```

fix: Use existing deployment key if found during creation

---

backend/controller/internal/sql/conn.go
kotlin-runtime/ftl-plugin/src/main/kotlin/xyz/block/ftl/gradle/FTLPlugin.kt

Bash doesn't propagate SIGTERM to child processes.

fix: Kotlin replicas can be terminated now

---

backend/common/model/keys.go
backend/common/slices/slices.go
backend/controller/controller.go
backend/controller/internal/dal/dal.go
backend/controller/internal/dal/dal_test.go
backend/controller/internal/dal/notify.go
backend/controller/internal/sql/models.go
backend/controller/internal/sql/querier.go
backend/controller/internal/sql/queries.sql
backend/controller/internal/sql/queries.sql.go
backend/controller/internal/sql/schema/001_init.sql
go.mod
go.sum
scripts/ftl-run

Previously the routes for each request were retrieved via a databas query. This change introduces dynamic routing updates from triggers on the runners table.
For now this can be disabled with `ftl-controller --no-experimental-dynamic-routing-updates`.

feat: experimental dynamic routing updates

---

console/client/src/layout/IDELayout.tsx

BEFORE (notice the rows behind the filter bar):
AFTER:

Remove extra padding

---

console/client/src/layout/IDELayout.tsx
console/client/src/layout/Notification.tsx
console/client/src/providers/AppProviders.tsx
console/client/src/providers/notifications-provider.tsx
console/client/src/providers/schema-provider.tsx

Add new notification system to add notifications from anywhere

---

console/client/src/features/timeline/TimelineCall.tsx
console/client/src/features/timeline/TimelineDeployment.tsx
console/client/src/features/timeline/TimelineLog.tsx

Clean up spacing on timeline a bit

---

backend/controller/controller.go
cmd/ftl-go/main.go
scripts/integration-tests

Also update `integration-test` script to pull the supported platforms from the cluster before deploying.

fix: add flags to ftl-go for multi-platform support

---

console/client/src/features/modules/ModuleDetails.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelineFilterBar.tsx
console/client/src/features/verbs/VerbCalls.tsx
console/client/src/layout/Tabs.tsx
console/client/src/utils/style.utils.ts

Add cursor to tappable things. Clean up log levels

---

.mvn/maven.config
Bitfile
Makefile
examples/echo-kotlin/pom.xml
kotlin-runtime/ftl-generator/pom.xml
kotlin-runtime/ftl-runtime/pom.xml
pom.xml

[This][1] discussion is from 2017, but it seems to reflect the behaviour I was seeing, where running tests would not find the main source code, but re-running it would succeed. Disabling incremental compilation did in fact fix it, so...
[1]: https://discuss.kotlinlang.org/t/kotlin-compiler-incremental-not-copying-resources/5640

fix: disable Kotlin incremental compilation

---

console/client/package-lock.json
console/client/package.json
console/client/src/features/modules/ModulesPage.tsx
console/client/src/providers/AppProviders.tsx
console/client/src/theme/colors.js
console/client/src/theme/create-components.js
console/client/src/theme/create-palette.js
console/client/src/theme/create-shadows.js
console/client/src/theme/create-typography.js
console/client/src/theme/index.js
console/client/tsconfig.json

```ts
<Container maxWidth='sm' sx={{ m: 4 }}>
<Stack spacing={2}>
<Button variant='contained'>Sample MUI Button</Button>
<Button variant='contained'>Sample MUI Button</Button>
</Stack>
</Container>
```
Produces this UI:

feat: Add material UI and theme

---

Bitfile
backend/common/rpc/headers/headers.go
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/client/VerbServiceClient.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/client/grpc.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/main/main.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/server/Server.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/server/ServerInterceptor.kt
scripts/ftl-dev
scripts/ftl-run
scripts/integration-tests

As part of this, switched to using plain gRPC for client calls (rather than okhttp).
Also switched to using bit for builds in scripts. Bit has much better
dependency specificiation than make so, for example, when repeatedly
running integration tests, it won't constantly rebuild the JARs.

feat: propagate FTL headers through kotlin-runtime

---

console/client/src/components/CodeBlock.tsx
console/client/src/features/logs/LogLevelBadge.tsx
console/client/src/features/logs/LogLevelBadgeSmall.tsx
console/client/src/features/logs/log.utils.tsx
console/client/src/features/timeline/TimelineIcon.tsx
console/client/src/features/timeline/details/TimelineLogDetails.tsx
console/client/src/features/timeline/filters/FilterPanelSection.tsx
console/client/src/features/timeline/filters/LogLevelsFilter.tsx
console/client/src/features/timeline/filters/TimelineFilterPanel.tsx
console/client/src/utils/style.utils.ts
console/client/tsconfig.json

feat: Timeline style updates

---

backend/controller/internal/dal/dal.go
backend/controller/internal/sql/queries.sql
backend/controller/internal/sql/queries.sql.go
backend/controller/internal/sql/schema/001_init.sql

I believe this was being triggered when a controller creates a reservation transaction, issues the reservation to a runner, then dies before being able to complete the transaction. This leaves the runner in a state where it is telling controllers it's reserved, without having set a reservation_timeout, as the only place that was previously set was during the reservation transaction. The UpsertRunner calls were not setting this.
To work around this, and another potential issue, I've added two triggers:
1. When a runner is set to the reserved state with a NULL reservation_timeout, set it to a default of 2m.
2. Update runner.module_name whenever runner.deployment_id is set or unset.
Fixes #392

fix: case where a runner ends up reserved without a timeout

---

console/client/src/components/CodeBlock.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/services/console.service.ts

fix: request graph loading calls in reverse order

---

Bitfile
Dockerfile.controller
Makefile
backend/controller/controller.go
cmd/ftl-controller/main.go
console/local.go
console/release.go

Turns out, embedded files don't contain any filesystem metadata, which meant that ServeContent() caching was unable to function.

fix: use build timestamp for resources rather than embedded FS

---

console/client/src/services/console.service.ts

@alecthomas this should provide more detailed connect errors than just the error `code`. 
Although, I doubt we would have got more info with this specific `code 2` error since it's this 
```ts
/**
* Unknown error
*/
Unknown = 2,
```

fix: display full error message for connect errors

---

console/client/index.html
console/client/src/App.tsx
console/client/src/components/ButtonSmall.tsx
console/client/src/components/Card.tsx
console/client/src/features/deployments/DeploymentPage.tsx
console/client/src/features/deployments/DeploymentsPage.tsx
console/client/src/layout/Navigation.tsx

Super basic layout for displaying deployments

feat: starting on deployments page

---

console/client/src/App.tsx
console/client/src/components/PageHeader.tsx
console/client/src/features/deployments/DeploymentPage.tsx
console/client/src/features/modules/ModulePage.tsx
console/client/src/features/verbs/VerbPage.tsx

feat: Add stub pages for module and verb

---

console/client/src/features/modules/ModulePage.tsx
console/client/src/features/requests/RequestGraph.tsx
console/client/src/features/verbs/VerbPage.tsx

fix: clean up padding a bit with new layout

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/main/main.kt

chore: suppress debug logs from GRPC server in kotlin runtime

---

cmd/ftl/cmd_ps.go
cmd/ftl/cmd_status.go

Added JSON formatting w/ indents & line breaks for the ftl status output -- previously was a giant JSON all on one line

Improve `ftl status` output readability 

---

console/client/src/features/deployments/DeploymentPage.tsx

- Fixed issue where calls wouldn't reload on the deployments page
- Make calls buttons link to verb pages
- Add empty state for no calls

fix: call list reloading and button actions

---

backend/common/log/json.go
backend/common/plugin/spawn.go

Previously, anything that failed to decode would silently be converted to a text line. With this change, a line that fails to decode but looks like it is JSON will result in a warning.

fix(plugin): log JSON decoding errors for lines that appear to be JSON

---

backend/common/download/download.go
examples/echo-kotlin/pom.xml
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt

By adding the following fragment to the POM:
```xml
<execution>
<id>copy-dependencies</id>
<phase>compile</phase>
<goals>
<goal>copy-dependencies</goal>
</goals>
<configuration>
<outputDirectory>${project.build.directory}/dependency</outputDirectory>
<includeScope>runtime</includeScope>
</configuration>
</execution>
```
`ftl deploy ./target` will upload all dependencies as well as compiled source. This actually works super well in practice, and I think we can completely remove the need for building a custom `ftl-runner` Docker image.
One issue is that this now results in the runners having to download quite a few MB of artefacts on each deploy, but we can mitigate this by making the controller->runner artefact download process incremental too, and have each runner maintain its own cache. …

fix: include JAR dependencies in Kotlin deploys

---

examples/echo-kotlin/pom.xml
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
pom.xml

Then extend `ftl.toml` to use it. This fixes issues where older versions of JARs were shadowing newer versions because we were just file-system globbing the classpath.

fix: use Maven to output the correct classpath for user code

---

console/client/src/features/deployments/DeploymentPage.tsx

feat: add timeline to deployment page

---

backend/runner/runner.go
cmd/ftl/cmd_serve.go

Fixes #470 
```bash
ftl serve --help
Usage: ftl serve
Start the FTL server.
Flags:
-h, --help           Show context-sensitive help.
--version        Show version.
--config=FILE    Load configuration from TOML file.
--endpoint=http://127.0.0.1:8892
FTL endpoint to bind/connect to ($FTL_ENDPOINT).
--authenticators=HOST=EXE,…
Authenticators to use for FTL endpoints
($FTL_AUTHENTICATORS).
Logging:
--log-level=info    Log level ($LOG_LEVEL).
--log-json          Log in JSON format ($LOG_JSON).
Command flags:
--bind=http://localhost:8892
Starting endpoint to bind to and advertise to. Each
controller and runner will increment the port by 1
-c, --num-controllers=1    Number of controllers to start.
-r, --num-runners=10       Number of runners to start.
```

feat: add 'ftl serve' command for local dev

---

backend/common/bind/bind_allocator.go
backend/controller/controller.go
backend/controller/scaling/k8s_scaling.go
backend/controller/scaling/local_scaling.go
backend/controller/scaling/scaling.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_serve.go

feat: add auto scaling to `ftl serve`

---

backend/common/rpc/context.go
backend/common/rpc/rpc.go
backend/controller/scaling/local_scaling.go
cmd/ftl/cmd_serve.go

Also added `--recreate` flag to `ftl serve`.
Fixes #534
Before:
```
info:reconcileRunners: Removing runner: R00000000000000000000002000
warn:runner0: Stream handler failed, retrying in 100ms: context canceled
warn:runner0: Stream handler failed, retrying in 100ms: context canceled
error:reconcileRunners: Error starting runner: context canceled: context canceled
error:controller0: Streaming RPC failed: invalid_argument: protocol error: incomplete envelope: stream error: stream ID 3; CANCEL: /xyz.block.ftl.v1.ControllerService/RegisterRunner
```
After:
```
info:reconcileRunners: Removing runner: R00000000000000000000002000
error:controller0: Streaming RPC failed: invalid_argument: protocol error: incomplete envelope: stream error: stream ID 9; CANCEL: …
```

fix: suppress noisy log spam when scaling runners

---

Bitfile
backend/controller/scaling/localscaling/devel.go
backend/controller/scaling/localscaling/local_scaling.go
backend/controller/scaling/localscaling/release.go
cmd/ftl/cmd_serve.go
go-runtime/devel.go
internal/source_root.go

In development mode this will build the template directory first, in release mode it will embed a zip file containing the template directory.
Fixes #541

fix: embed runner template for `ftl serve`

---

examples/echo-kotlin/pom.xml
examples/online-boutique/services/ad-kotlin/pom.xml
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/ftl-runtime/pom.xml
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/SchemaExtractorRuleSetProvider.kt
kotlin-runtime/ftl-runtime/src/main/resources/META-INF/services/io.gitlab.arturbosch.detekt.api.RuleSetProvider
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
kotlin-runtime/scaffolding/pom.xml

feat: use detekt to extract kotlin schema

---

.github/workflows/ci.yml

For now this will just add comments to the PR, but once we've stabilised we should make it fail CI.

chore: add buf breaking change detection to CI

---

cmd/ftl/cmd_serve.go

Fixes #557 
We weren't setting the port correctly after a new db had been created.

fix: db port when `ftl serve` creates from scratch

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/registry/Registry.kt

The actual bug was in [this line](https://github.com/TBD54566975/ftl/blob/9d7030f310e3e12d98d943a268a09f78c8f1c700/kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/registry/Registry.kt#L63). This return statement bailed from the entire `registerAll()` function, rather than the `forEach` iteration as intended. The fix is directing the return with `return@forEach` — the rest of this PR is small cosmetic changes for readability.
This only affected modules compiled when other modules were active in the cluster because those contained generated stubs whose modules were annotated with `Ignore`, causing this return to execute.

fix kotlin verb registry

---

cmd/ftl/cmd_serve.go

Fixes #562 
Output when container is stopped:
```
ftl serve
info: Using docker container 'ftl-db' for postgres db
info: Postgres DSN: postgres://postgres:secret@localhost:5433/ftl-db?sslmode=disable
info: Starting 1 controller(s) and 0 runner(s)
```

fix: ftl serve auto start docker container

---

cmd/ftl/cmd_schema.go

Fixes #566 
Output:
```
ftl schema generate ~/dev/online_boutique/templates ~/dev/online_boutique/templates/api
ftl: error: destination directory /Users/wesbillman/dev/online_boutique/templates/api must not be inside the template directory /Users/wesbillman/dev/online_boutique/templates
```

fix: ensure code gen output is not inside template

---

examples/echo-kotlin/pom.xml
examples/online-boutique/services/ad-kotlin/pom.xml
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/scaffolding/pom.xml

for now, we can use the entire base directory as the input source for detekt type resolution. [i've submitted a change](https://github.com/Ozsie/detekt-maven-plugin/pull/214) against the `detekt-maven-plugin` we're using that will allow us to specify multiple input sources. once this goes through we can be more granular to explicitly use the source directory plus generated sources with the following config:
`<input>${project.basedir}/src/main/kotlin,${project.build.directory}/generated-sources/ftl</input>`

temporarily use base directory as source for detekt type resolution

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

Kotlin `extractIngress` was using the full path of the enum `Method.GET` instead of just the value `GET` This would put an ingress route in the db that wouldn't be found with our query.
Since it couldn't be found, all Kotlin ingresses would return `404 not found`
This is a quick change by pulling just the part of the string we want, but we may way a more robust solution the future.

fix: kotlin ingress was adding "Method"

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

Empty data classes can be defined in Kotlin as `typealias <ClassName> = Unit`

feat: allow empty data classes in kotlin schema

---

Bitfile
examples/echo-kotlin/pom.xml
examples/online-boutique/services/ad-kotlin/pom.xml
kotlin-runtime/ftl-runtime/pom.xml
kotlin-runtime/scaffolding/pom.xml
scripts/integration-tests

Instead we rely on classpath.txt to include everything we need.

fix: don't build ftl-runtime uber JAR

---

backend/common/moduleconfig/config.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/main.go

Fixes #597
This currently only supports building `kotlin` modules. `go` support will be added in the future.
I'm not 100% sure if this is the best way to activate `hermit` as part of the build but we can discuss.
Create new module and build:
```bash
ftl init kotlin services alice
ftl build services/ftl-module-alice
info: Building kotlin module 'alice'
info: Using build command 'source ../bin/activate-hermit && mvn compile'
```
With log-level=debug
```bash
ftl build services/ftl-module-alice --log-level=debug
info: Building kotlin module 'alice'
info: Using build command 'source ../bin/activate-hermit && mvn compile'
debug: ../bin/activate-hermit: line 61: /bin/hermit: No such file or directory
debug: ../bin/activate-hermit: line 20: /bin/hermit: No such file or directory
debug: Hermit …
```

feat: add `ftl build` command

---

cmd/ftl/cmd_schema.go

I was getting errors trying to run the `schema scaffold` command
BEFORE:
```
info: Watching /Users/wesbillman/dev/ftl-examples/frontend/mobile/templates
ftl: error: failed to write file: open lib/api/ftl_client.dart: no such file or directory
```
AFTER:
```
ftl schema generate templates src/api/
info: Watching /Users/wesbillman/dev/ftl-examples/frontend/web/templates
info: Generated 8 modules in src/api/
```

fix: schema scaffold copy errors

---

cmd/ftl/cmd_schema.go

Reverts TBD54566975/ftl#615
This needs a bit more thought. It's also copying the template files, which we won't want to do.

revert: "fix: schema scaffold copy errors"

---

.goreleaser.yaml
Bitfile
backend/common/rpc/context.go
backend/common/rpc/rpc.go
backend/common/rpc/server.go
cmd/ftl-controller/main.go
cmd/ftl-runner/main.go
cmd/ftl/cmd_serve.go
cmd/ftl/main.go
examples/go.mod
examples/online-boutique/go.mod
version.go

The FTL servers now return their version in response headers. We should do some "real" semver checking down the line, but for now a simple warning if the client is older than the server should be okay.
Fixes #625

feat: client logs a warning if its version is older than the server

---

kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/ftl-generator/src/test/kotlin/xyz/block/ftl/generator/ModuleGeneratorTest.kt

Before:
```kotlin
data class Foo(
val bar: String?,
)
```
After:
```kotlin
data class Foo(
val bar: String? = null
)
```

fix(kt): optional fields now default to null

---

backend/schema/schema_test.go
backend/schema/validate.go
go-runtime/compile/generate/external_module.go
go-runtime/compile/generate/external_module.go.tmpl

Previously the schema allowed module-relative VerbRef's and DataRef's with an empty module name to be persisted to the database. This change ensures that all *Ref's are fully qualified during validation.
This might need some changes to downstream consumers that relied on the previous behaviour.

fix: fully-qualify schema references

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
examples/online-boutique/common/money/money.go
examples/online-boutique/services/checkout/checkout.go
examples/online-boutique/services/currency/currency.go
examples/online-boutique/services/email/email.go
examples/online-boutique/services/payment/payment.go
examples/online-boutique/services/productcatalog/productcatalog.go
examples/online-boutique/services/shipping/shipping.go

This change loads all existing schemas, merges the current deployment's schema, then validates the entire schema together. This ensures only valid modules can be deployed to the cluster, but requires deployment in a specific order.

fix: validate full schema on deploy

---

cmd/ftl/cmd_build.go
examples/kotlin/pom.xml

This ensures the Kotlin builds are always using the latest version.
Fixes #669

feat: sync ftl version into pom.xml

---

backend/schema/jsonschema.go
backend/schema/jsonschema_test.go

The lookup for finding data in the `dataTypes` map was failing because the refs contained the full definition of the dataRef but the map only contained the `Module` and `Name` fields.
This was causing the console to fail with the following error when using `GetModules` which will build the `jsonSchema` for each module.
```
modules-provider.tsx:27 
POST http://localhost:8892/xyz.block.ftl.v1.console.ConsoleService/GetModules 500 (Internal Server Error)
modules-provider.tsx:32 ModulesProvider - Connect error: ConnectError: [unknown] unknown data type cart.Item
at errorFromJson (error-json.js:54:19)
at next (connect-transport.js:84:31)
at async Object.unary (connect-transport.js:50:20)
at async Object.getModules (promise-client.js:66:26)
at async fetchModules (modules-provider.tsx:27:25)
``` …

fix: normalize dataref in jsonschema lookup

---

go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go
go-runtime/sdk/call.go

FTL's schema requires all fields be in "lowerCamelCase", but the go-runtime has been encoding fields with the literal field name, usually resulting in "UpperCamelCase". This change adds a custom encoder (because there is seemingly no existing library that will do this).
Decoding should be fine because Go's JSON decoder is case-insensitive.
Fixes #705

fix: ensure Go runtime uses the correct field names without "json" tags

---

backend/controller/ingress/ingress.go

Fixes #709 
Most of this work was pushed directly to main 🤦 here: 9a80d004ee5b55b87fa801f5e4c946222300f79e
With a missing field (fails validation):
With a valid request:

fix: remove extra printfs and fix previous commit

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

If a verb to verb request object had multiple parameters the regex would capture the last found match. This would result in the matcher finding something like `ages = ...` instead of `TimeRequest`
With a call like this, the regex would find `ages = listOf(1, 2, 3)` for the `req` instead of `TimeRequest`
```kotlin
val response = context.call(TimeModuleClient::time, TimeRequest(name = req.name ?: "anonymous", ages = listOf(1, 2, 3)))
```

fix: kotlin schema extract request regex

---

backend/controller/controller.go
backend/schema/schema.go
backend/schema/validate.go

The previous change resulted in relative refs within a module not being written back to the schema before committing to the DB.

fix: validate module schema on deployment

---

backend/controller/controller.go
backend/schema/schema_test.go
backend/schema/validate.go

Also renamed builtin module to "builtin" from "ftl" so that imports are `ftl.builtin` rather than `ftl.ftl`.

fix: `{Get,Pull}Schema()` weren't returning builtin module

---

go-runtime/compile/build.go
go-runtime/sdk/config.go
go-runtime/sdk/config_test.go
go-runtime/sdk/secrets.go
kotlin-runtime/ftl-runtime/pom.xml
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/config/Config.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/config/ConfigTest.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/secrets/Secrets.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/secrets/SecretTest.kt
pom.xml

This currently loads from environment variables
`FTL_{CONFIG,SECRET}_<MODULE>_<KEY>`, which will eventually be delivered by the Runner.

feat: add (hacky) support for config and secrets

---

backend/common/rpc/context.go
integration/integration_test.go

They work locally, just not in CI. But I need to get a release out for project work, so I'll temporarily disable them.

fix: temporarily disable integration tests

---

cmd/ftl/cmd_init.go

0644 are the default perms for macOS

fix: ignore linting for file perms

---

cmd/ftl/cmd_dev.go

When the `ftl dev` command detects a schema change in any module, it will trigger a rebuild of all modules, including the one that caused the schema change.
This isn't ideal because we might end up rebuilding a single module twice (if it caused a schema change), but the logic is simple and rebuilds are fast.

fix: redeploy all modules on schema changes

---

CONTRIBUTING.md
backend/controller/ingress/ingress.go
backend/schema/protobuf.go
go-runtime/compile/build.go
go-runtime/encoding/encoding.go

- "v" was not passed through to go.mod (again)
- fixed use of bytes in request encoding

fix: some bugs

---

backend/controller/ingress/ingress_test.go
go-runtime/compile/build.go

- Don't write go.mod file if FTL version hasn't changed
- Write the file atomically to avoid corruption
Fixes #799

fix: two bugs with updating a module's go.mod file

---

cmd/ftl/cmd_serve.go

Fixes #783 
After running `docker kill ftl-db-1` the db would need to be started again.
In the previous code, we were only doing the health check on a new db, but we also need it for existing dbs to handle this error.
Here's an example of this working with some debug messages added for visibility:
```bash
docker kill ftl-db-1
```
```bash
ftl serve
info: Reusing existing docker container "ftl-db-1" on port "54320" for postgres db
info: Waiting for ftl-db-1 to be healthy
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is starting
warn: Container ftl-db-1 is …
```

fix: ftl serve health check existing dbs

---

backend/schema/schema.go
cmd/ftl/cmd_init.go
go-runtime/compile/build.go

Types like `AbstractRef[github.com/TBD54566975/ftl/protos/xyz/block/ftl/v1/schema.DataRef]` would return to the generate with `AbstractRef`
What we really want in the generator/templates is `DataRef` for this.

fix: AbstractRef typenames

---

go-runtime/sdk/config.go
go-runtime/sdk/secrets.go

We'll include referenced data structures in the schema at some point, but for now this will make it more convenient to use.

fix: allow secret and config values to be any type

---

backend/schema/metadataingress.go
backend/schema/parser.go
go-runtime/compile/parser.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
kotlin-runtime/ftl-runtime/pom.xml
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt

feat: support http-valid characters in ingress paths

---

integration/integration_test.go

I tried adding just `"m"` but it seemed to fail still. Not sure if that's expected or not @worstell

fix: add metadata to integration test

---

backend/controller/controller.go
backend/controller/ingress/ingress.go
examples/go/httpingress/httpingress.go

Basic support for different content-types on HTTP responses. This will need to be extended in the future, but is setup now to support `text/` types. This will definitely need more thought in the future.
This allows us to return HTML content from an HTTP ingress
```go
return builtin.HttpResponse[string]{
Status:  200,
Headers: map[string][]string{"Content-Type": {"text/html; charset=utf-8"}},
Body:    "<html><body><h1>HTML Page From FTL 🚀!</h1></body></html>",
}, nil
```

feat: add support for different content types

---

backend/schema/jsonschema.go

Displaying deployments and the graph was broken on the console
```
error: Unary RPC failed: unknown data type {/dev/ftl/examples/online-boutique/services/cart/cart.go:29:1 cart Item}: /xyz.block.ftl.v1.console.ConsoleService/GetModules
```

fix: console errors on jsonschema

---

backend/common/model/deployment_name.go
backend/common/model/request_name.go
backend/common/rpc/headers/headers.go
backend/controller/console.go
backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/dal/events.go
backend/controller/dal/notify.go
backend/controller/deployment_logs.go
backend/controller/observability.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql.go
backend/controller/sql/types.go
backend/runner/runner.go
backend/schema/schema.go
backend/schema/verb.go
examples/online-boutique/services/checkout/go.mod
examples/online-boutique/services/checkout/go.sum
examples/online-boutique/services/recommendation/go.mod
examples/online-boutique/services/recommendation/go.sum
go.mod
go.sum
protos/xyz/block/ftl/v1/mixins.go
sqlc.yaml

The types were moved into separate packages, so this upgrade couldn't be automated by Renovate.

chore: upgrade alecthomas/types

---

go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go

Without this, optional types (and others) weren't being encoding correctly.

fix: extend encoding to support stdlib marshaller interfaces

---

backend/controller/controller.go
backend/controller/ingress/ingress.go
backend/controller/ingress/ingress_test.go

feat: default response content type to json if not specified

---

.github/workflows/integration.yml
integration/integration_test.go
integration/testdata/go/database/echo.go
integration/testdata/go/externalcalls/echo.go
integration/testdata/go/httpingress/echo.go
integration/testdata/kotlin/database/Echo.kt
integration/testdata/kotlin/externalcalls/Echo.kt
integration/testdata/kotlin/httpingress/Echo.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/Database.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
kotlin-runtime/scaffolding/ftl-module-{{ .Name | lower }}/src/main/kotlin/ftl/{{ .Name | camel | lower }}/{{ .Name | camel }}.kt
scripts/integration-tests

refactors integration tests to execute identically across runtimes
with this change, we can also specify tests to run with the integration-test script (e.g. `integration-tests TestLifecycle` — all tests are fully encapsulated and can execute alone). providing no option will run all tests.
tests have been split into the following:
- TestLifecycle (init, deploy, call)
- TestHttpIngress (tests aliased fields and all http methods )
- TestDatabase
- TestExternalCalls (kotlin -> go call, kotlin -> kotlin call, etc. for all runtime permutations)
a couple small changes captured by the integration tests are also included in this PR:
- Database.kt converts module name and DB name to uppercase to align with the Go DB SDK
- Kotlin schema extractor includes module names for all DataRef schema objects, …

chore: parameterize integration tests

---

integration/integration_test.go
integration/testdata/kotlin/httpingress/Echo.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/registry/VerbHandle.kt

Fix kotlin integration tests.
Fix gson serialization with generic types.
Before this change, generic requests like `HttpRequest<GetRequest>` would serialize the `body` field to a map instead of the concrete type of the request.

fix: kotlin generic serialization and tests

---

cmd/ftl/cmd_dev.go

```bash
ftl dev --help
Usage: ftl dev [<base-dir>]
Watch a directory for FTL modules and hot reload them.
Arguments:
[<base-dir>]    Directory to watch for FTL modules
Flags:
-h, --help           Show context-sensitive help.
--version        Show version.
--config=FILE    Load configuration from TOML file.
--endpoint=http://127.0.0.1:8892
FTL endpoint to bind/connect to ($FTL_ENDPOINT).
--authenticators=HOST=EXE,…
Authenticators to use for FTL endpoints
($FTL_AUTHENTICATORS).
Logging:
--log-level=info    Log level ($LOG_LEVEL).
--log-json          Log in JSON format ($LOG_JSON).
Command flags:
--watch=500ms           Watch template directory at this frequency and regenerate
on change.
--failure-delay=5s      Delay before retrying a failed deploy.
--reconnect-delay=1s    Delay before …
```

feat: add flag to `ftl dev` to exit after deploying

---

backend/controller/ingress/ingress.go
backend/schema/builtin.go
backend/schema/data.go
backend/schema/data_test.go
backend/schema/jsonschema_test.go
backend/schema/parser.go
backend/schema/protobuf_dec.go
backend/schema/protobuf_enc.go
backend/schema/schema.go
backend/schema/typeparameter.go
go-runtime/compile/build.go
go-runtime/compile/schema.go

I originally intended to replace `DataRef` references to type parameters, with concrete `TypeParameter` instances, but this ended up conflating the parameter declaration and the reference. Instead, it's now left as a `DataRef`, and I've made `TypeParameter` no longer implement `Type`.
Note that it being a `DataRef` doesn't make much sense either, because it's not a data structure, but that's part of a large issue where data references can also refer to verbs within the schema parsing. The correct solution here is to use an untyped `Ref` everwhere and resolve these to the correct reference types when validating.

fix: monomorphising would fail under some circumstances

---

backend/controller/sql/databasetesting/devel.go

There seems to be a race between when the Docker PG healthcheck passes, and when the Docker port becomes available:
trace: exec: cd . && docker inspect --format \{\{.State.Health.Status}} ftl-db-1
debug: Postgres DSN: ***localhost:54320/ftl?sslmode=disable
ftl: error: failed to connect to `host=localhost user=postgres database=`: failed to receive message (unexpected EOF)
It's not clear if that's a deficiency in Docker, or perhaps pg_isready is only checking the Unix socket and not the TCP port, and there's some delay between the two becoming available. Either way, this should solve it.

fix: databasetesting.CreateForDevel() now tries to connect for 10s

---

backend/schema/module.go
backend/schema/schema_test.go

They were missing in the code gen for clients

fix: add imports for type parameter datarefs

---

backend/controller/controller.go

Instead of removing these log messages, I lowered them to `Debug` in case they are useful in the future. I can remove if that's preferred as well.

fix: reduce controller log warnings

---

examples/kotlin/ftl-module-ad/src/main/kotlin/ftl/ad/Ad.kt
examples/kotlin/ftl-module-api/src/main/kotlin/ftl/api/Api.kt
examples/kotlin/ftl-module-echo/src/main/kotlin/ftl/echo/Echo.kt
integration/testdata/kotlin/httpingress/Echo.kt
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/ftl-generator/src/test/kotlin/xyz/block/ftl/generator/ModuleGeneratorTest.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/HttpIngress.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/registry/RegistryTest.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/testdata/dependencies/TimeModuleClient.kt
kotlin-runtime/scaffolding/ftl-module-{{ .Name | lower }}/src/main/kotlin/ftl/{{ .Name | camel | lower }}/{{ .Name | camel }}.kt

chore: use HttpIngress instead of Ingress in kotlin

---

backend/schema/dataref.go
backend/schema/module.go
backend/schema/schema_test.go

It was returning nil previously, resulting in the Visit() function never visiting the type parameters and all sorts of things failing!

chore: implement DataRef.schemaChildren()

---

go-runtime/compile/build-template/go.work.tmpl

removes harcoded go version in autogenerated `go.work` files

fix: update go.work.tmpl to use .GoVersion rather than hard-coded version

---

examples/kotlin/ftl-module-api/src/main/kotlin/ftl/api/Api.kt
integration/integration_test.go
integration/testdata/go/httpingress/echo.go
integration/testdata/kotlin/database/Echo.kt
integration/testdata/kotlin/httpingress/Echo.kt
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/ftl-generator/src/test/kotlin/xyz/block/ftl/generator/ModuleGeneratorTest.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/ContextTest.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/testdata/dependencies/BuiltinModuleClient.kt

feat: use builtin.Empty instead of Unit typealias in Kotlin

---

backend/controller/ingress/ingress.go
backend/controller/ingress/request.go
backend/controller/ingress/response.go
integration/integration_test.go
integration/testdata/go/httpingress/echo.go
integration/testdata/kotlin/httpingress/Echo.kt

Some `go` examples:
```go
//ftl:verb
//ftl:ingress http GET /int
func Int(ctx context.Context, req builtin.HttpRequest[int]) (builtin.HttpResponse[int], error) {
return builtin.HttpResponse[int]{Body: req.Body}, nil
}
//ftl:verb
//ftl:ingress http GET /float
func Float(ctx context.Context, req builtin.HttpRequest[float64]) (builtin.HttpResponse[float64], error) {
return builtin.HttpResponse[float64]{Body: req.Body}, nil
}
//ftl:verb
//ftl:ingress http GET /bool
func Bool(ctx context.Context, req builtin.HttpRequest[bool]) (builtin.HttpResponse[bool], error) {
return builtin.HttpResponse[bool]{Body: req.Body}, nil
}
```

feat: add support for int, float, and bool on ingress

---

.github/workflows/workflow-next.yml
.github/workflows/workflow-roadmap.yml

- Clear triage label when moved to next
- Only add triage label on new tickets

chore: workflow tweaks

---

cmd/ftl/cmd_dev.go

Failed module builds will only retrigger if any of the following occur:
1. If the number of failed builds changes between one pass and the next. This is for the case when we're iteratively trying to bring up the entire graph.
2. If zero builds have succeeded. This catches the case where no builds are able to start initially because FTL isn't up yet.
3. Finally, if any files change in a module. This catches changes due to the normal development cycle.
I also decreased the failure delay, because we don't inifinitely spam rebuilds anymore.
Fixes #914

feat: improve `ftl dev` rebuild algorithm

---

examples/kotlin/pom.xml
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
kotlin-runtime/scaffolding/pom.xml

fixes #938
fixes #934
fixes #929
This change fixes the java class resolution issue in module POMs, but I still unfortunately haven't figured out how to do the same for unit tests run from `kotlin-runtime/ftl-runtime`. So, the change was validated locally instead of in unit tests.
with the given Echo.kt:
```
package ftl.echo
import ftl.builtin.Empty
import xyz.block.ftl.Context
import xyz.block.ftl.Verb
import java.time.OffsetDateTime
import java.util.ArrayList
import java.util.HashMap
class InvalidInput(val field: String) : Exception()
data class EchoRequest(val name: String?)
data class EchoResponse(
val message: String,
val time: OffsetDateTime? = null,
val arrayList: ArrayList<Empty> = ArrayList(),
val hashMap: HashMap<String, String> = HashMap()
)
@Throws(InvalidInput::class)
@Verb …
```

fix: kotlin schema extractor fixes

---

backend/controller/ingress/alias_test.go
backend/schema/field.go
backend/schema/schema_test.go
go-runtime/compile/schema_test.go

fix: JSON aliases can be any string, not just identifiers

---

.gitignore
buildengine/build.go
buildengine/build_go.go
buildengine/build_kotlin.go
buildengine/deps.go
buildengine/discover.go
buildengine/discover_test.go
buildengine/filehash.go
buildengine/topological_test.go
buildengine/watch.go
buildengine/watch_test.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_init.go
common/moduleconfig/moduleconfig.go
go-runtime/compile/build.go
go-runtime/encoding/encoding_test.go

This is just a pure move, with no logic changes.

refactor: move logic from cmd/ftl/cmd_build* into buildengine

---

cmd/ftl/cmd_serve.go

Example:
```sh
ftl serve --background && ftl status
info: FTL running in background with pid: 26990
error: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/Status
{
"controllers": [
{
"key": "C01HQBDJSK0C249VV2QBN3B856J",
"endpoint": "http://localhost:8892"
}
],
"runners": [
...
```
We'll probably want a way in the future to not print the `error` in the status request, but it shouldn't stop the Integration/CI flow from working here.

fix: make sure `ftl serve --background` waits for controller to start

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go

Local dev and integration tests were failing with this error:
```sh
panic: no RPC client in context
goroutine 1 [running]:
github.com/TBD54566975/ftl/internal/rpc.ClientFromContext[...]({0x101cb1038, 0x140005171d0?})
/Users/wesbillman/dev/ftl/internal/rpc/context.go:173 +0x88
github.com/TBD54566975/ftl/buildengine.buildGo({0x101cb1038, 0x140005171d0}, {{{0x14000156f60, 0x2a}, {0x140005206d8, 0x2}, {0x140005206dc, 0x4}, {0x140005206e0, 0x4}, ...}, ...})
/Users/wesbillman/dev/ftl/buildengine/build_go.go:17 +0x34
....
```
@alecthomas I'm not sure if you had another idea for setting the client on the context here, but wanted to get things passing again, so did this for now :)

fix: make sure client is in context before building

---

backend/controller/ingress/request_test.go
go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go
go-runtime/ftl/call.go
go-runtime/ftl/option.go
go-runtime/server/server.go
integration/integration_test.go

chore: implement encoding.Unmarshal

---

kotlin-runtime/external-module-template/go.mod

`|` is not supported in filenames retrieved by the Go toolchain, as Windows doesn't allow it in filenames. As we're zipping these files, this isn't a concern for us, but it's still prevented by Go. To work around this we create a dummy `go.mod` file which Go interprets as a separate module and thus ignores.
Ask me how I figured this out?
Fixes #991

fix: template directories must be ignored by Go

---

cmd/ftl/cmd_serve.go

Makes things easier for CI/testing so you don't have to check if the server is running before backgrounding each time.
```sh
ftl serve --recreate --stop --background && ftl deploy examples/go/time && ftl ps
info: `ftl serve` running in background with pid: 64997
info: Preparing module 'time' for deployment
info: Successfully created deployment time-af8f00d2bf
DEPLOYMENT                     REPLICAS
time-af8f00d2bf                1/1
```

fix: allow using --stop with --background to restart

---

cmd/ftl/cmd_serve.go

In some CI cases the timeout was too short. This will use a longer default + add the command line option

fix: allow timeout to be passed in for ftl serve

---

go-runtime/ftl/config.go
go-runtime/ftl/secrets.go

It will slightly more obvious that a ConfigValue can't be directly used as via `%s`.

fix: Secret/ConfigValue implement fmt.GoStringer now rather than fmt.Stringer

---

backend/controller/controller.go
frontend/local.go
frontend/release.go

I think a recent update to the buf connect stuff might have surfaced an issue with using `http://localhost:5173` for the console.

fix: update url output for the console

---

internal/log/configure.go
internal/log/plain.go

#1009
Adding `add --log-timestamps` include timestamps in terminal logs
Example
```
16:26:20 info: Starting FTL with 1 controller(s) and 0 runner(s)
16:26:20 warn: Detected change in +/Users/mtoohey/Code/ftl/examples/go/echo/go.sum, rebuilding...
16:26:20 error: Error deploying module /Users/mtoohey/Code/ftl/examples/go/echo. Will retry: module "time" not found
16:26:20 warn: Detected change in +/Users/mtoohey/Code/ftl/examples/go/time/time.go, rebuilding...
16:26:20 info:time: Building module
```

feat: add —log-timestamps option

---

buildengine/engine.go
buildengine/watch.go
cmd/ftl/cmd_dev.go

Still a bit more to do here + some testing, but wanted to push up progress.
```sh
ftl dev ../ftl-examples/online-boutique/backend/services examples/go --recreate
info: Starting FTL with 1 controller(s) and 0 runner(s)
info:cart: Building module
info:ad: Building module
info:currency: Building module
info:ad: Deploying module
info:cart: Deploying module
info:currency: Deploying module
info:controller0: Deployed currency-f4a032646d
info:controller0: Deployed time-ca2556f75d
info:controller0: Deployed cart-c9a2f125f9
info:controller0: Deployed ad-54a5b61320
info:shipping: Building module
info:payment: Building module
info:echo: Building module
info:productcatalog: Building …
```

feat: ftl dev now using buildengine

---

Justfile
common/configuration/1password.go

It turns out it's not actually a URI at all, so FTL's parser borks on it.

fix: encode op "URI" as base64

---

backend/controller/controller.go
backend/controller/scaling/localscaling/local_scaling.go
cmd/ftl/cmd_serve.go

Adds `--idle-runners` arg to define how large the idle pool should be.
Fixes #1036
Fixes #1030
Currently a draft because this PR makes #1036 more likely to be hit.
Before this change, killing all deployments would mean there are 0 runners, leading to no runner id collisions when you bring up more deployments
After this change, killing all deployments means that there will still be runners which will cause collisions if the idle runner ids aren't the lowest possible [`R00000000000000000000002000`, `R00000000000000000000004000` ... ]
I've been testing with a hacky fix replacing line `bankend/controller/scaling/local_scaling.go:96` to:
```
binary.BigEndian.PutUint32(ulid[10:], rand.Uint32())
```

feat: maintain idle pool of runners

---

cmd/ftl/cmd_dev.go
cmd/ftl/cmd_serve.go

fix: return error if ftl serve is already running

---

buildengine/engine.go

Fixes #1031
Introduces non-blocking deploys so that they can while other modules are build. 
BEFORE (20s cold, 11s warm):
AFTER (16s cold, 8s warm):

fix: parallelize deployments

---

backend/controller/controller.go
cmd/ftl/cmd_serve.go

fixes #1030
- Log level for failure to increase replicas depends on how many repeated attempts (error when >= 5)
- Increase default idle runners to 3

fix: reduce error logs for failure to increase replicas

---

Bitfile
backend/controller/scaling/localscaling/devel.go
deployment/db-migrate/schema
frontend/local.go

This was occurring because frontend/local.go was calling `npm install` explicitly on every run, resulting in changes to the frontend that invalidated some of the dependencies of the JAR file.
The fix is to use `bit` to build the frontend as well, resulting in its dependency cache being correct.

chore: fix for local dev rebuilding ftl-runtime.jar on every run

---

backend/controller/scaling/localscaling/devel.go
backend/runner/runner.go
cmd/ftl/cmd_config.go
cmd/ftl/cmd_secret.go
cmd/ftl/main.go
common/configuration/1password_provider.go
common/configuration/api.go
common/configuration/defaults.go
common/configuration/envar_provider.go
common/configuration/inline_provider.go
common/configuration/keychain_provider.go
common/configuration/manager.go
common/configuration/manager_test.go
common/configuration/projectconfig_resolver.go
common/projectconfig/merge.go
common/projectconfig/merge_test.go
examples/go/echo/go.mod
examples/go/echo/go.sum
go-runtime/ftl/config_test.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/secrets_test.go
go-runtime/server/server.go
go.mod
go.sum

This necessitated splitting the construction of the config resolver from the providers so that the configuration files can be specified at the global level.

feat: support configuration overrides

---

common/configuration/projectconfig_resolver.go

This writes only the configuration already in the "writable" configuration, rather than writing all merged configuration.

fix: config/secret override was writing merged configs

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

This caused a build failure because a symbol was added to the schema package which overrode an existing symbol, breaking the compile

fix: don't use wildcard imports in ExtractSchemaRule.kt

---

go-runtime/compile/errors.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/failing.go

Previously:
```
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:2:1: 
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:14:1: 
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:14:70: 
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:15:2: 
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:15:2: 
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:15:2: call must have exactly three arguments
```
Now:
```
/Users/alec/dev/ftl/go-runtime/compile/testdata/failing/failing.go:15:2: call must have exactly three arguments
```
Fixes #1062

fix(go-runtime): remove duplicate positional information in errors

---

backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

fixes #1046
Runners that were found to have died (rather than cleanly being killed) end up with deployment_id & module_name not set to null.
Changes:
- removes all dead runners from showing in the `ps` command
- correctly updates `deployment_id` and `module_name` to null in the following cases:
-  Runner terminates unexpectedly
-  Runner is stale

fix: ps cmd should ignore dead runners

---

.github/workflows/ci.yml
backend/controller/console.go
backend/controller/ingress/ingress.go
backend/schema/any.go
backend/schema/bool.go
backend/schema/bytes.go
backend/schema/config.go
backend/schema/data.go
backend/schema/database.go
backend/schema/enum.go
backend/schema/float.go
backend/schema/int.go
backend/schema/jsonschema.go
backend/schema/module.go
backend/schema/normalise.go
backend/schema/parser.go
backend/schema/protobuf_enc.go
backend/schema/secret.go
backend/schema/string.go
backend/schema/time.go
backend/schema/typeparameter.go
backend/schema/typeresolver.go
backend/schema/unit.go
backend/schema/validate.go
backend/schema/verb.go
buildengine/build_kotlin.go

Previously the two were conflated such that builtin types were treated as declarations, making some type switches much more verbose than necessary. The Decl type was also used to resolve types during symbol resolution, now the Symbol type is used for that, more closely matching its intended purpose.
Also fix a bug where linters weren't failing CI.

refactor: differentiate between symbols and declarations

---

cmd/ftl/cmd_dev.go
cmd/ftl/cmd_serve.go

I don't love this flow at the moment given how confusing the `--stop` flag can be to use, but this fixes the issue. Hopefully, as we nail down the ergonomics of how we want this to work we can help to avoid confusion in the future.
Without FTL running:
```sh
ftl dev --stop --recreate examples/go
info: Starting FTL with 1 controller(s)
...
```
If FTL is running in the background:
```sh
ftl dev --stop --recreate examples/go
info: `ftl serve` stopped (pid: 41006)
info: Starting FTL with 1 controller(s)
...
```

fix: ftl dev hanging with `--stop` flag

---

backend/controller/dal/dal.go
backend/controller/dal/events.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/001_init.sql
backend/controller/sql/types.go
internal/model/deployment_name.go
internal/model/deployment_name_test.go
sqlc.yaml

See also PR for renaming deployment name -> deployment key: [1080](https://github.com/TBD54566975/ftl/pull/1080)
Fixes: #1072

feat: deploymentname as struct

---

go-runtime/compile/build.go
internal/model/deployment_key.go

This isn't necessary to build, but VSCode doesn't like it.

fix: run go mod tidy on _ftl/go/modules too

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt

feat: extract configs/secrets in kotlin

---

backend/schema/any.go
backend/schema/array.go
backend/schema/bool.go
backend/schema/bytes.go
backend/schema/data.go
backend/schema/float.go
backend/schema/int.go
backend/schema/jsonschema.go
backend/schema/map.go
backend/schema/normalise.go
backend/schema/optional.go
backend/schema/parser.go
backend/schema/schema_test.go
backend/schema/string.go
backend/schema/time.go
backend/schema/typeresolver.go
backend/schema/typeresolver_test.go
backend/schema/unit.go
backend/schema/validate.go
backend/schema/validate_test.go

This vastly improves ingress schema validation, ensuring that the request/response body types are valid, and that if path parameters are used the request body is a data structure with a corresponding field.
cc @lifeizhou-ap

chore: improve ingress schema validation

---

buildengine/build.go
buildengine/build_go.go
buildengine/build_kotlin.go
buildengine/deps.go
buildengine/engine.go
buildengine/project.go
buildengine/watch.go
go-runtime/compile/build.go

Fixing some logs/errors so they are no longer printed like this one:
```
...failed to build "module circle": failed to extract module...
```

chore: clean up module and library logs

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_dev.go
cmd/ftl/main.go
common/configuration/projectconfig_resolver.go
common/projectconfig/merge.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go
common/projectconfig/testdata/ftl-project.toml
ftl-project.toml
go-runtime/ftl/config_test.go

Issue: https://github.com/TBD54566975/ftl/issues/1125

chore: dev cmd can read directories from project toml

---

buildengine/testdata/projects/lib/lib.go

No tests affected as it is only used for dependency & discovery tests

test: invalid return within external library

---

cmd/ftl/cmd_schema.go
cmd/ftl/cmd_schema_get.go

https://github.com/TBD54566975/ftl/issues/1090
```
ftl schema get --modules <modules>
eg: ftl schema get --modules time,echo
```
Allows filtering of schemas to the named modules.
If the input includes a module that was not found, it is returned as an error
The behaviour for these remains the same:
```
ftl schema
ftl schema get
```

feat: filter schemas by name

---

backend/schema/module.go
backend/schema/schema_test.go
go-runtime/compile/schema_test.go

https://github.com/TBD54566975/ftl/issues/1089
Ordering and spacing is the following (example has 2 of each declaration type)
```
{
config
config
secret
secret
database
database
enum
enum
data
data
verb
verb
}
```
Full example:
```
module echo {
config default String
config default2 String
secret default3 String
secret default3 String
// An echo request.
data EchoRequest {
name String? +alias json "name"
inner echo.EchoRequest2 +alias json "inner"
}
data EchoRequest2 {
name String? +alias json "name"
}
data EchoResponse {
message String +alias json "message"
inner echo.EchoResponse2 +alias json "inner"
}
data EchoResponse2 {
message String +alias json "message"
}
// Echo returns a greeting with the current time.
verb echo(echo.EchoRequest) echo.EchoResponse  
+calls time.time
verb …
```

chore: group declarations when printing module

---

buildengine/engine.go
cmd/ftl/cmd_dev.go
lsp/logger.go
lsp/lsp.go

https://github.com/TBD54566975/ftl/assets/51647/eddab587-ae5b-4786-99dd-92434b38d729

fix: parse out word for errors and clear them

---

backend/schema/errors.go
buildengine/build_go_test.go
buildengine/build_kotlin.go
buildengine/build_kotlin_test.go
buildengine/build_test.go
internal/exec/exec.go
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt
lsp/lsp.go

although we've temporarily suspended development on the kotlin runtime, this was a useful proof-of-concept to demonstrate how we can build non-Go runtimes to interact with the language server
fixes #1123
fixes #1159

feat: pass kotlin build errors to the language server

---

internal/cron/cron.go
internal/cron/cron_test.go
internal/cron/pattern.go

Built a cron implementation which will be used as part of our cron jobs feature (See: https://github.com/TBD54566975/ftl/pull/1155)
Splitting this off into this smaller PR to make things easier.

feature: cron implementation

---

backend/controller/ingress/alias.go
backend/controller/ingress/request.go
backend/controller/ingress/response.go
backend/schema/field.go
go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go

There should ideally be no relationship between the ingress encoder and the encoding package, but for now this is the simplest solution.
Fixes #1196

fix: ensure zero fields are included in ingress responses

---

CONTRIBUTING.md

Remove dead, irrelevant link that came from the original template.

docs: Remove dead link from contrib guide

---

backend/controller/console.go
backend/controller/dal/dal.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

Fixes #1200 
This introduces a new query to get deployments with `min_replicas > 0`. We could also modify some other existing queries if that's preferred.

fix: add query for getting deployments with replicas

---

backend/controller/controller.go
backend/schema/parser.go
backend/schema/schema.go
backend/schema/schema_test.go
backend/schema/validate.go

when deploying a module, we will only validate the deploying module's schema (but do so within the context of the greater schema).
this change prevents issues where a schema error outside of the deploying module prevents the deploy from succeeding—causing issues like #1211. now in combination with the buildengine logic, a change in the upstream module that breaks a downstream module will not prevent the upstream module from deploying (if the module still has a valid standalone schema). the deploy will succeed and then the subsequent deploy triggered for the downstream module will fail if the schema change from its dependency breaks it.
fixes #1211

fix: validate deploying module rather than entire schema

---

buildengine/engine.go

Fixes an issue where build errors would cancel the deploys for modules that build successfully.
For example, if we have `time` and `echo` (echo depends on time).
```sh
build: time
(time builds successfully)
deploy: time
build: echo
(echo fails to build)
>>> time's deploy ctx would get canceled here so it would never deploy
```
Then, we fix the build error in `echo`, but time never deployed and since it doesn't depend on `echo` it's never triggered to rebuild (unless a change to time is made).
This change introduces a `buildCtx` and `deployCtx` If there are any build failures we will report them after the deploys for successful builds complete.

fix: build errors canceling deploy contexts

---

backend/schema/errors.go
backend/schema/validate.go
buildengine/build.go
buildengine/build_go_test.go
buildengine/build_kotlin.go
go-runtime/compile/build.go
internal/errors/errors.go
lsp/lsp.go

This approach enables arbitrary runtimes to surface schema errors via proto. Go will use this approach for consistency across runtimes.
fixes #1207

feat: produce errors.pb during go schema extraction

---

common/configuration/api.go
examples/go/echo/echo.go
go-runtime/ftl/config.go
go-runtime/ftl/config_test.go
go-runtime/ftl/secrets.go
go-runtime/ftl/secrets_test.go

Rather than `ftl.Config[string]("foo").Get(ctx)` it is now `ftl.Config[string]("foo").Get()`.

feat: simplify config/secret API

---

CODEOWNERS

Update CODEOWNERS such that @alecthomas will be on PRs, and members of @TBD54566975/ftl-team will be assigned to PRs round-robin.

chore: change code review process

---

backend/controller/dal/dal.go
backend/controller/dal/notify.go
backend/controller/sql/migrate.go
backend/protos/xyz/block/ftl/v1/mixins.go
backend/runner/runner.go
cmd/ftl/cmd_schema_generate.go
cmd/ftl/cmd_schema_get.go
common/plugin/serve.go
common/plugin/spawn.go
go-runtime/compile/parser.go
internal/observability/client.go
internal/rpc/context.go

I think I was getting caught out by copilot mimicking nearby odd string interpolation, so I figured a clean up might help avoid it in the future.

chore: clean up string interpolation

---

backend/controller/controller.go
backend/controller/cronjobs/cronjobs.go
backend/controller/cronjobs/cronjobs_integration_test.go
backend/controller/cronjobs/cronjobs_test.go
backend/controller/cronjobs/state.go
backend/controller/dal/dal.go
backend/controller/scheduledtask/scheduledtask.go
backend/controller/scheduledtask/scheduledtask_test.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/schema/normalise.go
backend/schema/validate.go
backend/schema/validate_test.go
internal/model/cron_job.go
internal/model/verb_ref.go
sqlc.yaml

Separating into different PRs:
https://github.com/TBD54566975/ftl/issues/1141

feat: cron jobs

---

buildengine/build_go_test.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go

percolates errors up the chain of affected exports, e.g. if a type contains schema errors and is used in a verb schema, the errors will be highlighted in the type itself and the failing type will be highlighted in the verb that uses it

feat: chain schema errors in Go for the LSP

---

common/configuration/manager_test.go
common/configuration/projectconfig_resolver.go
common/configuration/projectconfig_resolver_test.go
common/configuration/testdata/ftl-project.toml
common/projectconfig/projectconfig.go

Fixes issue https://github.com/TBD54566975/ftl/issues/1174
Also tested manually by:
```
Open ftl-project.toml and confirm no module "echooo" is referenced
$ ftl config set --inline echooo.HILLBILLY JENKINS
Open ftl-project.toml and confirm this KV pair was added
$ rm ftl-project.toml
$ ftl config set --inline echooo.HILLBILLY JENKINS
Open ftl-project.toml and confirm this KV pair was added
Repeat for s/config/secret/
```

feat: If not already existant, create `ftl-project.toml` and/or module config or secret

---

backend/controller/controller.go

chore: decrease devel startup/reconciliation time

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/protos/xyz/block/ftl/v1/ftl.proto

Fixes issue https://github.com/TBD54566975/ftl/issues/1171
This PR includes some proto field deletions following the guidance here: https://protobuf.dev/programming-guides/proto3/#deleting
Manually tested `ftl serve` and `ftl status` (the two commands that reference `StatusRequest`) and got the desired output:
```
$ ftl status
{
"controllers": [
{
"key": "ctr-0-3lky7r59cey54xq",
"endpoint": "http://localhost:8892"
}
]
}% 
$ ftl serve --recreate
info: Starting FTL with 1 controller(s)
^C% 
$
```

feat: Remove runners and ingress from dal GetStatus

---

buildengine/deps.go
buildengine/engine.go
buildengine/watch.go

Fixes #1210 
This required a bit of a refactor to use pointers for `Module` and `ExternalLibrary` here. Hopefully, that's ok.
Example of rapid changes getting skipped. Note that I logged skips in `Warnf` just to highlight for this screenshot. Real skip messages are logged at `Debugf`

fix: skip out of date file changes

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/protos/xyz/block/ftl/v1/ftl.proto

Fixes issue https://github.com/TBD54566975/ftl/issues/1171
Generated file changes produced by running `./bin/sqlc generate`
Manually tested by running `ftl status` and `ftl serve`, the two commands that use `GetStatus()` via `StatusRequest`:
1. In tab 1, ran `ftl dev ./examples/go`. Confirmed everything started as expected.
2. Opened a new tab 2, ran `ftl status`. Confirmed everything got returned.
3. Went back to tab 1, Ctrl+C.
4. Went back to tab 2 and ran `ftl status` again. Confirmed got `ftl: error: unavailable: dial tcp 127.0.0.1:8892: connect: connection refused`.
5. Went back to tab 1 and ran `ftl serve`. Confirmed serving executed as expected.
6. Went back to tab 2 and ran `ftl status` again. Confirmed everything got returned again.

GetStatus() should always return just the active controllers/runners/ingress paths

---

buildengine/watch_test.go

increasing the watch period frequency relative to the test sleep periods, in case we're encountering races causing the flakiness

fix: maybe fix flaky watch test

---

go-runtime/ftl/singleton.go
go-runtime/ftl/singleton_test.go

Fixes issue https://github.com/TBD54566975/ftl/issues/1295

feat: Create Singleton func for convenient singleton construction

---

.golangci.yml

I was getting these warnings when running go linting.
```sh
./bin/golangci-lint run
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
```

chore: fix linter warnings in terminal

---

backend/protos/xyz/block/ftl/v1/ftl.proto
backend/schema/validate.go
backend/schema/validate_test.go
buildengine/engine.go

We don't have access to the full schema at this point, so we can't validate that external types exist
Fixes #1298

fix: skip validation on external req/resp types

---

go.mod
go.sum
renovate.json

It has been found that when version 1.16.0 of connectrpc is used, that there can be duplicate headers present which results in malformed headers when using FTL in an environment where it communicates through an Envoy sidecar.
This change downgrades to 1.14.0 as that is a known good version, and it also prevents the renovate bot from updating this dependency.

fix: Resolve Header Duplication

---

backend/controller/cronjobs/cronjobs_integration_test.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/one/one.go
integration/testdata/go/database/echo.go

fixes integration tests on main.
`modulecontext` was not passing along DSNs to modules because the schema never included the database declaration in the schema.

feat: extract database into schema for go

---

cmd/ftl/cmd_dev.go

Fixes https://github.com/TBD54566975/ftl/issues/1167
Manually tested:
```
$ ftl dev --stop --no-serve ./examples/go --log-level=trace
trace: Loading config from /Users/dli/Development/ftl/ftl-project.toml
debug: FTL serve is not running in the background
$ ftl serve --background
info: `ftl serve` running in background with pid: 42320
$ ftl dev --stop --no-serve ./examples/go --log-level=trace
trace: Loading config from /Users/dli/Development/ftl/ftl-project.toml
info: `ftl serve` stopped (pid: 42320)
```

fix: return early from ftl dev when incompatible flags (--stop --no-serve) are used

---

backend/controller/controller.go
backend/controller/module_context.go
backend/controller/module_context_test.go
internal/slices/slices.go

It's preferable to pass only exactly what's needed into a function. In this case it was receiving a full slice of modules, and a module name, and only allowing a single entry.

chore: simplify moduleContexttoProto

---

go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/failing.go

Contributes to one part of https://github.com/TBD54566975/ftl/issues/1121

fix: check for duplicate configs and secrets within a module

---

cmd/ftl/cmd_serve.go

Fixes https://github.com/TBD54566975/ftl/issues/1170
The new terminal output, when I force an error to return from `runInBackground`, looks like:
```
$ build/release/ftl serve --background
ftl: error: mock error!
```

fix: runInBackground returns error

---

backend/schema/validate.go
backend/schema/validate_test.go

Fixes https://github.com/TBD54566975/ftl/issues/1121
* Addresses comments in PR https://github.com/TBD54566975/ftl/pull/1336
* Adds additional duplication error case for configs/secrets with the same name but different types, which also simplifies the overall validation logic

fix: simplify config/secret duplication validation logic

---

common/configuration/in_memory_provider.go
common/configuration/in_memory_resolver.go
common/configuration/manager.go

fixes https://github.com/TBD54566975/ftl/issues/1339

fix: fall back to global secrets was not working

---

backend/schema/validate_test.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/failing.go

Fix a bug I introduced in prior PRs for https://github.com/TBD54566975/ftl/issues/1121
In the go-runtime validation, we would previously error if a secret and config had the same name. This fixes that error and adds tests to ensure we don't rebreak this either in the go-runtime nor on the backend.

fix: go-runtime extraneous secret/config duplication error

---

buildengine/discover_test.go
buildengine/filehash.go
buildengine/filehash_test.go
buildengine/testdata/projects/highgoversion/go.mod
buildengine/watch.go
common/moduleconfig/moduleconfig.go
common/moduleconfig/moduleconfig_test.go
common/moduleconfig/testdata/imports.go

fix: watch for changes in replace paths

---

backend/controller/controller.go
backend/controller/dal/lease_test.go

Because a lease is required to run it, and if the lease is stale it will never be expired. This is a quick workaround by making the task parallel, but we should fix this probably by making the task use the hash ring.

fix: expireStaleLeases can't be singleton

---

backend/controller/cronjobs/cronjobs_test.go
backend/controller/cronjobs/cronjobs_utils_test.go

mockDal's `attemptCountMap` was being read without getting a lock

chore: fix race condition in cron tests

---

go-runtime/ftl/config.go
go-runtime/ftl/database.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/secrets.go

Get rid of any chance of:
- Mistyping a secret/config when writing a unit test
- Passing in the wrong value type when passing in a secret/config in a unit test
```
func TestEcho(t *testing.T) {
ctx := ftltest.Context(
ftltest.WithConfig(defaultName, "helloworld"),
ftltest.WithSecret(secretKey, "shhhhh"),
ftltest.WhenVerb(time.Time, func(ctx context.Context, req time.TimeRequest) (time.TimeResponse, error) {
return time.TimeResponse{Time: stdtime.Now()}, nil
}),
)
...
}
```
Other changes:
- `ftl.Database` holds its db type
- `ftl.ConfigValue` and ftl.SecretValue embeds Ref rather than holding private module+name fields

fix: test context strictly enforces names and types

---

.github/workflows/ci.yml
.github/workflows/writecache.yml
Justfile

don't build kotlin when running just build-all
follow up from #1364 with stuff that was missed

chore: disable kotlin tests/releases

---

buildengine/build_go_test.go
buildengine/engine_test.go
buildengine/testdata/projects/another/another.go
buildengine/testdata/projects/other/other.go
examples/go/time/time.go
go-runtime/compile/external-module-template/_ftl/go/modules/{{ range .NonMainModules }}{{ push .Name . }}{{ end }}/external_module.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/two/two.go
integration/actions_test.go
integration/integration_test.go
integration/testdata/go/notexportedverb/ftl.toml
integration/testdata/go/notexportedverb/go.mod
integration/testdata/go/notexportedverb/go.sum
integration/testdata/go/notexportedverb/notexportedverb.go
kotlin-runtime/external-module-template/target.tmpl/generated-sources/ftl/{{ range .ExternalModules }}{{ push .Name . }}{{ end }}/{{ .Name | camel }}.kt

fix: ignore non-exported decls in codegen

---

backend/schema/database.go
backend/schema/schema_test.go
backend/schema/validate_test.go
go-runtime/compile/schema_test.go

displaying attributes after the resource identifier for consistency with other resources

fix: display db type after 'database'

---

backend/schema/normalise.go
backend/schema/schema_test.go

Clearing the Pos was made redundant by the addition of `assert.Exclude[T]()`, so now we just need to clear the unnecessary bool flags which is much less work.

refactor: remove most of Normalise()

---

backend/controller/controller.go
go-runtime/ftl/call.go
go-runtime/ftl/config_test.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/secrets_test.go
go-runtime/modulecontext/from_environment.go
go-runtime/modulecontext/from_environment_test.go
go-runtime/modulecontext/from_proto.go
go-runtime/modulecontext/module_context.go
go-runtime/modulecontext/to_proto.go
integration/testdata/go/wrapped/wrapped_test.go

fixes: https://github.com/TBD54566975/ftl/issues/1398
Now a ModuleContext is built using the following functions:
- `New(moduleName)`
- `func (m ModuleContext) Update(configs map[string][]byte, secrets map[string][]byte, databases map[string]Database) ModuleContext`
- `func (m ModuleContext) UpdateForTesting(mockVerbs map[schema.RefKey]MockVerb, allowDirectVerbBehavior bool) ModuleContext`
- `func (m ModuleContext) UpdateFromEnvironment(ctx context.Context) (ModuleContext, error)`
- (this one will still be split up and changed in an upcoming PR)
`ftltest` now uses `ftltest.Options` as an opaque way of building up state to then create a ModuleContext with the above functions. Before we were passing around `context.Context` and mutating the ModuleContext directly each anything was changed. …

fix: module context should be immutable

---

backend/controller/controller.go
go-runtime/ftl/config_test.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/secrets_test.go
go-runtime/modulecontext/from_environment.go
go-runtime/modulecontext/from_environment_test.go
go-runtime/modulecontext/from_proto.go
go-runtime/modulecontext/module_context.go
go-runtime/modulecontext/module_context_test.go

Previously, ModuleContext had fields of maps which could be still be mutated.
Now we make a Builder which is a type alias of ModuleContext, which has all the mutating functions, and a Built() func that deep copies the builder and returns it as a ModuleContext.

fix: modulecontext no longer accidentally mutable

---

.github/workflows/integration.yml

Two changes:
- CI looks in `intergration` and `backend/controller/cronjobs` directories for integration tests
- Filters files by ones that include `//go:build integration`
```
$ echo "matrix={\"test\":$(jq -c -n '$ARGS.positional' --args $(grep -r -l '^//go:build integration' integration backend/controller/cronjobs | xargs grep '^func Test' | awk '{print $2}' | cut -d'(' -f1))}"
matrix={"test":["TestCron","TestLifecycle","TestInterModuleCall","TestDatabase","TestSchemaGenerate","TestHttpIngress","TestServiceWithRealDal"]}
```

chore: ci uses integration tag to find tests

---

go-runtime/ftl/call.go
go-runtime/ftl/ftltest/ftltest.go
internal/modulecontext/module_context.go

fixes https://github.com/TBD54566975/ftl/issues/1401
Now the logic is:
- `call.go` asks `modulecontext` for any custom behaviour for a verb
- `modulecontext` responds with a `VerbBehavior` if it wants anything custom to happen (mocks, direct calls, specialised unit test errors)
- `call.go` calls `Call(...)` on the `VerbBehavior` if one is returned. Otherwise it calls the controller itself.
- I think it's best that modulecontext isnt responsible for implementing that behavior, though it does make sense for modulecontext to implement the custom behaviors

fix: custom verb behaviors implement behaviors

---

go-runtime/ftl/ftltest/ftltest.go

Catches an edge case where the working directory changes between when the relative path is passed in and when the inner function is executed

fix: convert to absolute path immediately incase test changes dirs

---

go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go
go-runtime/ftl/option.go
go-runtime/ftl/option_test.go

This PR:
* Rips out the existing textMarshaler and jsonMarshaler usage from encoding.go. We may want to add those back for https://github.com/TBD54566975/ftl/issues/1296 down the road, but we will need to be thoughtful about how we do that. Removing it for now keeps the logic much more predictable.
* Moves the (un)marshaling logic for `ftl.Option` out of `option.go` and into `encoding.go`.
* Special-cases both `time.Time` (the only stdlib type we currently support) and `ftl.Option`. Also `json.RawMessage` for _just_ encoding to preserve the existing `omitempty` behavior.
* Fixes some existing issues where the Pointer unmarshaling wasn't actually working correctly
* [eww] Adds a rather grotesque alternative to `Peek()` in `isNextTokenNull()` because json Decoder does not support Peek. 
* …

fix: fix several go-runtime JSON encoding issues

---

backend/controller/ingress/handler_test.go
go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go
go-runtime/ftl/option.go
go-runtime/ftl/option_test.go

un-reverts @deniseli's prior [change](https://github.com/TBD54566975/ftl/pull/1417/files) with some adjustments
- optional fields remain private
- pointers not supported

feat: internal encoder updates

---

go-runtime/ftl/map.go
go-runtime/ftl/map_test.go

fixes https://github.com/TBD54566975/ftl/issues/1390
`ftl.Map` was just using `once` as an optimisation.
But this unit test case was not being handled properly:
```
ctx := ftltest.Context(
ftltest.WithConfig(example, "hello"),
)
//Call a verb that uses ftl.Map with example config
resp, err := Verb(ctx, req)
ctx = ftltest.Context(
ftltest.WithConfig(example, "world"),
)
//When this execution of the verb is done, it should execute again because the underlying value is different (hello -> world)
resp, err = Verb(ctx, req)
```
To solve this, now the mapping func is called each time.
For use cases where modules want to map a `*sql.DB` to a `DAL`, it will create a new DAL instance each time

fix: remove once in ftl.Map to allow changing underlying values

---

go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go

Fixes https://github.com/TBD54566975/ftl/issues/1262

feat: support omitempty in custom json de/encoder

---

go-runtime/ftl/ftltest/ftltest.go
integration/actions_test.go
integration/integration_test.go
integration/testdata/go/database/database_test.go
integration/testdata/go/database/go.mod
integration/testdata/go/database/go.sum

```
ftltest.Context(
ftltest.WithDatabase(dbHandle),
)
```
This new option does the following:
- reads the existing DSN but appends `_test` to the table name
- clears out all tables in the db's public schema
Integration test `TestDatabase()` has been updated to have real and test db set up, with a deployment writing to the real db and unit tests running on a test db.

feat: add ftltest.WithDatabase(…) to get a clean test db

---

go-runtime/ftl/ftltest/ftltest.go
integration/actions_test.go
internal/modulecontext/from_environment.go
internal/modulecontext/from_environment_test.go

This centralises the DSN envar name format, and hopefully makes it easier to move away from envars soon.

chore: expose getter/setter for DSN envars

---

buildengine/discover.go
buildengine/discover_test.go
buildengine/engine.go
buildengine/watch.go
buildengine/watch_test.go

Steps were sometimes being hit by `TestWatch`:
- `ftl init ...` scaffolds a go.mod file with the ftl version set to `latest`
- `discoverModules` finds the module, looks in the go.mod file for replacements to follow (newish behavior) but errors when it can't parse the file with `latest` (expects `v_._._`)
- watcher ignores this error and believes the new module list (empty)
- watcher sends events saying all known modules have been removed
I added this behavior to ignore the error when discovering modules & external libraries in watcher... But I don't remember why. Looks like a mistake now.
Related to https://github.com/TBD54566975/ftl/issues/1419

fix: watcher should not remove all modules on error

---

backend/controller/ingress/handler_test.go
backend/controller/ingress/response.go
go-runtime/encoding/encoding.go

Fixes https://github.com/TBD54566975/ftl/issues/1439
Alec was right - the `[]byte` array was the right solution here! The response does come back encoded the same way it was when it was typed `json.RawMessage`. I confirmed in `backend/controller/ingress/handler_test.go` (which would fail if we made the `encoding.go` change without the `response.go` change) and also cleaned up the test a bit.

fix: replace json.RawMessage with underlying []byte type in ingress response

---

backend/controller/controller.go
frontend/local.go

Fixes #1453 
```sh
build/release/ftl dev examples/go --recreate
info: Starting FTL with 1 controller(s)
info:controller0: Web console available at: http://localhost:8892/
info: FTL startup command ⚡️
```

fix: logging of console web url

---

go-runtime/ftl/option.go

We used to support ftl.Option in normal json decoding, but was removed here in this PR: [feat: Handle sum types in backend encoder (](https://github.com/TBD54566975/ftl/commit/76ae43c4bd6e20bd65639c5bd71b24ab7bd46793)
Now the issue is this use case that PFI has: They make external API requests and unmarshal the responses into ftl types, like this one:
```
type RecipientAddressResponse struct {
ID          uuid.UUID                 `json:"id"`
Chain       Chain                     `json:"chain"`
Address     string                    `json:"address"`
Description string                    `json:"description"`
AddressTag  ftl.Option[string]        `json:"addressTag,omitempty"`
Currency    ftl.Option[Currency]      `json:"currency"`
Status      BizRecipientAddressStatus `json:"status"`
}
``` …

fix: bring back json marshal support for ftl.Option

---

backend/controller/ingress/handler_test.go
backend/controller/ingress/response.go
go-runtime/encoding/encoding.go

Reverts TBD54566975/ftl#1454
Tragedy strikes! This is breaking the http ingress integration tests (TestHttpIngress and TestHttpEncodeOmitempty) - all the status codes are getting set to 500. Reverting for now

revert: "fix: replace json.RawMessage with underlying []byte type in ingress response"

---

integration/integration_test.go
integration/testdata/go/omitempty/omitempty.go

```
$ just integration-tests TestHttpEncodeOmitempty
=== RUN   TestHttpEncodeOmitempty
INFO: Building ftl
/Users/dli/Development/ftl/integration/harness_test.go:143: debug: go build -o build/release/ftl -tags release -ldflags '-X github.com/TBD54566975/ftl.Version=0.207.1-5-ge8fdce90-dirty -X github.com/TBD54566975/ftl.Timestamp=1715296195' ./cmd/ftl
INFO: Starting ftl cluster
INFO: Waiting for controller to be ready
/Users/dli/Development/ftl/integration/harness_test.go:143: debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/Status
/Users/dli/Development/ftl/integration/harness_test.go:143: debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: …
```

fix: unbreak ci - omitempty integration test

---

go-runtime/ftl/ftltest/ftltest.go
internal/modulecontext/database.go
internal/modulecontext/module_context.go

fixes https://github.com/TBD54566975/ftl/issues/1460
Issue says to panic, but in the end I just returned an error
Example error message:
> accessing non-test database "oidcauth" while testing: try adding ftltest.WithDatabase(db) as an option with ftltest.Context(...)

feat: prevent db access to dev dbs in tests

---

go-runtime/ftl/reflection.go
go-runtime/ftl/reflection_test.go

This will be used initally by `FSM.SendEvent()`.
@worstell I'm wondering if we shouldn't extend the `typeregistry` with this functionality, such that it can be used to resolve any Go type to its schema type, statically. The reason I'm thinking that is that this reflection code could get quite tedious to maintain.

feat: reflect a schema type from a Go type

---

frontend/src/features/verbs/VerbPage.tsx
frontend/src/features/verbs/VerbRightPanel.tsx

Because the deployment key format changed a bit to have the prefix `dpl-` the verb page redirection wasn't working. This PR should correct that issue.

fix: verb page redirection when new modules are deployed

---

common/configuration/1password_provider.go
common/configuration/envar_provider.go
common/configuration/inline_provider.go

This solves an issue with outputting invalid URLs that were unable to be round-tripped back into the Go URL structure.

fix: use base64 URL encoding for config/secrets

---

frontend/src/features/deployments/DeploymentPage.tsx
frontend/src/features/modules/module.utils.ts
frontend/src/features/verbs/VerbPage.tsx

Previously, only the verb page was redirecting correctly. This fixes the deployment page as well and centralizes the parsing logic.

fix: refactor and fix deployment redirect

---

cmd/ftl/main.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go

See https://github.com/TBD54566975/ftl/actions/runs/9102976431/job/25023813425
I'm going to pull the integration tests into PR CI, unfortunately it's really opaque when it only runs on main.
Revert "fix: error out if specified config doesn't exist, fixes #1347 (#1485)"
This reverts commit 57659f3e160a30439809fd15597a73052a70380f.

chore: revert error on missing config as it breaks the integration tests

---

backend/schema/parser.go

Fixes #1507. I'm really surprised we haven't hit this previously.

fix: increase parser lookahead

---

internal/log/api.go
internal/log/configure.go
internal/log/plain.go

LOG_COLOR env to override tty detection
eg `LOG_COLOR=1 LOG_LEVEL=trace go test -v ./buildengine -run TestEngine`

feat: FTL_LOG_COLOR env to override tty detection

---

cmd/ftl/main.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go

This reverts commit 4a2902d
Integration tests now run successfully after #1514

fix: error out if cli config doesn't exist, fixes #1347

---

go-runtime/compile/schema.go

For a module that has some subpackages, we can end up getting weird build errors.
If we ignore all subpackages when extracting a modules schema, this fixes all those issues.

fix: do not attempt to compile subpackages

---

cmd/ftl/cmd_schema_import.go
internal/container/container.go

The output is a bit messy but it at least will show progress, rather than hiding the output.

fix: explicitly need to pull docker images, fixes #1525

---

go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/one/one.go

FTL panics when compiling code like this:
```
//ftl:data
type DataWithType[T any] struct {
Value T
}
```
`VisitStruct` was iterating through type parameters and type parameter values, but there are no values in this case.

fix: fix crash extracting struct with type parameter

---

backend/controller/dal/dal.go
backend/controller/dal/lease.go
backend/controller/dal/lease_test.go
backend/controller/sql/conn.go
backend/controller/sql/queries.sql.go

Up until now all transactions were hidden behind DAL methods, but in order to cleanly separate the core of async calls from the type-specific post-execution callbacks, we'll need to pass an open DAL transaction to the callback.
eg. when an FSM transition async call completes there will be a callback that will update the executing FSM instance with the destination state.

refactor: add user-accessible transactions to the DAL

---

backend/controller/controller.go

Fixes #1352
With this change, the behavior is:
- `ftl dev examples/go`
- uses `ftl-project.toml` in the gitroot if it exists
- `FTL_CONFIG=ftl-project-inline-a.toml ftl dev examples/go`
- uses `ftl-project-inline-a.toml`
- `ftl dev examples/go --config=ftl-project-inline-b.toml`
- uses `ftl-project-inline-b.toml`
- `FTL_CONFIG=ftl-project-inline-a.toml ftl dev examples/go --recreate --config=ftl-project-inline-b.toml`
- uses `ftl-project-inline-b.toml`

fix: GetModuleContext: use config from context instead of from envar

---

renovate.json

Follow up to https://github.com/TBD54566975/ftl/pull/1539
We use `react-codemirror2`, which requires `codemirror` major version `5.*`, even on their [master branch](https://github.com/scniro/react-codemirror2/blob/master/package.json). Since we have no reason to stop using `react-codemirror2`, we just need to stop codemirror from continuing to get updated automatically by renovate.
After this PR merges (assuming reviewers think this looks right!), I'll close https://github.com/TBD54566975/ftl/pull/1539.

chore: pin codemirror npm module

---

go-runtime/ftl/ftltest/ftltest.go
integration/testdata/go/wrapped/ftl-project.toml
integration/testdata/go/wrapped/wrapped_test.go
renovate.json

Fixes #1502.
Adds tests to ensure we're correctly falling back to the config in `FTL_CONFIG` and to `ftl-project.toml` in the gitroot.

fix: ftltest config: use ConfigPaths with envar fallback

---

go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/ftltest/leases.go
go-runtime/ftl/ftltest/leases_test.go
go-runtime/ftl/leases.go
integration/integration_test.go
integration/testdata/go/leases/go.mod
integration/testdata/go/leases/go.sum
integration/testdata/go/leases/leases.go
integration/testdata/go/leases/leases_test.go
internal/modulecontext/module_context.go

- split up the code in `ftl/leases.go` between:
- the business logic, which drives the acquisition and heartbeating of the lease
- the communication code, now called `leaseClient`, which streams requests and responses with the controller
- `ftl/leases.go` chooses which client it uses by asking the ModuleContext for a mock lease client, and uses the standard one if no mock is provided.
- `ftltest.MockLeaseClient` implements the `LeaseClient` protocol. `ftltest` provides this mock to the `modulecontext` when building the context
It's odd that the `LeaseClient` protocol is in `modulecontext`, LMK if you have a better way of arranging things without making import cycles...

feat: allow leases in module tests

---

backend/controller/controller.go
backend/runner/runner.go

When using connectrpc to perform calls, duplicate headers are introduced if the response object is returned directly by the runner or the controller. This causes bugs when FTL is deployed to an environment that does not work when there are duplicate headers, such as an environment where envoy is used to facilitate traffic.
The fix for this is to instantiate a new response object to return from the Call functions.
For more information on the envoy bug, see the issue linked below. 
https://github.com/envoyproxy/envoy/issues/9019
The fix for this took place after reaching out to the Buf team on slack https://bufbuild.slack.com/archives/CRZ680FUH/p1716344335783839

fix: Fix Header Duplication

---

buildengine/build_go_test.go
integration/actions_test.go
integration/harness_test.go
integration/integration_test.go
integration/wrapper_test.go

This lets us leverage all of the convenient assertion functions we use in our normal tests.

refactor: integration test actions so they use testing.TB rather than returning errors

---

.gitignore
buildengine/build_go_test.go
buildengine/testdata/type_registry_main.go
go-runtime/compile/build-template/_ftl.tmpl/go/main/main.go
go-runtime/compile/external-module-template/_ftl/go/modules/{{ range .NonMainModules }}{{ push .Name . }}{{ end }}/external_module.go
go-runtime/encoding/encoding_test.go
go-runtime/ftl/fsm.go
go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/fsm.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/reflection/reflection.go
go-runtime/ftl/reflection/reflection_test.go
go-runtime/ftl/reflection/singleton.go
go-runtime/ftl/reflection/type_registry.go
go-runtime/ftl/reflection/type_registry_test.go
go-runtime/ftl/reflection/types.go
go-runtime/internal/api.go
go-runtime/internal/impl.go
go-runtime/server/server.go
integration/integration_test.go
integration/testdata/go/fsm/fsm_test.go
integration/testdata/go/fsm/go.mod
integration/testdata/go/fsm/go.sum

This also introduces an interface `go-runtime/internal.FSM` that provides a consistent interface for production and test code. Only `FSMSend` is supported currently as a proof of concept, but we should refactor all of our existing code to use this so it's something like this:
```go
type FTL interface {
GetConfig(ctx context.Context, name string, dest any) error
GetSecret(ctx context.Context, name string, dest any) error
// Call a verb.
Call(ctx context.Context, fn any, arg any) (any, error)
// FSMSend sends an event to an instance of an FSM.
FSMSend(ctx context.Context, fsm, instance string, event any) error
// AcquireLease attempts to acquire a new lease.
AcquireLease(ctx context.Context, module string, key []string, ttl time.Duration) (Lease, error)
}
```
cc @mistermoe

feat: add support for FSMs to ftltest

---

backend/controller/console.go
backend/controller/console_test.go

Fixes #1578 
We might want more protection around refs not being found, but I wasn't sure how to make this allow for `TypeParameters` and also keep that protection. This fix gets things working again, but we might want to revisit this as well.

fix: only build verb schema for non-nil refs

---

cmd/ftl-controller/main.go

Fixes #1588 by providing a workaround to load `ftl-project.toml`s from paths specified in command line args or `FTL_CONFIG` env.
I doubt we want this long-term given the work that is being done with AWS secrets manager, db config, and `AdminService` but this might help unblock the deployment work for now.

fix: panic when ftl-controller trying to access config and secrets

---

buildengine/build_go_test.go
buildengine/testdata/type_registry_main.go

Fixes #1580
It seemed like the test was just wrong, so I updated it. I ran it a bunch locally and it seemed ok 🤷

fix: flaky type registry test

---

cmd/ftl-controller/main.go
cmd/ftl/cmd_config.go
cmd/ftl/cmd_secret.go
cmd/ftl/main.go
common/configuration/1password_provider.go
common/configuration/api.go
common/configuration/db_config_provider.go
common/configuration/defaults.go
common/configuration/envar_provider.go
common/configuration/inline_provider.go
common/configuration/keychain_provider.go
common/configuration/manager.go
common/configuration/manager_test.go
common/configuration/projectconfig_resolver_test.go
go-runtime/ftl/ftltest/ftltest.go

This change is a precursor to #1565. It removes the notion of `MutableProviders` and requires a provider be specified when calling mutable functions in the manager. It also allows a 1Password vault to be set at the controller & main.go levels by using `--opvault=VAULT`. To operate on 1P secrets via CLI, continue to use `ftl secret ... --op=VAULT`, but this should eventually change to a bool flag.

fix: refactor manager.go to use provider key instead of MutableProviders, adds `--opvault=VAULT` controller flag

---

Justfile
backend/controller/controller.go
cmd/ftl/cmd_serve.go
frontend/src/features/verbs/verb.utils.ts
integration/actions.go
internal/http/server.go

Fixes #1609 
@alecthomas I took a stab at this one. Lemme know if there's a better approach here. :)

feat: use separate bind for http ingress server

---

CONTRIBUTING.md
backend/controller/controller.go

> [!WARNING]
> Highly controversial PR. 
JK 😄 
I recently bumped ftl in two projects and had to come look at what was merged recently to figure out where the http ingress server is listening. Thought it might be helpful to add an info log that prints the address so that folks know where it's running. 
Feel free to close this out if it's not desired!
```bash
❯ ftl dev --recreate ./examples/go
info: Starting FTL with 1 controller(s)
info:controller0: HTTP ingress server listening on: http://localhost:8891
info: FTL startup command ⚡️
info:echo: Building module
info:echo: Deploying module
info:controller0: Deployed dpl-time-2kwcynci5qht7uyh
info:controller0: Deployed …
```

feat: log http ingress server address

---

common/configuration/asm_test.go

Not because they're slow, but just so we don't need localstack running during day-to-day development.

chore: make AWS ASM tests integration tests

---

.gitignore
go-runtime/compile/build.go
go-runtime/compile/external-module-template/_ftl/go/modules/{{ range .NonMainModules }}{{ push .Name . }}{{ end }}/external_module.go.tmpl
go-runtime/compile/schema.go
go-runtime/compile/testdata/pubsub/pubsub.go
go-runtime/compile/testdata/subscriber/subscriber.go
go-runtime/ftl/pubsub.go

And the types are named TopicHandle/SubscriptionHandle. This aligns more with the existing naming conventions, eg. `Map()` -> `MapHandle`, etc.

refactor: use declarative naming for topic/subscription functions

---

extensions/vscode/package.json
extensions/vscode/src/config.ts
extensions/vscode/src/extension.ts

Fixes #1621
This seems to better identify which ftl to use based on what `which ftl` returns for a given workspace.
> [!NOTE]  
> The path will not be detected correctly if a workspace is changed via File->Open...

fix: use path from where vscode was launched

---

cmd/ftl/cmd_serve.go
examples/go/echo/go.sum

Fixes #1643
This change will increment the port for each `ingress` and `controller` being created. One ingress server per controller. The result would look something like this (keeping the `8892` and `8891` ports respectively)
```bash
info: Starting FTL with 5 controller(s)
info:controller2: Web console available at: http://localhost:8896
info:controller4: Web console available at: http://localhost:8900
info:controller3: Web console available at: http://localhost:8898
info:controller1: Web console available at: http://localhost:8894
info:controller4: HTTP ingress server listening on: http://localhost:8899
info:controller2: HTTP ingress server listening on: http://localhost:8895
info:controller0: HTTP ingress server …
```

fix: start one ingress server per controller

---

backend/controller/scaling/localscaling/devel.go
buildengine/walk.go
cmd/ftl/cmd_init.go
common/configuration/projectconfig_resolver_test.go
common/projectconfig/projectconfig.go
frontend/local.go
go-runtime/ftl/ftltest/ftltest_integration_test.go
integration/actions.go
integration/harness.go
internal/source_root.go

Fixes https://github.com/TBD54566975/ftl/issues/1639
The current implementation ignores any `--config` flag values, but let me know if we should default to creating the last _specified_ config whenever one's provided. For that, I'd just move this code to the resolver and add an `r.Config` check. I decided to minimize it purely to operating on the default path because the specified paths may not actually be at the Git root, which could make the new behavior a bit more complex to comprehend. That said, there could be a good reason to use the flag value that I didn't think of.

feat: generate ftl-project.toml in the Git root if it DNE

---

backend/controller/sql/testdata/go/database/ftl-project.toml
common/projectconfig/merge.go
common/projectconfig/merge_test.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go
common/projectconfig/testdata/ftl-project.toml
go-runtime/ftl/ftltest/testdata/go/wrapped/ftl-project-test-1.toml
go-runtime/ftl/ftltest/testdata/go/wrapped/ftl-project-test-2.toml
go-runtime/ftl/ftltest/testdata/go/wrapped/ftl-project.toml

This is unused since you have to issue `ftl` commands to do anything so we already know where that executable is. We originally added this to be used by extensions, but we can use `settings.json` for that instead.

fix: remove unused [executables] from ftl-project.toml

---

backend/controller/controller.go

Fixes case where async call's early failure skipped clean up and retries.
Issue steps:
- Deploy a module
- Deployment and related rows get added to db, but no runner has been assigned yet
- Add an async call that calls that module
- A controller picks up the async call and attempts it by calling `callWithRequest(...)`
- This gets the schema by calling `getActiveSchema` which gets the schema filtering by `minReplicas > 0 and r.assigned = 'assigned'` [(link)](https://github.com/TBD54566975/ftl/blob/matt2e%2Fasync-call-dead-end/backend/controller/sql/queries.sql#L150)
- `callWithRequest(...)` fails because this new module is not in the fetched schema
- `executeAsyncCalls(...)` return early due to this error, not updating the state of the async call
- the lease gets released rather than …

fix: handle async call not being able to be called

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_dev.go
common/projectconfig/integration_test.go
common/projectconfig/projectconfig.go
common/projectconfig/testdata/go/no-module-dirs-ftl-project.toml

Fixes https://github.com/TBD54566975/ftl/issues/1668
Note that this isn't usable in the `ftl` repo itself because `go-runtime/scaffolding/{{ .Name | camel | lower }}/ftl.toml` confuses the walker, so we do need to specify `examples/go` in our own `ftl-project.toml`. However, the change does WAI in normal repositories that don't have module templates.

fix: default to root when module-dirs is not set

---

backend/controller/controller.go
backend/controller/dal/pubsub.go
backend/controller/pubsub/integration_test.go
backend/controller/pubsub/manager.go
backend/controller/pubsub/testdata/go/publisher/publisher.go
backend/controller/pubsub/testdata/go/subscriber/subscriber.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/001_init.sql
integration/actions.go

closes https://github.com/TBD54566975/ftl/issues/1596 closes https://github.com/TBD54566975/ftl/issues/1642
How it works:
- pubsub managers poll for subscriptions that are behind the topic's head
- locks these subscriptions for the tx
- skips subscriptions that are already locked
- Then finds the next event for each subscription
-  If the event is newer than our artificial delay, we skip this subscription on this attempt
Pubsub also speeds things up by:
- Polling once a second
- When it schedules an async call, notifies controller so we can attempt to pick it up straight away
- this is wrapped in a mutex so that we don't accidentally get more and more async calls running at once on a single controller
- When the async call is completed, pubsub is notified so that it can immediately try …

feat: pubsub manager

---

common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go

I noticed an issue where the LSP was not clearing the diagnostics correctly for modules when rebuilding.
It turned out that the `module.Dir` was only relative when loaded from the project `toml` vs. absolute when used with `"."` or `ftl dev example/go`. This change makes sure we set the absolute paths on the `config.ModuleDirs` and `config.ExternalDirs` when loading them from `ftl-project.toml` files.
Before this change the `lsp` would try to clear files with the following path. This would result in LSP errors never being cleared.
```bash
lsp: Clearing diagnostics for file:///examples/go/echo
```
This update, ensures that path is absolute
```bash
lsp: Clearing diagnostics for file:///Users/wesbillman/dev/ftl/examples/go/echo
```

fix: when using module-dirs from project, make dirs absolute

---

go-runtime/compile/schema.go

I was getting a crash when doing this:
`ftl build go-runtime/compile/testdata`
We were returning a nil pointer but then didn't check for nil

fix: crash using nil ref pointer

---

backend/controller/ingress/ingress_integration_test.go
backend/controller/ingress/ingress_test.go
backend/controller/ingress/request.go
backend/controller/ingress/request_test.go
backend/controller/ingress/testdata/go/httpingress/httpingress.go
integration/actions.go

Fixes #1686
Here's the test I used:
```go
type GetRequest struct {
UserID string             `json:"userId"`
PostID string             `json:"postId"`
Tag    ftl.Option[string] `json:"tag"`
}
type GetResponse struct {
}
// Example:       curl -i http://localhost:8891/http/users/123/posts?postId=456&tag=foo
//
//ftl:ingress http GET /http/users/{userId}/posts
func Get(ctx context.Context, req builtin.HttpRequest[GetRequest]) (builtin.HttpResponse[GetResponse, string], error) {
tag := req.Body.Tag.Default("No value")
ftl.LoggerFromContext(ctx).Infof("Received request with tag: %s", tag)
return builtin.HttpResponse[GetResponse, string]{
Headers: map[string][]string{"Get": {"Header from FTL"}},
Body:    ftl.Some(GetResponse{}),
}, nil
}
```
```bash
curl -i …
```

fix: allow optional values in query params

---

cmd/ftl/cmd_config.go
cmd/ftl/cmd_secret.go
common/projectconfig/integration_test.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go

- 46b7c972d567c6e289e3f0aa792f38d3878f82c7. was writing absolute paths into `ftl-project.toml`
- `ftl config/secret get` were not writing raw JSON values

fix: fixes for behaviour regressions

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_dev.go
common/projectconfig/merge.go
common/projectconfig/projectconfig.go
lsp/lsp.go

This fixes clearing of errors from the lsp when modules are being rebuilt and improves duplication of errors (thanks @worstell!!)

fix: module dir paths and lsp error unwrapping

---

go-runtime/ftl/config.go
go-runtime/ftl/config_test.go
go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/map_test.go
go-runtime/internal/api.go
go-runtime/internal/impl.go
go-runtime/server/server.go
internal/modulecontext/module_context.go

This doesn't refactor secrets, but the same pattern can be applied there.
Also switched to forcing a type assertion on `fakeFTL` as it's an invariant of the testing system.
cc @matt2e

refactor: pull config from FTL runtime abstraction

---

backend/controller/console.go
frontend/src/features/verbs/verb.utils.ts

fix: show empty jsonSchema for verbs with no req

---

go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/failing.go
go-runtime/compile/testdata/pubsub/pubsub.go

Closes https://github.com/TBD54566975/ftl/issues/1640
Checks for:
- publishing directly to an external module's exported topic
- directly calling an external module's verb, rather than using `ftl.Call(...)`
- This already fails at runtime, but it's nice to have this as a compile error
Both of these compile-time checks are not fool proof, any indirection will mean these checks don't catch it. But it is good to catch what we can.
eg:
```go
var extTopic = external.Topic
extTopic.Publish(...) // compiler believes this is a local topic
```
Added a separate issue for this for pubsub as it may not be as high a priority: https://github.com/TBD54566975/ftl/issues/1703

fix: check for invalid function calls into external modules

---

backend/controller/dal/pubsub.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

We have a small delay between when a topic event is published and when we allow subscriptions to consume it to guarantee no new events will be inserted in-between.
Previously this check was done by the controller, comparing the db row's created_at with the controller's clock.
It seems there are cases where the controller thinks that enough time has passed, but not according to the db clock.
This PR moves these checks to the db layer. This should make our integration test more reliable as it also relies on comparing two timestamps generated by the db clock.
Example flaky integration test: https://github.com/TBD54566975/ftl/actions/runs/9432792904/job/25983007930#step:8:1

fix: use db clock for delaying event consumption

---

buildengine/engine.go
buildengine/engine_test.go

This reverts commit e711523cabbc597ea7acaf0434c9e89106adb263.
```
=== Failed
=== FAIL: buildengine TestDissallowMultipleEngines (0.00s)
/home/runner/work/ftl/ftl/buildengine/engine_test.go:65: Did not expect an error but got:
failed to lock file at: /home/runner/.ftl/build.lock
DONE 383 tests, 1 skipped, 1 failure in 115.533s
Error: === RUN   TestDissallowMultipleEngines
buildengine/engine_test.go:65: Did not expect an error but got:
failed to lock file at: /home/runner/.ftl/build.lock
```
cc @safeer 
This is occurring because `go test` runs each packages tests in parallel, so multiple tests will be running concurrently and thus multiple build engines.

revert: "fix: add a build.lock file to gate the buildengine (#1670)"

---

docs/content/docs/reference/pubsub.md

docs: add `Publish` example to pubsub docs

---

docs/content/docs/reference/cron.md
internal/cron/cron.go
internal/cron/cron_test.go
internal/cron/pattern.go
internal/duration/duration.go

Fixes #1628
Supports:
- Every n seconds: `//ftl:cron 10s`
- Every n minutes: `//ftl:cron 30m`
- Every n hours: `//ftl:cron 12h` (Starting at UTC midnight)
- Day of the week (UTC midnight): `//ftl:cron Friday` or `//ftl:cron Fri`
- Case insensitive with at least the first 3 chars of the day name.

feat: Add support for shorthand cron expressions

---

go-runtime/compile/schema.go
go-runtime/compile/schema_test.go

includes fixes for the following cases:
- fix panic when validating if a call is valid if the call was to an inbuilt type (which has no package)
- fix issue finding a topic's name when declaring a subscription
- the topic's var has a nil `.Obj` field, possibly because it was defined in a different file. Added a map from variable declaration position to the schema.Topic, and used that instead
- fix issue disambiguating between an illegal direct verb call (eg: `external.DoSomething(ctx)`, and an allowed field access (eg: `external.Data{}.Name`)

fix: pubsub schema fixes

---

go-runtime/compile/parser.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go

Fixes #1635
I also noticed that the directive errors were being shown on the `func` instead of the location of the directive so added `GetPosition` to directives as well.
and

fix: directive error positions and messages

---

internal/cron/cron.go
internal/cron/cron_test.go
internal/cron/pattern.go

2 issues found
- our cron implementation did not evaluate if the current time matched the day of the week properly
- discovered in this PR: https://github.com/TBD54566975/ftl/pull/1733/files
- this revealed that the new shorthand day of the week logic was doing the equivalent of `* * * * * x *` (every second of the chosen day) rather than `0 0 0 * * x *` (midnight of the chosen day)
fyi, plan is to replace with an actual cron lib anyway...

fix: evaluate if current day of week is valid correctly

---

backend/controller/dal/fsm_integration_test.go
backend/controller/dal/testdata/go/fsmretry/fsmretry.go

fsm retry test was sometimes failing because the async task was not picked up within the 1s interval that the test expected.
Now the interval is 1.5s. Retries in the test have also been increased to 2s with less retries so that the interval is still less than the retry frequency, and so we aren't approaching the 30s timeout.
Example of flakiness: https://github.com/TBD54566975/ftl/actions/runs/9494930873/job/26166196434?pr=1765#logs

test: fix flaky fsm retry test

---

backend/schema/verb.go

fixes #1751
We were hitting the above issue because we were trying to traverse the schema tree to implicitly export nodes, but were encountering a verb which added nil values into its children slice.

fix: only add valid nodes to verb children

---

buildengine/watch_test.go
cmd/ftl/cmd_init.go
common/projectconfig/projectconfig.go
go-runtime/ftl/ftl_integration_test.go

fix: don't attempt to create ftl-project.toml in fs root

---

cmd/ftl/main.go
internal/rpc/rpc.go

fix: add `--insecure` to skip TLS certificate verification

---

docs/content/docs/reference/unittests.md

docs: unit testing

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/map.go
go-runtime/ftl/testdata/go/mapper/mapper_test.go

- `ftltest.WhenMap(...)` included a func that returned `any` when it should be strongly types with the map's return type
- `ftl.Map` was returning `MapHandle` where as `handle.Get()` was defined on `*MapHandle` and `ftltest.WhenMap(...)` expected a pointer as well. I've made it all consistently use `*MapHandle` so you don't need to do `&handle` anywhere

fix: WhenMap() now typesafe, ftl.Map returns ptr

---

go-runtime/compile/schema.go

fix: provide a better error if go verb isn't upper camel case

---

go-runtime/compile/schema.go

It forced users to use eg. `GetUserById` rather than `GetUserByID`, which we currently don't want to do.

fix: don't do a full camel case check against exported verbs

---

backend/controller/sql/schema/001_init.sql

Was causes db errors deplying modules that use the same name for a subscription

fix: subscription names not unique

---

docs/content/docs/reference/verbs.md
lsp/completion.go
lsp/markdown/completion/configDeclare.md
lsp/markdown/completion/enumType.md
lsp/markdown/completion/enumValue.md
lsp/markdown/completion/ingress.md
lsp/markdown/completion/pubSubSink.md
lsp/markdown/completion/pubSubSubscription.md
lsp/markdown/completion/pubSubTopic.md
lsp/markdown/completion/retry.md
lsp/markdown/completion/secretDeclare.md
lsp/markdown/completion/typeAlias.md
lsp/markdown/completion/verb.md

If prefixed with a single /, the completion only shows go-style FTL directives.
Do not autocomplete past the first char so that it won't trigger in a function etc.
Fixes #1804

feat(lsp): scope based suggestions, add / specific prefix

---

backend/schema/metadatacronjob.go
internal/cron/pattern.go

Fixes #1807
Was crashing when having random words in each component.

fix: parse cron components without panic

---

cmd/ftl/cmd_init.go
cmd/ftl/cmd_schema_get.go

fix: add `--watch` to `ftl schema get`

---

backend/schema/visit.go
go-runtime/compile/build.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/child/child.go
go-runtime/compile/testdata/failing/failing.go
go-runtime/schema/common/common.go
go-runtime/schema/common/fact.go
go-runtime/schema/extract.go
go-runtime/schema/finalize/analyzer.go
go-runtime/schema/metadata/analyzer.go
go-runtime/schema/transitive/analyzer.go
go-runtime/schema/typealias/analyzer.go
go-runtime/schema/verb/analyzer.go

propagate failed extractions in the aggregate `extract.go` rather than via finalize.Analyzer, which is scoped to a single package

feat: improve error propagation for LSP in new schema extractor

---

.golangci.yml
authn/authn.go
backend/controller/admin/admin.go
backend/controller/controller.go
backend/controller/cronjobs/cronjobs.go
backend/controller/cronjobs/cronjobs_utils_test.go
backend/controller/dal/dal_test.go
backend/controller/sql/conn.go
backend/controller/sql/databasetesting/devel.go
backend/controller/sql/sqltest/testing.go
backend/runner/runner.go
backend/schema/fsm.go
backend/schema/module.go
backend/schema/normalise.go
backend/schema/protobuf.go
backend/schema/validate.go
buildengine/build_kotlin.go
cmd/ftl/cmd_serve.go
cmd/ftl/main.go
common/plugin/serve.go
common/plugin/spawn.go
frontend/local.go
go-runtime/compile/build.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/schema/extract.go
internal/flock/flock.go
internal/rpc/rpc.go
internal/zip_relative.go

Forces use of a `//nolint:errcheck // <reason>` directive, so future me doesn't wonder why I ignored the error.

chore: ensure that errors aren't ignored via _

---

extensions/vscode/src/extension.ts

fix: dont expand vscode console on startup

---

backend/controller/controller.go
backend/controller/dal/async_calls.go
backend/controller/dal/fsm.go
backend/controller/dal/lease.go
backend/controller/dal/lease_test.go
backend/controller/leader/coordinator.go
backend/controller/leader/leader.go
backend/controller/leases/fake_lease.go
backend/controller/leases/fake_lease_test.go
backend/controller/leases/leases.go
backend/controller/scheduledtask/scheduledtask.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/001_init.sql

- add `leader` package which coordinates between leaders and followers
- leader and followers conform to the same interface
- call `Get()` on the coordinator get get either a leader or a follower
- built on top of leases
- handles case when leader loses connection to the db and loses leader role
- leases now return a context which will be cancelled when the lease fails to heartbeat
- no other lease-based features make use of this yet

feat: add leader coordinator

---

backend/controller/dal/lease.go
backend/controller/dal/lease_test.go
backend/controller/leader/leader.go
backend/controller/leases/lease_integration_test.go

fixes #1678
leases interface documents that `leases.ErrConflict` is the expected error if lease acquisition fails, but dal was returning `dal.ErrConflict`

fix: return expected leases.ErrConflict from dal

---

cmd/ftl/cmd_new.go

fix: don't fail `ftl new` if there's no git repo

---

backend/controller/controller.go
backend/controller/dal/testdata/go/fsm/go.mod
backend/controller/dal/testdata/go/fsm/go.sum
backend/controller/leader/leader.go
backend/controller/leader/leader_test.go
backend/controller/leases/testdata/go/leases/go.mod
backend/controller/leases/testdata/go/leases/go.sum
backend/controller/sql/testdata/go/database/go.mod
backend/controller/sql/testdata/go/database/go.sum
cmd/ftl-controller/main.go
cmd/ftl/cmd_serve.go
common/configuration/asm.go
common/configuration/asm_follower.go
common/configuration/asm_leader.go
common/configuration/asm_test.go
common/configuration/secrets_cache.go
go-runtime/ftl/ftltest/testdata/go/pubsub/go.mod
go-runtime/ftl/ftltest/testdata/go/pubsub/go.sum
go-runtime/ftl/ftltest/testdata/go/subscriber/go.mod
go-runtime/ftl/ftltest/testdata/go/subscriber/go.sum
go-runtime/ftl/ftltest/testdata/go/verbtypes/go.mod
go-runtime/ftl/ftltest/testdata/go/verbtypes/go.sum
go-runtime/ftl/ftltest/testdata/go/wrapped/go.mod
go-runtime/ftl/ftltest/testdata/go/wrapped/go.sum
go-runtime/ftl/testdata/go/mapper/go.mod
go-runtime/ftl/testdata/go/mapper/go.sum

closes #1782
ASM changes:
- `ASM` uses `leader` package to coordinate between leader and followers
- The leader syncs secrets from ASM
- Only requests secrets that have been updated since last sync
- Followers always uses admin service to get the secrets from the leader
- Both leader and follower cache secrets using `secretsCache`
Other changes:
- Remove additional db connection pools created at start up. Now a single db pool is created along with a dal at start up, which is then passed into the controller service and anything else that needs it

feat: cache asm secrets

---

cmd/ftl/cmd_serve.go

ensure controller is live and db container is provisioned before executing startup tasks

fix: execute startup tasks after serving

---

buildengine/build.go
buildengine/build_kotlin.go
buildengine/build_test.go
buildengine/deploy.go
common/moduleconfig/moduleconfig.go
go-runtime/compile/build.go

`.Abs()` will return a clone with all paths made absolute. This avoids a bunch of manual and error prone joining.

chore: make using ModuleConfig paths more consistent

---

Dockerfile.box
buildengine/deploy.go
cmd/ftl/cmd_box.go
cmd/ftl/main.go
common/moduleconfig/moduleconfig.go

There are two commands:
`ftl box build <image>` builds a self-contained Docker container with a set of modules.
`ftl box run` runs modules inside an ftl-in-a-box container (currently does nothing).

feat: add `ftl box` command tree

---

common/configuration/asm_follower.go
common/configuration/asm_leader.go
common/configuration/secrets_cache.go

- Looking into why we are getting ASM sync errors on staging and it is hard to tell whether the error is happening in the leader or the follower. These error changes should help this.
- `secretsCache` should not have any mention of ASM as it is meant to be generic

fix: improve ASM error messages

---

Dockerfile.box
buildengine/engine.go
cmd/ftl/cmd_box.go
cmd/ftl/cmd_box_run.go
cmd/ftl/cmd_deploy.go
cmd/ftl/main.go
internal/modulecontext/module_context.go
internal/rpc/rpc.go

This required some changes to how the build engine works, in that build and deploy can now be run separately.
Building the box:
```
🐚 ~/dev/ftl $ ftl box echo examples/go
info:echo: Building module
info: Building image echo
```
Running locally:
```
🐚 ~/dev/ftl $ ftl box-run --dsn="postgres://postgres:secret@localhost:15432/ftl?sslmode=disable" examples/go/
info: Web console available at: http://0.0.0.0:8892
info: HTTP ingress server listening on: http://0.0.0.0:8891
info: Reusing deployment: dpl-time-xpun6vddce07f5s
info: Deployed dpl-echo-1bd1tvnmig06767u
info: Deployed dpl-time-xpun6vddce07f5s
info:echo: Deploying module
info: Reusing deployment: dpl-echo-1bd1tvnmig06767u
info: All modules deployed
```
Running the resulting image …

feat: implement `ftl box run`

---

backend/controller/admin/admin.go
common/configuration/asm_test.go
common/configuration/manager.go

previously we would see errors like this when getting the secrets list with values if a secret was not properly json encoded:
> unknown: invalid character 'c' looking for beginning of value
now we will get errors like this:
> unknown: failed to get value for [module].[name]: could not unmarshal: invalid character 'c' looking for beginning of value

fix: improve errors when unmarshalling config/secrets

---

common/configuration/asm_leader.go
common/configuration/asm_test.go

fix: add an FTL tag and filter ASM secrets

---

.github/workflows/ci.yml
.golangci.yml
Justfile

This has been disabled because manually wrapping all errors is very tedious when iterating quickly, but it's come to the point where we need to do this in order to provide useful errors. Recent examples of this are https://github.com/TBD54566975/ftl/pull/1885 and https://github.com/TBD54566975/ftl/pull/1879.

chore: enable wrapcheck for new code

---

backend/runner/runner.go

Fixes https://github.com/TBD54566975/ftl/issues/1900
I'm not totally confident in the error code here - possibly CodeUnknown would be more appropriate?

fix: return err properly in runner

---

cmd/ftl/cmd_dev.go

This prevented startup failures from being reported.

fix: one goroutine was waiting on a channel, blocking the waitgroup

---

lsp/lsp.go

Fixes #1849 
Error detection was far too aggressive, discarding legit schema.Errors.

fix: diagnostic errors were being discarded

---

extensions/vscode/src/client.ts

Previously it wasn't including "dev" when showing the command.
Also changed it so you can copy paste the command without text between the command and args.

fix(vscode): show full command executing ftl

---

extensions/vscode/package-lock.json
extensions/vscode/package.json
extensions/vscode/src/client.ts

Fixes #1890 
- Detect when FTL stops via crash and shows an error on the status bar.
- When restarting, start spinning again.
- Tested manually with both examples in #1890 and also killing the process directly.

fix(vscode): handle lsp crashes

---

common/configuration/1password_provider.go
common/configuration/defaults.go

Loading passwords this way took so long that deploys started failing.
This reverts commit b5fbf19765d91b42e198fb8bdf0e8712fa7b5edf.

revert: "fix: call `op` serially to avoid multiple authorization prompts

---

common/configuration/asm_leader.go

fixes #1937
Not able to reproduce the issue in local stack. A tag filter + 20 secret names worked fine there.

fix: reduce ASM batch size to stay within filter limit of 10

---

backend/controller/console.go
frontend/src/features/verbs/verb.utils.ts

fix: use body as root for ingress verb form fix console issue

---

backend/controller/admin/admin_test.go
backend/controller/admin/testdata/ftl-project.toml
backend/controller/sql/testdata/go/database/ftl-project.toml
common/configuration/manager_test.go
common/configuration/projectconfig_resolver.go
common/configuration/projectconfig_resolver_test.go
common/configuration/testdata/ftl-project.toml
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go
common/projectconfig/testdata/ftl-project.toml
common/projectconfig/testdata/go/configs-ftl-project.toml
common/projectconfig/testdata/go/findconfig/ftl-project.toml
common/projectconfig/testdata/go/no-module-dirs-ftl-project.toml
common/projectconfig/testdata/withMinVersion/ftl-project.toml
go-runtime/ftl/ftltest/testdata/go/wrapped/ftl-project-test-1.toml
go-runtime/ftl/ftltest/testdata/go/wrapped/ftl-project.toml
integration/harness.go

Validates project config files.
This breaks previous cases where `ftl config set` and similar would be able to create the project toml if it wasn't already created. Now that a project's name is required, an invalid project config would have been created.
It is now a requirement to go through `ftl init <name> <dir>`

fix: validate project config

---

extensions/vscode/package.json

Existing url on the extension page is old:

fix(vscode): url for repo update

---

.github/workflows/ci.yml
Justfile
backend/controller/sql/schema/file with space.sql
lefthook.yml
scripts/ensure-frozen-migrations

Fixes #1962
- Checks for changes to existing migration files against `main, ignoring new lines and single line comments.
- Adds a `just ensure-frozen-migrations`.
- Adds a CI check.

ci: ensure frozen migrations

---

common/configuration/asm_leader.go
common/configuration/comments.go
common/configuration/comments_test.go
common/configuration/manager.go
common/configuration/obfuscator.go
common/configuration/obfuscator_test.go

closes #1889
closes #1772
- Secrets manager has an obfuscator, config manager does not (`Secrets` conforms to `ObfuscatorProvider`)
- `configuration.Obfuscator` allows obfuscating/revealing of values
- These changes apply to all secrets providers
- Providers can also save a comment warning about tampering
- ASM does this by prefixing the secret with comments (lines starting with `#`)
- 1Password will support comments in another PR

feat: obfuscate secrets to avoid tampering

---

buildengine/engine.go
internal/modulecontext/module_context.go
internal/modulecontext/module_context_test.go
internal/rpc/rpc.go
testutils/modulecontext/module_context_utils.go

fixes #1959
controller startup failure troubleshooting was complicated by a failure to surface error messages from the `GetModuleContext` streaming end-point.
errors encountered from that end-point are now made visible and if those errors are deemed fatal the runner will terminate.

fix: controller startup failure visibility

---

backend/controller/controller.go
backend/runner/runner.go
common/plugin/serve.go
internal/http/pprof.go
internal/rpc/server.go

This adds debugging pprof HTTP handlers.
The controller serves this directly, while the runner forwards to the user verb server's handlers, allowing verb servers to be debugged directly.
Here's an example of CPU profiling the echo module:
```
🐚 ~/dev/ftl $ go tool pprof http://localhost:8894/debug/pprof/profile
Fetching profile over HTTP from http://localhost:8894/debug/pprof/profile
Saved profile in /Users/alec/pprof/pprof.main.samples.cpu.001.pb.gz
File: main
Type: cpu
Time: Jul 5, 2024 at 5:33am (AEST)
Duration: 30.18s, Total samples = 600ms ( 1.99%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 600ms, 100% of 600ms total
Showing top 10 nodes out of 73
flat  flat%   sum%        cum   cum%
210ms 35.00% 35.00%      210ms …
```

feat: add /debug/pprof handlers

---

backend/controller/controller.go
cmd/ftl/cmd_serve.go
frontend/local.go

- Now log why console crashed
- Use gitRoot based path for running console

fix: console was crashing quietly, relative paths

---

Dockerfile.runner

Runner applications egress to internet applications today, requiring basic CA bundles to be present.

feat: Add ca-certificates package to ftl-runner image

---

cmd/ftl/cmd_serve.go

Maybe #1942
* Use `--startup-timeout` flag for controller timeout when in foreground

fix: increase timeout for controller, log timings

---

common/configuration/1password_provider.go

We now obfuscate secrets which caused errors when retrieving values from 1Password because the provider was making sure the value was json

fix: do not verify obfuscated contents of 1password

---

backend/schema/jsonschema.go
frontend/src/features/verbs/verb.utils.ts

This doesn't fully fix the issue with jsonschema and `TypeAlias`ed fields, but will keep the console from failing completely when the schema is not valid.
See #2004 
See #1991

fix: console erroring with bad jsonschema values

---

common/configuration/asm_follower.go
common/configuration/asm_test.go
common/configuration/obfuscator.go

- Secret providers take in obfuscated bytes to store and should return obfuscated bytes when loading secrets
- ASM follower was not doing this because it stores and retrieves secrets through the admin API
- When storing secrets it would send obfuscated values to the admin endpoint, which would fail (can not parse json string because its base64)
- When retrieving secrets it woudl get unobfuscated values from the admin endpoint and return them. The manager would then fail when then unobfuscate this value (resulting in gibberish) which would then fail when trying to parse it as json
Solution:
ASM follower now directly accesses `Secrets{}.obfuscator()` to translate into the correct form.

fix: asm follower obfuscation

---

backend/controller/controller.go
backend/controller/ingress/ingress_integration_test.go
frontend/local.go
frontend/release.go
go-runtime/encoding/encoding_integration_test.go
integration/actions.go
internal/cors/cors.go

Fixes #1986 
- Added `--allow-headers` option eg `--allow-headers x-forwarded-capabilities`
- Works with env `FTL_CONTROLLER_ALLOW_HEADERS`

fix: cors allow headers option and env

---

backend/controller/leader/leader.go

fixes #2011
Cause: 
- Coordinator only does it coordination logic when something calls `Get()`
- If leader/follower coordinator's `Get()` function was not called then an expired leader/follower would not change
- ASM follower syncs with what it expects to be the leader even if that leader is not alive. Even if we get a new leader, the follower would not be swapped out for a valid one until `Get()` was called. So it would churn away failing to sync.
Fix:
- Proactively call `Get()` periodically so that coordination occurs even if no calls to Get() would otherwise happen.

fix: proactively coordinate leader/followers

---

internal/modulecontext/module_context.go

We were catching multiple calls for `wg.Done()` in the success case, but when an error was hit

fix: module context errors should not cause a negative wait group

---

backend/controller/sql/database_integration_test.go
backend/controller/sql/databasetesting/devel.go
backend/controller/sql/migrate.go
cmd/ftl/cmd_migrate.go
cmd/ftl/main.go
integration/actions.go

Fixes #1839
- Migration files are embedded in the binary, so the binary version matches the schema.
- Uses `DATABASE_URL` (same as dbmate) or `--dsn` to specify the connection.

feat: ftl migrate command

---

backend/controller/sql/testdata/go/database/database_test.go
go-runtime/ftl/ftltest/ftltest.go

fixes #1866 
introduces a rudimentary partial ordering scheme for context options - this is used to sort them before they get executed to build the context

fix: ftltest context option order insensivity

---

internal/rpc/rpc.go

fixes #2002
unexpected warnings caused by retryable errors - retryable errors will continue to be reported as debug.

fix: retryable streaming server errors to be logged as debug

---

buildengine/engine.go
buildengine/stubs.go
go-runtime/compile/build.go

This PR modifies the build engine to generate stubs for all known schemas at build time. After a build group is built, we then sync the stub references to help users get auto completions and imports in their IDEs or text editors.
It essentially changes the way we gather schemas for the module(s) we're building.
In `go` syncing the stub references means that we update the `go.work` file for each built module to include ALL shared module stubs. This helps when a module is adding a shared module as a dependency.

fix: sync stub references for each build group

---

backend/controller/controller.go

fixes #2045
Do not access `response.Msg` if `response` may be `nil` because we have an error

fix: do not panic if an error occurs making a call

---

common/configuration/asm.go
common/configuration/asm_follower.go
common/configuration/asm_leader.go
common/configuration/asm_test.go

It can be hard to tell in logs when an ASM follower can not sync with the leader what it thinks the leader is, which is important to know if it is following the current leader or an old one.

fix: include the IP of the leader in ASM follower sync error logs

---

buildengine/engine.go

Fixes #2042
Before this change, we would get build errors because the `go.work` file for a given module would include all the built modules including modules that were in the same build `group` layer as a given module.
For example, if we had 4 modules all in the same group `[a, b, c, d]` and we build with a `-j2` option (2 parallel builds), we would run into an issue where `a` and `b` would build first, in parallel. `a` would finish and we would start to build `c`. But, when we looked up the `schema` to get shared modules for the `go.work` file for `c`, that list would now include `a` even though they are in the same build group and should never depend on each other.
This fix changes the build func to not re-lookup built modules and instead just use the set of `builtModules` that were …

fix: building withing lower parallelism than dependency group size

---

cmd/ftl/cmd_schema.go
cmd/ftl/cmd_schema_diff.go
go.mod
go.sum

Fixes #1989
```
ftl schema diff --help
Usage: ftl schema diff <other-endpoint> [flags]
Print any schema differences between this cluster and another cluster. Returns
an exit code of 1 if there are differences.
Arguments:
<other-endpoint>    Other endpoint URL to compare against.
--endpoint=http://127.0.0.1:8892     FTL endpoint to bind/connect to ($FTL_ENDPOINT).
--color    Enable colored output regardless of TTY.
```
- Compares `<other-endpoint>` vs `--endpoint` into a unified diff with color.
- Exits with 1 if there is a difference.
- Detects tty and will not emit ANSI unless `--color` is passed in.

feat: ftl schema diff

---

cmd/ftl/main.go
common/configuration/1password_provider.go
common/configuration/1password_provider_test.go
common/configuration/defaults.go
common/configuration/manager.go
go-runtime/ftl/ftl_integration_test.go

closes #1947
closes #1772
Creates an entry in 1Password called `<projectname>.secrets` with each secret stored in a password field called `<modulename>.<secretname>`
Username is set to a warning string as that is presented at the top of the 1Password UI.
This will break existing secrets stored in 1Password. Migration can be done using commands made available in: https://github.com/TBD54566975/ftl/pull/1982

feat!: store all 1password secrets in a single entry

---

buildengine/build_go_test.go
go-runtime/compile/build.go
go-runtime/compile/schema_test.go
go-runtime/schema/call/analyzer.go
go-runtime/schema/common/common.go
go-runtime/schema/data/analyzer.go
go-runtime/schema/extract.go
go-runtime/schema/verb/analyzer.go

- fixes a code gen issue for types.ftl.go
- validate global uniquness on Decl names (required because ref->Decl resolution breaks if two Decls have the same name, even of different types)
- fixes logic that determines if path is local because pass.Pkg may not be root module package

fix: some fixes!

---

go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/child/child.go
go-runtime/compile/testdata/failing/failing.go

duplicates need to be declared in separate files (parent and child) for error report test. otherwise the ordering of which is discovered first may change and the test is flaky

fix: flaky test

---

common/configuration/1password_provider.go
common/configuration/api.go
common/configuration/asm.go
common/configuration/asm_test.go
common/configuration/cache.go

Changes:
- Asynchronous providers are given a list of known entries when syncing
- 1Password provider uses these entries to know which vaults to sync
- Removed logic for whether an asynchronous provider was active. This was there to make sure we didnt attempt syncing with 1Password for projects that weren't using 1Password. This is now solved by 1PasswordProvider only syncing known vaults.

fix: no need to specify —opvault to access secrets

---

Justfile
deployment/Justfile
deployment/README.md
deployment/db-migrate/kustomization.yml
deployment/ftl-controller/ftl-controller.yml

Fixes #2069
Fixed up a few things around k8s deploy scripts and docs.

test: k8s justfile and fixes

---

Justfile

Part 2 of https://github.com/TBD54566975/ftl/issues/2020
This PR adds `just otel-ui`, which wraps the otel collector so you can view signals generated in `ftl dev` through a webapp without separately needing to start the collector.
Unfortunately, the latest version of `otel-desktop-viewer` that we can install only supports traces, not metrics or logs. The latest version on their github repo does have metrics/logs support, but can't be installed without cloning the whole repo and building from source code. Instead of doing that, I filed this issue: https://github.com/CtrlSpice/otel-desktop-viewer/issues/146
For now, when we're only debugging/developing traces, we can use this desktop viewer, which is quite nice. When working with metrics/logs, we'll still need to use the collector itself: …

chore: add `just otel-ui` to view traces through browser

---

backend/controller/controller.go

fixes https://github.com/TBD54566975/ftl/issues/2068
Errors can occur after we were adding the `defer` and when we would try upserting the runner.
This PR makes it so we only add the defer once we have upserted the runner

fix: only deregister runner if runner was ever inserted

---

backend/controller/dal/async_calls.go
backend/controller/dal/async_calls_test.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

When a controller tries to get a lease on the next async call to execute, the lease creation code should first check to see if there was a call found.
Before when a controller tried to get a hold on the next async call to execute, it would result in this error:
```
2024-07-15 16:00:08 UTC:10.2.111.21(46692):adminuser@tbd:[60308]:ERROR:  null value in column "key" of relation "leases" violates not-null constraint
2024-07-15 16:00:08 UTC:10.2.111.21(46692):adminuser@tbd:[60308]:DETAIL:  Failing row contains (1632753, 37a8d114-73ca-46a1-b03b-a17331d17181, null, 2024-07-15 16:00:08.260772+00, 2024-07-15 16:00:13.260772+00, null).
2024-07-15 16:00:08 UTC:10.2.111.21(46692):adminuser@tbd:[60308]:STATEMENT:  -- name: AcquireAsyncCall :one
WITH async_call AS (
SELECT id
FROM async_calls
WHERE …
```

fix: prevent db error if no async calls to execute

---

backend/controller/admin/client.go
backend/controller/admin/local_client.go
cmd/ftl/cmd_config.go
cmd/ftl/cmd_secret.go
cmd/ftl/cmd_serve.go
cmd/ftl/integration_test.go
cmd/ftl/main.go
cmd/ftl/testdata/secrets1.json
cmd/ftl/testdata/secrets2.json

fixes #2086
- Recently we added a feature for cf.Manager to sync providers (1Password & ASM)
- We should not create these managers if they are not used, otherwise we will prompt the user for 1Password access unnecessarily
- Previously we were creating config + secret managers in `main.go` for every command, even though it is only needed for these commands:
- `ftl serve`
- `ftl dev`
- `ftl config ...` if there is no controller running
- `ftl secret ...` if there is no controller running

fix: only create config managers if needed to avoid syncing on every cmd

---

common/configuration/1password_provider.go

fix: only check for `op` if 1Password holds secrets

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/dal/notify.go

fix: remove pg_notify usage in favor of polling

---

common/configuration/dal/dal_test.go
common/configuration/sql/queries.sql
common/configuration/sql/queries.sql.go

Addresses part of https://github.com/TBD54566975/ftl/issues/2084
Postgresql way to handle upserts: https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/
This PR fixes the issue for secrets since that's causing issues for the client team, but not for config, which has the same issue. I confirmed the test fails before this change but passes with it.

fix: avoid insertion key dupls in `module_secrets` table by upserting on conflict

---

common/configuration/dal/dal_test.go
common/configuration/sql/queries.sql
common/configuration/sql/queries.sql.go

Fixes https://github.com/TBD54566975/ftl/issues/2084
This PR addresses the config side, whereas https://github.com/TBD54566975/ftl/pull/2105 fixed it for secrets.
I confirmed the test fails before this change but passes with it:
```
$ go test ./common/configuration/dal/... -run TestModuleConfiguration
debug:migrate: Applying: 20231103205514_init.sql
debug:migrate: Applied: 20231103205514_init.sql in 134.088875ms
debug:migrate: Applying: 20240704103403_create_module_secrets.sql
debug:migrate: Applied: 20240704103403_create_module_secrets.sql in 5.793958ms
--- FAIL: TestModuleConfiguration (0.30s)
--- FAIL: TestModuleConfiguration/HandlesConflicts (0.00s)
dal_test.go:108: Did not expect an error but got:
duplicate key value violates unique constraint "module_configuration_module_name_key": …
```

fix: avoid insertion key dupls in `module_configuration` table by upserting on conflict

---

common/configuration/asm.go
common/configuration/asm_test.go
common/configuration/cache.go
common/configuration/manager.go
common/configuration/manual_sync_utils.go

fixes #2092
- mock clock was causing the same race conditions as this issue: https://github.com/TBD54566975/ftl/issues/1368#issuecomment-2087944187
- instead we are now wrapping the ASM provider with a manual sync provider
- This wrapper allows us to trigger when syncs should happen in tests, and block until sync completes

fix: flaky asm tests fixed by wrapping async provider

---

backend/controller/controller.go
backend/controller/dal/dal.go
buildengine/deploy.go

also logs now include old and new deployment keys

fix: wrap errors in ReplaceDeployment, don’t hide errconflicts

---

go-runtime/encoding/encoding.go

fix: ignore unknown ingress fields

---

backend/controller/controller.go

We are storing clients per endpoint. During FTL upgrade we may see controllers try to connect to runners at an endpoint and fail but keep the client around. This may cause the RBAC issues we've seen in production.
This changes the cache to work based on runner key instead of endpoint so that a new runner at an old endpoint will not re-use an old client.

fix: experimental fix for runner connection failures

---

go-runtime/ftl/ftl_integration_test.go

This was disabled due to a bug that is now fixed.

fix: re-enable TestLifecycle

---

.github/workflows/ci.yml

It seems like based on the docs [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks), that a "When a job fails, any jobs that depend on the failed job are skipped and do not report a failure.".
This could be causing the issue where if an integration test fails, the status is reported as `Skipped` vs. `Failed`. The solution described there is "To use a required check on a job that depends on other jobs, use the always() conditional expression in addition to needs, see "[Using jobs in a workflow](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs).""
Here's the original offending CI …

chore: fix integration success to always report status

---

backend/runner/runner.go

We think there may be some issues with runners registering themselves before istio is fully ready, resulting in RBAC errors.
This workaround should allow for a delay that will prevent this.
Possible fix for #2059

fix: add ability to delay runner registration

---

go-runtime/ftl/leases.go
go-runtime/ftl/reflection/reflection.go
go-runtime/ftl/reflection/reflection_test.go
go-runtime/server/server.go

In `.ftl/go/main/main.go` when registering verb handlers, we were calculating the refs for each verb as `Ref{module:subpackage, name:verb}`.
This fixes the conversion from go function to FTL ref by handling subpackages correctly.

fix: allow subpackage's verbs to be called

---

go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/go/two/two.go
go-runtime/schema/call/analyzer.go
go-runtime/schema/common/fact.go
go-runtime/schema/enum/analyzer.go
go-runtime/schema/extract.go
go-runtime/schema/finalize/analyzer.go
go-runtime/schema/metadata/analyzer.go
go-runtime/schema/transitive/analyzer.go
go-runtime/schema/typeenumvariant/analyzer.go

migrates verb call extraction out of the legacy extractor. also supports transitive calls now

feat: extract verb call metadata

---

backend/controller/pubsub/integration_test.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_schema_import.go
cmd/ftl/cmd_serve.go
docker-compose.yml
internal/container/container.go

Also change the default to 15.4 to match production
fixes #2111

fix: allow for postgres image to be specified

---

backend/controller/ingress/handler.go

Also make sure we log errors related to HTTP processing.
closes #2162

fix: don't include error in response

---

cmd/ftl/cmd_schema_diff.go
cmd/ftl/integration_test.go
integration/actions.go

If no remote URI is specified for schema diff it will attempt to diff the local project
closes #2174

feat: add local schema diff

---

frontend/package-lock.json
frontend/package.json

Downgrade `codemirror-json-schema` to fix the massive bundle size based on the comments [here](https://github.com/jsonnext/codemirror-json-schema/issues/125). After downgrading this is the new bundled output:
```sh
> tsc && vite build
vite v4.5.3 building for production...
✓ 1481 modules transformed.
dist/index.html                       0.65 kB │ gzip:   0.41 kB
dist/assets/favicon-2732bf7e.ico     15.41 kB
dist/assets/index-1905dbdc.css       52.20 kB │ gzip:   9.56 kB
dist/assets/index-5b44d2c3.js     1,662.44 kB │ gzip: 526.12 kB
```
Thanks @mistermoe for searching github issues with me! :)

fix: remove all the crazy bundled files

---

internal/rpc/otel_interceptor.go

also adds an array of sent and received message sizes (in addition to the unary fields) for the streaming interceptors

fix: otel rpc metrics also as span attributes

---

backend/controller/observability/pubsub.go

Issue: https://github.com/TBD54566975/ftl/issues/2194
Remove error messages from attribute logging to avoid leaking private info into metrics

feat: remove error message attribute

---

backend/controller/controller.go
backend/controller/observability/async_calls.go
backend/controller/observability/observability.go

These are just the basic metrics. Queue depth up-down counters should come next
```
ScopeMetrics #3
ScopeMetrics SchemaURL: 
InstrumentationScope ftl.async_call 
Metric #0
Descriptor:
-> Name: ftl.async_call.acquired
-> Description: the number of times that the controller tries acquiring an async call
-> Unit: 1
-> ftl.async_call.origin: Str(sub:echo.sub)
-> ftl.async_call.time_since_scheduled_at_ms: Int(24)
-> ftl.async_call.verb.ref: Str(echo.echoSinkOne)
-> ftl.status.succeeded: Bool(true)
StartTimestamp: 2024-07-31 00:33:53.897947 +0000 UTC
Timestamp: 2024-07-31 00:34:08.898478 +0000 UTC
Value: 1
Metric #1
Descriptor:
-> Name: …
```

feat: async call otel metrics

---

scripts/update-workflow-issue

chore: show next in order of priority in Dashboard

---

backend/controller/observability/async_calls.go
backend/controller/observability/observability.go

Printout showing the exact latency value is the same on the counter attr and on the hist metric itself:
```
Metric #2
Descriptor:
-> Name: ftl.async_call.completed
-> Description: the number of times that the controller tries completing an async call
-> Unit: 1
-> ftl.async_call.origin: Str(sub:echo.sub)
-> ftl.async_call.time_since_scheduled_at_ms: Int(39)
-> ftl.async_call.verb.ref: Str(echo.echoSinkOne)
-> ftl.status.succeeded: Bool(true)
StartTimestamp: 2024-07-31 18:54:35.526397 +0000 UTC
Timestamp: 2024-07-31 18:55:10.527278 +0000 UTC
Value: 1
Metric #3
Descriptor:
-> Name: ftl.async_call.ms_to_complete
-> Description: duration in ms to …
```

feat: add new async call latency histogram metric: `ftl.async_call.ms_to_complete`

---

backend/controller/dal/dal.go

fixes #2225
This was breaking pubsub because we would:
- upsert all subscribers and subscriptions to the new deployment (which is the same as the old deployment)
- then delete all subscribers and subscriptions from the old deployment (which is... bad)
We also had comments saying that the func would return that specific error in this case, but we were not returning it.

fix: do not replace deployment with itself

---

backend/controller/cronjobs/sql/models.go
backend/controller/dal/pubsub.go
backend/controller/observability/pubsub.go
backend/controller/sql/models.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/20231103205514_init.sql
backend/controller/sql/schema/20240731230343_create_topic_events_caller.sql
common/configuration/sql/models.go

Previously, only `ftl.pubsub.published` had the caller attribute. This PR adds caller to the rest of the pubsub metrics and also slightly restructures the topic name/ref logging to be more consistent with the rest of this file
```
Metric #0
Descriptor:
-> Name: ftl.pubsub.published
-> Description: the number of times that an event is published to a topic
-> Unit: 1
-> ftl.pubsub.publish.caller.verb.ref: Str(echo.Echo)
-> ftl.pubsub.topic.ref: Str(echo.echotopic)
-> ftl.status.succeeded: Bool(true)
StartTimestamp: 2024-08-01 01:19:43.556864 +0000 UTC
Timestamp: 2024-08-01 01:20:08.558236 +0000 UTC
Value: 1
Metric #1
Descriptor:
-> Name: …
```

feat: propagate `Publish` caller through all pubsub metrics

---

go-runtime/ftl/reflection/reflection.go

It seems that in some curcumstances inlining can break module detection, resulting in incorrect 'must be called from an FTL module' errors.

fix: inlining can break module detection

---

buildengine/testdata/type_registry_main.go
cmd/ftl-controller/main.go
cmd/ftl-runner/main.go
cmd/ftl/cmd_serve.go
go-runtime/compile/build-template/.ftl.tmpl/go/main/main.go.tmpl
go-runtime/compile/build.go
go-runtime/server/server.go
internal/observability/client.go

otel: add `project_name` and `is_user_service` attributes

---

backend/controller/controller.go
backend/controller/dal/async_calls.go
backend/controller/dal/fsm.go
backend/controller/dal/fsm_test.go
backend/controller/dal/pubsub.go
backend/controller/observability/async_calls.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

Adds 2 metrics:
`ftl.async_call.queue_depth` is a gauge, so not all recorded values will appear in the stream. Locally, enqueued async calls complete so quickly that the gauge gets reset to 0 before the incremented value (1) can appear in the stream. I confirmed the enqueue `Record()` does work by temporarily removing the `Record()` call upon completion.
```
Metric #5
Descriptor:
-> Name: ftl.async_call.queue_depth
-> Description: number of async calls queued up
-> Unit: 1
-> DataType: Gauge
StartTimestamp: 2024-08-05 18:13:41.233336 +0000 UTC
Timestamp: 2024-08-05 18:14:01.232978 +0000 UTC
Value: 0
```
`ftl.async_call.created` is a simple counter:
```
Metric #0
Descriptor:
-> Name: ftl.async_call.created
-> Description: the number of times that an async call was …
```

feat: add `ftl.async_call.queue_depth` and `ftl.async_call.created` metrics

---

backend/controller/observability/async_calls.go
backend/controller/observability/observability.go
backend/controller/observability/observability_test.go

This PR bucketizes the latency _attribute_ (NOT the latency _metric_! That would be very bad!)
For better filtering capabilities in datadog, we need to bucket our high-cardinality numeric attributes. This uses log base8 because:
1. That seems to give the most useful results for current production numbers we're seeing in DD - good functional granularity for analysis purposes without being so granular that it's annoying to sort through the buckets. Current values range from 62 to 20279, concentrated in the 100-1000 range.
2. Base 8 bucket labels are all powers of 2, so it's relatively easy for our brains to skim
Sample output:
```
-> ftl.async_call.time_since_scheduled_at_ms.bucket: Str([8,64))
```
Issue: https://github.com/TBD54566975/ftl/issues/2194

feat: bucketize latency attribute

---

backend/controller/controller.go
backend/controller/observability/calls.go
backend/controller/observability/observability.go

Replaces the original toy `requests` metric with `ftl.call.requests` and adds a new `ftl.async_call.ms_to_complete` histogram metric. Latency attribute is bucketed by powers of 2, rather than 8 as async calls are, because (1) direct verb calls should be faster and (2) this is a new metric, so while we know less about realistic production values, it's better to err on the side of more granularity.
```
InstrumentationScope ftl.call 
Metric #0
Descriptor:
-> Name: ftl.call.requests
-> Description: the number of times that the FTL controller receives a verb call request
-> Unit: 1
-> ftl.call.run_time_ms.bucket: Str([8,16))
-> ftl.call.verb.ref: Str(time.time)
-> …
```

feat: add `ftl.call.requests` and `ftl.async_call.ms_to_complete`

---

backend/controller/observability/calls.go

whoops
```
Metric #1
Descriptor:
-> Name: ftl.call.ms_to_complete
-> Description: duration in ms to complete a verb call
-> Unit: ms
-> DataType: Histogram
HistogramDataPoints #0
-> ftl.call.verb.ref: Str(echo.echo)
-> ftl.status.succeeded: Bool(true)
StartTimestamp: 2024-08-06 21:59:38.317129 +0000 UTC
Timestamp: 2024-08-06 22:00:33.317447 +0000 UTC
Count: 1
Sum: 17.000000
Min: 17.000000
Max: 17.000000
```
Issue: https://github.com/TBD54566975/ftl/issues/2194

fix: s/ftl.async_call.ms_to_complete/ftl.call.ms_to_complete

---

backend/schema/metadataretry.go
docs/content/docs/reference/retries.md
lsp/markdown/completion/retry.md

closes #2292
Previous behaviour:
- Default max backoff is 24hrs.
- Default retry count was 100
New behaviour:
- Default max backoff is 1hr (or min backoff if it is larger), but users can specify values up to 24hrs still.
- Default retry count is now 10

fix: more reasonable defaults for retry directives

---

backend/controller/controller.go
backend/runner/runner.go
cmd/ftl/cmd_serve.go

macOS prompts for permission if we do not specify `127.0.0.1`

fix: do not ask to allow incoming connections on macOS

---

backend/schema/validate.go
go-runtime/schema/common/fact.go
go-runtime/schema/enum/analyzer.go
go-runtime/schema/schema_test.go
go-runtime/schema/testdata/two/two.go
go-runtime/schema/transitive/analyzer.go
go-runtime/schema/valueenumvariant/analyzer.go

fixes value enum type validation
const block variants with the same underlying type are correctly associated to their parent enum object
fixes #2254

fix: value enum bugs

---

backend/controller/sql/migrate/migrate.go
backend/controller/sql/migrate/migrate_test.go
backend/controller/sql/migrate/testdata/30280101000000_init.sql
backend/controller/sql/sqltest/testing.go

We'll need to be doing data migrations quite a bit in the near future, and while at some point we will need to do proper [zero downtime migrations](https://teamplify.com/blog/zero-downtime-DB-migrations/) with all that this entails, for now it will be more expedient to accept some downtime. With that in mind, this PR adds a function for applying a mix of SQL and code-based migrations to a database.
An example of where this will be used is our encrypted table columns, which are currently JSONB with a base-64 encoded JSON envelope which we want to move to raw encrypted bytes. We might also need to re-encrypt some data with new keys soon. etc.
Note: this is not hooked up to `ftl migrate` or `ftl dev`'s migration subsystems yet.

feat: add support for code and SQL based database migrations

---

backend/controller/leader/leader.go
backend/controller/leader/leader_test.go
common/configuration/asm.go
common/configuration/asm_follower.go
common/configuration/asm_test.go

We don't want error alerts if a controller is just failing over, this PR adds some infrasturcture to allow for a lower level of error reporting when the errors all occur within the lease TTL.
fixes #2133

fix: don't log at error level in lease timeout

---

cmd/ftl/cmd_new.go

The directory was being prefixed to the path twice.
fixes #2297

fix: ftl new fails

---

backend/controller/controller.go
backend/controller/ingress/handler.go
backend/controller/ingress/handler_test.go
backend/controller/observability/ingress.go
backend/controller/observability/observability.go

```
InstrumentationScope ftl.ingress 
Metric #0
Descriptor:
-> Name: ftl.ingress.requests
-> Description: the number of ingress requests that the FTL controller receives
-> Unit: 1
-> ftl.ingress.method: Str(GET)
-> ftl.ingress.path: Str(/http/echo)
-> ftl.ingress.run_time_ms.bucket: Str([16,32))
-> ftl.ingress.verb.ref: Str(echo.getEcho)
StartTimestamp: 2024-08-12 17:44:51.923107 +0000 UTC
Timestamp: 2024-08-12 17:45:26.923594 +0000 UTC
Value: 1
Metric #1
Descriptor:
-> Name: ftl.ingress.ms_to_complete
-> Description: duration in ms to complete an ingress request
-> Unit: ms
-> DataType: Histogram …
```

feat: otel metrics for ingress

---

java-runtime/ftl-runtime/deployment/src/main/java/xyz/block/ftl/deployment/FtlProcessor.java
java-runtime/ftl-runtime/runtime/src/main/java/xyz/block/ftl/LeaseClient.java
java-runtime/ftl-runtime/runtime/src/main/java/xyz/block/ftl/LeaseFailedException.java
java-runtime/ftl-runtime/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java
java-runtime/ftl-runtime/runtime/src/main/java/xyz/block/ftl/runtime/FTLRecorder.java

Tests will come later as part of a larger testing effort

feat: java lease support

---

backend/controller/sql/databasetesting/devel.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_box_run.go
cmd/ftl/cmd_serve.go
examples/go/echo/go.mod
examples/go/echo/go.sum
ftl-project.toml
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.mod
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.sum
go.mod
go.sum
internal/modulecontext/database.go
internal/observability/client_test.go
internal/reflect/reflect.go
internal/reflect/reflect_test.go

Fixes https://github.com/TBD54566975/ftl/issues/2285
Register the standard otel database metrics using: https://github.com/XSAM/otelsql
Found call sites by grepping for `sql.Open` and skipping all test code.
Sample:
```
ScopeMetrics #2
ScopeMetrics SchemaURL: 
InstrumentationScope github.com/XSAM/otelsql 0.32.0
Metric #0
Descriptor:
-> Name: db.sql.latency
-> Description: The latency of calls in milliseconds
-> Unit: ms
-> DataType: Histogram
HistogramDataPoints #0
-> method: Str(sql.conn.begin_tx)
-> status: Str(ok)
StartTimestamp: 2024-08-08 23:18:01.011762 +0000 UTC
Timestamp: 2024-08-08 23:18:11.012177 +0000 UTC
Count: 23
Sum: 17.082795
Min: 0.137584
Max: 3.233917
```

feat: register db.sql metrics

---

docs/content/docs/reference/matrix.md

Probably incomplete and inaccurate, we will iterate on it.
Fixes #2344

docs: add feature matrix

---

.github/workflows/ci.yml

The label must be added as the PR is being created, not afterwards.

ci: run integration tests if the PR is labelled with "run-integration"

---

backend/controller/console/console.go
backend/controller/cronjobs/sql/models.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/dal/events.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/20240814060154_rename_events_to_timeline.sql
common/configuration/sql/models.go
internal/encryption/encryption.go
internal/encryption/encryption_test.go
internal/encryption/integration_test.go

1. Renamed the "events" table to "timeline" to more clearly reflect its purpose and usage.
2. Renamed the encryption key from "logs" to "timeline" as the events table contains more than just logs. This just makes things a bit clearer.

fix: rename some timeline related names

---

backend/controller/admin/local_client_test.go
backend/controller/console/console_integration_test.go
backend/controller/cronjobs/cronjobs_integration_test.go
backend/controller/dal/fsm_integration_test.go
backend/controller/ingress/ingress_integration_test.go
backend/controller/leases/lease_integration_test.go
backend/controller/pubsub/integration_test.go
backend/controller/sql/database_integration_test.go
cmd/ftl/integration_test.go
common/projectconfig/integration_test.go
go-runtime/compile/compile_integration_test.go
go-runtime/encoding/encoding_integration_test.go
go-runtime/ftl/ftl_integration_test.go
go-runtime/ftl/ftltest/ftltest_integration_test.go
go-runtime/ftl/integration_test.go
go-runtime/ftl/reflection/reflection_integration_test.go
go-runtime/internal/integration_test.go
integration/actions.go
integration/harness.go
internal/encryption/integration_test.go
java-runtime/java_integration_test.go

Previously we had full test coverage in each language, so we would just run them all, but as we're building up support for other languages for now, this change allows multiple languages to be supported per-test.
Also cleans up the test harness so there's just a single Run() function whose behaviour can be configured.

refactor: extend the integration testing framework to support multiple languages

---

backend/controller/sql/databasetesting/devel.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_box_run.go
cmd/ftl/cmd_serve.go
examples/go/echo/go.mod
examples/go/echo/go.sum
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.mod
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.sum
go.mod
go.sum
internal/modulecontext/database.go
internal/observability/client_test.go
internal/reflect/reflect.go
internal/reflect/reflect_test.go

revert: "feat: register db.sql metrics (#2305)"

---

.github/workflows/ci.yml

Running just build-all will cause these changes, commiting them so that building does not modify source controlled files.
Also add a check for this so we won't get into this state in future.

chore: update versions in files

---

java-runtime/ftl-runtime/deployment/src/main/java/xyz/block/ftl/deployment/FtlProcessor.java

fix: java types should be auto exported when appropriate

---

go-runtime/ftl/database.go
internal/modulecontext/database.go
internal/modulecontext/module_context.go

The ModuleContext was designed to be an abstract data model in the Controller for the resources required by a module, but along the way it started to be used for storing DB connections for use by the go-runtime. This change cleanly separates those requirements so that the go-runtime is entirely responsible for creating new connections from the DSN provided by the ModuleContext.
I think there's a bit more work to be done here, in that the ModuleContext knows about testing in the go-runtime, which it really shouldn't, but this will unblock #2373 for now.

refactor: decouple conflicting ModuleContext requirements

---

backend/controller/dal/dal_test.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
cmd/ftl/cmd_serve.go

The workaround is to do a dummy update and return the updated id.

fix: turns out ON CONFLICT DO NOTHING doesn't work with RETURNING

---

jvm-runtime/java/scaffolding/go.mod
jvm-runtime/kotlin/scaffolding/go.mod

Without these the Go toolchain tries to scan the directories and fails due to the | characters, which are not supported by Go's build system.
Fixes the following failure:
```
info: go: finding module for package github.com/TBD54566975/ftl/go-runtime/ftl
go: downloading github.com/TBD54566975/ftl v0.345.0
go: ftl/builtin imports
github.com/TBD54566975/ftl/go-runtime/ftl: create zip: jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/ftl.toml: malformed file path "jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/ftl.toml": invalid char '|'
jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl: malformed file path "jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl": invalid char '|'
jvm-runtime/java/scaffolding/{{ .Name | camel | lower …
```

fix: add go.mod file to jvm scaffolding dirs

---

.github/workflows/ci.yml
internal/buildengine/testdata/depcycle1/go.mod
internal/buildengine/testdata/depcycle2/go.mod
internal/integration/harness.go
jvm-runtime/jvm_integration_test.go

fix(integration): create a new test dir per language

---

backend/controller/controller.go
backend/controller/pubsub/integration_test.go
backend/controller/pubsub/testdata/go/subscriber/subscriber.go
backend/schema/builtin.go
backend/schema/schema_test.go
backend/schema/validate.go
backend/schema/validate_test.go

closes #2213
`builtin.CatchRequest` now has the following features:
- the associated request type can be `any` to allow for catching multiple verbs with different request types
- The request will be unmarshalled to primitives (like string, int, map, array etc) rather than ftl structs
- Includes the verb that failed as a `builtin.Ref`, which is a data type with `module` and `name` strings
- Includes the request type as a string, eg: `example.Input`, `String`, etc
- Originally I had this as a `builtin.Ref` but that doesnt work for non-ref types
There is certainly room for improvement in terms of how we want to expose these schema definitions, but this PR doesn't try go too far down that road.

feat: allow catch verbs to receive request types as `any`

---

go-runtime/schema/schema_test.go
go-runtime/schema/testdata/two/go.mod
go-runtime/schema/testdata/two/two.go
go-runtime/schema/typealias/analyzer.go

fixes #2397
`pass.Pkg.Imports()` did not always* include the local name alias from the import statement, so instead we need to do our checks via `PkgName` which does include it.
*it includes it in the example in our tests, but didn't in the case that our partner project was hitting...
I've added another test case that previously failed like theirs did.

fix: handle custom local names for widened types

---

backend/controller/controller.go
backend/controller/cronjobs/cronjobs_integration_test.go
backend/controller/cronjobs/cronjobs_test.go
backend/controller/dal/async_calls_test.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/dal/encryption.go
backend/controller/dal/fsm_test.go
backend/controller/dal/lease_test.go
backend/controller/sql/sqltest/testing.go
cmd/ftl-controller/main.go
internal/encryption/encryption.go
internal/encryption/encryption_test.go
internal/encryption/integration_test.go

refactor: encryption refactor

---

backend/controller/sql/databasetesting/devel.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_box_run.go
cmd/ftl/cmd_serve.go
examples/go/echo/go.mod
examples/go/echo/go.sum
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.mod
go-runtime/ftl/reflection/testdata/go/runtimereflection/go.sum
go.mod
go.sum
internal/observability/client_test.go
internal/observability/db.go
internal/reflect/reflect.go
internal/reflect/reflect_test.go

Fixes https://github.com/TBD54566975/ftl/issues/2285
Unreverts https://github.com/TBD54566975/ftl/pull/2305 with these changes:
* Reverts [`copyAny`](https://github.com/TBD54566975/ftl/blob/main/internal/reflect/reflect.go#L149) changes except for the `list.List` handling.
* The original PR caused a panic when deploying to prod: `reflect: internal error: must be a Pointer or Ptr; got unsafe.Pointer`
* https://github.com/TBD54566975/ftl/pull/2376 removed the DB handles from the module context Database struct, so we no longer need to handle all these types in `DeepCopy`.
* Updates all `reflect.Ptr` refs to `reflect.Pointer`. Not a big deal, but `Ptr` is the [old name](https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/reflect/type.go;l=303), and since we're using `reflect.Pointer` …

feat: un-revert registration of `db.sql` metrics

---

frontend/src/features/verbs/VerbPage.tsx

Less broke now! 😂 
I think with streaming queries, `isLoading` will always be true with tanstack since it's like streaming yo.

fix: console verb page loading

---

backend/controller/observability/async_calls.go
backend/controller/observability/calls.go
backend/controller/observability/ingress.go
backend/controller/observability/observability.go
backend/controller/observability/observability_test.go

Fixes https://github.com/TBD54566975/ftl/issues/2286
This PR introduces the ability to constrain `logBucket` with a max and min bucket. Log buckets just bucket numbers (in this case, ms latency):
Example for base 4:
```
<1, [1,4), [4,16), [16,64), [64,256), [256,1024), [1024,4096), ...
```
In DataDog, looking across the last week, we see several latency buckets displaying low counts in the noise, especially on the buckets closer to 1. This makes sense given the intrinsic nature of log buckets - they are densest close to 1 and sparser the further up you go. To reduce cardinality (thus, cost), we can chop away that noise at the low end.
It's similarly worth capping the buckets at the high end because although the buckets get exponentially larger, you can still have infinitely more buckets. …

feat: tune latency attribute buckets to reduce cardinality

---

frontend/src/features/calls/CallList.tsx

Preserve the alignment of flex-width columns when resizing browser window.
Updated:
Before fix:

feat: set min width on flex columns in the console's calls table

---

frontend/src/features/calls/CallList.tsx

Set min width on console's calls table to prevent tbody rows from getting chopped.
Steps to reproduce:
1. Make browser window so small that the table cannot fit
1. Scroll to the table all the way to the right to see the full Error column
1. Observe how the border lies too far to the left, chopping off the contents of the table below the header.
Before fix:
Issue: https://github.com/TBD54566975/ftl/issues/2460

feat: fix browser resizing + scrolling bug on console table rendering

---

frontend/src/features/timeline/TimelineCall.tsx
frontend/src/features/timeline/TimelineDeploymentCreated.tsx
frontend/src/features/timeline/TimelineDeploymentUpdated.tsx
frontend/src/features/timeline/TimelineLog.tsx

The Content column in the timeline table can be truncated when the browser window is small, but doesn't display its contents on hover. 
https://github.com/TBD54566975/ftl/issues/2460

feat: add titles (show on hover) to truncate-able columns in console tables

---

backend/controller/cronjobs/sql/models.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/dal/encryption.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/20240820011612_encryption_verification.sql
internal/configuration/sql/models.go
internal/encryption/database.go
internal/encryption/encryption.go

fix: bug with subkeys, verify test fields on startup

---

.github/workflows/ci.yml
Justfile
frontend/.gitignore
frontend/biome.json
frontend/package-lock.json
frontend/package.json
frontend/playwright.config.ts
frontend/src/layout/navigation/Navigation.tsx
frontend/tests/deployment.spec.ts
frontend/tests/deployments.spec.ts
frontend/tests/events.spec.ts
frontend/tests/ftl-test.ts
frontend/tests/verb.spec.ts

chore: add console e2e testing with playwright

---

frontend/src/components/CodeEditor.tsx
frontend/src/components/ResizeableVerticalPanels.tsx
frontend/src/features/verbs/VerbFormInput.tsx
frontend/src/features/verbs/VerbRequestForm.tsx

Issue: https://github.com/TBD54566975/ftl/issues/2458
Changes:
* Response panel is only displayed when `Body` tab (i.e. Request tab) is selected, instead of taking screen real estate away from the read-only schema tabs
* Border between request and response panels is replaced with a full-width draggable handle
* Related: fixed the existing bugs in `components/ResizeableVerticalPanels.tsx`
* All codemirror components automatically take the full height of their container
https://github.com/user-attachments/assets/9594c696-1ddb-4412-bd13-722c73cd7662

fix: clean up codemirror panel resizing

---

frontend/src/components/CodeEditor.tsx

Fixes https://github.com/TBD54566975/ftl/issues/2458
Before, tabbing would change the focus to the next element on the page. This adds the correct key binding so that hitting tab within the codemirror editor actually inserts 2 spaces.

feat: hitting tab key inserts a tab in codemirror

---

internal/encryption/encryption.go
internal/mutex/mutex.go

There is a situation where getDerivedPrimitive can be called concurrently, and two separate keys will be created. This fixes that issue.
Also added a type-safe Mutex type.

fix: concurrency issue in getDerivedPrimitive

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/java/integration-tests/src/main/java/xyz/block/ftl/java/runtime/it/FtlJavaRuntimeResource.java
jvm-runtime/ftl-runtime/java/runtime/src/main/java/xyz/block/ftl/runtime/processor/AnnotationProcessor.java
jvm-runtime/ftl-runtime/java/runtime/src/main/resources/META-INF/services/javax.annotation.processing.Processor

This is a very basic PoC implementation that can serve as a base for further work.

feat: use JavaDoc as comments
