backend/controller/ingress/handler.go

fix: scope ingress logs with the request signature

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/ftltest/ftltest_test.go
go-runtime/ftl/ftltest/testdata/go/verbtypes/verbtypes_test.go

Adds a new `SubContext` function, that replays options from a previous fakeFTL creation, appending new options to it.
Closes https://github.com/TBD54566975/ftl/issues/2393

chore: support extending ftltest context with additional options

---

frontend/src/components/CodeEditorV2.tsx
frontend/src/features/modules/decls/VerbPanel.tsx
frontend/src/features/modules/decls/VerbRequestEditor.tsx

Adds new externally-controlled codemirror component with a reset button
Really basic, UI-side only. Doesn't hook into actually sending the call yet.
https://github.com/user-attachments/assets/f773bf49-6bb4-4ed9-862d-2f4b180b151b

feat: console: add verb request editor + reset button

---

frontend/playwright.config.ts

Hoping to make the `Console e2e` tests more stable.

fix: avoid reusing servers for e2e tests

---

backend/controller/controller.go

fixes #2554
Current theory is this:
- cluster has a low number of modules active (let's say 0)
- gRPC call comes into controller to PullSchema
- this causes us to subscribe to schema changes, with a chan with the length of the count of the current active modules (in our example, 0)
- The lib then creates an extra buffer to queue up messages while the subscriber processes messages, with the buffer being the same size as the provided chan (again, 0)
- As a change schema change message is received by the subscriber, we stream the message back over gRPC. This may take time.
- While this is happening, another schema update may occur. the lib will not be able to ack the message because the buffer size is too small (0) so it will wait for the message to be received.
- the lib will timeout if the …

fix: prevent tiny buffer preventing subscriber acking message quickly

---

frontend/biome.json
frontend/e2e/ftl-test.ts
frontend/e2e/infrastructure.spec.ts
frontend/src/components/Pill.tsx
frontend/src/components/Tabs.tsx
frontend/src/features/infrastructure/ControllersList.tsx
frontend/src/features/infrastructure/DeploymentsList.tsx
frontend/src/features/infrastructure/InfrastructurePage.tsx
frontend/src/features/infrastructure/RoutesList.tsx
frontend/src/features/infrastructure/RunnersList.tsx
frontend/src/layout/navigation/Navigation.tsx
frontend/src/stories/Pill.stories.ts
frontend/src/stories/Tabs.stories.ts

See #2552
Also created new `Tabs` and `Pill` components

feat: add infrastructure tabs and state

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/FTLDotNames.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/JVMCodeGenerator.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TypeAliasBuildItem.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TypeAliasProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TypeKey.java
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/TypeAlias.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/TypeAliasMapper.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/JsonSerializationConfig.java
jvm-runtime/ftl-runtime/common/runtime/src/test/java/xyz/block/ftl/runtime/JsonSerializationConfigTest.java
jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/JavaCodeGenerator.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java
jvm-runtime/jvm_integration_test.go
jvm-runtime/testdata/go/gomodule/go.mod
jvm-runtime/testdata/go/gomodule/go.sum
jvm-runtime/testdata/go/gomodule/server.go
jvm-runtime/testdata/java/passthrough/pom.xml
jvm-runtime/testdata/java/passthrough/src/main/java/xyz/block/ftl/test/DidMapper.java
jvm-runtime/testdata/java/passthrough/src/main/java/xyz/block/ftl/test/TestInvokeGoFromJava.java
jvm-runtime/testdata/kotlin/passthrough/pom.xml
jvm-runtime/testdata/kotlin/passthrough/src/main/kotlin/xyz/block/ftl/test/DidMapper.kt
jvm-runtime/testdata/kotlin/passthrough/src/main/kotlin/xyz/block/ftl/test/TestInvokeGoFromKotlin.kt

fix: use typemap in JVM

---

backend/controller/dal/notify.go
backend/controller/sql/schema/20240902030242_remove_notify.sql

closes #2156
- pubsub was never using the pg_notify events, but the controller was listening for them anyway
- deployment updates we switched to a polling approach and seems to be working fine.
- This PR cleans up the code and sql that is no longer being used.
@alecthomas  Feel free to reject this PR if you want to keep this streaming code because you think it's worth bringing it back in the future.

chore: remove usused pg_notify code

---

frontend/.gitignore
frontend/console/e2e/infrastructure.spec.ts
frontend/console/src/components/List.tsx
frontend/console/src/components/StatusIndicator.tsx
frontend/console/src/features/infrastructure/ControllersList.tsx
frontend/console/src/features/infrastructure/DeploymentsList.tsx
frontend/console/src/features/infrastructure/InfrastructurePage.tsx
frontend/console/src/features/infrastructure/RoutesList.tsx
frontend/console/src/features/infrastructure/RunnersList.tsx
frontend/console/src/features/infrastructure/infrastructure.utils.ts
frontend/console/src/providers/routing-provider.tsx

feat: add infrastructure tabs and content

---

frontend/cli/cmd_box.go
frontend/cli/cmd_build.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_dev.go
go-runtime/compile/build.go
internal/buildengine/build.go
internal/buildengine/build_go.go
internal/buildengine/engine.go
internal/exec/exec.go

This allows for multi platform builds on go

feat: allow for build env vars

---

frontend/console/src/features/modules/ModulesTree.tsx

fix: use icon to indicate exported

---

frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/decls/ConfigPanel.tsx
frontend/console/src/features/modules/decls/DataPanel.tsx
frontend/console/src/features/modules/decls/DatabasePanel.tsx
frontend/console/src/features/modules/decls/DeclLink.tsx
frontend/console/src/features/modules/decls/DeclPanel.tsx
frontend/console/src/features/modules/decls/EnumPanel.tsx
frontend/console/src/features/modules/decls/PanelHeader.tsx
frontend/console/src/features/modules/decls/SecretPanel.tsx
frontend/console/src/features/modules/decls/TypeAliasPanel.tsx
frontend/console/src/features/modules/decls/TypeEl.tsx
frontend/console/src/features/modules/decls/VerbPanel.tsx

Part 1 of https://github.com/TBD54566975/ftl/issues/2616
Adds (or significantly adds to) pages for the following decl types:
* config
* data
* database
* enum
* secret
* typealias
Not yet added: FSM, topic, subscription
Adds components for:
* `DeclLink`: takes a ref and links to the page for that decl
* `TypeEl`: renders an appropriate string for a given Type, with links if appropriate
* `PanelHeader` renders the standard decl panel page header (e.g. comments, export badge)

feat: new console pages for config, data, database, enum, secret, and typealias

---

frontend/console/src/components/ResizableHorizontalPanels.tsx
frontend/console/src/features/modules/ModulesTree.tsx

Fixes https://github.com/TBD54566975/ftl/issues/2610
Issues fixed:
* The `export` icons:
* Used to compress to a smaller size when you resized the tree panel smaller than the width of the decl's row. Now, the size is fixed.
* Added on-hover text so users can find out what it means more easily.
* Panel resizing handle: 
* Got rid of its background color so it's invisible until used
* Set the width back to its original 3px, which is easier to use and not a problem now that it's invisible. I originally adjusted it down to 2px to be less visually intrusive.
* Fixed the on-hover color in dark mode so it's always easy to latch onto it now.
* Highlight color of each decl row would only extend as far as the right-side border minus padding+margin. However, text would overflow beyond that container …

fix: polish module tree scroll and resize actions

---

frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx

fix(bug): time range selection

---

frontend/console/package.json
frontend/console/src/features/command-pallete/CommandPalette.tsx
frontend/console/src/features/command-pallete/command-palette.utils.ts
frontend/console/src/layout/navigation/SearchInput.tsx
pnpm-lock.yaml

Fixes #2626 
- also add struct field names

feat: add fuzzy search to console

---

backend/controller/admin/admin.go
internal/configuration/api.go
internal/configuration/manager/cache.go
internal/configuration/manager/manager.go
internal/configuration/manager/manager_test.go
internal/configuration/providers/1password_provider.go
internal/configuration/providers/asm.go
internal/configuration/providers/db_config_provider.go
internal/configuration/providers/envar_provider.go
internal/configuration/providers/inline_provider.go
internal/configuration/providers/keychain_provider.go
internal/configuration/providers/providerstest/manual_sync_utils.go
internal/configuration/providers/registry.go
internal/configuration/routers/file_router.go
internal/configuration/routers/file_router_test.go
internal/profiles/internal/persistence.go
internal/profiles/profiles.go
internal/profiles/profiles_test.go
internal/projectconfig/projectconfig.go

This adds the beginnings of a high-level package for initialising a project, saving and loading profiles. There's also a lower-level API over the storage mechanism.
Design: https://hackmd.io/@ftl/Sy2GtZKnR

feat: start of profile support

---

frontend/console/src/features/modules/decls/DeclPanel.tsx
frontend/console/src/features/modules/decls/FsmPanel.tsx
frontend/console/src/features/modules/decls/TypeEl.tsx

Tested with `ftl dev --recreate backend/controller/dal/testdata/go/fsm`
This PR steals the `RefLink` change from https://github.com/TBD54566975/ftl/pull/2662, so whichever one merges first, the other will have to rebase.
Later, we should make this a graph, but for this base page, the list of links is sufficient.
Fixes https://github.com/TBD54566975/ftl/issues/2616

feat: add console decl page for fsm

---

backend/controller/controller.go
backend/controller/cronjobs/cronjobs.go
backend/controller/cronjobs/cronjobs_test.go
backend/controller/cronjobs/dal/internal/sql/models.go
backend/controller/dal/fsm.go
backend/controller/dal/internal/sql/models.go
backend/controller/dal/internal/sql/queries.sql.go
backend/controller/dal/pubsub.go
backend/controller/encryption/dal/dal.go
backend/controller/encryption/dal/internal/sql/models.go
backend/controller/leases/dal/internal/sql/models.go
backend/controller/sql/schema/20240913035022_encrypted_fsm_next_request.sql
backend/controller/sql/schema/20240913041619_encrypted_topic_events_payload.sql
internal/configuration/dal/internal/sql/models.go
internal/encryption/database.go
internal/encryption/encryption.go

Make EncryptedColumn a struct so we can't accidentally implicitly convert `[]byte` to/from it. As a side-effect, discovered a few columns in the DB that weren't the correct types.

fix: prevent implicit conversions to/from EncryptedColumn

---

Justfile

Turns out using {{X}} in a global doesn't get interpolated by Just. This resulted in files like the literal `{{CONSOLE_ROOT}}/foo/bar`, which don't exist, being used for dependency checks, triggering rebuilds on every invocation.
In particular this would trigger proto rebuilds and console rebuilds, the latter of which was quite time consuming :\

chore: fix Justfile refs

---

backend/controller/controller.go

Polling the deployments should only be done once, not once per connection

fix: single poll loop

---

renovate.json5

This should fix some of the issues we are having on renovate pull requests

fix: run pnpmDedupe after renovate update

---

frontend/console/index.html
frontend/console/src/features/infrastructure/InfrastructurePage.tsx

Fixes https://github.com/TBD54566975/ftl/issues/2698
There were actually two underlying issues fixed here:
1. If you hard scroll down on any page in dark mode, the `<body>` element would not respect dark mode, so you could still see white bg underneath. That's gross. It's fixed now in `index.html`.
2. On the infrastructure page specifically, we never set the page body's overflow behavior to scroll, so instead it would overflow the container. Technically, with 1 fixed, you wouldn't even notice this issue, but it was still worth fixing to future-proof the page.

fix: console background color scroll bug

---

frontend/console/src/features/modules/decls/DataPanel.tsx
frontend/console/src/features/modules/decls/DataSnippet.tsx
frontend/console/src/features/modules/decls/DeclLink.tsx
frontend/console/src/features/modules/decls/DeclSnippet.tsx
frontend/console/src/features/modules/decls/EnumPanel.tsx
frontend/console/src/features/modules/decls/EnumSnippet.tsx
frontend/console/src/features/modules/decls/PanelHeader.tsx
frontend/console/src/features/modules/decls/TypeAliasPanel.tsx
frontend/console/src/features/modules/decls/TypeAliasSnippet.tsx
frontend/console/src/features/modules/decls/TypeEl.tsx
frontend/console/src/features/modules/decls/enum.utils.ts

Fixes https://github.com/TBD54566975/ftl/issues/2673
This only adds the snippet implementations for data, enum, and typealias, since those are the types that currently would actually come up as a link in a decl panel.
This also changes the static decl panel bodies for enum + data to follow the actual FTL schema format.

feat: show schema snippets on hover of decl links in the console

---

backend/controller/controller.go
backend/runner/runner.go

With the recent changes to the protocol and to routing there is no real need for the controller to ping the runner. This ping was causing the ISTIO RBAC issues that resulted in us disabling the health check.
fixes: #2710

fix: restore kube health check

---

frontend/console/src/features/console/ConsolePage.tsx
frontend/console/src/features/timeline/TimelinePage.tsx
frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx
frontend/console/src/layout/Page.tsx

Part 1 of https://github.com/TBD54566975/ftl/issues/2490
Deletes the `Page.Header` component, which is an artifact of a bygone era.
Since the timeline page also had a time range filter embedded in the header, I moved that over to the left-hand-side filter panel. It just need a tiny bit of resizing to fit.

chore: remove Page.Header console component

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/jvm_integration_test.go

fix: JVM Map value type extraction

---

frontend/cli/main.go
go.mod
go.sum

feat: bash completion

---

frontend/cli/cmd_interactive.go
frontend/cli/main.go
go.mod

feat: completion for interactive mode

---

.go-arch-lint.yml
.goreleaser.yaml
Justfile
cmd/ftl
scripts/ftl

It's annoying because some editors will index both directories and every file will show up twice.

chore: delete cmd/ftl symlink

---

frontend/console/package.json
pnpm-lock.yaml

This PR introduces the usage of `please-use-pnpm` to cause usage of `npm` or `yarn` to bork e.g.
```
❯ npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'console@0.0.0',
npm warn EBADENGINE   required: {
npm warn EBADENGINE     npm: 'please-use-pnpm',
npm warn EBADENGINE     yarn: 'please-use-pnpm',
npm warn EBADENGINE     pnpm: '>=9.9.0',
npm warn EBADENGINE     node: '>=22.7.0'
npm warn EBADENGINE   },
npm warn EBADENGINE   current: { node: 'v22.8.0', npm: '10.8.2' }
npm warn EBADENGINE }
npm error code 127
npm error path /path/to/ftl/node_modules/.pnpm/@codemirror+state@6.4.1/node_modules/@codemirror/state
npm error command failed
npm error command sh -c cm-buildhelper src/index.ts
npm error sh: cm-buildhelper: command not found
npm error A complete …
```

fix: error out if `npm` is used

---

go-runtime/compile/build.go

Let's see if this helps with the upstream flakiness

chore: disable HTTP/2 for module builds

---

internal/bind/bind_allocator.go

The port can change between when we increment and when we return the value. This can cause ports to not be unique when calling `Next()`.

fix: avoid race when allocating ports

---

frontend/cli/cmd_dev.go
internal/buildengine/engine.go

I think this is important as if this starts to creep up it is bad for developer experience, and printing it out each time makes us much more likely to notice if things are slowing down.

feat: print time taken to start

---

backend/controller/scaling/k8sscaling/deployment_provisioner.go
backend/controller/scaling/localscaling/local_scaling.go

If we delete the deployments/runners straight away it may still be in some controllers route tables. By adding a small delay we make sure that all the controllers will have updated their table.
This is a pretty nasty hack, but will likely be temporary.
fixes: #2789

fix: rolling deployments race

---

backend/controller/scaling/localscaling/local_scaling.go

This code is no longer called under lock, we need to check that the runner is still valid

fix: local scaling panic

---

examples/java/echo/ftl.toml
examples/java/echo/pom.xml
examples/java/echo/src/main/java/ftl/echo/Echo.java
examples/java/echo/src/main/java/ftl/echo/EchoRequest.java
examples/java/echo/src/main/java/ftl/echo/EchoResponse.java
examples/java/time/ftl.toml
examples/java/time/pom.xml
examples/java/time/src/main/java/ftl/time/Time.java
examples/java/time/src/main/java/ftl/time/TimeResponse.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java

Also add a Java example
fixes: #2746

fix: disallow non-static inner classes

---

internal/console/status.go

This might help keep some icon/ideas in sync between cli and console.
Changing from:
```sh
const BuildStateWaiting BuildState = " 🚦️"
const BuildStateBuilding BuildState = " 🏗️"
const BuildStateBuilt BuildState = "📦️️"
const BuildStateDeploying BuildState = " 🚚️"
const BuildStateDeployed BuildState = " ✅️️"
const BuildStateFailed BuildState = "💥"
```
To:
```sh
const BuildStateWaiting BuildState = " 🕗"
const BuildStateBuilding BuildState = " 🛠️"
const BuildStateBuilt BuildState = " 📦️️"
const BuildStateDeploying BuildState = " 🚀"
const BuildStateDeployed BuildState = " ✅"
const BuildStateFailed BuildState = " ❌"
```

fix: update cli status icons

---

renovate.json5

This should split out Java and Javascript updates to make the resulting PRs easier to manage.
The current PRs can end up with multiple cross ecosystem issues that require more colaberation to fully resolve.

chore: create seperate renovate PRs

---

internal/log/plain.go

We should colour the module names in the status line too, so it's easier to visually associate them with their logs.

feat: deterministically set the colour of log scopes

---

frontend/cli/cmd_dev.go
frontend/cli/cmd_interactive.go
frontend/cli/main.go
internal/terminal/interactive.go
internal/terminal/status.go

Instead of passing around all the parameters required manually, we capture them in a closure once at startup.

refactor: simplify terminal.KongContextBinder

---

frontend/cli/cmd_serve.go
frontend/console/src/features/verbs/VerbFormInput.tsx
frontend/console/src/features/verbs/VerbRequestForm.tsx
frontend/console/src/features/verbs/verb.utils.ts
frontend/console/src/layout/Notification.tsx
frontend/console/src/providers/app-providers.tsx

Fixes #2720
Fixes #2753 (will add similar functionality to request/events page in the future)
With this change we can now see `ingress` events are part of the request since we're using fetch.
Copy `curl`
Copy `ftl.call`

feat: send ingress requests via http

---

scripts/ftlDebug

This makes it easy to run FTL under dlv, and dlv will wait for the IDE to attach. This is useful if you want to debug commands other than ftl dev

chore: add ftlDebug script

---

Justfile
backend/controller/pubsub/integration_test.go
internal/integration/harness.go

By adding a bunch of t.Helper() calls.
Before:
```
=== NAME  TestLeaseFailure/go
/Users/alec/dev/ftl/internal/integration/harness.go:267: Timed out waiting for assertion to pass: Expected values to be equal:
-error
+executing
```
After:
```
=== NAME  TestLeaseFailure/go
/Users/alec/dev/ftl/backend/controller/pubsub/integration_test.go:178: Timed out waiting for assertion to pass: Expected values to be equal:
-error
+executing
--- FAIL: TestLeaseFailure (22.26s)
--- FAIL: TestLeaseFailure/go (18.18s)
```

chore: report file location of the integration test that failed

---

backend/controller/controller.go
backend/controller/pubsub/service.go
backend/controller/scheduledtask/scheduledtask.go
backend/controller/scheduledtask/scheduledtask_test.go
backend/controller/sql/databasetesting/devel.go

Singleton scheduled tasks were broken due to the job functions being wrapped. This was causing the derived name for each job to be the same, which meant they all competed for the same lease.
Since we recently added a name for each of the scheduled tasks, this PR passes those names along to the scheduler rather than relying on a derived name.

fix: scheduled tasks should not derive names

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java

feat: enforce FTL name rules in JVM

---

backend/controller/controller.go

As the sync works on module name rather than deployment when a deployment is removed it will remove any newer version of the module.
This PR changes to build the schema in the same function as the route table, so they stay in sync.
At persent this is not an atomic operation however, so there is a slight possibility for a request to see a new schema for an old route table, however this is still way better than the current situation.

fix: schema sync is broken

---

Justfile

This was because `just build-sqlc` didn't have correct dependencies, resulting in it always rebuilding. I've updated it to pull the dep locations directly out of sqlc.yaml, which will future-proof it.
Fixes #2846

fix: just dev now works

---

.gitignore
frontend/cli/cmd_init.go
frontend/cli/cmd_profile.go
frontend/cli/main.go
internal/profiles/internal/persistence.go
internal/profiles/profiles.go
internal/profiles/profiles_test.go

Also refactor profiles package a bit to be more flexible.
```
🐚 ~/dev/ftl $ ftl profile init ftl
Project initialized in /Users/alec/dev/ftl.
🐚 ~/dev/ftl $ ftl profile new --local test
🐚 ~/dev/ftl $ ftl profile list
local (local, default)
test (local)
🐚 ~/dev/ftl $ ftl profile switch test
🐚 ~/dev/ftl $ ftl profile list
local (local, default)
test (local, active)
```

feat: add "ftl profile ..." command tree

---

deployment/CODEOWNERS
frontend/CODEOWNERS
go-runtime/CODEOWNERS
jvm-runtime/CODEOWNERS

This will assign a single reviewer rather than every single CODEOWNER being assigned. GitHub is annoying.

chore: add teams for the various subsystems

---

backend/schema/module.go
frontend/console/src/features/modules/schema/schema.utils.ts
go-runtime/schema/schema_fuzz_test.go
go-runtime/schema/schema_test.go

Fixes: https://github.com/TBD54566975/ftl/issues/2803
Also fixed a separate issue where one of the decl types configured for the filter had the wrong display name.

fix: update type spacing rules

---

frontend/console/src/components/Divider.tsx
frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/traces/TracesPage.tsx

fix: minor tweaks to module type filter

---

go-runtime/compile/build.go

sometimes these need to be genned even if they're not referenced by the main module, e.g. the request in an external verb for which the main module needs a client. we need to generate the client with its resolved request type

fix: imports for non-referenced external types

---

backend/provisioner/provisioner_integration_test.go
backend/provisioner/service.go
backend/provisioner/testdata/go/echo/echo.go
backend/provisioner/testdata/go/echo/ftl.toml
backend/provisioner/testdata/go/echo/go.mod
cmd/ftl-provisioner/main.go
frontend/cli/cmd_deploy.go
frontend/cli/main.go
internal/buildengine/deploy.go
internal/integration/actions.go
internal/integration/harness.go

runs deployments through the provisioner if requested
This also adds a hidden CLI flags
`--use-provisioner` to deploy using the provisioner service instead of controller
`--provisioner-endpoint` to set the provisioner endpoint
Next, I will look how to integrate `ftl-provisioner` better with `ftl serve`

chore: integration test option to use `ftl-provisioner`

---

Dockerfile.controller
Justfile

Reduces the image size from 381MB to 94MB:
```
ftl0/ftl-controller                    latest                                     37007a93754e   2 minutes ago       93.9MB
ftl0/ftl-controller                    <none>                                     66ae6a69737d   3 months ago        381MB
```

feat: use "scratch" base image for ftl-controller

---

renovate.json5

Fixes:
```
Post-upgrade command 'pnpm install' has not been added to the allowed list in allowedPostUpgradeCommands
```

chore: allow "pnpm install" to be run as a post-upgrade command

---

internal/terminal/status.go

fix: remove module from status line

---

.github/actions/build-cache/action.yml

I am not 100% sure this will work, but the docs seem to imply it will.

fix: don't cache SNAPSHOT versions

---

frontend/cli/main.go

This fixes the most common cases of this, but it still could happen if os.Exit is called elsewhere.
Fixes #2866

fix: FTL truncating output

---

backend/runner/runner.go
docs/content/docs/reference/verbs.md

fix: user errors are not logged

---

go-runtime/compile/build.go
internal/buildengine/testdata/alpha/types.ftl.go
internal/buildengine/testdata/type_registry_main.go

visit all children of resolved refs rather than just the resolved decl itself so we don't miss any types referenced by the main module

fix: missing types in genned files

---

frontend/cli/cmd_new.go
frontend/cli/main.go
internal/buildengine/plugin.go
internal/buildengine/plugin_go.go
internal/buildengine/plugin_java.go
internal/buildengine/plugin_rust.go

Each language plug in can expose flags for `ftl new`.
- Users can see these by using `ftl new <language> --help`
- FTL uses kong to set defaults, validate values, fill in envars, show help text, etc
- This is done by adding `kong.Flag` items to kong's graph at start up based on the selected language.
- All flags are string values. It is up to each plugin to parse the values further (like go's `replace` flag being transformed into a map)
eg: this is appended at the bottom of `ftl new go --help`
```
Flags for Go modules
-r, --replace=OLD=NEW,...    Replace a module import path with a
local path in the initialised FTL module
($FTL_INIT_GO_REPLACE).
```

feat: allow language plugins to expose flags for module creation

---

backend/provisioner/deployment/deployment.go
backend/provisioner/deployment/noop_provisioner.go
backend/provisioner/deployment/plugin_provisioner.go
backend/provisioner/deployment/provisioner.go
backend/provisioner/provisioner_integration_test.go
backend/provisioner/service.go
backend/provisioner/testdata/go/echo/echo.go
frontend/cli/cmd_serve.go
internal/integration/harness.go

Adds a TOML config file for configuring which provisioner plugin to use for which resource. 
There is a hard coded `noop` provisioner doing nothing. Otherwise a binary with name `ftl-provisioner-<name>` is used as plugin.
Next, I will use Localstack to test that the Cloudformation plugin actually creates a DB.

chore: configurable provisioners in ftl-provisioner

---

backend/schema/array.go
backend/schema/config.go
backend/schema/data.go
backend/schema/database.go
backend/schema/enum.go
backend/schema/errors.go
backend/schema/field.go
backend/schema/fsm.go
backend/schema/map.go
backend/schema/metadataingress.go
backend/schema/module.go
backend/schema/protobuf_dec.go
backend/schema/ref.go
backend/schema/secret.go
backend/schema/subscription.go
backend/schema/topic.go
backend/schema/typealias.go
backend/schema/typeparameter.go
backend/schema/verb.go

This is in preparation of language proto’s owning build errors, which use schema.Pos

chore: make schema.posFromProto public

---

internal/buildengine/engine.go

chore: neaten up log for initial deployment duration

---

bin/hermit.hcl

This PR adds an env var to hermit, `DBMATE_NO_DUMP_SCHEMA`, as a catch-all way to prevent creation of `db/schema.sql`
ran `dbmate up` from the command-line and noticed the pesky `db/schema.sql` crop up again because i forgot the `--no-dump-schema` flag. Added the env var incase anyone else makes the same mistake.

feat: Add env var to prevent dbmate from dumping the schema

---

internal/integration/actions.go
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/DefaultOptionalBuildItem.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HTTPProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/Nullability.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsProcessor.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/config/FTLConfigSource.java
jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/FTLJavaProcessor.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/FTLKotlinProcessor.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java
jvm-runtime/jvm_integration_test.go
jvm-runtime/testdata/java/javamodule/src/main/java/xyz/block/ftl/test/TestInvokeGoFromJava.java
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/TestInvokeGoFromKotlin.kt

For Kotlin this should exactly match the language semantics. For Java types are not considered Optional unless they are wrapped in a java.util.Optional, or annotated with @Nullable.
The exception to this are the boxed primitive types, which are always considered nullable.
fixes: #2356

fix: optional handling in the JVM

---

backend/controller/cronjobs/internal/sql/models.go
backend/controller/cronjobs/internal/sql/queries.sql.go
backend/controller/dal/internal/sql/models.go
backend/controller/dal/internal/sql/queries.sql
backend/controller/dal/internal/sql/queries.sql.go
backend/controller/sql/schema/20241002225509_create_last_activated.sql
deployment/base/db-migrate/kustomization.yml
sqlc.yaml

Use the activation time to determine which module is the current one.
fixes: #2961

fix: record when modules are activated

---

backend/controller/scaling/localscaling/local_scaling.go

If the runner keeps crashing dont keep restarting it

fix: don't retry indefinitly with local scaling

---

frontend/console/playwright.config.ts

This can be an issue if the test has to pull docker images

fix: increase playwright timeout

---

internal/terminal/interactive.go

Send SIGINT so all processess in the group also shut down

fix: readline exit behaviour

---

frontend/console/src/components/CodeEditor.tsx
frontend/console/src/components/ResizableVerticalPanels.tsx
frontend/console/src/features/verbs/VerbRequestForm.tsx
frontend/console/src/features/verbs/verb.utils.ts

- Fixes #2975 
- Adds back in the example request body instead of empty `{}`
- Adds a `reset` button to get reset to the default body

fix: verb for resetting after submit

---

frontend/console/playwright.config.ts

https://playwright.dev/docs/test-webserver#adding-a-server-timeout

fix: increase playwright webserver timeout for docker

---

backend/controller/controller.go
backend/controller/scaling/k8sscaling/deployment_provisioner.go
backend/controller/scaling/k8sscaling/k8s_scaling.go
backend/controller/scaling/kube_scaling_integration_test.go
deployment/base/ftl-controller/deployment-config.yaml
deployment/base/ftl-controller/ftl-controller.yml
internal/log/plain.go

Fixes an issue with kube rolling deployments

fix: kube test failures

---

frontend/console/src/api/modules/use-modules.ts
frontend/console/src/api/schema/use-schema.ts
frontend/console/src/features/modules/schema/Schema.tsx

Fixes #2997
Also fixes refreshing of modules when schema changes

fix: enum syntax highlighting

---

backend/controller/controller.go

This smol PR includes a micro optimization by ensuring that a verb is callable (a.k.a exported OR a call within the same module) _before_ validating the request body. 
This change is not necessary by any means. Just something that crossed my mindwhile looking at controller logic with @wesbillman. 
* moves `!verb.IsExported` check to before validating request body
* use the current caller to see if the call is intra-module instead of looping over all callers. 
> [!NOTE]
> there may have been a reason why all callers are being looped over instead of checking the current caller, but i couldn't think of a good one. if someone knows definitely let me know!

refactor: move verb export check to before req body validation

---

backend/controller/controller.go
backend/controller/ingress/ingress.go
backend/controller/timeline/timeline_test.go

This PR moves a function `ingress.ValidateCallBody` from the `ingress` package to `controller`
function is only being used in the controller for grpc stuff but lived in `ingress` package. 
props to @wesbillman for catching this

refactor: move `ingress.ValidateCallBody` function

---

internal/buildengine/plugin_go.go

fixes #3006
This was due to FTL trying to parse `""` as the format `A=B,C=D` and failing when it didn't have any pairs.

fix: emty replace flag is allowed in `ftl new go`

---

frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts

Fixes: https://github.com/TBD54566975/ftl/issues/2982
This fix delves into the nuance of component re-rendering lifecycle a bit. Basically, before, we would add the selected module to local storage AND update the component state on every single re-render of the component (at `const [expandedModules, setExpandedModules] = useState(...)`. The problem with that was that when we toggled the selected module to close it, the re-render would cause the selected module to still be added back to local storage, but the component state would be out of sync. Then when you went to expand that module again, because the states got unsynced, it would stay stuck in the visibly-closed state. Now, we only add the selected module to local storage in the effect, which doesn't get triggered on toggle a module's …

fix: module tree expansion state when closing the module of the selected decl

---

frontend/console/local.go
scripts/ftl

Previously, trying to run `~/Development/ftl/scripts/ftl dev` from a separate project failed with
```
error:controller0: error: No justfile found
```
After this, `scripts/ftl dev` builds the console correctly, though the console UI still does not load correctly, due to
```
http: proxy error: dial tcp [::1]:5173: connect: connection refused
```

fix: allow running the local scripts outside of the main FTL directory.

---

internal/watch/watch_integration_test.go

When creating a new module, files can be added (scaffolded) and then edited (eg: `go mod tidy`).
The watch tests are now lenient to update events being fired in this case.

fix: flaky watch tests

---

frontend/cli/cmd_box.go
go-runtime/compile/build.go
internal/buildengine/build.go
internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/buildengine/languageplugin/go_plugin.go
internal/buildengine/languageplugin/go_plugin_test.go
internal/buildengine/languageplugin/java_plugin.go
internal/buildengine/languageplugin/java_plugin_test.go
internal/buildengine/languageplugin/plugin.go
internal/buildengine/languageplugin/rust_plugin.go
internal/buildengine/module.go
internal/moduleconfig/moduleconfig.go
internal/moduleconfig/moduleconfig_test.go

Remove things from ModuleConfig in preparation for language plugins:
- `ModuleConfig.Errors`
- Removed logic to ever write errors to disk (except Java plugin, which just hardcodes `errors.pb` until it moves to being an external plugin)
- `ModuleConfig.Deploy`
- This has been refactored to being part of a build result. This also allows language plugins to dynamically include files to deploy.

feat: remove Error and Deploy from ModuleConfig

---

frontend/cli/cmd_new.go

Fixes #3040
If the specified "language" to the new command starts with '-', assume it's an option to the new command. Shortcircuit the following logic and handle the option.

feat: Default to "new" command handler for options

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

This PR introduces workspace configuration for the [vscode-proto3](https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3) extension that specifies the path to the `protos` dir. This prevents all the red squigglies from showing up whenever a `.proto` file is opened.
> [!NOTE]
Also added [vscode-proto3](https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3) as a recommended extension by including it in `.vscode/extensions.json`
> [!NOTE]
> there's a newer protobuf vscode extension that pbkit.dev made called: [Protobuf](https://marketplace.visualstudio.com/items?itemName=pbkit.vscode-pbkit). might be worth trying

fix: add config to prevent red squigglies when opening `.proto` files in vscode

---

otel-local-config.yaml

This PR replaces a deprecated `logging` exporter being used in the local otel collector causing it to bork on startup. replaced with [debug exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md)
closes #3019 
```
docker compose --profile infra up otel-collector
[+] Running 4/4
✔ otel-collector Pulled                                                                                                                               6.0s
✔ f269895151d7 Pull complete                                                                                                                        0.4s
✔ 5d76f70d74fd Pull complete                                                                                                                        4.3s
✔ …
```

fix: replace deprecated `logging` exporter

---

examples/java/time/src/main/java/ftl/time/Time.java
jvm-runtime/ftl-runtime/common/deployment/pom.xml
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/StaticConfigSource.java
jvm-runtime/ftl-runtime/common/deployment/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
jvm-runtime/ftl-runtime/common/runtime/pom.xml

feat: observability support for JVM

---

backend/controller/admin/admin.go
backend/controller/admin/admin_test.go
backend/controller/admin/local_client.go
backend/controller/admin/local_client_test.go
backend/controller/controller.go
backend/controller/dal/dal.go
bin/hermit.hcl
frontend/cli/cmd_config.go
frontend/cli/cmd_new.go
frontend/cli/cmd_schema_diff.go
frontend/cli/cmd_serve.go
frontend/cli/main.go
internal/buildengine/engine.go
internal/buildengine/languageplugin/go_plugin_test.go
internal/buildengine/languageplugin/java_plugin_test.go
internal/buildengine/languageplugin/plugin.go

This is a prerequisite for external language plugins. This PR makes sure `languageplugin.New()` is called with a bind allocator so that external plugins will soon able to able to acquire a bind url.

feat: language plugins require a bind allocator to be provided

---

scripts/autoversion

Now that this is manual we should always release when we run the workflow

fix: always release a new version on workflow

---

go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/ftltest/testdata/go/verbtypes/verbtypes_test.go
go-runtime/ftl/ftltest/testdata/go/wrapped/wrapped_test.go
internal/modulecontext/module_context.go

when using ftltest.Call, you don't need to mock the verb directly invoked. only downstream verbs must be mocked (or overridden by setting WithCallsAllowedWithinModule globally)
https://sq-tbd.slack.com/archives/C04PEQERFM0/p1727995042643089
fixes #2984

fix: ftltest.Call always allows direct initial verb

---

backend/controller/admin/local_client.go
backend/protos/xyz/block/ftl/v1/language/mixins.go
frontend/cli/cmd_new.go
frontend/cli/cmd_schema_diff.go
frontend/cli/main.go
internal/buildengine/build.go
internal/buildengine/engine.go
internal/buildengine/languageplugin/external_plugin.go
internal/buildengine/languageplugin/external_plugin_client.go
internal/buildengine/languageplugin/external_plugin_test.go
internal/buildengine/languageplugin/go_plugin.go
internal/buildengine/languageplugin/java_plugin.go
internal/buildengine/languageplugin/java_plugin_test.go
internal/buildengine/languageplugin/plugin.go
internal/buildengine/languageplugin/rust_plugin.go
internal/moduleconfig/moduleconfig.go
internal/moduleconfig/moduleconfig_test.go

Adds `languageplugin.externalPlugin` for working with plugins over gRPC. This PR does not include any non-test implementations.
Part of #2452

feat: add external plugin to build engine

---

backend/controller/observability/calls.go
backend/controller/observability/controller.go
backend/runner/runner.go
go-runtime/server/server.go
internal/observability/logger.go

Only works for the go runtime at the moment, as the JVM logging needs to be cleaned up to match the go format.
fixes: #3105

feat: add DD trace id to the logs

---

.github/workflows/ci.yml
.github/workflows/release.yml
Dockerfile.provisioner
ftl-provisioner-config.toml

This is an image configured to use cloudformation for provisioning postgres databases. 
Though it should not be used in production yet, we are releasing it here to make testing easier in dev environment

feat: release a docker image for the provisioner

---

frontend/console/e2e/cron.spec.ts
frontend/console/e2e/pubsub.spec.ts
frontend/console/src/features/verbs/verb.utils.ts

Sending on the `cron` and `pubsub` verbs was broken due to invalid "path" in the form. This fixes it and adds a quick test to make sure it stays working.

fix: cron and pubsub verb forms and test

---

frontend/console/src/features/command-pallete/CommandPalette.tsx
frontend/console/src/features/command-pallete/command-palette.utils.ts
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts

- Fixes issues with `CommandPallete` erroring when `typeAlias` is used since we had `typealias` in the icons list
- Fixes issues with urls that have `module/typealias/declName` in them vs. `module/typeAlias/declName`
- Performance improvements on `CommandPallete` searching/filtering.
See also #3146

fix: typealias case issues in icons and urls

---

backend/provisioner/deployment.go
backend/provisioner/deployment_test.go

Previously we were polling the next state in a busy loop, now, we do an exponential fallback when polling a task state until it either fails or is complete.

fix: backoff for provisioning status checks

---

backend/controller/controller.go
backend/controller/ingress/handler.go
backend/controller/timeline/events_ingress.go
backend/controller/timeline/internal/timeline_test.go
frontend/console/src/features/timeline/timeline.utils.ts
frontend/console/src/features/traces/TraceRequestList.tsx

Fixes #3149
Also fixes:
- ingress request keys were not being added to the database
- ingress events not adding to the db because of request body reading twice resulting in `error:timeline: Failed to insert 1 events, most recent error: failed to read request body: http: invalid Read on closed Body`
- call event errors were not being inserted as events (just logged)
- call not reusing the ingress request key correctly
- TimelineIcon not respecting error fields in responses

fix: reporting call and ingress event errors

---

frontend/cli/cmd_dev.go
internal/buildengine/engine.go
internal/buildengine/terminal.go
internal/lsp/lsp.go

#2937
- Module error state is now maintained, so that a changed file in one module getting successfully deployed does not get confused as "everything is good now"
- CLI status bar updates now rely on these engine events, rather than being spread across the engine code
- LSP uses EngineStarted and EngineEnded events to update status indicator
- Bring all engine status update logs to one place, to align explicit build commands and plugin triggered builds

refactor: buildengine publishes clearer state events

---

frontend/console/src/components/AttributeBadge.test.tsx
frontend/console/src/components/AttributeBadge.tsx
frontend/console/src/components/List.tsx
frontend/console/src/features/infrastructure/DeploymentsList.tsx
frontend/console/src/features/infrastructure/RunnersList.tsx
frontend/console/src/features/modules/ModulesPanel.tsx
frontend/console/src/features/timeline/details/TimelineCallDetails.tsx
frontend/console/src/features/timeline/details/TimelineCronScheduledDetails.tsx
frontend/console/src/features/timeline/details/TimelineDeploymentCreatedDetails.tsx
frontend/console/src/features/timeline/details/TimelineDeploymentUpdatedDetails.tsx
frontend/console/src/features/timeline/details/TimelineIngressDetails.tsx
frontend/console/src/features/timeline/details/TimelineLogDetails.tsx
frontend/console/src/features/traces/details/TraceDetailsCall.tsx
frontend/console/src/features/traces/details/TraceDetailsIngress.tsx

Minor changes to make `AttributeBadge` look less bad :)

feat: update Attribute badge styling

---

deployment/Dockerfile.runner.test

This seems to possible be the root cause of the out of disk space errors.

chore: remove java from the kube tests

---

frontend/cli/cmd_box.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_build.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_dev.go
frontend/cli/cmd_serve.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go

We already added bind allocator to build engine so that it can launch language plugins but we did not pass in the bind allocator.
Added a task to clean this up here: https://github.com/TBD54566975/ftl/issues/2452

fix: pass in bind allocator to build engine

---

frontend/console/src/features/verbs/VerbPage.tsx
frontend/console/src/features/verbs/VerbRightPanel.tsx
frontend/console/src/features/verbs/verb.utils.ts

Adds `Callers` to verb right panel. Also cleans up CSS for the identical `Calls` panel.

feat: show callers in console verb page

---

backend/controller/admin/admin.go
backend/controller/admin/admin_test.go
backend/controller/admin/local_client.go
backend/controller/admin/local_client_test.go
backend/controller/controller.go
backend/controller/dal/dal.go
frontend/cli/cmd_box.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_build.go
frontend/cli/cmd_config.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_dev.go
frontend/cli/cmd_schema_diff.go
internal/buildengine/build.go
internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go
internal/buildengine/languageplugin/java_plugin.go
internal/buildengine/languageplugin/rust_plugin.go
internal/moduleconfig/moduleconfig.go
internal/projectconfig/projectconfig.go

This removes the need for some cli commands to have a bind allocator, as they no longer need a language plugin to declare where the deploy dir is.

feat: save module schemas to .ftl/schemas

---

frontend/console/src/features/modules/decls/DeclPanel.tsx
frontend/console/src/features/modules/schema/schema.utils.ts

This fixes the 2 issues we saw this morning:
* `compliance.Case` showed the schema for `compliance.CaseToken` instead of its own
* `typealias` decl pages don't show the schema at all

fix: regex match to show decl schema string

---

frontend/console/e2e/helpers.ts
frontend/console/src/components/List.tsx
frontend/console/src/features/modules/ModulesPanel.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/decls/DeclLink.tsx

Fixes https://github.com/TBD54566975/ftl/issues/3021

feat: support cmd+click to open module + decl links in new tab

---

backend/controller/scaling/localscaling/local_scaling.go
frontend/cli/cmd_box.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_build.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_dev.go
frontend/cli/cmd_new.go
frontend/cli/cmd_schema_diff.go
frontend/cli/cmd_serve.go
internal/bind/bind_allocator.go
internal/buildengine/engine_test.go
internal/buildengine/languageplugin/external_integration_test.go
internal/buildengine/languageplugin/plugin.go

The BindAllocator was designed for dynamically allocating ports, and will skip bound ports. This is intentional, but we don't want the initial controller ports (ingress and RPC) to be skipped if those ports are already bound.
Fixes #3190

fix: fail BindAllocator.Next() allocation for required ports

---

backend/controller/artefacts/oci_registry.go
frontend/cli/cmd_release.go
go.mod

fixes #3076
module binaries now stored as blobs (instead of images); enumeration operations dropped due to inefficiency - deployment workflows do not need it anyways

feat: emit module artifacts as blobs

---

frontend/cli/cmd_deploy.go

Hacky fix. Will fix properly later.

fix: do not use remote endpoint for deploy’s bind allocator

---

backend/controller/sql/schema/20241029015638_subscription_cursor.sql

This is because the subscription will lose it’s place if this happens. If we set it to null, the subscription will start from scratch (unexpected). If we cascade then we accidentally delete the subscription. We only delete topic events when trying to fix issues in a cluster, so restricting seems like the safest option to avoid accidental knock on effects.

fix: prevent topic_events being deleted if there is a subscription referencing it

---

frontend/cli/cmd_schema_diff.go

This was slow and required a bind allocator.
Now that we have `$(projectroot)/.ftl/schemas`, `ftl diff` can use that to find module schemas.

fix: `ftl diff` no longer needs language plugins for schemas

---

common/plugin/spawn.go
frontend/cli/cmd_bench.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_call.go
frontend/cli/cmd_ping.go
frontend/cli/cmd_replay.go
frontend/cli/cmd_serve.go
internal/buildengine/languageplugin/external_plugin_client.go
internal/rpc/rpc.go

We call Ping over grpc at a frequent rate when waiting for services to be ready, with each grpc failure being automatically logged (debug).
Also, soon language plugins will be using grpc and so the amount of ping logs at start up will roughly double.
This PR tries to reduce the noise.
- Ping logs:
- Constant ping call failures are silenced (noop log sync passed into the call)
- Refactor: moved more logic into `rpc.Ping()` so that each caller doesn't need to write extra code, including
- deadline handling
- returning the relevant error (the latest ping error if deadline reached, otherwise the context error)

fix: reduce spammy logs for pings

---

backend/controller/sql/schema/20241029142130_add_index_to_async_calls.sql

Lease deletions are done by executing the following sql statement: 
```sql
-- name: ReleaseLease :one
DELETE FROM leases
WHERE idempotency_key = $1 AND key = $2::lease_key
RETURNING true
```
This table is referenced by `leases_id` in the `async_calls` table. So a deletion needs to lookup of such foreign key within the `async_calls` table in order to set the row's value to NULL.
This PR adds an index to that foreign_key, so that deletions of leases can happen much much faster.

feat: Add index to async_table to speed up lease deletions

---

backend/provisioner/deployment.go
backend/provisioner/deployment_test.go
backend/provisioner/registry.go
backend/provisioner/resource_graph.go
backend/provisioner/service.go

Previously, we populated all dependencies at the start of the deployment, meaning any intermediate outputs were not visible to followup tasks

fix: populate task resources as deployment progresses

---

backend/controller/controller.go
internal/configuration/manager/manager.go

We need to proeprly define a defaul secret manager, but for now, fall back to ASM manager if inline is not available. This will unblock DB provisioning in dev

fix: fallback to asm secret provider in cluster

---

backend/controller/controller.go
backend/controller/cronjobs/internal/cronjobs_test.go
backend/controller/dal/async_calls_test.go
backend/controller/dal/dal_test.go
backend/controller/pubsub/integration_test.go
backend/controller/pubsub/service.go
backend/controller/timeline/internal/timeline_test.go

Before the change, the new integration test was showing delays ranging from 0.2s - 1.2s from when an event is published to when the async call is created.
After the change we are consistently under 0.2s.

fix: improve delay before subscriber receives event

---

common/plugin/spawn.go
frontend/cli/cmd_bench.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_call.go
frontend/cli/cmd_ping.go
frontend/cli/cmd_replay.go
frontend/cli/cmd_serve.go
internal/buildengine/languageplugin/external_plugin_client.go
internal/rpc/rpc.go

Reverts TBD54566975/ftl#3150
This broke runners. They failed to start with
```
{"level":"warn","attributes":{"deployment":"dpl-alice-4p86gzxx2zr5soc0","module":"alice","scope":"alice"},"message":"Plugin failed to start, terminating pid 11","time":"2024-10-30T03:06:14.701727838Z"}
ftl-runner: error: failed to spawn plugin: plugin process died: context canceled
```

revert: "fix: reduce spammy logs for pings"

---

frontend/cli/bind.go
frontend/cli/bind_test.go
frontend/cli/cmd_box.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_build.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_new.go

There is odd behaviour we need when choosing a port to use for runners and language plugins:
- Do not bind to the port reserved for controllers
- Do not use the cli.Endpoint if it is a remote endpoint
Best to have all that oddness collected into one place.

chore: clean up bind allocator without controller port

---

.github/workflows/ci.yml
Justfile
scripts/ftl-language-python

Language plugins can timeout if `./script/language-plugin-xyz` builds it each time in CI.
Instead in CI we pre-build all language plugins and make the script use the release binary.

ci: CI uses build/release for language plugins

---

frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/command-pallete/CommandPalette.tsx
frontend/console/src/features/command-pallete/command-palette.utils.ts
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts
frontend/console/src/features/modules/schema/schema.utils.ts

Fixes: https://github.com/TBD54566975/ftl/issues/3219
https://github.com/user-attachments/assets/dccdc8e9-1c72-4de1-8538-0bdece0beed2
Use verb metadata to classify each verb as a subtype: cronjob, ingress, subscriber, or none of the above. The backend guarantees these metadata are mutually exclusive, so the frontend can just check which (if any) exists in a verb proto.
Changes:
* Add new icons for each subtype
* Thread new icons through both existing callsites: module tree and global fuzzy search
* Show decl type name on hover of each icon
* Add new verb types to filter dropdown
* Support groups in `Multiselect` to handle verb subtypes
* Make fuzzy search use the same icon for modules as the module tree. They had accidentally diverged.
Next: verb page customizations per subtype

feat: console shows verb subtypes: cronjob, ingress, subscriber, all other verbs

---

frontend/console/src/api/timeline/use-timeline.ts

See #3260
We can get some console connection errors in our deployed environment which causes streaming to get restarted. However, it seems like we don't clear the cache when this happens so duplicate events get returned from our streaming hooks. This change should ensure the events are cleared anytime we restart the stream.

fix: clear events when streaming starts

---

cmd/ftl-provisioner-cloudformation/provisioner.go

We want to still keep the stack around, as it contains history of infra changes

fix: support deleting all resources from a stack

---

cmd/ftl-provisioner-cloudformation/provisioner.go

This is a temporary solution to allow DB connectivity until we have module specific securty groups implemented

fix: set the rds security group via env var

---

Justfile

This task is getting really slow, and the tests are a big part of that.

chore: don't run tests in rebuild-all

---

internal/buildengine/engine.go

With each group of the topology, we were writing stubs for all modules. This is a fairly slow task. 
It now only writes stubs for the modules that were just built. Cuts about 900ms off PFI startup time.

fix: Only generate stubs for modules once

---

go-runtime/goplugin/service.go
internal/buildengine/languageplugin/plugin.go
internal/buildengine/languageplugin/plugin_test.go

Otherwise `buildengine` tries to read a nil schema value leading to a crash

fix: language plugins should always include an error with level=ERROR for BuildFailure

---

.github/actions/build-cache/action.yml
.github/workflows/ci.yml
.github/workflows/smoketest.yml
.github/workflows/writecache.yml

We only write to the cache on main.
It also turns out we were only intermittently using the native caching anyway, so this should be more reliable.

chore: don't use cashapp/activate-hermit's native caching

---

frontend/cli/cmd_build.go
frontend/cli/cmd_deploy.go
frontend/cli/cmd_new.go
frontend/cli/main.go
internal/buildengine/engine_test.go
jvm-runtime/plugin/common/java_plugin_test.go

Fixes #3287
Handles `ftl build`, `ftl deploy`, `ftl new` and `just test-backend`

fix: kill language plugins after cli and tests

---

.github/actions/build-cache/action.yml
.github/workflows/writecache.yml

Cache playwright browser binaries to improve CI test speed
Fixes #3286

chore: cache playwright's browser binaries

---

renovate.json5

We don't need this without rust, and it is making renovate do weird things.

chore: disable lock file maintenance

---

scripts/ftl

In some cases you can end up with a linux build on a mac if you are building the kube tests.

fix: always build go2proto for current arch

---

frontend/cli/cmd_serve.go

1s is a very long poll time, reducing this will improve startup time

fix: improve startup time

---

.github/workflows/smoketest.yml

Run the tagged release's smoke test on its released image, which sets up the deployments to upgrade, before running the upgrade tests.

fix: smoke test the tagged release before upgrading

---

backend/controller/scaling/localscaling/local_scaling.go
backend/controller/scaling/scaling.go
internal/rpc/rpc.go

When your laptop goes to sleep we were seeing lots of runner restarts using a cancelled lease context.
It is hard to reproduce reliably, but this should work around it for now.
I could not reproduce the issue by manually cancelling the lease, it only happens when the computer hibernates.
fixes: #3177

fix: handle lease failure better

---

cmd/devel-provisioner/main.go
cmd/ftl-provisioner-cloudformation/cloudformation_util.go
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-cloudformation/status.go

Connects to the freshly created psql instance, and creates a database if it does not exist.
This closes https://github.com/TBD54566975/ftl/issues/3117 with https://github.com/tbdeng/ftl-aws/pull/35
We should refactor the DB creation from the success step to be part of the actual provisioning flow. Thicket for this: https://github.com/TBD54566975/ftl/issues/3333
We should also not use the root credentials when connecting to the DB from a module. However, we should change this when looking at DB migrations, when we won't expect modules to execute DDL anymore.

feat: Create psql DB in the CF provisioner

---

deployment/Dockerfile.runner-jvm.test

Previously this relied on the standard runner image which no longer includes the jvm (as of the latest release)

fix: local jvm runner relies on released jvm runner

---

frontend/console/src/features/traces/TraceDetailItem.tsx
frontend/console/src/features/traces/TraceDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx
frontend/console/src/features/traces/TraceGraphHeader.tsx
frontend/console/src/features/traces/TraceGraphRuler.tsx
frontend/console/src/features/traces/TraceRulerItem.tsx
frontend/console/src/features/traces/details/TraceDetailsAsyncCall.tsx
frontend/console/src/features/traces/details/TraceDetailsPubsubPublish.tsx
frontend/console/src/features/traces/traces.utils.ts

feat: add request time ruler. refactor calculations

---

go-runtime/compile/build.go
go-runtime/compile/dependencies.go
go-runtime/compile/main-work-template/go.work.tmpl
go-runtime/compile/stubs.go
go-runtime/goplugin/service.go
internal/watch/filehash.go
internal/watch/watch.go
jvm-runtime/plugin/common/jvmcommon.go

closes #3129
Increases performance of go builds by 0.5s-0.8s in some cases.
Changes:
- Track if any thing has changed that would require us to
- call `go mod tidy` (in either the main module directory, or in the build directory)
- scaffold the build template (if we scaffold, we also need to run go mod tidy)
- If a build fails for any reason, reset ongoing build state so next time we always rebuild everything.
Trigger details:
- If we detect changes in `go.mod`, `go.sum` or `types.ftl.go`, always rebuild fully
- If the list of imported packages has changed, `go mod tidy` is required in the module's directory
- If the MainModuleContext has changed in any way, then the build template needs to be scaffolded, and `go mod tidy` needs to be run in `.ftl/go/main`
Performace:
- Scaffolding is …

feat: detect when `go mod tidy` and build scaffolding is needed

---

frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/decls/DeclLink.tsx

- swap out icons for visibility indicators

feat: improve styling on tree header a bit

---

internal/rpc/headers/headers.go

There may be others we need to add here but these two are a good start.

fix: strip protocol level headers

---

go-runtime/compile/build.go
internal/buildengine/languageplugin/plugin_client.go

Language plugin logs had the following issues:
- No scope
- Some logs had extra new line chars

fix: language plugin logs

---

backend/controller/timeline/events_ingress.go
frontend/cli/cmd_serve.go
frontend/console/src/features/verbs/VerbRequestForm.tsx

fix: CORS errors with additional headers in local dev

---

frontend/cli/cmd_serve.go
go-runtime/goplugin/service.go
jvm-runtime/plugin/common/jvmcommon.go

chore: reduce log info output on startup

---

cmd/ftl-provisioner-cloudformation/postgres.go
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-cloudformation/status.go
cmd/ftl-provisioner-cloudformation/task.go
go.sum

Previously, we were `CREATE DATABASE ... ` as a response to a successful status check. Now, we spawn a background goroutine to wait for the stack to become ready and run any DDL commands before reporting the task as a success.
Closes https://github.com/TBD54566975/ftl/issues/3333

refactor: Juho/refactoring

---

frontend/console/src/components/Button.tsx
frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx
frontend/console/src/features/traces/TraceGraphHeader.tsx
frontend/console/src/features/traces/TracesPage.tsx
frontend/console/src/features/verbs/KeyValuePairForm.tsx
frontend/console/src/features/verbs/VerbFormInput.tsx
frontend/console/src/features/verbs/VerbRequestForm.tsx
frontend/console/src/stories/Button.stories.ts

Creating reusable `<Button />` component to avoid all the duplicated styles everywhere and keep things a bit more consistent.
Some examples:

feat: create reusable button component for console

---

go-runtime/compile/build.go
go-runtime/compile/dependencies.go
internal/buildengine/languageplugin/plugin_integration_test.go
internal/watch/discover.go
internal/watch/filehash.go
internal/watch/walk.go
internal/watch/watch.go

- The two longest parts to build a go module is schema extraction and compilation.
- Some code changes (like a verb changing name, or sumtype changes) require compilation to happen after schema extraction so that we can generate code based on the latest schema.
- During development though, most builds will be done with compilation not dependant on schema extraction.
- This PR optimises for this case by optimistically compiling while schema extraction occurs if previous code generation is present. After the schema is extracted we then generate code and check if anything has changed that requires re-compilation.
Ran `ftl dev examples/go/time`, waiting for the initial builds to complete, and then modified the module code 20 times to get an average.
| Case |  Small Change | Verb Change |
-- | …

feat: optimistically compile go modules while extracting schema

---

backend/controller/observability/observability.go
backend/cron/observability/cron.go
backend/cron/service.go
backend/cron/service_test.go
internal/cron/pattern.go
internal/rpc/rpc.go
internal/slices/slices.go

Functional but not not completely wired up. Tests pass, metrics aren't hooked up, no main service binary.

feat: cron service

---

backend/cron/observability/cron.go
backend/cron/service.go

There were a couple of metrics that no longer made sense, and we don't have the deployment key available in the cron module, which might be a problem.

fix: wire up cron metrics

---

common/plugin/serve.go

It is unlikely this is the issue behind #3419, but the inability to disconnect from the port we want the plugin to bind to should be an error.
Even if it is the issue behind that ticket it won't fix it, but it should help us uncover why.

fix: handle error disconnecting from port

---

backend/controller/artefacts/oci_registry.go
backend/controller/controller.go
backend/runner/runner.go
frontend/cli/cmd_release.go

fix: OCI client is slow

---

frontend/cli/cmd_new.go

fix: ftl new uses project root as dir

---

frontend/cli/cmd_serve.go

This is the same as the module build and deploy timers

chore: controller start time only needs 2 decimal places

---

cmd/ftl-proxy-pg/main.go
internal/pgproxy/pgproxy.go

Still missing implementation for cancellation, which I will add as a followup.
Will also add custom DSN rewriters, like IAM based authenticator to the `ftl-proxy-pg`

feat: add a pgproxy for rewriting dsn strings

---

frontend/cli/cmd_deploy.go
internal/integration/actions.go

Also limit test deploy to 1m to help diagnose issues

feat: timeout for deploy command

---

backend/controller/controller.go
backend/runner/runner.go
cmd/ftl-proxy-pg/main.go
cmd/ftl-runner/main.go
go-runtime/server/database.go
internal/modulecontext/module_context.go
internal/pgproxy/pgproxy.go

High level changes:
- Stop sending PostgreSQL DSNs with the `ModuleContext` to the runners.
- Instead, when `GetDatabase` in the runner is called, and there is no DSN for the DB, it gets translated to pgproxy DSN. 
- We start the pgproxy before the deployment in the runner, and pass the local address in an environment variable to the runner.
- pgproxy gets the active schema, and redirects connections to the DSN defined in the runtime of that schema.
Follow-ups
- Integrate MySQL proxy
- Remove DSNs from `ModuleContext` completely

feat: Resolve DSN from runtime in PG Proxy

---

internal/pgproxy/pgproxy.go

Supports use cases where we fetch credentials from a secrets manager where they are rotated regularly

fix: retry connection once in pgproxy to support credential rotations  in the DSN function

---

.github/workflows/ci.yml

This is now the slowest CI job and is holding up merging.

fix: split up the runner image builds

---

backend/provisioner/dev_provisioner.go

Topic or subscription `a.b_c` would have previously clashed with `a_b.c` as we were separating module and name by underscores

fix: prevent pubsub naming clashes

---

backend/provisioner/registry.go
charts/ftl/templates/provisioner-config-map.yaml
frontend/cli/cmd_serve.go
ftl-provisioner-config.toml

The default is confusing regarding the ordering and grouping of provisioner tasks. Let's get rid of it!

chore: remove default from provisioner config

---

charts/ftl/templates/runner.yaml

This is so that we can attach a single IAM role to runners. This is a temporary workaround until we will have proper runner based identities in AWS per module

fix: add service account to runners

---

frontend/console/src/features/graph/graph-utils.ts

Subscriptions have been removed from schema, so this new mention of subscriptions broke.
Please revert/re-add when you know how you want subscriptions to work in console @wesbillman

fix: remove new subscriptions usage in console

---

backend/controller/artefacts/oci_registry.go

Required, because it does not work without it

fix: mark RegistryConfig.Registry as required

---

.github/workflows/ci.yml
Justfile
backend/provisioner/dev_provisioner.go
docker-compose.yml
frontend/cli/cmd_dev.go
frontend/cli/cmd_serve.go
internal/buildengine/engine.go
internal/container/container.go
internal/dev/db.go
internal/dev/docker-compose.grafana.yml
internal/dev/docker-compose.mysql.yml
internal/dev/docker-compose.postgres.yml
internal/dev/docker-compose.registry.yml
internal/dev/grafana.go
internal/dev/redpanda.go
internal/dev/registry.go
internal/integration/harness.go
internal/pgproxy/pgproxy_test.go

closes #3521
Rather than having separate docker compose ymls and API calls to set up containers, switch to always using docker compose files.
This also sets the postgres version to 15.10 (we previously ran with 15.8 or 15.10 depending on how FTL was started).

chore: converge on docker compose up rather than docker api

---

frontend/cli/cmd_serve.go

This conflicts with the auto generated env var on kube if there is a service named ftl-registry.

chore: change registry env var

---

Justfile

I've been getting network issues in `docker compose up` causing integration test failures on CI.
Hopefully this makes it more resilient.

ci: retry docker compose up once if it fails

---

Dockerfile
backend/provisioner/runner_scaling_provisioner.go
backend/provisioner/scaling/k8sscaling/k8s_scaling.go

Per deployment is to granular for our security use cases.

feat: use one ServiceAccount per module

---

internal/routing/routing.go
internal/routing/routing_test.go

This is a prototype routing package that syncs routes from the schema. It will no doubt need adjustment.

feat: add routing table package

---

frontend/cli/cmd_serve.go
frontend/cli/main.go

We will also need to do this for other services that need to call timeline later.

chore: serve timeline service and dial client

---

bin/hermit.hcl

This breaks JVM runner proxying as we can't override this when running java.

fix: remove FTL_ENDPOINT var

---

backend/controller/pubsub/integration_test.go
backend/controller/pubsub/testdata/kotlin/publisher/src/main/kotlin/xyz/block/ftl/java/test/publisher/Publisher.kt
backend/runner/pubsub/publisher.go
backend/runner/pubsub/pubsub.go
backend/runner/runner.go
go-runtime/internal/impl.go

This leaves pubsub in a stable state while we put kafka work on pause

fix: publish to old pubsub impl and kafka

---

.goreleaser.yaml
Justfile
backend/timeline/service.go
cmd/ftl-controller/main.go
cmd/ftl-cron/main.go
cmd/ftl-http-ingress/main.go
cmd/ftl-provisioner/main.go
cmd/ftl-proxy-pg/main.go
cmd/ftl-timeline/main.go
frontend/cli/cmd_serve.go
frontend/cli/main.go
version.go

Move version parsing into the ftl package, combine version+timestamp into a single variable.

refactor: simplify main entry points a bit

---

frontend/cli/cmd_dev.go
frontend/cli/cmd_serve.go

We seem to have lost this check somewhere, and I keep hitting silent failures when I have k3d up.

fix: don't attempt to start if controller allready running

---

backend/controller/pubsub/integration_test.go

Deleted some that won't make sense in the new pubsub

chore: disable pubsub tests

---

frontend/console/src/api/timeline/use-timeline.ts

Timeline service sorts by ID (ie the order events were published which is affected by batching), so console now re-sorts events for presentation.
Thanks @wesbillman for pairing on this.

fix: sort console timeline by time

---

backend/controller/console/console.go
backend/controller/controller.go
backend/controller/deployment_logs.go
backend/controller/pubsub/internal/dal/async_calls_test.go
backend/controller/pubsub/internal/dal/dal.go
backend/controller/pubsub/service.go
backend/cron/service.go
backend/cron/service_test.go
backend/ingress/handler.go
backend/ingress/handler_test.go
backend/ingress/service.go
backend/runner/proxy/proxy.go
backend/runner/runner.go
backend/timeline/client.go
cmd/ftl-console/main.go
cmd/ftl-controller/main.go
cmd/ftl-cron/main.go
cmd/ftl-http-ingress/main.go
frontend/cli/cmd_replay.go
frontend/cli/cmd_serve.go
frontend/cli/main.go
internal/routing/verb_routing.go

fix: inject timeline client instead of using ctx

---

backend/provisioner/scaling/localscaling/local_scaling.go
frontend/cli/cmd_serve.go

Currently they are racy with some of our new services, there is no real need for them the port they use to be close.

fix: allocate runner ports randomly

---

backend/provisioner/dev_provisioner.go

No need to make sure redpanda is up for subscriptions as they rely on topics which rely on redpanda being up.

chore: speed up subscription provisioning

---

frontend/cli/main.go

If you start FTL with --trace=trace.out after execution you can look at the execution time details via:
go tool trace trace.out

feat: allow easy generation of a trace file

---

docs/content/docs/getting-started/quick-start/index.md

This is a bit weird because the "language" selected is global, but I think that's okay.

docs: put hermit/brew/manual in tabs

---

backend/protos/buf.gen.yaml

This seems to be causing build stability issues.

chore: temporarily disable rust proto generation

---

backend/protos/buf.gen.yaml
scripts/protoc-gen-prost
scripts/update-roadmap-issues

1. Redirect stdout to stderr so we don't break the protoc plugin protocol
2. Use a file lock to avoid multiple concurrent invocations of protoc-gen-prost running cargo install many times

fix: make protoc-gen-prost work

---

frontend/cli/cmd_config.go
frontend/cli/cmd_secret.go

Fixes #3408
Adds more info to the `--json` flag for `ftl config/secret set` commands
```
Command flags:
--json    Assume input value is JSON. Note: For string secrets, the JSON value
itself must be a string (e.g., '"hello"' or '"{'key': 'value'}"').
```
and
```
Command flags:
--json    Assume input value is JSON. Note: For string configs, the JSON value
itself must be a string (e.g., '"hello"' or '"{'key': 'value'}"').
```

fix: improve help docs for config/secret --json flag

---

frontend/cli/cmd_dev.go
frontend/cli/cmd_serve.go
internal/terminal/interactive.go
internal/terminal/status.go

The interactive console could eat error messages on exit

fix: stop readline eating exit messages

---

backend/runner/runner.go

This became apparent when pubsub would immediately start trying to consume events once the runner claimed to be ready.

fix: wait for dev endpoint to be available before runner is ready

---

backend/runner/pubsub/consumer.go
backend/runner/pubsub/publisher.go
backend/runner/pubsub/testdata/go/publisher/publisher.go
internal/log/logger.go

fixes https://github.com/block/ftl/issues/3808

fix: handle pubsub rebalance and closure

---

backend/runner/pubsub/consumer.go
backend/runner/pubsub/integration_test.go
backend/runner/pubsub/testdata/go/publisher/publisher.go
backend/runner/pubsub/testdata/go/publisher/types.ftl.go
backend/runner/pubsub/testdata/go/subscriber/subscriber.go
backend/runner/pubsub/testdata/go/subscriber/types.ftl.go
internal/integration/harness.go

closes https://github.com/block/ftl/issues/3472
- Rebalance after old deployment is killed is faster
- Added integration test that checks to make sure slow consumers are not affected by rebalances (the call will fail due to rebalance and then try again after rebalance)

fix: close consumer group

---

Justfile

This is not perfect, because "args" is variable, but for most use cases this will help quite a bit, avoiding rebuilding the jvm-runtime between every test run.

chore: conditionally rebuild jvm-runtime when inputs change

---

Justfile

Running the clean means that the clean plugin will be downloaded and cached, which should help with the rate limiting we are seeing.

chore: use mvn clean install for JVM build

---

examples/go/cron/cron.go

These info logs were bugging me 😂 
```
info: All modules deployed in 32.57s, watching for changes...
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
```

chore: change cron example to Debugf log

---

backend/controller/state/deployments.go

I noticed the console wasn't showing the runtime language for the deployment state.
BEFORE:
AFTER:

fix: runtime language was not being set in controller state

---

backend/controller/controller.go
backend/controller/state/controllerstate_test.go
internal/eventstream/eventstream.go
internal/raft/eventview.go
internal/raft/eventview_test.go

Implements the View part of EventStream on top of Raft.
Subscribing to events is not supported, as Raft protocol is not designed for that.
We should add notifications on view changes to the API as a followup, though.

chore: eventview implementation on top of raft

---

backend/controller/controller.go
backend/provisioner/runner_scaling_provisioner.go
internal/rpc/context.go
internal/rpc/rpc.go
internal/schema/schemaeventsource/schemaeventsource.go
jvm-runtime/plugin/common/jvmcommon.go

This drops the level of some of the most noisy / less informative debug messages to trace.

chore: drop some log messages to trace

---

backend/console/console.go
backend/controller/controller.go
backend/controller/deployment_logs.go
backend/ingress/view.go
backend/provisioner/scaling/localscaling/local_scaling.go
backend/runner/pubsub/consumer.go
backend/timeline/service.go
frontend/cli/cmd_serve.go
go-runtime/ftl/ftltest/pubsub.go
go-runtime/goplugin/service.go
internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/buildengine/terminal.go
internal/channels/itercontext.go
internal/lsp/lsp.go
internal/routing/routing.go
internal/routing/verb_routing.go
internal/schema/schemaeventsource/schemaeventsource_test.go

Simplifies this:
```go
for {
select {
case <-ctx.Done():
return
case msg := <-events:
// DO STUFF
}
}
```
To this:
```go
for msg := range channels.IterContext(ctx, events) {
// DO STUFF
}
```

refactor: simplify the common case of ranging over a channel w/ cancellation

---

Justfile
cmd/go2proto/main.go
cmd/go2proto/pbtmpl.go
cmd/go2proto/testdata/model.go
cmd/go2proto/toprototmpl.go
common/schema/schema.go

This makes the source files more self-contained, which is nice, but is also a step towards being able to support multiple packages - when we import a Go package with directives, we will know that it is a protobuf package, and we won't generate types for it in the current package.
Next I'll move the definition of the "roots" into code.

refactor: move go2proto configuration from flags to comment directives

---

common/schema/validate.go
common/schema/validate_test.go

- Visit each child before validating it's parent, so normalization of child nodes is done before validation of parent nodes.
- A bunch of tests used `ref.Module == ""` to refer to builtins, but we want all schema to be fully qualified.

fix: all references without module get normalized to its module

---

backend/runner/pubsub/integration_test.go
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRecorder.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/VerbRegistry.java
jvm-runtime/jvm_integration_test.go
jvm-runtime/testdata/go/gomodule/server.go
jvm-runtime/testdata/go/gomodule/types.ftl.go
jvm-runtime/testdata/java/javaclient/src/main/java/xyz/block/ftl/test/TestInvokeGoFromJava.java
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/TestInvokeGoFromKotlin.kt

fix: handle JVM deserialization of generic types

---

frontend/console/src/components/Button.tsx
frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx

- Match the dropdown style to the filter panel dropdown
- Update dividers, background, and selected colors
- Update spacing to be consistent

feat: updating styling on multiselect and tree

---

frontend/cli/main.go

Fixes #3142
BEFORE:
```sh
ftl deploy --endpoint=http://localhost:4678/
info:time:build: Building module
info:time:build: Module built (1.48s)
info:time:deploy: Deploying module
✘[time]
```
AFTER:
```sh
ftl deploy --endpoint=http://localhost:4678/
info:time:build: Building module
info:time:build: Module built (1.61s)
info:time:deploy: Deploying module
ftl: error: failed to deploy: failed to get artefact diffs: unavailable: dial tcp 127.0.0.1:8893: connect: connection refused
```

fix: console dropping some errors messages

---

go-runtime/compile/stubs.go

This should fix the issue where FTL will always use the latest released version in some cases.

fix: when using a dev version scaffold a replacement

---

backend/controller/leases/testdata/go/leases/go.mod
backend/controller/leases/testdata/go/leases/go.sum
backend/controller/sql/testdata/go/database/go.mod
backend/controller/sql/testdata/go/database/go.sum
backend/controller/sql/testdata/go/mysql/go.mod
backend/controller/sql/testdata/go/mysql/go.sum
examples/go/mysql/go.mod
examples/go/mysql/go.sum
examples/go/postgres/go.mod
examples/go/postgres/go.sum
go-runtime/ftl/ftltest/testdata/go/subscriber/go.mod
go-runtime/ftl/ftltest/testdata/go/subscriber/go.sum
go-runtime/ftl/ftltest/testdata/go/verbtypes/go.mod
go-runtime/ftl/ftltest/testdata/go/verbtypes/go.sum
go-runtime/ftl/ftltest/testdata/go/wrapped/go.mod
go-runtime/ftl/ftltest/testdata/go/wrapped/go.sum
go-runtime/ftl/testdata/go/mapper/go.mod
go-runtime/ftl/testdata/go/mapper/go.sum
go-runtime/ftl/testdata/go/typeregistry/go.mod
go-runtime/ftl/testdata/go/typeregistry/go.sum
internal/container/container.go
internal/terminal/noop.go
internal/terminal/status.go

Without this FTL appears to hang on startup for clean installs
Note that this could still be improved as it is slightly janky when pulling multiple laters, but is still a big improvement over the current state.

feature: show container pulls

---

internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/eventview_test.go

Dragonboat returns shard not ready errors if there is a leader election in progress. This catches those and retries

fix: cleanly leaving the raft cluster

---

frontend/console/src/api/timeline/use-module-trace-events.ts
frontend/console/src/api/timeline/use-request-trace-events.ts
frontend/console/src/api/timeline/use-timeline.ts
frontend/console/src/features/timeline/Timeline.tsx

This integrates [ tanstack infinite query ](https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries) to avoid reloading the entire timeline when new events arrive.

feat: use infinite query for streaming endpoint

---

internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/eventview_test.go

Also, adds retries in the case of timeouts when an election is in progress

chore: when closing a nodehost, self deregister from all shards

---

cmd/raft-tester/main.go
cmd/raft-tester/statemachine.go
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/eventview_test.go
internal/retry/retry.go

Changes `Join` to take a cluster control endpoint to send the add member request when joining as a new member.
Changes the raft tester to support joining.
Still, it seems that recovering from crashed nodes is not working properly, fixing that as a followup.

feat: Automatically join the raft cluster

---

cmd/raft-tester/main.go
internal/eventstream/eventstream.go
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/eventview.go
internal/raft/eventview_test.go

Unfortunately, it seems that polling for log id changes is the only way to listen to changes in dragonboat.

feat: Channel to listen to changes

---

cmd/raft-tester/main.go
cmd/raft-tester/statemachine.go
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/eventview.go
internal/raft/statemachine.go
internal/statemachine/statemachine.go

This will make it easier to replace raft based implementations with in memory versions for testing

chore: extract statemachines and state machine handles to a separate package

---

go-runtime/schema/enum/analyzer.go
go-runtime/schema/schema_integration_test.go
go-runtime/schema/testdata/one/one.go
go-runtime/schema/testdata/one/types.ftl.go
go-runtime/schema/testdata/pubsub/types.ftl.go
go-runtime/schema/testdata/two/types.ftl.go
python-runtime/compile/testdata/echo/uv.lock

Fixes #2857
This `go` code...
Extracts to this schema now

fix: reused enum type schema extraction

---

backend/provisioner/dev_provisioner.go

fixes https://github.com/block/ftl/issues/3909
We don't yet have a good solution for resetting topics to change the number of partitions. So warning is better for now and we can revisit it later.

fix: allow and warn for partition mismatches in dev

---

backend/provisioner/inmem_provisioner.go

Fixes a race condition where multiple go routines would try and append to the same slice concurrently.
We would end up losing some RuntimeEvents.
The fix involves publishing to a channel, aggregating the events and then marking the step as complete.
I only started seeing the bug when pubsub provisioning began completing multiple steps in quick succession: https://github.com/block/ftl/pull/3916

fix: race condition while collecting runtime events

---

backend/runner/runner.go
internal/dev/redpanda.go

fixes: https://github.com/block/ftl/issues/3901
prerequisite: https://github.com/block/ftl/pull/3917
Wraps `docker compose up` with a lock and a cached success flag.

fix: speed up pubsub provisioning

---

backend/cron/service.go
backend/ingress/view.go
internal/schema/schemaeventsource/schemaeventsource.go
internal/schema/schemaeventsource/schemaeventsource_test.go

Can only be true because of 
```
if !resp.ModuleRemoved {
return nil
}
```
guard

chore: remove event field that is always true

---

backend/provisioner/registry.go
docs/content/docs/getting-started/quick-start/index.md
frontend/cli/cmd_init.go
frontend/cli/cmd_new.go
frontend/cli/main.go
jvm-runtime/jvm_hot_reload_test.go

Fixes #3924
Automatically create project folder and update help:
```
Usage: ftl init <name> [<dir>] [flags]
Initialize a new FTL project.
Examples:
ftl init myproject        # Creates a new folder named "myproject" and initializes it
ftl init myproject .      # Initializes the current directory as "myproject"
ftl init myproject custom # Creates a folder named "custom" and initializes it as "myproject"
```
Creating a new ftl project will provide some help to the user as well:
```
ftl init myproject
Successfully created FTL project 'myproject' in myproject
To get started:
cd myproject
ftl dev
```
And update docs site:

feat: `ftl new` and `ftl init` updates

---

jvm-runtime/plugin/common/jvmcommon.go

Each build command would accumulate a file watcher in the jvm plugin which would eventually lead to slow downs.

fix: jvm plugin stops accumulating file watchers

---

jvm-runtime/plugin/common/jvmcommon.go

fixes #3935
Previously only the first build attempt would send a build failure event if quarkus could not successfully start.

fix: send build failure event when quarkus can not start for subsequent builds

---

backend/controller/leases/clientleaser.go
backend/lease/service.go

Previously all leases were being obtained with the key `[ ]`

fix: leases were not passing along keys

---

frontend/console/src/features/graph/GraphPane.tsx
internal/buildengine/build.go

fix: layout on graph pane

---

backend/controller/controller.go
backend/controller/schemaservice.go
backend/controller/state/controllerstate.go
backend/controller/state/controllerstate_test.go
backend/controller/state/deployments.go
backend/controller/state/eventextractor.go
backend/controller/state/eventextractor_test.go
backend/controller/state/runners.go
backend/controller/state/statemachine.go
backend/protos/xyz/block/ftl/v1/mixins.go

Eventually, we will want to include runner state in the runtime of schemas. However, for now, separate the schema state from runner state so we can move the schema state management into a separate service without explicitly including runners in its API

chore: separate runner state from schema state

---

docs/content/docs/reference/pubsub.md

closes https://github.com/block/ftl/issues/3496

docs: update pubsub docs

---

backend/controller/state/controllerstate.go
backend/controller/state/controllerstate_test.go
backend/controller/state/deployments.go
backend/controller/state/eventextractor.go
backend/controller/state/eventextractor_test.go
backend/controller/state/runners.go
internal/model/deployment_key_test.go
internal/model/keys.go
internal/model/runner_key_test.go

Unfortunately `[]byte` is not `comparable` in go, so I had to convert that to string.

chore: make KeyType comparable, so that we can retain the type safety when using them as map keys

---

jvm-runtime/ftl-runtime/common/bom/pom.xml
jvm-runtime/ftl-runtime/common/build-parent/pom.xml
jvm-runtime/ftl-runtime/common/deployment/pom.xml
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/ftl-runtime/java/build-parent/pom.xml
jvm-runtime/ftl-runtime/java/deployment/pom.xml
jvm-runtime/ftl-runtime/java/runtime/pom.xml
jvm-runtime/ftl-runtime/kotlin/build-parent/pom.xml
jvm-runtime/ftl-runtime/kotlin/deployment/pom.xml
jvm-runtime/ftl-runtime/kotlin/runtime/pom.xml
jvm-runtime/ftl-runtime/pom.xml
jvm-runtime/ftl-runtime/test-framework/pom.xml

Makes JVM names consistent
Old:

chore: consistent capitalisation of FTL in poms

---

frontend/cli/cmd_new.go
go-runtime/goplugin/service.go
internal/buildengine/engine.go
internal/projectconfig/projectconfig.go
internal/watch/watch.go
internal/watch/watch_integration_test.go
jvm-runtime/plugin/common/jvmcommon.go

fixes https://github.com/block/ftl/issues/4039
`watch` can now be configured to only discover modules while it has acquisition of a file lock.
This allows coordination with `ftl new` so that half scaffolded modules are not detected too quickly, causing build errors.

fix: prevent discovery of modules while scaffolding modules

---

internal/buildengine/engine.go

Even modules without any dependancies should have stubs generated so that the user can easily import them.

fix: all modules should have stubs generated

---

backend/protos/xyz/block/ftl/language/v1/mixins.go
cmd/go2proto/testdata/go2proto.to.go
examples/go/echo/types.ftl.go
go-runtime/compile/build.go

Compiler errors can have newlines in them, which seems to break our terminal formatting. Removing those newlines.
BEFORE:
AFTER:

fix: formatting of go compiler errors

---

internal/buildengine/deploy.go

closes https://github.com/block/ftl/issues/4062
We were logging the start of deployment at info level, but not the completion log.

chore: log deployment finished as info

---

backend/controller/controller.go
backend/controller/schemaservice.go
backend/controller/state/controllerstate.go
backend/controller/state/controllerstate_test.go
backend/controller/state/deployments.go
backend/controller/state/eventextractor.go
backend/controller/state/eventextractor_test.go

Removes `Deployment` struct, which is no longer needed. After this the state is a map from deployment key -> schema

feat: Remove Deployment

---

backend/runner/runner.go

If lots of services are starting startup can take a while

fix: increase runner timeout

---

docs/content/docs/help/glossary.md
docs/content/docs/reference/types.md

Added a table for basic types, and sections for the more complex types such as sum types. Each section includes examples in the three main supported languages.
Note: there are some TODOs

docs: flesh out the types documentation

---

backend/controller/controller.go

BEFORE:
`ftl status`
```json
{
"key": "dpl-echo-1b4ika76nibqepu0",
"name": "echo",
"minReplicas": 1,
"replicas": 1
},
```
AFTER:
`ftl status`
```json
{
"key": "dpl-echo-ylcjj355jm6dja",
"language": "go",
"name": "echo",
"minReplicas": 1,
"replicas": 1
},
```

fix: missing language in the deployment runtime status

---

frontend/console/package.json
frontend/console/vite.config.ts
pnpm-lock.yaml

- add new `build:analyze` script to console for rollup visualizations
BEFORE (9.38s with warnings):
```
vite v6.0.11 building for production...
✓ 5440 modules transformed.
dist/index.html                                       1.36 kB │ gzip:   0.55 kB
dist/assets/favicon-jjzVXmZJ.ico                     15.41 kB
dist/assets/index-CB5hp2DV.css                       64.74 kB │ gzip:  10.95 kB
dist/assets/vendor-fuse-DPyu62bB.js                  15.77 kB │ gzip:   5.40 kB
dist/assets/vendor-react-D8uXf6-9.js                 87.16 kB │ gzip:  29.84 kB
dist/assets/vendor-json-schema-library-c1NQVLVx.js   95.20 kB │ gzip:  27.38 kB
dist/assets/vendor-yaml-DPZo3Gqr.js                 105.03 kB │ gzip:  32.43 kB
dist/assets/vendor-protos-DP8__gRb.js               168.87 kB │ gzip:  27.59 kB …
```

chore(rollup): update rollup config to fix warnings

---

cmd/ftl/cmd_serve.go
frontend/console/local.go
frontend/console/release.go

Previously the console would build (if needed) while we were deploying modules. This would cause the console to not become available until all modules were deployed in some cases which made using the console to debug quite challenging. Now we synchronously build the console code first, then async start the server.

feat: Aat/foreground console

---

common/schema/edges.go
common/schema/edges_test.go

closes https://github.com/block/ftl/issues/4190
It didn't end up being a method on `schema.Node` as the implementation is the same for all node types.

feat: calculate graph edges for schema

---

.golangci.yml
backend/controller/leases/clientleaser.go
backend/controller/leases/fake_lease.go
backend/controller/scheduledtask/scheduledtask_test.go
backend/provisioner/scaling/localscaling/local_scaling.go
backend/runner/pubsub/consumer.go
backend/runner/runner.go
backend/schemaservice/schemaservice.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/cmd_dev.go
cmd/ftl/main.go
common/plugin/serve.go
go-runtime/goplugin/service.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go
internal/buildengine/languageplugin/plugin.go
internal/channels/itercontext_test.go
internal/integration/harness.go
internal/pgproxy/pgproxy.go
internal/pgproxy/pgproxy_test.go
internal/raft/cluster.go
internal/terminal/interactive.go
jvm-runtime/plugin/common/jvmcommon.go

Why? Because error messages like `error: updates service failed: build updates
service stopped serving: context canceled` are not super useful.

refactor: context.WithCancel() -> context.WithCancelCause()

---

cmd/ftl/main.go
go-runtime/ftl/ftltest/ftltest.go
internal/configuration/providers/registry.go
internal/profiles/profiles.go
internal/profiles/profiles_test.go

This will simplify factoring out `projectconfig`.

refactor: temporarily disable 1Password secret provider

---

backend/runner/runner.go

Fixes https://github.com/block/ftl/issues/4229
Some more info:
- The old runner is terminated properly, but there seems to be some race where the context cancellation cause is propagated places sometimes.
- eg: `https://github.com/block/ftl/blob/main/backend/runner/runner.go#L385`
- We had checks in place to ignore the errors if they were context cancelled errors, but we have moved away from using context cancelled errors.

fix: silence unwanted runner terminated errors

---

backend/provisioner/dev_provisioner.go

fixes: https://github.com/block/ftl/issues/4191
Existing data stays on the original partitions, new data is spread across all partitions.
There is no way to decrease the number of partitions for a topic, so that remains as a warning.

fix: allow dev provisioner to increase topic partitions

---

cmd/ftl/cmd_new.go
common/schema/validate.go
common/schema/validate_test.go

We can't compile go modules if module names use reserved go keywords.
Previously we checked for this in `ftl new` but modules can be manually renamed.

fix: disallow modules to use reserved names

---

backend/runner/runner.go

Fixes these 2 issues:
- Logger was being created with runner key before the runner key was defaulted to a value
- Logger with runner key attributes was not saved to context, so it was not being used in later logs
Old logs via kubectl:
```
{"level":"debug","message":"Starting FTL Runner","time":"2025-02-03T02:39:51.92719858Z"}
// Initial logs have a runner key of "rnr-"
{"level":"debug","attributes":{"runner":"rnr-"},"message":"Starting FTL Runner","time":"2025-02-03T02:39:51.92719858Z"}
{"level":"debug","attributes":{"runner":"rnr-"},"message":"Deployment directory: deployments","time":"2025-02-03T02:39:51.927242169Z"}
{"level":"debug","attributes":{"runner":"rnr-"},"message":"Using FTL endpoint: http://10.0.1.244:8892","time":"2025-02-03T02:39:51.927341253Z"} …
```

fix: runner logger includes key attribute

---

backend/provisioner/deployment.go
backend/provisioner/runner_scaling_provisioner.go
backend/schemaservice/changesetstate_test.go
backend/schemaservice/events.go
backend/schemaservice/schemaservice.go
backend/schemaservice/state.go

This is currently a bit of a no-op, but this adds the relevant states and get the provisioner to move the changset through the states. 
Significant additional work/tests etc are required.

feat: add changeset cleanup states

---

frontend/console/src/features/engine/hooks/use-engine-status.ts
frontend/console/src/features/engine/hooks/use-stream-engine-events.ts
frontend/console/src/features/infrastructure/BuildEngineEvents.tsx
internal/buildengine/updates.go

There were many random cases where the console status would not match the status displayed in the terminal:
This change fixes some of the logic in the updates and simplifies the frontend code now that we can rely on order and deduplication on the backend.

fix: module status in console not matching actual engine status

---

backend/cron/service_test.go

Fixes #4237
Hopefully. I couldn't reproduce locally.
What I suspect was happening is that the 2 crons were running at the same schedule so it could be possible for `echo` to fire twice before `time` gets a chance to run.

fix: flaky cron test

---

internal/raft/cluster_test.go

I ran this 200 times with no issues. Maybe recent cluster test improvements have stabilised this as well

chore: re-enable TestStateIter.

---

backend/schemaservice/changesetstate_test.go
backend/schemaservice/state.go

We should add proper pre log proposal validation to prevent these

fix: do not fail the raft host if there is an invalid event in the log

---

frontend/console/e2e/global-setup.ts
frontend/console/playwright.config.ts

Some changes/optimizations for the console e2e tests
- Add more logging to report on module deployment time when starting `ftl dev`
```
All modules ready after 96.698s
Total startup time: 101.976s
```
- Increase number of workers for playwright to `2` (previous was `1` on CI)
- Increase number of cores for `ftl dev` to `2` on CI

chore: improve CI times for console e2e

---

backend/schemaservice/schemaservice.go
charts/ftl/values.yaml
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/rpc/server.go

Adds the Raft control service to existing grpc servers, and uses it to join the cluster if the shard is not an initial member.
Scaling down is not automatic yet. When we scale down, we will need to do it manually via an endpoint I will add next.

fix: automatic scale up for raft clusters

---

backend/schemaservice/schemaservice.go

The field was previously always empty

fix: changesets get created time

---

charts/ftl/templates/admin-deployment.yaml
charts/ftl/templates/cron.yaml

Consolidating `FTL_SCHEMA_ENDPOINT` to literal `http://ftl-schema:8892` the same as elsewhere to fix this error:
I think because ftl schema now has multiple services incl raft?
```
│ Error: template: ftl-aws/charts/ftl/templates/cron.yaml:41:39: executing "ftl-aws/charts/ftl/templates/cron.yaml" at <.Values.schema.service.name>: nil pointer evaluating interface {}.name
│ 
│   with helm_release.ftl,
│   on main.tf line 136, in resource "helm_release" "ftl":
│  136: resource "helm_release" "ftl" {
│ 
```

fix: charts unable to calculate schema endpoint value

---

backend/cron/service.go
examples/go/echo/types.ftl.go

The original cron job in map was overwritting the updated time, using pointers means that there is only one instance to update

fix: cron called repeatedly when schema is updated

---

common/schema/databaseruntime.go
common/schema/moduleruntime.go
common/schema/moduleruntimebase.go
common/schema/moduleruntimedeployment.go
common/schema/moduleruntimerunner.go
common/schema/moduleruntimescaling.go
common/schema/topic.go
common/schema/topicruntime.go
common/schema/verbruntime.go

Just makes it a bit easier to navigate.

refactor: split runtime types into separate files

---

docs/docs/getting-started/quick-start.md
docs/docusaurus.config.ts
docs/package.json
docs/src/css/custom.css
docs/src/pages/index.module.css
docs/src/pages/index.tsx
pnpm-lock.yaml

- Remove nasty green colors (replace with tailwind colors to better match the console)
- Remove section about VSCode extension starting the dev server
- Add some icons
- Route directly to quick start page if "Get Started" is clicked on the homepage
- Add back empty `blog` folder to silence build warnings

chore: fix docs styling and cleanup

---

charts/ftl/templates/ingress.yaml
charts/ftl/templates/schema-deployment.yaml
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/controlapi.go
internal/rpc/server.go

Generates a random replica id for non initial members. Properly restarts the pod if the id is taken. Makes initial member ids adjustable.
After this, and with the help of the Raft API, we should be able to recover any corrupted data nodes (as long as we retain quorum)
Next, I will write a quick runbook on managing the Raft cluster.

feat: Raft Ops

---

charts/ftl/templates/schema-deployment.yaml
charts/ftl/values.yaml

8992 is easier to mistake for 8892

chore: move raft to listen to 8893 instead of 8992.

---

cmd/ftl/cmd_await_summary.go
internal/buildengine/engine.go

Handle case where modules stay in "waiting for build" state if a module it depends on failed to build.
Also `ftl await-summary` handles no module state.

fix: engine is idle if modules are waiting for failed modules

---

internal/sqlc/sqlc.go

Previouslly the build engine would only receive "exit status code 1" as the build error, while the actual error was logged. This in turn left goose unable to figure how to fix the issue.

fix: sqlc command captures stderr

---

cmd/ftl/cmd_await_summary.go
internal/exec/exec.go

Otherwise we typically have an extra newline at the end of each error.
Also fixed the spacing of `ftl await-summary` due to this whitespace change.

fix: errs from stderr should be trimmed of whitespace

---

go-runtime/compile/build.go
internal/watch/watch.go

Builds would fail if all queries were removed because marking a file as changed within the build assumed the file still existed.

fix: handle deletion of queries file

---

internal/buildengine/sql_migration_extract.go

Fixes #4365
Looks like `deployDir` will already contain `.ftl` in it's path.

fix: duplicate .ftl folders in module dirs

---

internal/raft/cluster_test.go

This made the tests flaky as we could get port binding collisions

chore: do not run raft tests in parallel.

---

jvm-runtime/plugin/common/error_detector.go
jvm-runtime/plugin/common/jvmcommon.go

Maven logs initial compile errors to `stdout` which means FTL logs them but doesn't capture them.
This fix captures these logs while forwarding them to stdout, then if we do not get a connection from quarkus we search the logs for errors.
This allows build errors to contain the actual errors, which in turn lets users or Goose to fix them.

fix: find initial build errs in stdout for jvm modules

---

internal/rpc/server.go

I was getting
```
error: controller0 failed: failed to start server: FTL terminating with signal interrupt: context canceled: failed to start server: 
```
FTL terminating with signal interrupt: context canceled
occasionally in ftl dev. This fixes it

fix: random ctx cancelled errors

---

internal/buildengine/engine.go

Previously you would get
```
error: Initial deploy failed: build failed: failed to generate language stubs: plugin failed to generate stubs: canceled: context canceled
```
When ctrl+c during the initial build

fix: remove context cancelled error

---

internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/controlapi.go

If the member we are trying to add is alredy in the group, return success.
Previously if the request timed out, the retry would fail ass the member was already in the membership group. This makes such retries succeed

fix: make raft add member idempotent

---

cmd/ftl-provisioner-cloudformation/cf_executor.go
cmd/ftl-provisioner-cloudformation/executor/executor.go
cmd/ftl-provisioner-cloudformation/executor/executor_test.go
cmd/ftl-provisioner-cloudformation/executor/runner.go
cmd/ftl-provisioner-cloudformation/executor/states.go
cmd/ftl-provisioner-cloudformation/mysql.go
cmd/ftl-provisioner-cloudformation/postgres.go
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-cloudformation/status.go
cmd/ftl-provisioner-cloudformation/task.go
internal/concurrency/resgroup.go
internal/concurrency/resgroup_test.go

Separates the CF provisioning into stages with specific inputs and outputs.
This will allow us to overwrite some outputs from CF execution with either hard coded values or executions from a shared CF stack to use a common RDS instance for DBs if desired.
On a high level, the idea here is that we define an ordered list of `Stage`s to execute, and a set of `Ecxecutor`s applying to each stage, and a set of resource types, converting a `State` instance in that stage to a state in a followup `Stage`
So, a Postgres provisioner gets added to the CF template in `StageProvisioning` and the virtual DB and user are created in `StageSetup` after which we reach the final stage `StageDone` from which the runtime updates are created.
This allows us to configure optional executors for `StageProvisioning` …

refactor: Refactor Cloudformation Provisioner

---

internal/rpc/rpc.go

If the context is cancelled it should abort immediatly

fix: improve rpc wait

---

internal/terminal/status.go

- ftl dev
- In the interactive console:
- `ftl kill` each module
- We would end up with the old status getting printed still and leaking into the normal logs
- `ftl schema get` 
- Each line of schema output would be interlaced with the old module status

fix: update terminal status bar when last module being removed

---

cmd/ftl/cmd_serve.go
frontend/console/local.go

This adds a status indicator for the console build, and moves it into a gorouting so it does not block startup.
This should not affect FTL when built with the release tag

fix: improve console build in dev mode

---

jvm-runtime/plugin/common/error_detector.go
jvm-runtime/plugin/common/jvmcommon.go

- Captures errors from jvm build logs (like we do already for `ftl dev` build logs)
- Format the output from jvm build to be consistent with the rest of our logs

fix: collect ftl build logs and format output

---

cmd/ftl/cmd_serve.go

The startup command was being logged with the wrong scope

fix: don't leak logger scope

---

backend/admin/service.go
backend/provisioner/deployment.go

fixes https://github.com/block/ftl/issues/4487
Multiple modules were being treated as deployed because we were only checking if *any* changeset completed, not whether the changeset with that module completed

fix: deploy watches for specific changeset to end

---

go-runtime/compile/stubs.go
internal/buildengine/stubs.go

I noticed that we were creating empty folders in `.ftl/kotlin` at the root of ftl projects. Since we don't use this for `kotlin` and `java` I've moved the folder creation to the language plugin instead.
BEFORE:
AFTER:

fix: only generate .ftl stubs for languages that need it

---

go-runtime/compile/build.go
go-runtime/goplugin/service.go

Changes
- If go plugin can't scaffold code, build failure now includes compiler errors as well as they are usually the reason for the failure
- This exposes the reason better to the user and goose
- Parses go compiler errors into separated build errors, rather than simply removing newlines and creating a single error.
- No special err type for invalidating deps (since we aren't returning any other errors), instead just pass that back as a bool.

fix: include go compiler errors if ftl can’t scaffold

---

cmd/ftl/cmd_new_migration.go

- Run `ftl dev`
- Create a module
- Define a db in the module
- Run `ftl new-sql-migration <modulename>.<dbname> <migrationname>`
The new migration would be created and then FTL will immediately detect it and deploy the module, causing the empty migration to be completed. Writing the actual migration now does nothing...
Hacky fix: We generate the migrartion with placeholder text which makes the migration invalid. This causes the automatic build to fail, preventing the migration until the user updates it with an actual migration.

fix: prevent immediate execution of new migrations

---

internal/buildengine/engine.go

fixes https://github.com/block/ftl/issues/4548
Build engine logs each build error as they happen, and logs a summary of all errors after the first time the engine goes idle.
We don't need to also print out build errors after the first build attempt.

chore: remove duplicate log

---

frontend/console/src/features/engine/engine.utils.ts
frontend/console/src/features/infrastructure/BuildEngineEvents.tsx

Fixes #4596 
* Added `moduleDeployWaiting` to console UI

fix: missing field moduleDeployWaiting in build events

---

jvm-runtime/plugin/common/jvmcommon.go

This makes the status display start spinning when the file change is detected.

fix: send build started event earlier

---

common/schema/visit.go
go-runtime/compile/build.go
go-runtime/schema/extract.go

fixes https://github.com/block/ftl/issues/4623
Repro steps:
- Inject a verb's client into itself
- We now show this error: `cyclic references are not allowed: stockdb.saveStockPriceHandler refers to stockdb.saveStockPriceHandler`

fix: fail go build on infinite ref loop

---

go-runtime/compile/dependencies.go

fixes [ftl dev idles at startup](https://github.com/block/ftl/issues/4622)

fix: skip generated go files when looking for dependencies

---

cmd/ftl/goose_instructions_first_prompt.txt

Hacky workaround. Goose is confused by the logger.Errorf() args and FTL logs errors anyway.

fix: goose doesn’t need to log errors before returning them

---

docs/src/css/custom.css
internal/lsp/markdown/completion/java/pubSubTopic.md
internal/lsp/markdown/completion/kotlin/pubSubTopic.md

Fixes #4638
Example:
```kt
data class Event(
// Event fields
)
@Export
@Topic(name = "topicName", partitions = 1)
interface TopicName : WriteableTopic<Event, SinglePartitionMapper>
```

fix: snippets for @Topic are not @Export by default

---

common/schema/validate.go
go-runtime/goplugin/service.go
go-runtime/schema/schema_integration_test.go
go-runtime/schema/testdata/subscriber/subscriber.go
internal/buildengine/stubs.go
jvm-runtime/plugin/common/jvmcommon.go

Build plugins could claim a module was built when it was actually invalid when validated against the build schema.

fix: validate built module against schema

---

go-runtime/compile/build.go
go-runtime/goplugin/service.go

Changes
- If go plugin can't scaffold code, build failure now includes compiler
errors as well as they are usually the reason for the failure
- This exposes the reason better to the user and goose
- Parses go compiler errors into separated build errors, rather than
simply removing newlines and creating a single error.
- No special err type for invalidating deps (since we aren't returning
any other errors), instead just pass that back as a bool.

fix: each go compiler error should be a separate build error

---

cmd/ftl/cmd_module.go

Improved error output:
```
$ ftl module new go stockticker/mymodule
ftl: error: module name "stockticker/mymodule" cannot contain path separators. Did you mean 'ftl module new mymodule stockticker'
```

fix: suggest correct if new module name is a path

---

backend/provisioner/deployment_test.go
backend/provisioner/registry.go
backend/provisioner/service.go

Now, instead of panic and hanging forever, a deployment to an environment with unsupported resources gives an error like this:
```
> ftl deploy postgres
info:postgres:build: Building...
info:postgres:build: Module built (2.59s)
◞[postgres]
ftl: error: failed to deploy: failed to deploy changeset: unknown: failed to apply changeset: error running deployments: resource type postgres is not supported in this environment
```

fix: proper error when trying to deploy with unsupported resources

---

go-runtime/compile/build.go

- Remove extra whitespace
- Forgot to remove line from slice when we joined it with another line

fix: clean go compile errors and prevent infinite loop

---

backend/controller/controller.go
backend/controller/leases/clientleaser.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_serve.go
go-runtime/ftl/leases.go
go-runtime/internal/impl.go
go-runtime/server/rpccontext/context.go
go-runtime/server/server.go

Step 1 of removing rpc.ContextwithClient from the backend. This functionality was intended to only be used for the go-runtime, but has crept its way into normal backends.
It's problematic because it's "spooky action from a distance", failing at runtime.

refactor: rpc.ContextWithClient copied into go-runtime

---

internal/buildengine/engine.go
internal/buildengine/testdata/depcycle1/go.mod
internal/buildengine/testdata/depcycle2/go.mod
internal/buildengine/topological.go

Fixes https://github.com/block/ftl/issues/4568
Changes:
- Modules with dependency cycles are treated as failed to build (status item goes red, error is logged)
- Once a dependency is detected, we send a build command for the module but ignore the error
- This means we have an active build stream so module changes are detected
- Once the user has fixed a dependency cycle, the updated module will rebuild and then all other modules in the cycle will rebuild (normal dependency build logic)
- Other modules can be built and deployed as usual (previously all modules would sit waiting for the dependency cycle to be resolved)

fix: dependency cycles can be fixed by the user without restarting

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/JVMCodeGenerator.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/PackageOutput.java
jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/JavaCodeGenerator.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java

Fixes: #4734
Note that this does not fix the 'leftover kotlin .class files' problem, this needs to be fixed in Quarkus itself.

fix: delete clients that no longer exist

---

internal/integration/harness.go

This avoids a connection refused spam deludge in the logs

chore: use rpc.Wait in tests

---

frontend/console/src/features/timeline/filters/TimelineFilterPanel.tsx

fix: hide changeset change events by default in timeline

---

backend/cron/go2proto.to.go
backend/provisioner/dev_provisioner.go
backend/provisioner/service.go
charts/ftl/templates/provisioner-deployment.yaml
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-cloudformation/status.go
cmd/ftl-provisioner-sandbox/provisioner.go
cmd/ftl-provisioner/main.go
cmd/ftl/cmd_serve.go
internal/log/logger.go
internal/provisioner/executor/mysql.go
internal/provisioner/executor/postgres.go
internal/provisioner/executor/pubsub.go
internal/provisioner/executor_test.go
internal/provisioner/runner.go

- wires timeline client and timeline log sink to the provisioner
- adds deployment key to the logger when running provisioning tasks

feat: Provisioner logs to timeline

---

jvm-runtime/ftl-runtime/common/deployment/pom.xml
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/pom.xml
jvm-runtime/plugin/common/jvmcommon.go

This lib is unmaintained, and uses an old version of antlr that results in annoying messages

chore: remove toml parsing from the JVM runtime

---

backend/provisioner/service.go
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-sandbox/provisioner.go

Changed log level from Info/Trace to Debug for timeline logging in:
- Main provisioner service
- CloudFormation provisioner plugin
- Sandbox provisioner plugin
This ensures all debug and above logs are sent to the timeline for better visibility into provisioning operations.

feat: send debug and above logs to timeline from provisioner and plugins

---

cmd/ftl/cmd_call.go
cmd/ftl/cmd_replay.go
internal/routing/verb_routing.go

- It can be helpful to know the request key to then understand what happened as part of the call (via the timeline)
- Goose will make use of this
- We will probably want more info in the future so i made the flag not request key specific
- Verb router now includes the request key in the call response it creates

feat: `ftl call -v` prints out more info (just request key for now)

---

backend/provisioner/service.go
cmd/ftl-lease/main.go
cmd/ftl-provisioner/main.go
cmd/ftl-proxy-pg/main.go
cmd/ftl-schema/main.go
cmd/ftl-timeline/main.go
cmd/ftl/cmd_dev.go
internal/buildengine/deploy.go
internal/log/logger.go

Previously, in the dev mode, we were logging events both via the timeline, and directly to stdout. This removes stdout logging so all log events are logged from the timeline.
This also guarantees that the logs look same in local and remote deployments.

feat: Logs via timeline in `dev` mode

---

backend/provisioner/scaling/localscaling/local_scaling.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/cmd_dev.go
internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go

Getting this working reliably requires a bit more work, so lets just disable it for now and log directly from all submodules.
closes https://github.com/block/ftl/issues/4838

fix: do not log from timeline in dev mode

---

.github/workflows/ci.yml

We can't have the pipe char in the artifact name

fix: archive on failure name

---

internal/buildengine/deploy.go

Removes occasional
```
error:build-engine: failed to stream changeset logs: canceled: context canceled
```

fix: no failed to stream changeset logs error if the ctx is cancelled

---

backend/ingress/handler.go
backend/ingress/openapi.go

```
~/dev/ftl $ curl -i http://127.0.0.1:8891/.well-known/service-desc
HTTP/1.1 200 OK
Content-Type: application/vnd.oai.openapi+json; version=2.0
Vary: Origin
Date: Thu, 13 Mar 2025 04:14:10 GMT
Content-Length: 1786
{"swagger":"2.0","info":{"description":"API generated from FTL schema","title":"FTL API","version":"1.0.0"},"paths":{"/get/{name}":{"get":{"description":"Example usage of path and query params\ncurl http://localhost:8891/get/wicket?age=10","consumes":["application/json"],"produces":["application/json"],"operationId":"http.get","parameters":[{"name":"name","in":"path","required":true,"schema":{"type":"string"}},{"name":"age","in":"query","schema":{"type":"integer","format":"int64"}}],"responses":{"200":{"description":"Successful …
```

chore: wire up OpenAPI spec to /.well-known/service-desc

---

common/builderrors/builderrors.go
common/schema/parser.go
go-runtime/compile/build.go
go-runtime/schema/common/common.go
go-runtime/schema/extract.go

This module code:
```go
//ftl:verb
func Verb(ctx context.Context, req struct{}) (TimeResponse, error) {
return TimeResponse{Time: time.Now()}, nil
}
```
Would previously give this build error which lacks any information of where to find the bad code:
`error:time:build: Build failed: unsupported type <nil>`
We now try and attach the best position available to errors that occur in various places of `build/compile.go`, so now we get this error:
`error:time:build: Build failed: /Users/mtoohey/Code/ftl/examples/go/time/time.go:30:1: could not parse request type: unsupported type <nil>`
At this point in the code the verb's request type does not have any position information so it is given the position of the verb instead (ie column 1).

fix: add positions to more go build errors

---

common/schema/jsonvalidate.go
common/schema/jsonvalidate_test.go

Issue #4863: JSON validation now properly checks that float values used as integers are whole numbers. This prevents the internal server error that occurred when passing non-whole numbers (e.g., 1.5) to integer fields.
- Accepts: integers (123) and whole number floats (123.0)
- Rejects: non-whole number floats (123.5) with proper validation error
- Added test cases to verify this behavior

fix: JSON validation now properly handles non-integer values

---

cmd/ftl/cmd_mcp.go
cmd/ftl/goose_instructions.txt
go.mod
internal/mcp/cli.go
internal/mcp/readwrite.go
internal/mcp/status.go
internal/mcp/utils.go

Aims:
- Goose takes a lot of time between each action taken. Often we know the thing goose should find out next, so we should just proactively gather that info for goose to avoid needless back and forth with goose
- Goose is given hints as to what is in code files via the schema. Sometimes goose is confident enough to overwrite those files without actually **reading** those files first... which means it just makes up the parts of the file it wasn't trying to change. We want some level of guarantee that goose reads a file before writing the file.
Changes:
- Added Read and Write MCP tools for FTL, which we tell Goose to use instead of the general `develop` tools included with Goose.
- Read tool returns the content as well as a verification token (just a hash of the content)
- Write tool …

feat: MCP reads and writes files and can proactively provide info

---

go-runtime/schema/schema_integration_test.go
go-runtime/schema/verb/analyzer.go

This code:
```go
//ftl:verb
func Example(ctx context.Context, nothing ftl.Unit) error { ... }
```
Gives this error:
`second parameter must not be ftl.Unit`
It is not clear what the solution to this is for users that do not know to just leave out the request parameter. Goose would try replacing unit with `struct{}`
It now results in this error:
`second parameter must not be ftl.Unit (verbs without a request type should omit the request parameter)`

fix: improve go error if req type is Unit

---

common/schema/edges_test.go
common/schema/metadatadatabases.go
common/schema/schema_test.go

"calls" just seemed a little odd, gramatically.

chore: switch "database calls" to "database uses"

---

go-runtime/compile/build.go

fixes https://github.com/block/ftl/issues/4892

fix: types.ftl.go imports types found within arrays/maps/optionals

---

backend/admin/service.go
backend/timeline/filters.go
backend/timeline/filters_test.go
backend/timeline/service.go
backend/timeline/service_test.go
cmd/ftl/cmd_logs.go
cmd/ftl/main.go
internal/channels/notifier_test.go

For now, it streams all logs from the start, and only streaming is supported. Will add a limit of how much logs to read as a follow-up, as well just returning latest logs.
Also, timeline does scan all events on every update to the event stream. Will look at fixing this as aa follow-up as well

fix: implement a ftl logs command to allow streaming of logs from modules

---

cmd/ftl/cmd_sql_migration_new.go
cmd/ftl/cmd_sql_new.go

Elsewhere we use the `ftl dev` search paths (interactive console) or the project search paths.
This will be cleaned up better soon when we standardize on a single module dir for a project.

fix: db commands use common module dirs search paths

---

backend/admin/service.go
backend/timeline/service.go
backend/timeline/service_test.go
cmd/ftl/cmd_logs.go

`ftl logs -t` works now both independently and with `-f` to fetch n previous logs

feat: support -t to fetch only given number of log events

---

internal/buildengine/engine.go

Introduced the bug in this PR: https://github.com/block/ftl/pull/4923
We cleared the error out too late such that builds keep failing so the errors never get cleared

fix: slq build errors would never get cleared

---

.github/renovate.json5

```
🐚 ~/dev/ftl $ npx --yes --package renovate -- renovate-config-validator --strict
INFO: Validating .github/renovate.json5
WARN: Found errors in configuration
"file": ".github/renovate.json5",
"warnings": [
{
"topic": "Configuration Error",
"message": "The \"allowedCommands\" option is a global option reserved only for Renovate's global configuration and cannot be configured within a repository's config file."
}
]
```

chore: remove unused config entry

---

backend/timeline/filters.go
backend/timeline/service.go
backend/timeline/service_test.go

Previously, every `GetTimeline` would iterate over all events in the timeline. As this is called on every update in streaming timeline endpoint, it could get slow with a lot of data.

feat: index timeline by event ids

---

common/schema/metadatagenerated.go
internal/sql/sql.go
internal/sql/sql_test.go

- sqlc does not provide enough information for us to get a position of a verb in the source sql file.
- Instead we read in the sql files and try to match `-- name: <name>` lines with the names of the verbs.

fix: add position to sql verbs and data types

---

go-runtime/schema/topic/analyzer.go

Topics with external event types were causing issues because the event type was not `*ast.Ident`. Fixed by using common `ExtractType` method to extract the event type.

fix: allow injecting topics with external events

---

go-runtime/compile/build.go
go-runtime/schema/call/analyzer.go
go-runtime/schema/schema_integration_test.go
go-runtime/schema/verb/analyzer.go

Previously we looked for `topic.Publish(...)` calls to detect if a module tried to publish to an external topic.
Now that we use injection for resources, we can instead check if a topic resource is from a different module.
When injecting an external topic I was getting a seemingly unrelated error that was not obvious that it was because it was not allowed (something about a partition mapper couldn't be found).

fix: prevent injecting external topics

---

frontend/console/src/features/traces/TraceDetails.tsx

fixes https://github.com/block/ftl/issues/4836
Duration text is fixed and graph shows the correct width for each segment.

fix: trace graph shows long durations correctly

---

backend/runner/pubsub/integration_test.go
backend/timeline/integration_test.go
internal/integration/actions.go
jvm-runtime/jvm_integration_test.go
smoketest/exemplar_integration_test.go
smoketest/exemplar_smoke_test.go

Building and deploying modules in integration tests take more time than needed if we do them serially.

chore: speed up tests by deploying in parallel

---

backend/cron/service.go

```
debug:cron: Received cron event &{2f2f204275696c742d696e20747970657320666f722046544c2e0a6275696c74696e206d6f64756c65206275696c74696e207b0a20202f2f20436174636852657175657374206973206120726571756573742073747275637475726520666f722063617463682076657262732e0a20206578706f72742064617461204361746368526571756573743c5265713e207b0a2020202076657262206275696c74696e2e5265660a2020202072657175657374205265710a20202020726571756573745479706520537472696e670a202020206572726f7220537472696e670a20207d0a0a20206578706f7274206461746120456d707479207b0a20207d0a0a20202f2f204661696c65644576656e74206973207573656420696e2064656164206c657474657220746f706963732e0a20206578706f72742064617461204661696c65644576656e743c4576656e743e207b0a202020206576656e74204576656e740a202020206572726f7220537472696e670a20207d0a0a20202f2f204854 …
```

fix: remove weird (and incorrect debug print)

---

internal/clirpc/clirpc.go

Connect [supports application/proto](https://connectrpc.com/docs/protocol) via standard HTTP, so rather than try to emulate gRPC we just use this.

refactor: simplify clirpc.Invoke

---

cmd/ftl/cmd_call.go

Uses escape codes to encode trace URL as a hyperlink (based on: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)
A better fix would be to detect if the terminal emulator supports this escape sequence if out the hyperlink on the request key line itself.
In iTerm2:
In Mac Terminal (fallbacks to just text):

fix: show trace url as a link in terminal

---

examples/go/time/types.ftl.go
internal/terminal/interactive.go

Fixes #4900
Sending `ftl --help`:
```
❯ ftl --help
Usage: ftl <command> [flags]
FTL is a platform for building distributed systems that are safe to operate,
easy to reason about, and fast to iterate and develop on.
```
Starting interactive `ftl` then sending `--help`
```
❯ ftl
❯ --help
Usage: ftl <command> [flags]
FTL is a platform for building distributed systems that are safe to operate,
easy to reason about, and fast to iterate and develop on.
```
Starting interactive `ftl dev` then sending `--help`
```
info:echo:build: Module built (1.69s)
info:build-engine: All modules deployed in 16.40s, watching for changes...
❯ --help
Usage: ftl <command> [flags]
FTL is a platform for building distributed systems that are safe to operate,
easy to reason about, and fast to iterate and develop on. …
```

fix: duplicate commands in cli output

---

jvm-runtime/ftl-runtime/common/build-parent/pom.xml
jvm-runtime/plugin/common/commands.go
jvm-runtime/plugin/common/java_plugin_test.go
jvm-runtime/plugin/common/jvm_logging.go
jvm-runtime/plugin/common/service.go

- Don't run with -q by default, so all info can be logged
- Log normal maven output at debug level, so it is not visible by default but can easily be retrieved
- Dump full maven output if startup fails
- Return error output to the build engine
fixes: #5066

fix: better maven output

---

cmd/ftl/cmd_mysql.go
cmd/ftl/cmd_postgres.go
cmd/ftl/cmd_sql_new.go

Setting the sub command struct value broke Kong's defaulting for env values.
Updated the logic to just update the field we care about, which fixes the issue.
Previously:
```
ftl dev somedir <-- a dir with a users module
ftl mysql new users.db
```
This would fail because the `ftl mysql new` command did not know where the modules could be found (passed as a env var)

fix: allow kong to set flags based on env

---

cmd/ftl/cmd_mcp.go

I think this solves the invalid json schema errors we were seeing in Goose

fix: mcp tool schema is now valid

---

.github/workflows/ci.yml

This should help with rate limiting issues in integration tests with redpanda. Previously, we were doing this for ifrastructure tests alredy

chore: login to docker also in integration tests

---

backend/controller/state/controllerstate_test.go
backend/cron/service_test.go
backend/ingress/handler_test.go
backend/provisioner/deployment_test.go
backend/provisioner/dev_provisioner.go
backend/provisioner/scaling/kube_scaling_integration_test.go
backend/runner/pubsub/integration_test.go
backend/schemaservice/changesetstate_test.go
backend/schemaservice/eventextractor_test.go
backend/schemaservice/schemaservice.go
backend/schemaservice/state_test.go
cmd/go2proto/testdata/model_test.go
go-runtime/ftl/ftltest/database.go
internal/key/deployment_key.go
internal/key/deployment_key_test.go
internal/routing/routing_test.go
internal/schema/schemaeventsource/schemaeventsource_test.go
jvm-runtime/plugin/common/service.go

This will enable us to propagate the realm name with deployments.
For now, the realm defaults to "default" everywhere, but next we will propagate that from the project config properly and store to state

chore: add realm to deployment key

---

backend/goose/goose.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_goose.go

This way we don't have `cmd_goose` calling `backend/goose` and backend/goose calling `ftl goose`.
Moving to `jsonl` file extension to reflect the real data type

fix: reset goose session directly and rename file to jsonl

---

internal/buildengine/engine.go

This speeds up goose a lot as it doesnt need to wait as long to know that all modules are finished building

fix: reduce time it takes for engine to idle

---

.npmrc

This prevents us from overriding npm registry in our own npmrc files in a corporate environment

chore: remove registry from .npmrc

---

backend/runner/pubsub/consumer.go

fixes https://github.com/block/ftl/issues/4822
Confirmed that killing FTL could cause progress consumer group offsets. It is a very hard edge case to reproduce though.
Steps:
- Call to verb fails due to a `connect.Error` while the pubsub context is not yet cancelled.
- Consumer marks the offset
- Sarama library then tries to sync the offset to kafka/redpanda. This usually never actually completes which is why we don't see this happen in practice a lot.
Was not able to make an integration test that would fail for this.

fix: connection errors do not count as a consumption attempt

---

backend/runner/pubsub/pubsub_common_test.go
backend/runner/pubsub/testdata/kotlin/publisher/src/main/kotlin/xyz/block/ftl/java/test/publisher/Publisher.kt

fixes https://github.com/block/ftl/issues/5163
Cause: After loading RedPanda in CI, the first consumer group can take longer to claim partitions than other times.
This caused the first pubsub test to fail (`TestPubSub/java`). After all three languages were attempted, we would then retry all 3, which would succeed. This doubled the time it took to run this test.
Fix: We already had a delay to wait for consumers to be read in the test. Increasing that delay should fix this annoying issue.

fix: TestPubSub was slow

---

backend/runner/pubsub/consumer.go
backend/runner/pubsub/integration_test.go

closes https://github.com/block/ftl/issues/4831
`TestConsumerGroupMembership` tries to make sure that runners de-register themselves from redpanda on shutdown.
That test was flakey though, and so the duration was made more leniant. But that meant the test didn't really check anything as the new timeout was longer than redpandas timeout, so if our runners didn't notify redpanda the test would still pass.
A recent fix to how we handle shutdowns while consuming may have fixed the flakiness, so we can make the test strict again.
Please revert this PR if the test remains flakey...

chore: make previously flaky pubsub test strict again

---

internal/watch/watch.go

We were not releasing a flock if an error occurerd while discovering modules.

fix: module watching would get stuck after error

---

cmd/ftl/cmd_dev.go

Looks like this PR moved the engine code but not the error handling code: https://github.com/block/ftl/pull/5125

fix: `ftl dev` handles build engine initiation error

---

internal/moduleconfig/moduleconfig.go

`.DS_STORE` in a module's db dir was causing building failures

fix: hidden files should not count as db engines

---

examples/go/echo/types.ftl.go
internal/buildengine/engine.go

Fixes #5039
This handles changes to the configuration by reloading and rebuilding modules. It also adds logging to the `BuildAndDeploy` calls so we can better track errors.
https://github.com/user-attachments/assets/950c2b73-85ff-4889-a721-ba64b8788320

fix: reload and rebuild modules when configuration changes

---

internal/buildengine/engine.go
internal/watch/watch.go
internal/watch/watch_integration_test.go

Fixes #5182
I'm not sure if this will have unwanted side effects as it could have weird behaviors with new ftl projects where the folder is empty since it's a newly created project.

fix: show error if module-dir does not exist

---

internal/terminal/status.go

Minor but hopefully useful color updates to the terminal status.
`blue` colors are indicating building
`green` colors are indicating deploying
So a user can tell what stage the module is in. This also should match the consoles status display on the web view.

feat: Improve terminal status rendering accuracy and colors

---

cmd/ftl/main.go

Killing the process group with SIGINT resulted in the main process terminating with an exit code of 0, regardless of the real exit code. This change ignores SIGINT just prior to killing the process group.
```
~/dev/ftl $ ftl status
Usage: ftl <command> [flags]
Run "ftl --help" for more information.
ftl: error: unexpected argument status
~/dev/ftl $ echo $?
0
```
After:
```
~/dev/ftl $ ftl status
Usage: ftl <command> [flags]
Run "ftl --help" for more information.
ftl: error: unexpected argument status
~/dev/ftl $ echo $?
80
```

fix: don't skip os.Exit(code)

---

internal/buildengine/engine.go

We were reading the modules from the list of modules we were copying them into

fix: stub generation would fail because the schema was incomplete

---

cmd/ftl/cmd_edit.go
cmd/ftl/main.go
internal/editor/editor.go
internal/terminal/predictors.go

Currently supporting `vscode`, `cursor`, `intelliji`, `zed`.

feat: Add edit cli command to open decls in editors

---

backend/console/console.go
backend/ingress/service.go
backend/schemaservice/schemaservice.go
common/schema/realm.go
common/schema/realm_test.go
common/schema/schema.go
internal/schema/schemaeventsource/schemaeventsource.go

This avoids a data race in the schema service

fix: make buildtin inclusion immutable

---

backend/ingress/handler_test.go
backend/ingress/request_test.go
common/schema/schema_test.go
common/schema/validate.go
common/schema/validate_test.go

fixes https://github.com/block/ftl/issues/5313

fix: validate schema for refs with invalid visibility

---

internal/raft/cluster.go
internal/raft/notificationstatemachine.go

Previously, event index could have been updated before statemachine was. Now, we send a notification after an update to make sure no notifications are missed

fix: race condition on notifying updates from raft

---

internal/raft/cluster.go

Avoids missing an update if it happens between subscription and getting a previous value

fix: subscripbe to notifications before getting previous value

---

bin/hermit.hcl
internal/testdata/ziprelative/test.txt
internal/zip_relative.go
internal/zip_relative_test.go

The alecthomas/errors package attempts to reduce the size of paths by stripping the main package, but this requires that all Go binaries are built with "-trimpath". This has been added to the Hermit environment as a default compile flag.
Also added a test for ZipRelativeToCaller.
Before:
> /Users/aat/dev/ftl/go-runtime/ftl/ftltest/ftltest.go:379: /Users/aat/dev/ftl/go-runtime/ftl/ftltest/ftltest.go:434: test harness failed to call verb mysql.insert: /Users/aat/dev/ftl/internal/deploymentcontext/module_context.go:360: /Users/aat/dev/ftl/go-runtime/ftl/ftltest/ftltest.go:450: /Users/aat/dev/ftl/go-runtime/server/server.go:153: /Users/aat/dev/ftl/common/reflection/verb.go:87: /Users/aat/dev/ftl/go-runtime/server/server.go:187: /Users/aat/dev/ftl/go-runtime/server/server.go:232: …

chore: ensure leading prefix of stack trace paths is stripped

---

.github/workflows/ci.yml

Reverts block/ftl#5368
Unfortunately `blockossreleases` has a very limited pull rate limit, so this breaks things more than fixes

revert: "chore(ci): log in to Docker Hub for integration tests"

---

backend/admin/service.go
backend/protos/xyz/block/ftl/admin/v1/admin.pb.go
backend/protos/xyz/block/ftl/admin/v1/admin.proto
backend/protos/xyz/block/ftl/v1/schemaservice.pb.go
backend/protos/xyz/block/ftl/v1/schemaservice.proto
backend/schemaservice/schemaservice.go
common/schema/schema.go
frontend/console/src/protos/xyz/block/ftl/admin/v1/admin_pb.ts
frontend/console/src/protos/xyz/block/ftl/v1/schemaservice_pb.ts
ftl-project.toml
internal/app/app.go
internal/app/cmd_realm.go
internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/git/git.go
internal/projectconfig/projectconfig.go
internal/projectconfig/projectconfig_test.go
internal/projectconfig/testdata/ftl-project.toml
internal/realm/realm.go
internal/schema/schemaeventsource/schemaeventsource.go

Also propagates the realm to the schema state.
However, the content of external realms are yet not stored in state. The new command
```
ftl realm add --git-repo=<> --git-branch=<>
```
is hidden until it is working e2e
When it is working e2e, will add an integration test.

feat: add support for external realms to ftl-project.toml

---

internal/configuration/manager/cache.go

Previously, this would set the ref map to nil, which would explode later

fix: log an error if secret s provider returns nil values

---

internal/log/json.go

Some JVM project was resulting in:
> Invalid log level: WARNING does not belong to Level values
Ideally this would be translated correctly by the language runtimes, but we're already doing this for "fine" et al so...

fix: hack support for "warning"

---

backend/provisioner/registry.go
backend/runner/runner.go
common/plugin/spawn.go
internal/buildengine/languageplugin/plugin_client.go
internal/log/json.go

At the moment we don't have a proper non-dev mode translation layer between the JVM and go log JSON formats, so the JVM logs are getting all of their exception information being stripped from them. This can hide critical errors, as only the outermost exception is present in the logs.
For now the simplest solution is to just pass them through so they get written directly to the kube pod logs. There is already transaction in place in dev mode so this only affects prod.

fix: pass log messages through directly in the runner

---

cmd/ftl/app.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_serve.go
internal/schema/schemaeventsource/schemaeventsource.go
internal/terminal/interactive.go
internal/terminal/predictors.go

Previously if this was set to something other than localhost you could end up in a situation where some dev mode services connect to another server.

fix: ignore FTL_ENDPOINT for dev mode

---

cmd/ftl/cmd_schema_diff.go
cmd/ftl/integration_test.go
cmd/ftl/main.go
internal/integration/harness.go

Previously could only diff against the running cluster.

feat: update `ftl schema diff` to support diffing to/from endpoint or file

---

internal/buildengine/deploy.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go

closes #5433
- Build engine collects module schemas when `Build()` is called.
- Build engine hands deploy coordinator each module schema, rather than a path to the schema

fix: build engine collects schemas when not deploying

---

.github/workflows/release.yml

It currently takes 10m+, so hopefully this will reduce that somewhat.

chore(ci): do release builds on the fast runners

---

frontend/console/src/features/graph/GraphPane.tsx

fix: add some defense against graph calculation errors

---

.github/workflows/writecache.yml
Justfile

Previously we were doing a `rebuild-all` in order to populate the Go module cache and the Maven m2 cache. Instead, we now just download the dependencies directly without building.

chore(ci): speed up Go and Maven dependency cache writes

---

frontend/console/src/shared/providers/app-providers.tsx

Prevent default action for CMD+S in console web app

fix: prevent CMD+S from breaking app

---

.github/workflows/dco-cla.yaml

This adds a check to all PRs and commits to make sure that all commits by external parties contain a [Developer Certificate of Origin](https://wiki.linuxfoundation.org/dco).

feat: Add DCO check to all PRs and commits

---

.github/workflows/writecache.yml
backend/runner/query/service.go
backend/runner/query/service_test.go
internal/buildengine/engine_integration_test.go

eg. from the test 
```sql
SELECT id FROM test_table WHERE name IN (/*SLICE:names*/?) AND value = ? AND id IN (/*SLICE:ids*/?)
```
with inputs `[["test1", "test3"], 100, [1]]`, would expand to `["test1", "test3", 100, 100]`.

fix: failure to expand sqlc.slice() if interspersed with scalar parameters

---

backend/runner/runner.go
examples/java/mysql/src/test/java/ftl/mysql/MySQLIntegrationTest.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java

This was needed when we mained DB connections, however it is no longer required.

fix: don't let runner connection block startup

---

backend/controller/sql/database_kube_test.go
backend/provisioner/scaling/kube_scaling_integration_test.go
backend/runner/runner.go
charts/ftl-k3d/values.yaml
charts/ftl/templates/runner.yaml
charts/ftl/templates/sidecar.yaml
internal/rpc/server.go

When running in a single namespace use abstract sockets for the runner.
We can't provision per-namespace sidecar config yet, so this is only for single namespace.

feat: use abstract sockets for the runner

---

Justfile
backend/schemaservice/schemaservice.go
charts/ftl/templates/_helpers.tpl
charts/ftl/templates/cron-deployment.yaml
charts/ftl/templates/http-ingress-deployment.yaml
charts/ftl/templates/runner.yaml
charts/ftl/templates/schema-deployment.yaml
charts/ftl/templates/schema-mirror-deployment.yaml
charts/ftl/templates/schema-mirror-role.yaml
charts/ftl/templates/schema-mirror-services.yaml
charts/ftl/values.yaml
cmd/ftl-schema/main.go

- Added schema-mirror
- Runners, ingress and cron use the mirror instead of the actual schema service if schema mirror is enabled
- Schema service pushes to the mirror if it is enabled

feat: schema mirror chart updates

---

backend/schemamirror/mirror_service.go
backend/schemamirror/schema_service.go
backend/schemamirror/service.go
backend/schemamirror/service_integration_test.go
cmd/ftl-schema-mirror/main.go

Split up the mirror into two service with different availability:
- Mirror service is always available (so that schema service can push to it)
- Schema service is only available when receiving schema pushes

fix: mirror's schema service readiness depends on whether it is receiving pushes

---

.golangci.yml
lefthook.yml

It's essentially a global variable, except worse. Don't use it.

chore: forbid os.Getenv

---

.github/actions/build-cache/action.yml
.github/workflows/writecache.yml

This should be slightly faster, as only packages used will be unpacked.

fix: cache downloaded Hermit artefacts, not extracted

---

backend/cron/service.go
backend/cron/service_test.go
backend/ingress/handler_test.go
backend/provisioner/service.go
backend/runner/runner.go
cmd/ftl-admin/main.go
cmd/ftl-console/main.go
cmd/ftl-cron/main.go
cmd/ftl-http-ingress/main.go
cmd/ftl-provisioner-cloudformation/provisioner.go
cmd/ftl-provisioner-sandbox/provisioner.go
cmd/ftl-provisioner/main.go
cmd/ftl-schema/main.go
cmd/ftl/app.go
cmd/ftl/cmd_mcp.go
cmd/ftl/cmd_serve.go
internal/timelineclient/client.go

Set `FTL_TIMELINE_ENDPOINT=discard://` to create a no-op timeline client.
Also DRY timeline config so we get consistent help/envars/etc.

refactor: allow timeline client to be a null sink

---

common/schema/change/change.go
common/schema/change/change_test.go
common/schema/data.go
common/schema/field.go
common/schema/parser.go

This is intended for use with external API boundaries, including values that are being persisted to storage.
Currently this disallows:
- Removing (or renaming) fields in data structures.
- Changing a type.
- Adding or removing enum values - adding is disallowed because a consumer that doesn't expect the new value will fail. Not ideal.

feat: breaking change detection

---

.cursor/rules/go.mdc
.rules

This seems to be the more generic location for rules.

chore: symlink .cursor/rules -> .rules

---

internal/config/file.go

We don't really need to as writes are atomic, and we're seeing lock timeouts locally for some reason.

fix: don't flock in file config/secrets provider

---

backend/provisioner/oci_image_provisioner.go
backend/provisioner/registry.go
backend/provisioner/service.go
cmd/ftl-provisioner/main.go
cmd/ftl/app.go
cmd/ftl/cmd_image.go
cmd/ftl/cmd_image_build.go
cmd/ftl/cmd_image_inspect.go
cmd/ftl/cmd_serve.go
common/protos/xyz/block/ftl/schema/v1/schema.pb.go
common/protos/xyz/block/ftl/schema/v1/schema.proto
common/schema/go2proto.to.go
common/schema/metadataimage.go
common/schema/parser.go
common/schema/validate.go
frontend/console/src/protos/xyz/block/ftl/schema/v1/schema_pb.ts
internal/oci/image_service.go

- Store image metadata in the schema
- Append schema digest into a label so it can be inspected without pulling the full image
- Add ability to dump image to disk

feat: image build improvements

---

cmd/ftl/cmd_call.go
cmd/ftl/cmd_replay.go

This fixes warnings when calling an endpoint without schema-service running

fix: remove ftl call suggestions when the call fails.

---

backend/admin/service.go
backend/console/console.go
backend/cron/service.go
backend/ingress/service.go
backend/provisioner/service.go
backend/runner/proxy/proxy.go
backend/runner/pubsub/consumer.go
backend/runner/pubsub/publisher.go
backend/runner/pubsub/pubsub.go
backend/runner/runner.go
backend/schemaservice/schemaservice.go
backend/timeline/integration_test.go
cmd/ftl/app.go
cmd/ftl/cmd_replay.go
internal/routing/verb_routing.go
internal/timelineclient/client.go
internal/timelineclient/log_sink.go

Non functional change to prepare for better testing of timeline through fakes

chore: extract Publisher from timeline.Client for better testing
