console/src/routes/+layout.svelte
console/src/routes/+page.svelte
console/src/routes/logs/+page.svelte
console/src/routes/modules/[slug]/+page.svelte

Better light mode UI

---

console/src/features/graph/GraphPage.tsx
console/src/features/graph/GroupNode.tsx
console/src/features/graph/VerbNode.tsx
console/src/features/graph/create-layout.ts

- Module nodes should be draggable now

Improve graph nodes

---

go.mod
observability/client.go
observability/logger.go

Reroute OTELs logging through FTLs logger

---

cmd/ftl/cmd_go.go
cmd/ftl/main.go
controlplane/controlplane.go
go-runtime/compile/compile.go
internal/slices/slices.go

This command compiles and deploys a Go FTL module.
🐚 ~/dev/ftl $ ftl go deploy -S $PWD -d ./examples/time
info: Compiling /Users/alec/dev/ftl/examples/time
info: Gathering schema
info: Generating stubs
info: Tidying up
info: Compiling
info: Created deployment 01H2YRJ453Z9CXJJAT9HZ33X7K
🐚 ~/dev/ftl $ ftl go deploy -S $PWD -d ./examples/echo -m ./examples/time
info: Compiling /Users/alec/dev/ftl/examples/echo
info: Gathering schema
info: Generating stubs
info: Tidying up
info: Compiling
info: Created deployment 01H2YRSVF8K2M2YKWCXXMGASBS
🐚 ~/dev/ftl $ ftl call echo.echo '{"name": "Alec"}'
{"message":"Hello, Alec!!! It is 2023-06-15 15:36:09 +1000 AEST!"}
🐚 ~/dev/ftl $ ftl call time.time
{"time":1686807372,"date":0}

feat: "ftl go deploy" command working

---

controlplane/controlplane.go
controlplane/internal/dal/api.go
controlplane/internal/dal/dal_test.go
controlplane/internal/dal/local.go
controlplane/internal/dal/postgres.go
controlplane/internal/sql/querier.go
controlplane/internal/sql/queries.sql
controlplane/internal/sql/queries.sql.go

Also extended the DAL tests to exercise everything.

feat: local DAL is feature complete

---

controlplane/internal/dal/dal_test.go
controlplane/internal/dal/local.go

This turned out to be much simpler than I feared.

fix: re-enable local DAL now that it supports reservations

---

go.mod
reflex.conf
scripts/ftl-dev

This leverages Reflex, with a little bit of smarts to only reload when direct dependencies are changed.

chore: script to do hot reloading during devel

---

controlplane/controlplane.go
observability/interceptor.go

Fix source and dest fields on metrics interceptor

---

cmd/ftl/cmd_ps.go
cmd/ftl/main.go

feat: add `ftl ps` command

---

controller/controller.go
controller/observability.go

@alecthomas we should chat about this one. Since i need the `RunnerKey` and the `RequestKey` to store an error, I don't have a great way to handle more errors in the controller. Maybe we can pair a bit to see what will work best for us.

Add more error handling to ftl calls

---

kotlin-runtime/ftl-plugin/src/main/kotlin/xyz/block/ftl/gradle/FTLPlugin.kt

Delete generated folder from ftl-plugin on regen

---

console/client/src/main.tsx
console/client/src/providers/modules-provider.tsx

fix(console): when new module created|deleted updates/refreshes view

---

kotlin-runtime/ftl-plugin/src/main/kotlin/xyz/block/ftl/gradle/FTLClient.kt

Improved error message when plugin can't connect to FTL

---

console/.gitignore
console/client/.postcssrc
console/client/index.html
console/client/package-lock.json
console/client/package.json
console/client/postcss.config.js
console/local.go

drops vite for parcel due to the following
resolves  #221 221

fix: vite invalid-command bug by swapping to parcel

---

backend/common/log/configure.go
backend/common/log/logger.go
backend/common/log/plain.go
backend/common/plugin/serve.go
backend/common/plugin/spawn.go
backend/controller/internal/sql/queries.sql
backend/controller/internal/sql/queries.sql.go
backend/runner/deployment_logs.go
backend/runner/runner.go

@alecthomas putting this WIP stuff up to discuss some options on the logger

Getting deployment logs setup via runner

---

.github/workflows/ci.yml

fix: don't build docker images on branches

---

backend/common/exec/exec.go
backend/common/observability/client.go
backend/common/plugin/spawn.go
backend/controller/controller.go
backend/controller/databasetesting/migrate.go
backend/controller/deployment_logs.go
backend/controller/internal/dal/dal.go
backend/controller/internal/dal/dal_test.go
backend/integration/integration_test.go
backend/runner/deployment_logs.go
backend/runner/runner.go
console/local.go
go-runtime/compile/compile.go

Record controller logs in the events table

---

.github/workflows/ci.yml
console/client/src/features/log/LogsPage.tsx
console/client/src/features/modules/ModuleTimeline.tsx
console/client/src/features/requests/RequestPage.tsx
console/client/src/features/verbs/VerbCalls.tsx
console/client/src/utils/date.utils.ts

Also add "tsc" to CI so (some of) these get picked up.

fix: a bunch of TS type issues I introduced

---

backend/controller/console.go
backend/controller/controller.go
backend/controller/deployment_logs.go
backend/controller/internal/dal/dal.go
backend/controller/internal/dal/dal_test.go
console/client/.eslintrc.cjs
console/client/src/features/log/LogsPage.tsx
console/client/src/utils/date.utils.ts

- Style things up a bit to make it easier to read
https://github.com/TBD54566975/ftl/assets/51647/ba2a3ae7-f07a-4d47-ad02-9bfeb699c063

Fix log streaming to console

---

console/client/src/App.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelineEventDetailDeployment.tsx
console/client/src/features/timeline/TimelineEventDetailLog.tsx
console/client/src/layout/IDELayout.tsx
console/client/src/layout/SidePanel.tsx
console/client/src/main.tsx
console/client/src/providers/AppProviders.tsx
console/client/src/providers/side-panel-provider.tsx
console/client/src/utils/style.utils.ts

Fix side panel overflow. Improve transitions

---

console/client/src/App.tsx
console/client/src/features/modules/ModulePage.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelineFilterBar.tsx
console/client/src/layout/IDELayout.tsx
console/client/src/layout/SidePanel.tsx

Add filter bar to timeline

---

console/client/package-lock.json
console/client/package.json
console/client/src/features/verbs/VerbForm.tsx
console/client/tailwind.config.js

Add tailwind forms to improve styling

---

examples/online-boutique/services/checkout/checkout.go
examples/online-boutique/services/currency/currency.go

This is the cool one that brings it all together!
```
🐚 ~/dev/ftl $ ftl call cart.addItem '{userID: "Larry", item: {"productID": "OLJCESPC7Z", "quantity": 1}}'
{}
🐚 ~/dev/ftl $ ftl call checkout.placeOrder '{userID: "Larry", userCurrency: "AUD", address: {streetAddress: "1600 Amphitheatre Parkway", city: "Mountain View", state: "CA", country: "USA", zipCode: 94043}, email: "larry@google.com", creditCard: {number: "423412341234", cvv: 123, expirationYear: 2024, expirationMonth: 6}}'
{
"ID": "7b24ab66-8570-4fda-b825-12ca75018b2a",
"ShippingTrackingID": "KK-44489-228384098",
"ShippingCost": {
"CurrencyCode": "AUD",
"Units": 11,
"Nanos": 387449163
},
"ShippingAddress": {
"StreetAddress": "1600 Amphitheatre Parkway",
"City": "Mountain View",
"State": "CA",
"Country": "USA",
"ZipCode": 94043
}, …
```

feat: implement boutique checkout

---

console/client/src/features/verbs/VerbForm.tsx
console/client/src/layout/IDELayout.tsx

Add errors to verb form for when requests fail

---

backend/controller/internal/dal/events.go
backend/controller/internal/sql/queries.sql
backend/controller/internal/sql/queries.sql.go
backend/controller/observability.go
console/client/src/features/requests/RequestGraph.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx

Fix ordering of calls for the request graph

---

console/client/src/components/CodeBlock.tsx
console/client/src/components/DarkModeSwitch.tsx
console/client/src/features/requests/RequestGraph.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx
console/client/src/features/timeline/details/TimelineLogDetails.tsx
console/client/src/features/verbs/VerbForm.tsx
console/client/src/features/verbs/VerbPage.tsx
console/client/src/features/verbs/VerbTab.tsx
console/client/src/layout/SidePanel.tsx
console/client/src/providers/AppProviders.tsx
console/client/src/providers/dark-mode-provider.tsx
console/client/src/utils/style.utils.ts

Fix syntax highlighting styles when switching dark mode

---

Procfile.nowatch
backend/controller/controller.go
backend/runner/runner.go

By running each single round of reconciliation in parallel. This will be a problem if there are multiple controllers, so we will need to fix #150

fix: improve reconciliation speed

---

console/client/.eslintrc.cjs
console/client/scripts/dev.cjs
console/client/src/components/dep-check.spec.ts
console/client/src/features/modules/ModuleDetails.tsx
console/client/src/features/requests/RequestGraph.tsx
console/client/src/features/requests/RequestsModal.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/verbs/VerbCalls.tsx
console/client/src/layout/IDELayout.tsx

Clean up linting rules

---

console/client/src/features/requests/RequestGraph.tsx

Add better tooltips on request graph

---

console/client/src/features/timeline/Timeline.tsx

Fixes #325 
This fixes weird scrolling/jumping issues when new items are added

Use entry IDs for the key in timeline

---

console/client/src/features/requests/RequestGraph.tsx
console/client/src/features/timeline/TimelineCall.tsx
console/client/src/features/verbs/verb.utils.ts

Use better verbRef string format

---

console/client/src/components/CodeBlock.tsx
console/client/src/features/verbs/VerbForm.tsx

Limit height of syntax highlighted code blocks

---

deployment/helm/Chart.yaml
deployment/helm/README.md
deployment/helm/schema
deployment/helm/templates/db-migrate.yml
deployment/helm/templates/ftl-controller.yml
deployment/helm/templates/ftl-runner.yml
deployment/helm/templates/pg-cluster.yaml
deployment/helm/values.yaml

This is a duplicate of the kustomize deployment, and should be equivalent.
This will be a first step towards enabling Helm adoption for deployment to non local k8s

Helm deployment

---

scripts/integration-tests

See #352 for underlying bug, but we've worked around it for now.

fix: integration tests

---

console/client/index.html
console/client/src/App.tsx
console/client/src/components/PageHeader.tsx
console/client/src/features/graph/GraphPage.tsx
console/client/src/features/modules/ModulesPage.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelinePage.tsx
console/client/src/features/timeline/filters/TimelineFilterPanel.tsx
console/client/src/features/timeline/filters/TimelineTimeControls.tsx
console/client/src/layout/Layout.tsx
console/client/src/layout/Navigation.tsx
console/client/src/utils/date.utils.ts
console/client/src/utils/style.utils.ts
console/client/tailwind.config.js

feat: Style timeline page and add filter panel

---

backend/controller/console.go
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/filters/TimelineFilterPanel.tsx
console/client/src/features/timeline/filters/TimelineTimeControls.tsx
console/client/src/services/console.service.ts

feat: Panel filters are functional now

---

console/client/src/features/timeline/TimelinePage.tsx
console/client/src/layout/Layout.tsx

feat: make filter panel sticky to the top of the page

---

console/release.go

Because the routes are handled by JS, any sub-paths should be served from the root index.html. eg. /events -> /index.html, and so on.

fix: requests to /events were 404ing

---

console/client/src/features/logs/log.utils.tsx
console/client/src/features/timeline/filters/TimelineFilterPanel.tsx

feat: Style log level filter to be like a meter

---

console/client/src/components/AttributeBadge.tsx
console/client/src/components/Card.tsx
console/client/src/components/CloseButton.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx
console/client/src/features/timeline/details/TimelineDeploymentDetails.tsx
console/client/src/features/timeline/details/TimelineLogDetails.tsx
console/client/src/features/timeline/details/TimelineTimestamp.tsx
console/client/src/features/timeline/filters/TimelineFilterPanel.tsx
console/client/src/layout/SidePanel.tsx

feat: clean up layout and side bar components

---

console/client/src/components/PageHeader.tsx
console/client/src/features/deployments/DeploymentPage.tsx

feat: add simple breadcrumbs implementation

---

console/client/src/features/modules/ModulePage.tsx

feat: add call list to module page

---

backend/controller/internal/dal/events.go
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelinePage.tsx
console/client/src/features/timeline/filters/TimelineTimeControls.tsx
console/client/src/features/verbs/VerbPage.tsx
console/client/src/services/console.service.ts

Fixes #308
Demo video:
https://github.com/TBD54566975/ftl/assets/51647/33c7f398-3b4c-4104-86f6-10ebd6ff9be5

feat: shareable event urls

---

console/client/src/features/graph/create-layout.ts

feat: minor graph layout adjustments

---

console/client/src/features/calls/CallList.tsx
console/client/src/features/modules/ModulePage.tsx
console/client/src/features/timeline/TimelinePage.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx
console/client/src/features/verbs/VerbPage.tsx

feat: CallList component and update usage

---

console/client/.eslintrc.cjs
console/client/index.html
console/client/src/App.tsx
console/client/src/components/index.ts
console/client/src/features/deployments/DeploymentPage.tsx
console/client/src/features/deployments/DeploymentsPage.tsx
console/client/src/features/graph/GraphPage.tsx
console/client/src/features/modules/ModulePage.tsx
console/client/src/features/modules/ModulesPage.tsx
console/client/src/features/timeline/TimelinePage.tsx
console/client/src/features/verbs/VerbPage.tsx
console/client/src/layout/Layout.tsx
console/client/src/layout/Notification.tsx
console/client/src/layout/Page.tsx
console/client/src/layout/SidePanel.tsx
console/client/src/layout/index.ts
console/client/src/main.tsx

- Refactors layout to fix scroll bugs
- Creates a Page component and subcomponents to resolve issues and create consistent way of creating new pages without introducing scroll related styling bugs
- @wesbillman notification style I dropped under the transition to prevent it from making the screen black as the notification component as a whole covers the whole screen

feat(client): refactors layout to resolve scroll bugs

---

console/client/src/features/modules/ModulePage.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx
console/client/src/features/timeline/filters/TimelineTimeControls.tsx
console/client/src/features/verbs/VerbCalls.tsx
console/client/src/features/verbs/VerbPage.tsx
console/client/src/providers/modules-provider.tsx
console/client/src/providers/side-panel-provider.tsx
console/client/src/services/console.service.ts

Fixes #436 
Also enforces use of `AbortController` for connect requests to avoid hangs

fix: fix time conrols on timeline when eventID is set

---

console/client/src/components/Card.tsx
console/client/src/features/timeline/Timeline.tsx
console/client/src/features/timeline/TimelinePage.tsx
console/client/src/features/timeline/details/TimelineCallDetails.tsx
console/client/src/features/timeline/details/TimelineDeploymentCreatedDetails.tsx
console/client/src/features/timeline/details/TimelineDeploymentUpdatedDetails.tsx
console/client/src/features/timeline/details/TimelineLogDetails.tsx

Fixes #443 
Also add some deployment cards to event detail sidebar

feat: add deployment name to the timeline

---

console/client/src/components/Card.tsx
console/client/src/layout/SidePanel.tsx

feat: add hover to cards and fix sidepanel bottom margin

---

bin/hermit.hcl
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/client/grpc.kt

Also close TODO for supporting https.

fix(kotlin-runtime): correctly determine port for FTL endpoint

---

console/client/src/features/calls/CallList.tsx
console/client/src/features/verbs/VerbForm.tsx
console/client/src/features/verbs/VerbPage.tsx
console/client/src/layout/SidePanel.tsx

feat: add verb form to verb page

---

console/client/src/features/timeline/TimelineIcon.tsx

fix: call icon was not red on error

---

cmd/ftl-go/main.go

Related to #315 
@alecthomas is this sort of what you had in mind here?

feat: add url to console deployment page after deployment

---

console/client/src/features/timeline/filters/TimelineFilterPanel.tsx

Fixes #435 
https://github.com/TBD54566975/ftl/assets/51647/c79078ec-422f-44e5-a001-23056070deaf

feat: Adds new deployments to filters as they appear

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/main/main.kt
pom.xml

chore: integrate Kotlin logging

---

console/client/src/App.tsx
console/client/src/layout/NotFoundPage.tsx

feat: add 404 page

---

cmd/ftl/cmd_init.go
cmd/ftl/cmd_schema.go
internal/scaffolder.go

```
🐚 ~/dev/ftl $ ftl schema generate ./foo ./bar
info: Generated 8 modules in ./bar
🐚 ~/dev/ftl $ find foo
foo/{{ .Name | lower }}.dart
🐚 ~/dev/ftl $ find bar
bar/recommendation.dart
bar/shipping.dart
bar/payment.dart
bar/currency.dart
bar/checkout.dart
bar/ad.dart
bar/productcatalog.dart
bar/cart.dart
```

feat: add `ftl schema generate <in> <out>`

---

console/client/src/components/Chip.tsx
console/client/src/features/deployments/DeploymentCard.tsx
console/client/src/layout/Layout.tsx
console/client/src/layout/SidePanel.tsx
console/client/src/layout/navigation/MobileNavigation.tsx
console/client/src/layout/navigation/Navigation.tsx
console/client/src/layout/navigation/navigation-items.ts

The console was very broken when viewing on mobile. This improves that.

feat: add mobile navigation and layouts

---

console/client/src/hooks/use-local-storage.ts
console/client/src/layout/Layout.tsx
console/client/src/layout/navigation/Navigation.tsx
console/client/src/providers/dark-mode-provider.tsx

feat: make navigation bar collapsible

---

backend/controller/internal/dal/events.go
frontend/src/services/console.service.ts

fix: event ordering when more than 1000 events logged

---

cmd/ftl/cmd_serve.go

Adds flag to `ftl serve` to specify `--db-port=`
```
ftl serve
info: Creating docker container 'ftl-db' for postgres db
info: 0068928db25fe6c1b54b8c297c03d95b63f7e2bb14dae263551c78b22b9598ca
info: Waiting for ftl-db to be healthy
info: Postgres DSN: postgres://postgres:secret@localhost:/ftl-db?sslmode=disable
```
```
ftl serve --db-port=5555
info: Creating docker container 'ftl-db' for postgres db
info: 09eb81255880cdaccb090b0dffac35a0bceadd34397c757ae5f9df7132ad5b36
info: Waiting for ftl-db to be healthy
info: Postgres DSN: postgres://postgres:secret@localhost:5555/ftl-db?sslmode=disable
```
```
ftl serve --db-port=5432
info: Creating docker container 'ftl-db' for postgres db
ftl: error: port 5432 is already in use
```

feat: add flag to specify db port for ftl serve

---

backend/schema/schema.go
backend/schema/validate.go

This will initially be used by templates to generate import statements.

feat: add `.Imports()` method to `schema.Module`

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt

fix: do not add references directly to the module schema

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

Empty data classes can be defined in Kotlin as `typealias <ClassName> = Unit`

feat: allow empty data classes in kotlin schema

---

.github/workflows/release.yml
kotlin-runtime/ftl-generator/pom.xml
kotlin-runtime/ftl-runtime/pom.xml
pom.xml

feat: publish FTL JARs to Maven Central

---

backend/common/moduleconfig/config.go
cmd/ftl/cmd_deploy.go
go-runtime/scaffolding/{{ .Name | camel | lower }}/ftl.toml
kotlin-runtime/scaffolding/ftl-module-{{ .Name | lower }}/ftl.toml

Fixes #598 
https://github.com/TBD54566975/ftl/assets/51647/699d72d4-cb4e-4c81-bf97-33e2728f205a

feat: build modules when deploying

---

go.mod
go.sum

See https://github.com/TBD54566975/scaffolder/pull/3

fix: bump scaffolder to fix a couple of bugs

---

.github/workflows/cc.yml
cmd/ftl/cmd_init.go

See https://github.com/TBD54566975/ftl/pull/607 for an example :\

fix: early-exit gptcc because it's a bit too enthusiastic

---

examples/kotlin/pom.xml
examples/online-boutique/services/ad-kotlin/pom.xml
kotlin-runtime/scaffolding/pom.xml
pom.xml

>  java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled

fix: target Java 1.8 to fix weird reflection issues

---

backend/common/moduleconfig/config.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/cmd_dev.go
cmd/ftl/main.go
go.mod
go.sum

https://github.com/TBD54566975/ftl/assets/51647/456fa1f1-543f-4d71-9b1a-854343496da1

feat: add ftl dev command to watch and deploy

---

frontend/src/layout/Layout.tsx
frontend/src/layout/navigation/Navigation.tsx

Also fixes duplicate StreamEvents being active at the same time.

fix: remove duplicate Outlets in layout

---

cmd/ftl/cmd_serve.go

Also eradicated some reliance on external shell tools.

fix: make `ftl serve`'s DB compatible with docker compose

---

frontend/src/features/deployments/DeploymentPage.tsx

Fixes #596 
https://github.com/TBD54566975/ftl/assets/51647/e823d130-d714-4e90-9a5f-43222eefc952

feat: redirect to latest deployment if current one is not found

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/logging/Logging.kt

fix: explicitly suppress GRPC debug logs

---

kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

chore: add source references in schema parser

---

go-runtime/scaffolding/bin/hermit.hcl
kotlin-runtime/scaffolding/bin/hermit.hcl

This is akin to a brew tap and is automatically updated on every FTL release. The `@latest` channel will automatically download the newest release every hour, if it has changed.

fix: runtime scaffolding now includes our ftl Hermit "tap"

---

backend/schema/schema.go
backend/schema/schema_test.go

fix: sort imports before using in templates

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_init.go

Previously this was only occurring when running `ftl build`.
Fixes #757

fix: set properties in the pom file when running `ftl init`

---

cmd/ftl/cmd_dev.go
cmd/ftl/cmd_schema_generate.go

```bash
info: Generated 7 modules in /Users/wesbillman/dev/ftl-examples/frontend/mobile/lib/api
info: Generated 7 modules in /Users/wesbillman/dev/ftl-examples/frontend/mobile/lib/api
info: Stream disconnected, attempting to reconnect...
info: Generated 1 modules in /Users/wesbillman/dev/ftl-examples/frontend/mobile/lib/api
info: Generated 2 modules in /Users/wesbillman/dev/ftl-examples/frontend/mobile/lib/api
```

fix: handle reconnect for schema generate

---

examples/kotlin/ftl-module-echo/src/main/kotlin/ftl/echo/Echo.kt
kotlin-runtime/ftl-generator/src/main/kotlin/xyz/block/ftl/generator/ModuleGenerator.kt
kotlin-runtime/ftl-generator/src/test/kotlin/xyz/block/ftl/generator/ModuleGeneratorTest.kt
kotlin-runtime/ftl-runtime/pom.xml
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt
kotlin-runtime/ftl-runtime/src/test/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRuleTest.kt

fix: update kotlin codegen for empty data structures

---

backend/schema/validate.go
cmd/ftl/cmd_init.go

feat: validate module names on init

---

backend/controller/console.go
backend/controller/ingress/ingress.go
backend/schema/array.go
backend/schema/bool.go
backend/schema/bytes.go
backend/schema/data.go
backend/schema/database.go
backend/schema/dataref.go
backend/schema/field.go
backend/schema/float.go
backend/schema/int.go
backend/schema/map.go
backend/schema/metadatacalls.go
backend/schema/metadatadatabases.go
backend/schema/metadataingress.go
backend/schema/module.go
backend/schema/optional.go
backend/schema/parser.go
backend/schema/protobuf_enc.go
backend/schema/refs.go
backend/schema/schema.go
backend/schema/schema_test.go
backend/schema/string.go
backend/schema/time.go
backend/schema/unit.go
backend/schema/validate.go
backend/schema/verb.go
internal/errors/errors.go

Previously it was very basic, simply trying to resolve types from top-level module declarations. But with the introduction of generics, we need to be able to resolve types from type parameters. This PR introduces a generalised, scoped type-resolution system.
I also fixed all the sum-type type switches I could find.

feat: improve type analysis

---

cmd/ftl/cmd_dev.go

Fixes #792 
Example of rebuilding `shipping` and `checkout` because they depend on `cart` schema
```bash
warn: Detected change in file /Users/wesbillman/dev/ftl/examples/online-boutique/services/cart/cart.go
info: Creating deployment for module cart
info: Building Go module 'cart'
info: Generating external modules
info: Tidying go.mod
info: Extracting schema
info: Generating main module
info: Compiling
info: Uploading 0/1 files
info: Created deployment cart-548ccb3647
warn: Rebuilding "shipping" because of "cart" schema changes
warn: Rebuilding "checkout" because of "cart" schema changes
info: Creating deployment for module checkout
info: Building Go module 'checkout'
info: Generating external modules
info: Tidying go.mod
info: Extracting schema
info: Generating main module
info: …
```

feat: only rebuild dependent modules on schema changes

---

backend/controller/controller.go
backend/controller/scheduledtask/scheduledtask.go
backend/controller/scheduledtask/scheduledtask_test.go
go.mod
go.sum

So that the tests don't take 6 seconds, which is annoying.

fix: test scheduledtask with a fake clock

---

.vscode/tasks.json
backend/common/log/logger.go
backend/controller/controller.go
backend/runner/runner.go
go-runtime/sdk/logging.go

@wesbillman can you let product eng know that a logger is now available please

feat: expose FTL logger through the Go SDK

---

backend/controller/controller.go

Clean up building of the HTTPResponse and also fixes an issue with the headers being set correct.
```go
return builtin.HttpResponse[GetResponse]{
Status:  200,
Headers: map[string][]string{"Get": {"Header from FTL"}, "Content-Type": {"application/json"}},
Body:    GetResponse{Message: fmt.Sprintf("UserID, %s : PostID %s", req.Body.UserID, req.Body.PostID)},
}, nil
```
```bash
curl -i http://localhost:8892/ingress/http/users/123/posts/456\?wes\=test
HTTP/1.1 200 OK
Content-Type: application/json
Get: Header from FTL
Date: Thu, 25 Jan 2024 16:37:26 GMT
Content-Length: 38
{"message":"UserID, 123 : PostID 456"}%    
```

fix: clean up HTTPResponse building

---

backend/controller/controller.go
backend/controller/ingress/ingress.go
backend/controller/ingress/ingress_test.go
backend/controller/ingress/request.go
backend/controller/ingress/response.go
integration/integration_test.go
integration/testdata/go/httpingress/echo.go
integration/testdata/kotlin/httpingress/Echo.kt
kotlin-runtime/ftl-runtime/src/main/kotlin/xyz/block/ftl/schemaextractor/ExtractSchemaRule.kt

feat: add support for string and Unit request and response types

---

go-runtime/encoding/encoding.go

@alecthomas do you still need these?

chore: remove extra printfs

---

backend/controller/console.go

The console was erroring due to this issue.
All good with this fix added.

fix: use correct dataref for json schema

---

go-runtime/compile/build-template/_ftl.tmpl/go/main/go.mod.tmpl

fix: add "v" to ftl version

---

FTL.code-workspace
examples/go/echo/go.mod

fix: workspace file had old boutique example

---

frontend/src/components/CodeBlock.tsx
frontend/src/features/deployments/DeploymentPage.tsx
frontend/src/providers/side-panel-provider.tsx
frontend/src/services/console.service.ts

Fixes:
- Deployment page was not showing side panel when timeline entries were tapped
- Deployment timeline was reloading excessively
- Console service was spamming unnecessary error messages
- CodeBlock was not clearing before highlighting

fix: various console fixes

---

buildengine/testdata/modules/echokotlin/go.mod

Not 100% sure what we should do with this dummy `go.mod` file, but the other test modules have it checked in so I did the same. Without this we get a new file changed each time we run `go test ./...`

chore: this file gets created each time we test

---

go-runtime/compile/schema.go

fix: lowercase request and response fields should produce an error

---

CONTRIBUTING.md

Small things that confused me when starting

docs: Updated "ftl dev" command

---

pom.xml

fix: disable Kotlin incremental compilation because it sucks

---

buildengine/deploy.go
buildengine/engine.go

fix: terminate deleted modules

---

buildengine/engine.go

Fixes #1032 
Schema change on the `time` module:
```sh
ftl dev examples/go --recreate
info: time's schema changed; redeploying: [echo]
info:echo: Building module
info:controller0: Stopped time-cbfb2a0492
info:controller0: Deployed time-e21924cdd1
info:echo: Deploying module
info:controller0: Stopped echo-040fbeef14
info:controller0: Deployed echo-be607675b7
```
Schema change on the `productcatalog` module:
```sh
ftl dev ../ftl-examples/online-boutique/backend/services examples/go --recreate
info:productcatalog: Building module
info:productcatalog: Deploying module
info: productcatalog's schema changed; redeploying: [checkout recommendation]
info:recommendation: Building module
info:checkout: Building module
info:controller0: Stopped …
```

fix: rebuild dependent modules when schema changes

---

buildengine/engine.go

chore: improve dev deployment messaging

---

go-runtime/compile/schema_test.go

I must have accidentally included it in a previous PR

chore: remove printf call

---

backend/schema/intvalue.go
backend/schema/jsonschema.go
backend/schema/jsonschema_test.go
backend/schema/parser.go
backend/schema/schema.go
backend/schema/stringvalue.go

feat: handle enums in jsonschema

---

Justfile

I wasn't able to repro this after I changed it in a few places, so hopefully this is the only part that actually needed to be updated :)

chore: fix go generate path

---

.github/workflows/autofmt.yml
backend/controller/dal/dal.go

for issue: https://github.com/TBD54566975/ftl/issues/1075
Not sure of best way to test - I may try it on another branch perhaps? 
edit: tested it by having it push to this branch as if it was main, and it did what I expected. Doesn't need the FTL_AUTOFIX_TOKEN anymore, and won't trigger a rebuild (flip side of that is if it does have a rebuild, there won't be a build run against it - is that suitable @alecthomas ?)

feat: only do autofmt on main

---

backend/schema/schema_test.go
backend/schema/validate.go
backend/schema/validate_test.go
go-runtime/compile/parser.go
go-runtime/compile/schema.go
lsp/lsp.go

- make participle errors schema.Error so we can show then via LSP

fix: improve error position information

---

cmd/ftl/cmd_dev.go

fix: change --run-lsp to just --lsp

---

backend/controller/dal/notify.go

The `PullSchema` stream was broken causing issues for things like `ftl dev` which relies on updates to know when and how to rebuild.
The `LISTEN` needs to be called on each `topic` we want to listen to so we added a loop to listen to all topic channels.
Fixes #1182

fix: postgres db events listener initialization

---

go-runtime/encoding/encoding.go

fix: correctly encode strings

---

frontend/src/features/verbs/VerbPage.tsx

Fixes #1206 
https://github.com/TBD54566975/ftl/assets/51647/f63b18ae-070d-4e9e-99b7-3802e3622d37

fix: auto redirect to latest deployment

---

buildengine/engine.go
cmd/ftl/cmd_dev.go
common/projectconfig/merge.go
common/projectconfig/merge_test.go
common/projectconfig/projectconfig.go
common/projectconfig/projectconfig_test.go
common/projectconfig/testdata/ftl-project.toml
ftl-project.toml

fix: add commands section to ftl-project

---

Justfile
extensions/vscode/package.json
extensions/vscode/src/extension.ts

Show command list when FTL is clicked in the status bar

chore: add extension command list and just command to install

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/dal/dal_test.go
backend/controller/ingress/handler.go
backend/controller/ingress/handler_test.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
internal/rpc/context.go
internal/rpc/headers/headers.go

Centralised request row insertion into the controller.
Components responsible for other origins (HTTP, cron, ...) will create the RequestKey and sourceAddress and pass it along with the call.

chore: controller inserts requestkey into db

---

CONTRIBUTING.md
extensions/vscode/README.md
extensions/vscode/package.json

Fixes #1243 
https://marketplace.visualstudio.com/items?itemName=ftl.ftl

chore: update readme for VSCode extension

---

backend/schema/errors.go
buildengine/build.go
buildengine/build_go_test.go
go-runtime/compile/build.go
go-runtime/compile/parser.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go
go-runtime/compile/testdata/failing/failing.go
go-runtime/compile/testdata/lib.go

feat: aggregate go build errors for LSP

---

extensions/vscode/package-lock.json
extensions/vscode/package.json
extensions/vscode/src/config.ts
extensions/vscode/src/extension.ts

fix: add status and version checks to extension startup

---

backend/controller/controller.go

chore: improve logging when deployment is reused

---

README.md

chore: update readme layout

---

backend/schema/errors.go
buildengine/build_go_test.go
buildengine/build_test.go
go-runtime/compile/schema.go
go-runtime/compile/schema_test.go

feat: Go error messaging improvements for lsp

---

common/configuration/projectconfig_resolver.go

a NOOP followup to PR https://github.com/TBD54566975/ftl/pull/1273#discussion_r1566641940

refactor: Remove extraneous if-statement from `ftl-project.toml` path logic

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/protos/xyz/block/ftl/v1/ftl.proto

revert: "feat: Remove runners and ingress from dal GetStatus"

---

common/configuration/manager.go

Work around for #1309 until we get proper test support.

fix: hack to use FTL_CONFIG during ftltest

---

Justfile

This will rebuild build/release/ftl whenever source changes.

chore: add "just live-rebuild"

---

.github/workflows/ci.yml
.github/workflows/release.yml
buildengine/build_kotlin_test.go

chore: disable kotlin tests and releases

---

go-runtime/encoding/encoding.go

Resolves https://github.com/TBD54566975/ftl/pull/1417#discussion_r1591693874

chore: fix forward encoding cast

---

go-runtime/encoding/encoding.go

revert: "chore: fix forward encoding cast"

---

backend/controller/ingress/handler_test.go
backend/controller/ingress/request_test.go
go-runtime/encoding/encoding.go
go-runtime/encoding/encoding_test.go
go-runtime/ftl/call.go
go-runtime/ftl/option.go
go-runtime/ftl/typeregistry/type_registry.go
go-runtime/server/server.go

feat: Handle sum types in backend encoder

---

buildengine/watch_test.go

fixes #1419
Instead of calling `sleep` and trying to synchronise with the watcher's timing, this changes the logic to listen for expected events before continuing.

test: improve watch test reliability

---

frontend/src/components/ResizablePanels.tsx
frontend/src/features/console/right-panel/RightPanel.tsx
frontend/src/features/verbs/VerbFormInput.tsx
frontend/src/features/verbs/VerbPage.tsx
frontend/src/features/verbs/VerbRequestForm.tsx
frontend/src/features/verbs/VerbRightPanel.tsx

fix: split request and response area evenly

---

backend/controller/cronjobs/cronjobs_test.go

This might make the test more reliable. fixes https://github.com/TBD54566975/ftl/issues/1446
We may have been hitting a deadlock situation  where cronjobs were setting up their observation of channels and calling `clock.Now()` while the test tried to increment the mock clock (exact case is detailed more in https://github.com/TBD54566975/ftl/issues/1368).

test: make TestHashRing() more reliable

---

backend/controller/controller.go

This avoids having to acquire the lock to access the routing table, which can be easily forgotten.

refactor(controller): use an atomic.Value for storing routes

---

backend/controller/controller.go

Use the existing module change watcher to synchronise the complete schema into an atomic field. This will initially be used by the FSM code to lookup the desired FSM.

chore(controller): sync schema into an atomic field

---

buildengine/build_go_test.go
go-runtime/compile/build.go
go-runtime/compile/external-module-template/_ftl/go/modules/{{ range .NonMainModules }}{{ push .Name . }}{{ end }}/external_module.go

@matt2e Is this what you were expecting the fix should look like?
Looking at other generated code in the next PR if needed, eg fsm, config, etc
(Correct whitespace is tricky!)

fix: generate comments in module scaffolds #1489 (part 1)

---

backend/controller/console.go
backend/controller/console_test.go

Fixes this console error:
```
ModulesProvider - Connect error: ConnectError: [unknown] resolved declaration is not of the expected type: want *schema.Data, got *schema.Enum
```

fix: console ref traversal for enums and other types

---

integration/harness_test.go
internal/modulecontext/from_secrets.go

Address comments from https://github.com/TBD54566975/ftl/pull/1483

chore: address comments from DSNs-in-secrets PR #1483

---

backend/controller/dal/dal.go
backend/controller/dal/dal_test.go

Fixes https://github.com/TBD54566975/ftl/pull/1570#discussion_r1618128693

fix: query ModuleConfiguration via DAL

---

backend/controller/dal/dal.go
backend/controller/dal/notify.go
backend/controller/sql/models.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go
backend/controller/sql/schema/001_init.sql
internal/model/cron_job_key.go
internal/model/subscriber_key.go
internal/model/subscription_key.go
internal/model/topic_key.go
sqlc.yaml

Keys will have the following prefixes:
- topic: `top`
- subscription: `sub`
- subscriber: `subr`

feat: add topics, subscriptions & subscribers to db on deployment

---

internal/rpc/context.go

Fixes #1587 by creating a new grpc Interceptor to log panics in each wrap handler, then re-panic.

chore: intercept and log panics in wrap handlers, then re-panic

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/integration_test.go
go-runtime/ftl/map.go
go-runtime/ftl/map_test.go
go-runtime/ftl/testdata/go/mapper/ftl.toml
go-runtime/ftl/testdata/go/mapper/go.mod
go-runtime/ftl/testdata/go/mapper/go.sum
go-runtime/ftl/testdata/go/mapper/mapper.go
go-runtime/ftl/testdata/go/mapper/mapper_test.go
go-runtime/internal/api.go
go-runtime/internal/impl.go

Fixes: https://github.com/TBD54566975/ftl/issues/1586

feat: add Mock method to ftl.Map

---

backend/controller/cronjobs/cronjobs_test.go
buildengine/build_go_test.go
go-runtime/compile/schema_test.go
go-runtime/ftl/ftltest/leases_test.go

Before:
go test -count 1 -short ./...  19.76s user 9.29s system 238% cpu 12.175 total
After:
go test -count 1 -short ./...  6.82s user 2.15s system 269% cpu 3.336 total

chore: skip a bunch of tests in -short mode

---

backend/controller/sql/databasetesting/devel.go

fix: leftover fsm_executions in code

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/ftltest/ftltest_integration_test.go
go-runtime/ftl/map.go
go-runtime/ftl/secrets.go
go-runtime/ftl/secrets_test.go
go-runtime/internal/api.go
go-runtime/internal/impl.go
internal/modulecontext/from_secrets.go

refactor: pull secrets from FTL runtime abstraction

---

cmd/ftl/cmd_init.go

Fix for: https://github.com/TBD54566975/ftl/issues/1710

feat: check that go module name is valid and not a keyword

---

go-runtime/compile/schema.go
go-runtime/compile/testdata/one/one.go

fixes https://github.com/TBD54566975/ftl/issues/1747

fix: allow non-FTL enums to exists in a module

---

go-runtime/ftl/ftltest/ftltest.go

fix: disable FK constraints when wiping rows

---

lsp/completion.go
lsp/markdown/completion/enumType.md
lsp/markdown/completion/enumValue.md
lsp/markdown/completion/verb.md

This should make it easier to add new completions.

refactor(lsp): join help and completion

---

buildengine/engine.go

fixes #1706
when both of these things happen:
- we update a deployment successfully
- the engine idles for long enough for the file watcher to do 2 cycles
then we log "All modules deployed, watching for changes..."

fix: ftl dev notifies when all deployments are up to date

---

cmd/ftl/cmd_dev.go

This spins up the container and initialises the database, then exits.

feat: add `ftl dev --init-db` flag

---

go-runtime/compile/build.go
go-runtime/compile/external-module-template/_ftl/go/modules/{{ range .NonMainModules }}{{ push .Name . }}{{ end }}/external_module.go.tmpl

fix: don’t import ftl twice if pubsub and something else requires ftl

---

scripts/update-workflow-issue

Also fix for users who run coreutils on mac 😬 
Fixes #1815

feat: show issue and pr labels on gh dashboard

---

backend/controller/controller.go
buildengine/engine.go
cmd/ftl-controller/main.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_serve.go

fix: move startup command exec from Dev to cmd_serve

---

buildengine/deploy.go
buildengine/engine.go
cmd/ftl/cmd_dev.go
extensions/vscode/src/client.ts
extensions/vscode/src/extension.ts
extensions/vscode/src/status.ts
lsp/lsp.go

Fixes #1808
https://github.com/TBD54566975/ftl/assets/31338/54e6f71e-1ad5-4ef0-9b03-630a8ae428f5

feat: lsp/extension to show build status for failures and errs

---

.github/workflows/release.yml
buildengine/engine.go
cmd/ftl/cmd_build.go
deployment/README.md
deployment/ftl-controller/ftl-controller.yml
deployment/ftl-runner/ftl-runner.yml
deployment/kustomization.yml

chore: move Docker images to Docker Hub because GHCR is private and that sucks

---

cmd/ftl/main.go
common/configuration/api.go
common/configuration/asm.go
common/configuration/db_config_resolver.go
common/configuration/defaults.go
common/configuration/manager.go
common/configuration/projectconfig_resolver.go

Hi ,
Would like some help with rebasing this PR.
This is for (Rename configuration.Resolver to configuration.Router) #1886 
Thanks.

chore: Change interface name from Resolver to Router in Configuration

---

common/configuration/1password_provider.go
common/configuration/defaults.go

fix: call `op` serially to avoid multiple authorization prompts

---

buildengine/build_go.go
buildengine/engine.go
lsp/lsp.go

fix: lsp/vs less spammy with error toast popups

---

Justfile
extensions/vscode/src/extension.ts

Fixes #1853
* Clean visx files before build.
* Type safe string consts.

feat: start server workspace setting.

---

.github/workflows/release.yml
backend/controller/sql/testdata/go/database/go.mod
backend/controller/sql/testdata/go/database/go.sum
bin/hermit.hcl
extensions/vscode/package-lock.json
extensions/vscode/package.json

Fixes #1941 #1925
Version will match FTL version.

ci: auto release vscode extension

---

README.md
buildengine/watch_test.go
cmd/ftl/cmd_init.go
common/projectconfig/projectconfig.go
docs/content/docs/getting-started/quick-start/index.md
ftl-project.toml
go-runtime/ftl/ftl_integration_test.go

closes #1946
This will help name the singular 1Password entry we will use for a project

chore: add name to ftl projects

---

backend/controller/leader/leader_test.go

test: TestSingleLeader data race fixed

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest_test.go

.. when failing to access config or secrets
Fixes #1874

feat: suggest using project file in ctx in tests

---

buildengine/build.go
buildengine/engine.go

fix: panic in build engine when module building fails

---

internal/rpc/rpc.go

fix: demote already closed stream

---

docs/content/docs/reference/ingress.md

fix: add documentation for http ingress

---

Justfile

Just removing that last debug change. It looks like it was errtrace genrating code.

fix: remove git diff from ci

---

common/configuration/asm_follower.go

fix: ASM follower syncs more frequently

---

backend/controller/sql/conn.go

fix: remove unused savepoints and just use begin/commit

---

backend/schema/schema.go

resolve through type aliases if underlying type can be resolved to data

fix: fix ResolveMonomorphised

---

internal/log/logger.go

fix: log attrs being dropped

---

go-runtime/compile/build.go

fix: build module without verbs with a subpackage that has verbs

---

.golangci.yml
backend/controller/console.go
backend/controller/cronjobs/cronjobs.go
go.mod
go.sum

Also was logging with incorrect package...

fix: return error rather than logging

---

go-runtime/ftl/ftltest/fake.go
go-runtime/ftl/ftltest/ftltest.go
go-runtime/ftl/ftltest/ftltest_test.go
go-runtime/ftl/ftltest/testdata/go/pubsub/pubsub_test.go

fixes #2184
Could not repro easily in a test but was able to repro in partner project. Will look inout the tests during the week

fix: ftltest pubsub needs context associated with fake ftl

---

backend/controller/console.go
backend/controller/ingress/request.go
backend/schema/jsonschema.go
backend/schema/jsonschema_test.go
backend/schema/jsonvalidate.go
backend/schema/schema.go

support Data, Any or TypeAlias over either supported type

fix: supported verb req/resp types

---

frontend/src/features/verbs/VerbRequestForm.tsx

fix: header text reloading when changing tabs

---

cmd/ftl-controller/main.go
cmd/ftl/cmd_box_run.go
cmd/ftl/cmd_serve.go

fix: call Config.SetDefaults()

---

backend/controller/dal/pubsub.go
backend/controller/sql/querier.go
backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

We should get better visibility when we create/delete/update subscriber and subscription registrations

fix: add logs for subscription and subscriber changes

---

backend/controller/sql/queries.sql
backend/controller/sql/queries.sql.go

fix: make sure async calls are processed in order

---

.github/actions/build-cache/action.yml

Docker compose is taking around 50 seconds, hopefully this will speed that up.

chore(ci): cache Docker images

---

backend/controller/controller.go

For https://github.com/TBD54566975/ftl/pull/2273#discussion_r1706327825

fix: increase reap call events delays

---

.github/workflows/ci.yml
docker-compose.yml
scripts/go-test-annotate

Heavyweight tests do not run on pull requests, only in the merge queue.

chore(ci): fast-path for PR status checks

---

backend/controller/observability/async_calls.go
backend/controller/observability/cron.go
backend/controller/observability/deployment.go
backend/controller/observability/fsm.go
backend/controller/observability/observability.go
backend/controller/observability/pubsub.go
backend/runner/observability/deployment.go
backend/runner/observability/observability.go
backend/runner/observability/runner.go

part 1 of https://github.com/TBD54566975/ftl/issues/2286

chore: minor refactor to get all otel metric code following the same patterns

---

go-runtime/schema/extract.go

still haven't been able to repro but attempts to fix #2251

fix: maybe fix rare npe

---

cmd/ftl/cmd_schema_diff.go

fix: schema diff is reversed

---

backend/controller/dal/lease.go
backend/controller/leader/leader.go

fix: asm leader failing to read and write lease metadata

---

backend/controller/pubsub/integration_test.go
backend/controller/pubsub/testdata/go/subscriber/subscriber.go
go-runtime/schema/subscription/analyzer.go

This makes naming more consistent.

fix: also require camel case subscription names

---

docs/content/docs/reference/retries.md

docs: add explanation of how retries can be defined on FSMs

---

backend/controller/pubsub/integration_test.go
backend/controller/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/Publisher.java
backend/controller/pubsub/testdata/java/subscriber/src/main/java/xyz/block/ftl/java/test/subscriber/Subscriber.java

chore: Java tests for catch<Any>

---

scripts/update-workflow-issue

ci: do not show run-all tag on dashboard

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/FtlProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/SchemaBuilder.java

chore: move type building logic out of FTLProcessor

---

extensions/vscode/package-lock.json

Fixes #2486 
https://github.com/microsoft/vscode-vsce/issues/1026

fix: vscode extension build errors with glob

---

renovate.json5

We don't need/want a quick feedback loop for Renovate.

chore: add "run-all" label to Renovate PRs

---

go-runtime/compile/build.go
go-runtime/compile/testdata/go/two/two.go

fix: do not parse associated types as refs

---

frontend/src/api/modules/use-modules.ts
frontend/src/api/status/use-status.ts
frontend/src/api/timeline/use-timeline.ts
frontend/src/layout/Layout.tsx
frontend/src/layout/navigation/Navigation.tsx
frontend/src/layout/navigation/Version.tsx

feat: show real version in console nav

---

.npmrc
biome.json
extensions/vscode/biome.json
frontend/biome.json

chore(lint): centralize node linting rules

---

Dockerfile.box
Dockerfile.controller
Dockerfile.runner

fix: fix image builds

---

frontend/src/components/ResizableHorizontalPanels.tsx
frontend/src/features/modules/ModulesTree.tsx
frontend/src/layout/Layout.tsx

Final part of https://github.com/TBD54566975/ftl/issues/2487
https://github.com/user-attachments/assets/eb7ed1eb-d8ae-4a92-b56e-7bde8aed3a6b

feat: make the module tree scrollable + scroll to selected module

---

frontend/console/e2e/command-palette.ts
frontend/console/src/features/command-pallete/CommandPalette.tsx
frontend/console/src/features/command-pallete/command-palette.utils.ts
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts
frontend/console/src/layout/Layout.tsx
frontend/console/src/layout/navigation/Navigation.tsx
frontend/console/src/layout/navigation/SearchInput.tsx

Fixes #2623 
https://github.com/user-attachments/assets/0c1fa35c-7e95-4780-ab9c-b4f5764fdcf9

feat: add global search to console

---

Justfile

The dependencies were not correct.

build: fix incremental frontend builds

---

go-runtime/schema/extract.go

fix: don't setup extractors in init

---

frontend/console/src/features/modules/decls/DeclPanel.tsx
frontend/console/src/features/modules/decls/SubscriptionPanel.tsx
frontend/console/src/features/modules/decls/TopicPanel.tsx
frontend/console/src/features/modules/decls/TypeEl.tsx

Issue: https://github.com/TBD54566975/ftl/issues/2616
All the remains now is FSM.

feat: add decl pages for topics and subscriptions

---

backend/controller/dal/dal.go

fixes https://github.com/TBD54566975/ftl/issues/2655

fix: hang on redeployment

---

internal/configuration/obfuscator.go

fix: check len of input

---

.github/workflows/ci.yml
Justfile
backend/controller/scaling/k8sscaling/kube_scaling_integration_test.go

Also disabled TestKubeScaling() because it takes a minimum of 5 minutes and we want to minimise PR CI time.

chore(ci): run all CI tests on the branch so we can disable merge queue

---

backend/controller/controller.go
backend/controller/dal/dal.go
backend/controller/dal/internal/sql/queries.sql
backend/controller/dal/internal/sql/queries.sql.go
backend/controller/dal/notify.go
backend/controller/scaling/k8sscaling/deployment_provisioner.go
backend/controller/scaling/k8sscaling/k8s_scaling.go
backend/controller/scaling/k8sscaling/kube_scaling_integration_test.go
backend/controller/sql/schema/20240917062716_change_deployments_index.sql
deployment/base/db-migrate/kustomization.yml
internal/buildengine/engine.go

feat: rolling deployments

---

frontend/cli/cmd_interactive.go

It calls Kong's Exit() hook, so we now override it.

fix: `--help` in the interactive console wasn't working

---

backend/runner/runner.go
internal/interactive/interactive.go

With the protocol changes we don't need this anymore

chore: remove runner start delay

---

.github/workflows/release.yml

We need to strip the leading 'v'

fix: correct java version

---

Justfile
docker-compose.yml

chore: use docker compose for otel-collector in Justfile

---

frontend/cli/cmd_serve.go

fix: ftl dev crashes with OTEL enabled

---

.golangci.yml
backend/controller/controller.go
backend/controller/observability/calls.go
go.mod

This creates spans for HTTP ingress and verb invocations

feat: add tracing for HTTP ingress

---

internal/exec/exec.go

fix: build errors logged at info

---

backend/controller/console/console.go

fix: duplicate schema elements in console

---

frontend/console/src/features/calls/CallList.tsx
frontend/console/src/features/timeline/Timeline.tsx
frontend/console/src/features/timeline/TimelinePage.tsx
frontend/console/src/features/traces/TraceDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx
frontend/console/src/features/traces/TraceGraphHeader.tsx
frontend/console/src/features/traces/TracesPage.tsx
frontend/console/src/features/traces/details/TraceDetailsCall.tsx
frontend/console/src/features/traces/details/TraceDetailsIngress.tsx
frontend/console/src/providers/routing-provider.tsx

Fixes #2762
https://github.com/user-attachments/assets/e57009f3-bf9b-411e-8956-afd0795bc5ed

feat: traces page and basic setup

---

backend/controller/ingress/handler.go

Currently by the time the response body is added into the timeline it has been deserialized, so may not longer be valid JSON.

fix: include raw response body

---

frontend/console/src/features/timeline/TimelineIcon.tsx
frontend/console/src/features/timeline/details/TimelineCallDetails.tsx
frontend/console/src/features/timeline/details/TimelineDeploymentCreatedDetails.tsx
frontend/console/src/features/timeline/details/TimelineDeploymentUpdatedDetails.tsx
frontend/console/src/features/timeline/details/TimelineDetailsColorBar.tsx
frontend/console/src/features/timeline/details/TimelineIngressDetails.tsx
frontend/console/src/features/timeline/filters/TimelineFilterPanel.tsx
frontend/console/src/features/timeline/timeline.utils.ts
frontend/console/src/features/traces/TraceDetailItem.tsx
frontend/console/src/features/traces/TraceDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx
frontend/console/src/features/traces/traces.utils.ts

- Add utils for sharing colors for events etc. to make them easily changeable and consistent
- Add utils for shared computations on event bars
- Add child components to make the component sizes more manageable
- Minor adjustments to the bar colors to be more subtle

chore(refactor): add utils for timeline and requests

---

frontend/console/src/components/Tabs.tsx
frontend/console/src/features/infrastructure/DeploymentsList.tsx

fix: super tiny fix to tab count indicators

---

frontend/console/src/features/verbs/VerbPage.tsx

Fixes: https://github.com/TBD54566975/ftl/issues/2647

fix: update verb page contents on declName change

---

backend/controller/controller.go
frontend/cli/cmd_call.go
frontend/cli/cmd_dev.go
frontend/cli/cmd_interactive.go
frontend/cli/cmd_replay.go
frontend/cli/cmd_status.go
frontend/cli/main.go
internal/buildengine/engine.go
internal/exec/exec.go
internal/terminal/interactive.go
internal/terminal/noop.go
internal/terminal/predictors.go
internal/terminal/status.go

Also some cleanup around shutdown handling
fixes: #2807

fix: panic on shutdown

---

frontend/console/e2e/module.spec.ts
frontend/console/e2e/verb.spec.ts
frontend/console/src/features/modules/ModulesTree.tsx

Part 1 of https://github.com/TBD54566975/ftl/issues/2760

fix: console module tree: rip out disclosure button to fix all the state consistency bugs

---

internal/terminal/status.go

Another option for the progress/complete indicators on the interactive terminal.
No worries if the other is preferred, I was mostly playing around to see what we could do here.
https://github.com/user-attachments/assets/d2fc028a-e9b2-4087-b306-28ca0ab82817

feat: update terminal status indicators

---

frontend/cli/cmd_schema_get.go

fix: panic in schema watch

---

go-runtime/schema/extract.go

chore: figure out what is going on with the panic

---

go-runtime/schema/finalize/analyzer.go

this will all go away when we remove support for ftl.Call(...)

fix: legacy call metadata

---

backend/schema/jsonvalidate.go

Noticed this TODO so thought I'd clean it up

chore: fix todo for validation using reflect

---

frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts
frontend/console/src/features/modules/schema/schema.utils.ts
frontend/console/src/features/timeline/filters/TimelineTimeControls.tsx

https://github.com/user-attachments/assets/a59c1b36-f9d1-4754-b29d-d2f8409fe882
Fixes: https://github.com/TBD54566975/ftl/issues/2760

feat: add decl type filter + collapse all button to console's module tree

---

frontend/console/src/features/modules/ModulesTree.tsx

Fixes: https://github.com/TBD54566975/ftl/issues/2661
https://github.com/user-attachments/assets/b387fcbd-546f-4ec7-b240-a2400404d158

fix: expand and scroll to decl on click

---

internal/buildengine/engine.go

fix: rebuild dependent modules when new module detected

---

internal/terminal/interactive.go

fix: no interactive mode if not a terminal

---

backend/runner/runner.go

fix: duplicate log lines

---

cmd/go2proto/main.go

```
$ go2proto
Usage: go2proto <package> <ref> ... [flags]
Generate a Protobuf schema from Go types.
It supports converting structs to messages, Go "sum types" to oneof fields,
and Go "enums" to Protobuf enums.
The generator works by extracting protobuf tags from the source Go types.
There are two locations where these tags must be specified:
1. For fields using a tag in the form `protobuf:"<id>[,optional]"`.
2. For sum types as comment directives in the form //protobuf:<id>.
An example showing all three supported types and the corresponding protobuf
tags:
type UserType int
const (
UserTypeUnknown UserType = iota
UserTypeAdmin
UserTypeUser
)
// Entity is a "sum type" consisting of User and Group.
//
// Every sum type element must have a comment directive in the form //protobuf:<id>.
type …
```

docs: add docs to go2proto

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HTTPProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/PositionUtils.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/SubscriptionProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsBuildItem.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsProcessor.java

feat: capture schema element locations

---

frontend/cli/cmd_schema_get.go

fix: `ftl schema get` was not exiting

---

frontend/cli/cmd_schema_diff.go

fix: schema diff missing output

---

backend/controller/console/console.go
backend/controller/console/console_integration_test.go

Fixes: https://github.com/TBD54566975/ftl/issues/2805

feat: streaming module updates from console service backend

---

internal/integration/harness.go

This should not happen, but it can catch potential issues

chore: sanity check in test harness

---

backend/controller/controller.go
backend/controller/dsn/dsn.go
backend/controller/sql/database_integration_test.go
backend/controller/sql/sqltest/testing.go
cmd/ftl-controller/main.go
cmd/ftl-initdb/main.go
frontend/cli/cmd_box.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_migrate.go
frontend/cli/main.go
internal/dev/db.go
internal/integration/actions.go

This doesn't quite catch them all, as some are in k8s charts, Dockerfiles, etc. but it's an improvement on the previous state.

refactor: unify (many of) the DSN uses

---

Justfile
cmd/go2proto/main.go

Rather than hard-coding some, require them to be set explicitly.

chore: generalise go2proto options

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/VerbProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/VerbType.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/VerbClient.java
jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/JavaCodeGenerator.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java
jvm-runtime/testdata/java/javaclient/src/main/java/xyz/block/ftl/test/TestInvokeGoFromJava.java
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/TestInvokeGoFromKotlin.kt
smoketest/pulse/src/main/java/com/example/Pulse.java

- Move @VerbClient annotation from class to method 
- Rename client method from "call" to \<verbName\>

feat: Move VerbClient annotation to method

---

jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/JavaCodeGenerator.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java
jvm-runtime/jvm_integration_test.go
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/TestInvokeGoFromKotlin.kt
jvm-runtime/testdata/kotlin/kotlinserver/ftl.toml
jvm-runtime/testdata/kotlin/kotlinserver/pom.xml
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/Animal.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/AnimalWrapper.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/Cat.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/ColorInt.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/ColorWrapper.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/Dog.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/ScalarOrList.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/ScalarWrapper.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/Shape.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/ShapeWrapper.kt
jvm-runtime/testdata/kotlin/kotlinserver/src/main/kotlin/xyz/block/ftl/test/Verbs.kt

feat: Enums in Kotlin

---

internal/buildengine/languageplugin/external_integration_test.go
internal/integration/actions.go
internal/integration/harness.go

This is designed to test whether a language plugin behaves as expected in normal and unusual cases. As we add each language plugin, we should add them to the language list of each of these tests.

test: add test suite for language plugins

---

go-runtime/schema/extract.go

The requires slice was being appended to concurrently multiple times, this should only happen once.
fixes: #2845 #3162

fix: cursed panic

---

.goosehints

Can run things like 
G> `can you take a look at https://github.com/TBD54566975/ftl/issues/3162 and see if can reproduce or fix it`
with a profile like: 
```yaml
block:
provider: block
processor: claude-3-5-sonnet-2
accelerator: claude-3-5-sonnet-2
moderator: synopsis
toolkits:
- name: synopsis
requires: {}
```
which at time of writing is best

feat: Goose developing FTL itself

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/StaticConfigSource.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/config/FTLConfigSource.java

fix: disable metrics if endpoint not set

---

internal/integration/actions.go

chore: remove dead error handling

---

internal/terminal/interactive.go

fix: interactive console --help runs command

---

frontend/console/e2e/helpers.ts
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/module.utils.ts

Part 1 of https://github.com/TBD54566975/ftl/issues/3219
https://github.com/user-attachments/assets/5cb024af-4d59-4a6a-b7ca-678ad1001fed

feat: hide unexported decls in console by default and provide a toggle to show

---

backend/controller/cronjobs/internal/sql/queries.sql
backend/controller/cronjobs/internal/sql/queries.sql.go
backend/controller/dal/internal/sql/queries.sql.go

fix: improve cron deletion

---

common/plugin/spawn.go
frontend/cli/cmd_bench.go
frontend/cli/cmd_box_run.go
frontend/cli/cmd_call.go
frontend/cli/cmd_ping.go
frontend/cli/cmd_replay.go
frontend/cli/cmd_serve.go
internal/buildengine/languageplugin/external_plugin_client.go
internal/rpc/rpc.go

Reverts TBD54566975/ftl#3243
This was not the cause of failure

revert: Revert "revert: "fix: reduce spammy logs for pings""

---

go-runtime/schema/schema_fuzz_integration_test.go
go-runtime/schema/schema_integration_test.go

This test is fairly slow, we want to shard it out

chore: make schema test an integration test

---

frontend/cli/cmd_secret.go

fix: secret set pw prompt

---

examples/java/echo/src/main/java/ftl/echo/Echo.java
go-runtime/compile/build.go
go-runtime/goplugin/service.go
internal/buildengine/languageplugin/plugin.go
internal/buildengine/languageplugin/plugin_integration_test.go
internal/buildengine/languageplugin/testdata/java/plugintest/ftl.toml
internal/buildengine/languageplugin/testdata/java/plugintest/pom.xml
internal/buildengine/languageplugin/testdata/java/plugintest/src/main/java/xyz/block/ftl/java/test/plugintest/EchoRequest.java
internal/buildengine/languageplugin/testdata/java/plugintest/src/main/java/xyz/block/ftl/java/test/plugintest/EchoResponse.java
internal/buildengine/languageplugin/testdata/java/plugintest/src/main/java/xyz/block/ftl/java/test/plugintest/PluginTest.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/plugin/common/jvmcommon.go

Propagate errors back to FTL properly, also some bug fixes

fix: JVM error handling

---

frontend/console/package.json
frontend/console/src/components/CodeEditor.tsx
pnpm-lock.yaml

https://github.com/user-attachments/assets/fc289246-131b-44a2-b6a6-7e5d8ab8e7ef

feat: basic autocomplete on code editor

---

internal/buildengine/languageplugin/plugin.go
internal/buildengine/languageplugin/plugin_client.go

fix: fix incorrect build times in logs

---

jvm-runtime/ftl-runtime/.maven_settings.xml

chore: remove TBD artifactory

---

frontend/console/biome.json
frontend/console/e2e/cron.spec.ts
frontend/console/e2e/echo.spec.ts
frontend/console/e2e/ingress-http.spec.ts
frontend/console/e2e/pubsub.spec.ts
frontend/console/src/features/modules/schema/Schema.tsx
frontend/console/src/features/traces/TraceRequestList.tsx
frontend/console/src/features/verbs/KeyValuePairForm.tsx
frontend/console/src/features/verbs/VerbRequestForm.tsx
frontend/console/src/features/verbs/VerbRightPanel.tsx
frontend/console/src/features/verbs/hooks/useKeyValuePairs.ts

https://github.com/user-attachments/assets/739cb470-ddd2-4a5b-8333-31c34c4813c5

feat: add headers and query params input form

---

frontend/console/e2e/ingress-http.spec.ts

Tiny PR to actually test the query params form on verb request page.

chore: use query param form for e2e test

---

frontend/console/src/features/verbs/VerbRequestForm.tsx

feat: add button to copy request body on verb form

---

frontend/console/src/providers/routing-provider.tsx

chore: opt-in to new react router features to silence warnings

---

go.mod
go.sum
internal/container/container.go

This is much nicer than spamming JSON to our logs.
https://github.com/user-attachments/assets/3fd28752-962e-40cd-b0a3-bb30e9cdad4a

chore: use Docker's own progress formatting

---

backend/controller/sql/testdata/go/mysql/types.ftl.go
backend/provisioner/dev_provisioner.go
docker-compose.yml
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java

The provisioner should start it if it is needed.

chore: don't start mysql for every test

---

frontend/console/src/features/modules/decls/RightPanelHeader.tsx
frontend/console/src/features/modules/decls/database/DatabasePanel.tsx
frontend/console/src/features/modules/decls/database/DatabaseRightPanels.tsx
frontend/console/src/features/modules/decls/enum/EnumPanel.tsx
frontend/console/src/features/modules/decls/enum/EnumRightPanels.tsx
frontend/console/src/features/modules/decls/secret/SecretPanel.tsx
frontend/console/src/features/modules/decls/subscription/SubscriptionPanel.tsx
frontend/console/src/features/modules/decls/subscription/SubscriptionRightPanels.tsx
frontend/console/src/features/modules/decls/topic/TopicPanel.tsx
frontend/console/src/features/modules/decls/topic/TopicRightPanels.tsx
frontend/console/src/features/modules/decls/typealias/TypeAliasPanel.tsx
frontend/console/src/features/modules/decls/typealias/TypeAliasRightPanels.tsx

Just stubbing out these pages so we have somewhere to add content once we figure out what we need.

feat: stub out each decl panel

---

cmd/ftl-proxy-pg/main.go
cmd/ftl-runner/main.go
internal/pgproxy/pgproxy.go

feat: run pgproxy as a part of the runner

---

examples/java/echo/src/main/java/ftl/echo/Echo.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRecorder.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/HotReloadSetup.java

fix: display JVM errors in dev mode

---

internal/dev/docker-compose.redpanda.yml

fix: move redpanda console off common port

---

Justfile

Previously there were N slightly different duplicates of the same commands. This fixes that.

chore: normalise Go binary builds

---

backend/provisioner/service.go
cmd/ftl-provisioner/main.go
frontend/cli/cmd_dev.go
frontend/cli/cmd_serve.go

I think this functionality was removed earlier anyway, so this is no longer relevant?

refactor: provisioner is no longer a SchemaService

---

backend/controller/sql/testdata/java/database/src/main/db/testdb/20241103205514_postgres.sql
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/InsertResponse.java
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/Request.java
backend/controller/sql/testdata/java/database/src/main/resources/application.properties
backend/controller/sql/testdata/java/mysql/src/main/db/testdb/20241103205514_mysql.sql
backend/controller/sql/testdata/java/mysql/src/main/java/xyz/block/ftl/java/test/database/Database.java
backend/controller/sql/testdata/java/mysql/src/main/java/xyz/block/ftl/java/test/database/Request.java
backend/controller/sql/testdata/java/mysql/src/main/resources/application.properties
internal/buildengine/build.go
internal/buildengine/sql_migration_extract.go
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/StaticConfigSource.java
jvm-runtime/plugin/common/java_plugin_test.go
jvm-runtime/plugin/common/jvmcommon.go

feat: JVM DB migrations

---

Justfile

The comment had the right idea...

chore: sleep before retrying docker compose up

---

backend/provisioner/dev_provisioner.go
frontend/cli/cmd_serve.go

Closes https://github.com/TBD54566975/ftl/issues/3515

fix: only drop databases in ftl dev when running with --recreate

---

Justfile

Causes protos to be rebuilt every time.

fix: PROTOS_OUT missing space

---

backend/controller/pubsub/integration_test.go
backend/controller/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/Publisher.java
examples/java/ExampleInterface.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsProcessor.java
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/TopicPartitionMapper.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/WriteableTopic.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/TopicHelper.java

Removes jvm from pubsub integration tests as it is no longer consuming from where it is publishing.

feat: jvm publishes to kafka and adds partition mapper

---

backend/provisioner/controller_provisioner.go
backend/provisioner/deployment_test.go
backend/provisioner/dev_provisioner.go
backend/provisioner/inmem_provisioner.go
backend/provisioner/registry.go
backend/provisioner/resource_type.go
backend/provisioner/runner_scaling_provisioner.go
backend/provisioner/sql_migration_provisioner.go
frontend/cli/cmd_serve.go
internal/schema/database.go
internal/schema/module.go
internal/schema/provisioned.go
internal/schema/runtime.go
internal/schema/topic.go
internal/schema/verb.go

Commits should describe what the intent is, hopefully.

feat: Schema changes for using schema as provisioning input

---

backend/ingress/handler.go
charts/ftl/templates/http-ingress-deployment.yaml
cmd/ftl-http-ingress/main.go

closes https://github.com/TBD54566975/ftl/issues/3655

fix: ingress publishes events to timeline

---

backend/controller/artefacts/oci_registry.go
backend/controller/controller.go
backend/provisioner/scaling/localscaling/local_scaling.go
backend/provisioner/sql_migration_provisioner.go
backend/runner/runner.go
cmd/ftl-controller/main.go
cmd/ftl-runner/main.go
frontend/cli/cmd_serve.go

Specifically, rather than constructing a new OCI registry client all over the place, do it in main. Also pulled observability initialisation out into main.

refactor: pull construction of some dependencies to the outermost layer

---

frontend/cli/cmd_serve.go

We were returning "context cancelled" error before getting the errgroup error that caused the context to be cancelled.

fix: return startup errors properly

---

backend/controller/dal/internal/sql/models.go
backend/controller/dal/internal/sql/queries.sql.go
backend/controller/pubsub/internal/sql/models.go
backend/controller/pubsub/internal/sql/queries.sql
backend/controller/pubsub/internal/sql/queries.sql.go
backend/controller/sql/schema/20241209050728_remove_pubsub_keys.sql

Remove the relationship between the modules/deployments tables and pubsub.

chore: remove pubsub FKs

---

internal/buildengine/engine.go

Wait for module deployment before building next group

fix: wait for module deployment

---

backend/controller/controller.go
backend/timeline/service.go

chore: move timeline reaping to within timeline service

---

backend/controller/observability/async_calls.go
backend/controller/observability/calls.go
backend/controller/observability/deployment.go
backend/controller/observability/observability.go
backend/controller/observability/pubsub.go
backend/ingress/handler.go
backend/ingress/observability.go
backend/ingress/service.go
backend/timeline/client.go
backend/timeline/observability.go
internal/observability/helpers.go
internal/observability/helpers_test.go

Move metrics to correct packages. There is still some more work required (e.g. pubsub, peer-to-peer metrics) but this improves things.

chore: observability cleanup

---

backend/provisioner/runner_scaling_provisioner.go
frontend/cli/cmd_serve.go

fix: console cors errors

---

backend/runner/pubsub/consumer.go
backend/runner/pubsub/integration_test.go
backend/runner/pubsub/testdata/go/publisher/publisher.go
backend/runner/pubsub/testdata/go/publisher/types.ftl.go
backend/runner/pubsub/testdata/go/subscriber/go.mod
backend/runner/pubsub/testdata/go/subscriber/subscriber.go
backend/runner/pubsub/testdata/go/subscriber/types.ftl.go
backend/runner/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/HaystackRequest.java
backend/runner/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/PubSubEvent.java
backend/runner/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/Publisher.java
backend/runner/pubsub/testdata/java/subscriber/src/main/java/xyz/block/ftl/java/test/subscriber/Subscriber.java

feat: pubsub follows retry policies

---

.github/workflows/ci.yml
internal/schema/data.go
internal/schema/jsonschema.go
internal/schema/validate.go

Blocked by https://github.com/alecthomas/go-check-sumtype/pull/15

chore: cleanup empty switch cases

---

backend/runner/pubsub/consumer.go
backend/runner/pubsub/integration_test.go
backend/runner/pubsub/testdata/go/publisher/publisher.go
backend/runner/pubsub/testdata/go/subscriber/subscriber.go
backend/runner/pubsub/testdata/go/subscriber/types.ftl.go
backend/runner/pubsub/testdata/java/subscriber/src/main/java/xyz/block/ftl/java/test/subscriber/Subscriber.java
backend/runner/pubsub/testdata/kotlin/subscriber/src/main/kotlin/xyz/block/ftl/java/test/subscriber/Subscriber.kt

fix: start consuming based on `from` offset option

---

frontend/console/src/components/Checkbox.tsx
frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/decls/KeyValuePairForm.tsx
frontend/console/src/features/modules/decls/config/ConfigPanel.tsx
frontend/console/src/features/modules/decls/secret/SecretPanel.tsx
frontend/console/src/features/timeline/filters/TimelineFilterPanel.tsx

- Fixes #3404
- use it for the new json mode flag in config/secrets

feat: reusable checkbox component

---

.github/workflows/ci.yml

Initially three tests per shard.

chore(ci): multiple integration tests per shard in CI

---

.github/workflows/ci.yml

This reverts commit c6b2b27a163ca7b2e04799d98af7a1979a390a94.

revert: "chore(ci): multiple integration tests per shard in CI (#3789)"

---

internal/integration/actions.go
internal/integration/harness.go

This can result in image pulls so it needs to be longer

fix: use longer timeout for deployment and controller start

---

backend/cron/service.go

fix: set cron request key header before calling

---

frontend/console/src/components/Checkbox.tsx
frontend/console/src/components/Multiselect.tsx
frontend/console/src/features/modules/ModulesPage.tsx
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/decls/KeyValuePairForm.tsx
frontend/console/src/features/traces/TraceDetailItem.tsx
frontend/console/src/features/traces/TraceDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx
frontend/console/src/features/traces/TraceGraphHeader.tsx
frontend/console/src/features/traces/TracesPage.tsx
frontend/console/src/features/traces/traces.utils.ts

- Fix layout and spacing on module tree header
- Fix usage of new Checkbox on KeyValuePair component
- Fix reversed timeline events and layout issues

fix: lots of minor UI issues (and some major)

---

internal/routing/verb_routing.go

fix: empty (dpl-) keys in timeline events

---

internal/raft/cluster.go
internal/raft/cluster_test.go

See https://github.com/lni/dragonboat/issues/357#issuecomment-2155171795 for more info

fix: wait for the index to be synced before reporting a shard ready.

---

go-runtime/compile/build.go
go-runtime/compile/build_test.go
go-runtime/compile/stubs.go

fix: detect package name mismatches in go modules

---

backend/runner/pubsub/testdata/go/publisher/publisher.go
backend/runner/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/Publisher.java
backend/runner/pubsub/testdata/java/subscriber/src/main/java/xyz/block/ftl/java/test/subscriber/Subscriber.java
backend/runner/pubsub/testdata/kotlin/publisher/src/main/kotlin/xyz/block/ftl/java/test/publisher/Publisher.kt
docs/content/docs/reference/pubsub.md
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/SubscriptionProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsBuildItem.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsProcessor.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/Topic.java
jvm-runtime/ftl-runtime/java/deployment/src/main/java/xyz/block/ftl/javalang/deployment/JavaCodeGenerator.java
jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java

```java
@Export
@Topic(name = "testTopic", partitions = 10)
interface TestTopic extends WriteableTopic<PubSubEvent, PartitionMapper> {
}
```

feat: define partitions in jvm topic declarations

---

jvm-runtime/plugin/common/jvmcommon.go

Quarkus also watches for changes, but if the initial build fails we need to detect file changes ourselves.
Previously we only started watching for changes after the initial build failed, which meant changes made after the initial build started but before it failed were not detected.
fixes https://github.com/block/ftl/issues/3937

fix: jvm plugin watches for file changes while building

---

backend/controller/controller.go
backend/controller/scheduledtask/scheduledtask_test.go
backend/controller/state/controller.go
common/reflect/reflect.go
common/reflect/reflect_test.go

Closes https://github.com/block/ftl/issues/3945

fix: nil map deepcopy fix

---

backend/controller/controller.go
backend/controller/state/eventextractor.go
backend/controller/state/eventextractor_test.go
internal/channels/itercontext_test.go
internal/iterops/changes.go
internal/iterops/concat.go
internal/iterops/const.go
internal/iterops/contains.go
internal/iterops/dedup.go
internal/iterops/empty.go
internal/iterops/interops_test.go
internal/iterops/map.go
internal/iterops/window.go
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/statemachine/handle.go
internal/statemachine/handle_test.go

Seems that some of the utility functions implemented here are still discussed by Go people: https://github.com/golang/go/issues/66187

chore: window function to be a proper window function, StateIter to return always the current state as the first element

---

.github/workflows/release.yml
jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl
jvm-runtime/kotlin/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl
jvm-runtime/plugin/common/jvmcommon.go

fix: JVM release

---

jvm-runtime/plugin/common/jvmcommon.go

fix: send a build response when context changes

---

backend/runner/pubsub/testdata/java/publisher/src/main/java/xyz/block/ftl/java/test/publisher/Publisher.java
backend/runner/pubsub/testdata/kotlin/publisher/src/main/kotlin/xyz/block/ftl/java/test/publisher/Publisher.kt
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/SinglePartitionMapper.java

closes https://github.com/block/ftl/issues/4002

feat: add single partition mapper to jvm

---

jvm-runtime/plugin/common/jvmcommon.go

fix: go.mod in JVM scaffold

---

docs/content/docs/reference/pubsub.md

closes https://github.com/block/ftl/issues/4004 https://github.com/block/ftl/issues/4003

chore: fix pubsub sample code

---

jvm-runtime/plugin/common/jvmcommon.go
version.go

fix: generate JVM POMs with correct version

---

common/errors/errors.go
internal/buildengine/build.go

fix: errtrace issues with unwrapping errors

---

internal/buildengine/engine.go

Automatic rebuilds now trigger updates the generated stubs.
- Run `ftl dev` with a go module
- Wait for stubs to be generated
- Create a new exported verb in the go module and save
- Go language plugin will notify the build engine of an auto build success
- Stubs will not be updated, other modules can not use the new verb's client

fix: generate stubs after automatic rebuilds

---

internal/buildengine/engine.go

The build engine was not synchronising the list of stubbed modules correctly if a new build was triggered (such as by a module being added, or a dependency changing).
- `ftl dev examples/go`
- Wait for all modules to build
- Look at any module's `go.work` file, it'll contain each other module's stub path
- Move the `echo` module from `examples/go` to somewhere else
- FTL dev will remove the module
- Move the `echo` module back to its original location
- Look at any `go.work` file now. It'll only contain the stub paths for `builtin` and `echo`

fix: modifying modules should not break stub list

---

docs/content/docs/getting-started/quick-start/index.md
jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl
jvm-runtime/jvm_hot_reload_test.go
jvm-runtime/kotlin/scaffolding/{{ .Name | camel | lower }}/pom.xml.tmpl
jvm-runtime/plugin/common/jvmcommon.go

fix: better default group

---

frontend/intellij/build.gradle.kts
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRunnerConnection.java

fix: reconnect to runner on failure

---

backend/controller/state/statemachine.go
internal/eventstream/eventstream.go

fixes https://github.com/block/ftl/issues/3919
Should fix some edge cases. I experienced a crash yesterday based on this I think.

fix: fix race conditions in event stream and controller state

---

common/errors/errors.go
internal/authn/authn.go
internal/buildengine/build.go

Errors were not being unwrapper properly

fix: proper errtrace fix

---

internal/buildengine/updates.go

fixes https://github.com/block/ftl/issues/4065

fix: default to error level rather than unspecified

---

backend/controller/controller.go
internal/timelineclient/events_deployment.go

fixes https://github.com/block/ftl/issues/4063

fix: bring back language on DeploymentCreated events

---

examples/go/echo/types.ftl.go
frontend/console/src/components/ResizablePanels.tsx
frontend/console/src/features/modules/ModulePanel.tsx
frontend/console/src/features/modules/ModulesPage.tsx
frontend/console/src/features/modules/schema/Schema.tsx

fix: schema popup window clipping

---

frontend/console/src/features/modules/decls/verb/VerbPage.tsx
frontend/console/src/features/modules/decls/verb/VerbRequestForm.tsx
frontend/console/src/features/modules/decls/verb/verb.utils.ts
frontend/console/src/features/timeline/details/TimelineCallDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx

fix: various bugs with verb form body text

---

frontend/console/src/features/modules/decls/verb/VerbPage.tsx
frontend/console/src/features/modules/decls/verb/VerbRequestForm.tsx
frontend/console/src/features/modules/decls/verb/verb.utils.ts
frontend/console/src/features/timeline/details/TimelineCallDetails.tsx
frontend/console/src/features/traces/TraceGraph.tsx

This reverts commit 4e9d331f5fa2c786ceef45f2c029198f5e79a2d7.
Due to this issue: https://github.com/block/ftl/issues/4081

revert: "fix: various bugs with verb form body text (#4078)"

---

cmd/go2proto/testdata/go2proto.to.go
cmd/go2proto/toprototmpl.go
common/schema/go2proto.to.go

refactor(go2proto): replace use of protoSlicef with sliceMap

---

frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/timeline/filters/TimelineFilterPanel.tsx

Fixes #3999
https://github.com/user-attachments/assets/5c59f356-73bf-41bc-bf75-b22bcd0473ae

feat: add select "only" and "view" schema buttons

---

frontend/console/src/features/graph/GraphPage.tsx
frontend/console/src/features/graph/GraphPane.tsx
frontend/console/src/features/graph/ModulePanels.tsx
frontend/console/src/features/graph/RightPanelHeader.tsx
frontend/console/src/features/graph/graph-styles.ts
frontend/console/src/features/modules/ModulePanel.tsx
frontend/console/src/features/modules/decls/DeclDefaultPanels.tsx
frontend/console/src/features/modules/decls/config/ConfigPanel.tsx
frontend/console/src/features/modules/decls/config/ConfigRightPanels.tsx
frontend/console/src/features/modules/decls/data/DataPanel.tsx
frontend/console/src/features/modules/decls/data/DataRightPanels.tsx
frontend/console/src/features/modules/decls/database/DatabasePanel.tsx
frontend/console/src/features/modules/decls/database/DatabaseRightPanels.tsx
frontend/console/src/features/modules/decls/enum/EnumPanel.tsx
frontend/console/src/features/modules/decls/enum/EnumRightPanels.tsx
frontend/console/src/features/modules/decls/secret/SecretPanel.tsx
frontend/console/src/features/modules/decls/secret/SecretRightPanels.tsx
frontend/console/src/features/modules/decls/topic/TopicPanel.tsx
frontend/console/src/features/modules/decls/topic/TopicRightPanels.tsx
frontend/console/src/features/modules/decls/typealias/TypeAliasPanel.tsx
frontend/console/src/features/modules/decls/typealias/TypeAliasRightPanels.tsx
frontend/console/src/features/modules/decls/verb/VerbPage.tsx
frontend/console/src/features/modules/decls/verb/VerbRightPanel.tsx
frontend/console/src/features/modules/schema/Schema.tsx

fix: some data types did not show their name in schemas

---

jvm-runtime/java/scaffolding/{{ .Name | camel | lower }}/src/main/java/{{ .PackageDir }}/{{ .Name | camel }}.java
jvm-runtime/kotlin/scaffolding/{{ .Name | camel | lower }}/src/main/kotlin/{{ .PackageDir }}/{{ .Name | camel }}.kt

This makes IDE snippets work out of the box

fix: use star imports

---

common/schema/go2proto.to.go
jvm-runtime/ftl-runtime/common/deployment/pom.xml
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/jvm_hot_reload_test.go

These make too much log noise when they are included but not used

fix: remove implicit JDBC deps

---

backend/console/console.go

fix: only show deployed modules

---

examples/go/cron/types.ftl.go
examples/go/echo/types.ftl.go
examples/go/http/types.ftl.go
examples/go/mysql/go.mod
examples/go/mysql/queries.ftl.go
examples/go/mysql/types.ftl.go
examples/go/postgres/types.ftl.go
examples/go/pubsub/types.ftl.go
examples/go/time/types.ftl.go

- Add generated module changes.

chore: check in generated module code

---

docs/sass/main.scss
docs/static/js/code-selector.js
docs/static/js/copy-code.js
docs/templates/base.html

feat: add copy button to docs code examples

---

frontend/console/src/components/HoverPopup.tsx
frontend/console/src/features/timeline/TimelineEventList.tsx
frontend/console/src/features/traces/TraceGraph.tsx

- Create new reusuable hover item component

feat: simplify module name in events list

---

docs/sass/main.scss
docs/static/js/code-selector.js
docs/static/js/copy-code.js
docs/templates/base.html

chore: add copy button to docs code samples

---

internal/raft/cluster.go
internal/raft/cluster_test.go

After these changes, running the raft tests 3 * 50 times succeeded locally

test: raft test stability

---

backend/ingress/testdata/java/httpingress/src/main/java/xyz/block/ftl/java/test/http/TestHTTP.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HTTPProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/SubscriptionProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/VerbProcessor.java

fix: record metadata correctly for HTTP methods

---

common/plugin/serve.go
internal/terminal/interactive.go

fix: Java stays running if FTL killed

---

backend/ingress/handler.go
backend/ingress/handler_test.go
backend/ingress/service.go

fix: deployment key was missing in ingress events

---

backend/runner/runner.go

fix: check if process exited

---

internal/buildengine/engine.go

fixes https://github.com/block/ftl/issues/4138
Logic to detect when the engine became idle did not check all states:
- modules that were queued to start building
- there can be gaps between when a build completes and when deployment starts)
Also cleans up state storage by combining all modules states into a single map.

fix: engine idle logic checks all states

---

frontend/console/src/features/graph/GraphPage.tsx
frontend/console/src/features/graph/graph-utils.ts
frontend/console/src/features/modules/ModuleGraph.tsx
frontend/console/src/features/modules/ModulePanel.tsx

fix: module page now shows graph view

---

internal/sqlc/sqlc_test.go

fix: flakiness in sqlc test

---

backend/controller/leases/clientleaser.go
backend/controller/scheduledtask/scheduledtask_test.go
backend/provisioner/scaling/localscaling/local_scaling.go
backend/runner/pubsub/consumer.go
backend/schemaservice/schemaservice.go
cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go
cmd/ftl/cmd_dev.go
cmd/ftl/main.go
common/plugin/serve.go
go-runtime/goplugin/service.go
internal/buildengine/engine.go
internal/buildengine/engine_test.go
internal/buildengine/languageplugin/plugin.go
internal/deploymentcontext/module_context.go
internal/pgproxy/pgproxy.go
internal/pgproxy/pgproxy_test.go
internal/raft/cluster.go
jvm-runtime/plugin/common/jvmcommon.go

Allows other code to detect if errors were due to context cancellation

fix: wrap context cancelation causes

---

go-runtime/schema/schema_integration_test.go
go-runtime/schema/testdata/failing/failing.go
go-runtime/schema/valueenumvariant/analyzer.go

fixes https://github.com/block/ftl/issues/3964

fix: validate enum value case in go

---

cmd/ftl/cmd_build.go
cmd/ftl/cmd_deploy.go

fixes https://github.com/block/ftl/issues/4214

fix: add warning if build or deploy command finds no modules

---

internal/buildengine/engine.go

fixes https://github.com/block/ftl/issues/4213

fix: silence context cancelled error on engine shutdown

---

internal/terminal/status.go

fixes https://github.com/block/ftl/issues/4210
fixes https://github.com/block/ftl/issues/4200
fixes https://github.com/block/ftl/issues/4212

fix: terminal deadlock was preventing shutdown

---

go-runtime/compile/build.go

fix: remove queries.ftl.go if no queries

---

frontend/console/src/features/modules/ModulesTree.tsx

- I keep forgetting it's toggled on and I wonder why I don't see things :)

fix: make unexported icon red when enabled

---

frontend/console/src/features/graph/DeclNode.tsx
frontend/console/src/features/modules/decls/verb/VerbPage.tsx
frontend/console/src/features/modules/module.utils.ts
frontend/console/src/features/timeline/TimelineIcon.tsx
frontend/console/src/features/timeline/filters/TimelineFilterPanel.tsx

fix: new icons for pubsub in console

---

frontend/console/src/shared/components/RightPanelAttribute.tsx

chore: only show scrollbar when needed

---

frontend/console/e2e/helpers.ts

- This should make the filling of the request form more reliable and reduce flakiness

fix: e2e tests could have correct input

---

backend/provisioner/scaling/testdata/go/naughty/naughty.go

Permission denied seems to be manifesting differently

fix: kube tests

---

backend/cron/service_test.go
internal/buildengine/engine.go

feat: Engine deploy routine

---

cmd/ftl/cmd_schema_get.go

fix: schema get hangs

---

backend/schemaservice/changesetstate_test.go
backend/schemaservice/schemaservice.go
backend/schemaservice/state.go
cmd/ftl/cmd_serve.go
internal/raft/cluster.go
internal/raft/cluster_test.go

chore: wrap events to a marshallable wrapper

---

internal/buildengine/deploy.go

In theory the engine could create a changeset and then start pulling schema, but the changeset could complete inbetween those calls.

fix: avoid race between creating changeset and listening for updates

---

charts/ftl/values.yaml

- No ingress service on controller
- No provisioner service
- Controller listens on port 8892
- Schema adds a service

fix: chart fixes

---

examples/go/echo/types.ftl.go
internal/raft/cluster.go

fix: stop iteration on context cancellation

---

internal/raft/cluster_test.go

Ran this 50 times without issues, so it might be stable now.

test: re-enable Raft join test

---

backend/provisioner/registry.go
backend/provisioner/service.go
backend/schemaservice/schemaservice.go
cmd/ftl-http-ingress/main.go
cmd/ftl-provisioner/main.go
cmd/ftl/cmd_serve.go
internal/schema/schemaeventsource/schemaeventsource.go

This is a subset of the changes in https://github.com/block/ftl/pull/4367 to attempt to break it up into smaller pieces.

chore: improvements to allow specifying working directly

---

backend/schemaservice/events.go
backend/schemaservice/schemaservice.go
backend/schemaservice/state.go
common/schema/raftevents.go
internal/raft/cluster.go
internal/raft/cluster_test.go
internal/raft/statemachine.go

- Checks that the event is valid against latest known state
- If still, when applying the event, it is invalid, returns a generic error to the user.

feat(ftl-schema): pre-commit validation

---

backend/runner/runner.go

fix: panic when hard killing plugins

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HotReloadHandler.java
jvm-runtime/plugin/common/jvmcommon.go

fix: JVM error reporting

---

jvm-runtime/plugin/common/jvmcommon.go

fix: handle dev mode process exit

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HotReloadHandler.java
jvm-runtime/plugin/common/jvmcommon.go

fix: JVM should only reload on changes

---

cmd/ftl/cmd_dev.go

Fixes https://github.com/block/ftl/issues/4415

fix: context cancellation errors in ftl dev

---

cmd/ftl/cmd_schema_get.go

Fixes https://github.com/block/ftl/issues/4411

fix: schema get --json

---

cmd/ftl/main.go
internal/terminal/interactive.go
internal/terminal/status.go

fix: display errors on exit

---

internal/raft/cluster.go

This can happen if there is a leader election going when we are querying the state.

fix: retry dragonboat query if the shard is not ready

---

backend/provisioner/deployment.go

This should be a streaming call eventually

fix: decrease provisioner backoff max

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/FTLDotNames.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/TopicsProcessor.java

fix: enforce one partition for single partition mapper

---

backend/schemaservice/schemaservice.go
common/schema/raftevents.go
internal/buildengine/deploy.go
internal/key/keys.go
internal/schema/schemaeventsource/schemaeventsource.go

fix: panic on module removal

---

internal/lsp/lsp.go

fix: LSP panic

---

backend/provisioner/inmem_provisioner.go
backend/provisioner/registry.go
backend/provisioner/scaling/kube_scaling_integration_test.go
cmd/ftl/cmd_kill.go
common/schema/module.go
common/schema/provisioned.go

fix: remove runners on kill

---

cmd/ftl/cmd_deploy.go
internal/buildengine/engine.go

fixes: #4451
This needs more work.

fix: use changeset per module in dev mode

---

examples/go/echo/types.ftl.go
internal/buildengine/engine.go

Otherwise echo might attempt to deploy before time is ready

fix: also wait for module dependencies

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/VerbProcessor.java

This makes user error clearer
fixes #4006

fix: don't allow double declaration of verbs

---

cmd/ftl/cmd_new.go

fix: remove hermit logic from ftl new

---

cmd/ftl/cmd_dev.go
cmd/ftl/cmd_new.go

fixes https://github.com/block/ftl/issues/4470
- FTL dev exposes the current directories being watched for modules to child processes.
- `ftl new` now fails if it is called within `ftl dev` and the new module path is outside the expected directories for modules.
- `--force` allows you to skip this check
- The error explains where modules are expected to be. This also helps goose correct itself.
- This affects running `ftl new` manually or via goose in the interactive console.

fix: fail new module creation outside of dev module dirs by default

---

cmd/ftl/cmd_new.go

Gitroot is still used for staging files with git.

fix: default ftl new path to cwd

---

go-runtime/compile/build.go

fix: don't panic if type can't be resolved during go type gen

---

internal/buildengine/updates.go

The LSP and Goose would wait forever for the build engine update stream to begin. The first grpc message on the stream would contain the headers, so callers would not progress past the initial call until the first event was sent.

fix: build engine event stream would hang if there are no modules

---

internal/buildengine/engine.go

- Start `ftl dev` with no modules
- Wait a minute
- run `ftl new`
- Logs will say initial deploy took 1min + build and deploy

fix: adding modules to an empty engine shouldnt show long initial build time

---

go-runtime/compile/build.go
go-runtime/goplugin/service.go

This reverts commit 3c9fe653d4b9bf7de15f7133014fadc9267068fb.
The PR wasnt passing a integration test but auto merge let it through anyway...

revert: "fix: include go compiler errors if ftl can’t scaffold (#4528)"

---

cmd/ftl/cmd_dump_help.go
cmd/ftl/main.go

This is used by goose to learn about all the commands we want to expose to it (and hide the ones we dont want it to learn about).

chore: new hidden command that dumps all help text with filters

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/StaticConfigSource.java
jvm-runtime/plugin/common/error_detector.go

fix: JVM logging should match go

---

cmd/ftl/main.go

fix: install signal handler earlier

---

jvm-runtime/plugin/common/jvmcommon.go

fix: properly report start errors

---

backend/runner/runner.go

fix: make sure proxy is up before starting runner

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HotReloadHandler.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/PositionUtils.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/StaticConfigSource.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java

fix: disable live reload through config

---

go-runtime/schema/verb/analyzer.go

fix: improve error message

---

cmd/ftl/main.go

fix: pause after sending SIGINT

---

cmd/ftl/cmd_serve.go

This means 'ftl serve --stop' will always work.

fix: always write PID file

---

go-runtime/compile/build.go
go-runtime/compile/build_test.go
go-runtime/compile/stubs.go

fix: build loop

---

frontend/console/src/features/modules/hooks/use-stream-modules.ts

Fixes #4581
We don't need a merging strategy here since we get all the modules in the stream

fix(console): detect when modules are removed and update

---

internal/lsp/markdown/completion/java/verb.md
internal/lsp/markdown/completion/kotlin/verb.md

fix(lsp): Make the default verb name lowercase

---

frontend/console/src/features/traces/TraceDetailItem.tsx
frontend/console/src/features/traces/TraceDetails.tsx
frontend/console/src/features/traces/TraceGraphRuler.tsx
frontend/console/src/features/traces/TraceRulerItem.tsx

Fixes #4597
- Reduce number of ticks to 3 if the component width is small

fix: resizing of trace details

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/PositionUtils.java

This is better than throwing an exception

fix: report JVM failures as schema errors

---

README.md
go-runtime/scaffolding/{{ .Name | camel | lower }}/{{ .Name | camel | lower }}.go.tmpl

fix: make go scaffolding consistent

---

jvm-runtime/plugin/common/jvmcommon.go

Reverts block/ftl#4625
This needs more thought, as we miss sending the build complete event if nothing has changed.

revert: "fix: send build started event earlier"

---

cmd/ftl/cmd_mysql.go
cmd/ftl/cmd_postgres.go
cmd/ftl/cmd_sql_migration_new.go
cmd/ftl/cmd_sql_new.go
cmd/ftl/goose_instructions_first_prompt.txt
cmd/ftl/main.go
docs/docs/reference/databases.md
internal/moduleconfig/moduleconfig.go
jvm-runtime/jvm_hot_reload_test.go

feat: add sql CLI cmds; new and new migration

---

cmd/ftl/main.go

TODO: this is a bit of a hack, we should clean it up

fix: binding issue

---

cmd/ftl/main.go

fix: use correct binding param

---

cmd/ftl/cmd_sql_new.go
internal/sql/sql.go

fix: new sql command

---

frontend/console/src/features/graph/GraphPane.tsx
frontend/console/src/features/graph/graph-utils.ts

Fixes #4612
https://github.com/user-attachments/assets/f60aae9f-7924-4572-9db3-0c539e5ef891

fix: swap edges for topic->subscriber graph nodes

---

cmd/ftl/cmd_await_summary.go

This should help it find code to alter.
Includes some TODOs and hacks, but wanted to get this in for the demo to help goose.

fix: goose should get path to each decl in schema

---

go-runtime/compile/build.go

I noticed that after I got an error about `go work` versions when creating a new module, I could not resolve the error without manually deleting the `.ftl` folder below the failing module.
I'm guessing we should just clean this folder before we build to make sure there's nothing stale left over.

fix: make sure we clean the module/.ftl folder before builds

---

internal/dev/db.go

fixes https://github.com/block/ftl/issues/4695

fix: speed up db provisioning by caching db compose up result

---

go-runtime/goplugin/service.go
internal/buildengine/engine.go

chore(logs): reduce log levels for building... and file changes

---

frontend/console/src/features/graph/ModulePanels.tsx
frontend/console/src/features/graph/graph-utils.ts

fix: remove duplicate schema panel

---

backend/cron/service.go

Fixes #4708
These changes should ensure that the CronScheduled event is only fired when:
1. A new job is added to the system
2. A job's schedule changes
3. A job executes and gets rescheduled

fix: cron scheduled events

---

backend/cron/service.go
backend/provisioner/service.go
common/plugin/spawn.go
go-runtime/goplugin/service.go
internal/log/logger.go

- Fix scope
- Read all messages from plugins

fix: logging replay issues

---

backend/schemaservice/schemaservice.go

fix: include changesets in GetSchema

---

internal/buildengine/deploy.go

fixes https://github.com/block/ftl/issues/4724

fix: log deploy failures

---

.golangci.yml
cmd/ftl/cmd_schema.go
cmd/ftl/cmd_schema_ebnf.go
common/schema/parser.go

```
~/dev/ftl $ ftl schema ebnf
Schema = Module* .
Module = <comment>* "builtin"? "module" <ident> "{" Metadata* Decl* "}" .
Metadata = MetadataCalls | MetadataConfig | MetadataIngress | MetadataCronJob | MetadataDatabases | MetadataAlias | MetadataRetry | MetadataSecrets | MetadataSubscriber | MetadataTypeMap | MetadataEncoding | MetadataPublisher | MetadataSQLMigration | MetadataArtefact | MetadataPartitions | MetadataSQLQuery | MetadataSQLColumn .
MetadataCalls = "+" "calls" Ref ("," Ref)* .
Ref = (<ident> ".")? <ident> ("<" Type ("," Type)* ">")? .
MetadataConfig = "+" "config" Ref ("," Ref)* .
MetadataIngress = "+" "ingress" "http"? ("GET" | "POST" | "PUT" | "DELETE") ("/" IngressPathComponent)+ .
IngressPathComponent = IngressPathLiteral | IngressPathParameter .
IngressPathLiteral = …
```

feat: add "ftl schema ebnf"

---

frontend/console/src/features/graph/DeclNode.tsx
frontend/console/src/features/graph/graph-utils.ts
frontend/console/src/features/modules/decls/DeclGraphPane.tsx

fix: show decls as unexported in graphview

---

.vscode/settings.json
backend/ingress/openapi.go
backend/ingress/openapi_test.go

Also added a test case for string body request/response.

fix: Cursor just decided to swallow all errors, so I've fixed that

---

internal/buildengine/engine.go

- No need to add module name to build error log if we are also adding it to the scope
- Initial build error summaries looked weird if there were more than one error as the first module was the same line as the summary text but subsequent errors were on new lines

fix: clean up build error logs

---

internal/watch/watch.go

Lock was not released if the loop did a `continue` (such as if there was a current compilation occuring).
Moved the locked part of the loop into a function so we can use `defer` to release the lock

fix: edge cases caused file changes to stop being detected

---

cmd/ftl/cmd_dev.go

When working with multiple environments, I set `FTL_ENDPOINT` to point to them. 
If I forget to unset it, it breaks `ftl dev` for me.
This makes `ftl dev` ignore `FTL_ENDPOINT` when running the dev environment.

fix: use FTL_DEV_ENDPOINT instead of FTL_ENDPOINT when using ftl dev

---

internal/buildengine/engine.go

When a module changes dependencies it used to appear as an error log. Now it just marks the module as waiting to build before scheduling the rebuild.

fix: dependency update doesn’t count as build failure

---

go-runtime/compile/build.go
go-runtime/compile/build_test.go
go-runtime/schema/schema_integration_test.go

closes https://github.com/block/ftl/issues/4633

test: add unit test for catching cyclic verbs

---

backend/provisioner/inmem_provisioner.go

fix: provisioner hangs if it has nothing to provision

---

backend/provisioner/dev_provisioner.go
backend/provisioner/plugin.go
cmd/ftl-provisioner-sandbox/provisioner.go
cmd/ftl-provisioner-sandbox/status.go
internal/provisioner/executor/pubsub.go
internal/provisioner/runner.go
internal/provisioner/state/aws.go
internal/provisioner/state/input.go
internal/provisioner/state/output.go

This uses plaintext for MSK connections. TLS support will be a follow-up

feat: PubSub in ftl-aws using a shared MSK cluster

---

jvm-runtime/ftl-runtime/common/deployment/pom.xml
jvm-runtime/ftl-runtime/common/runtime/pom.xml
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/config/FTLConfigSource.java
jvm-runtime/plugin/common/jvm_logging.go
jvm-runtime/plugin/common/jvmcommon.go

fix: JVM logging

---

internal/terminal/interactive.go
internal/terminal/status.go

fix: interactive console commands that span multiple lines

---

backend/provisioner/service.go

Added info-level logs when:
- Starting a changeset deployment
- Successfully completing a changeset deployment
- Completing a changeset rollback
These logs will appear in the timeline and provide clear visibility into the major lifecycle events of changesets.

feat: add info-level logging for changeset lifecycle events

---

cmd/ftl/cmd_mcp.go
cmd/ftl/cmd_mcp_test.go
cmd/ftl/goose_instructions_first_prompt.txt
internal/mcp/cli.go
internal/mcp/timeline.go

Goose can now look up events using a (simplified) version of the timeline.

feat: give MCP access to timeline

---

go-runtime/compile/build.go
go-runtime/compile/build_test.go

closes https://github.com/block/ftl/issues/4369
- All paths prefixed with `../../../` are cut out (previously only the first path in each error was)
- Better whitespace handling
- Added unit test

fix: parse go compile errors better

---

common/schema/data.go
common/schema/schema_test.go

This is consistent with eg. module metadata.

fix: move "data" metadata to just after the {

---

internal/buildengine/build.go

fix: log git errors at debug

---

internal/config/file.go

Closes https://github.com/block/ftl/issues/4871

fix: flaky test by always sorting List() values in providers

---

backend/cron/state.go
backend/schemaservice/state.go
backend/timeline/service.go
backend/timeline/service_test.go
internal/channels/broadcast_test.go
internal/channels/notify.go
internal/statemachine/handle_test.go

This is a preparation for `ftl logs` command

perf: no busy polling in timeline streaming

---

backend/cron/service.go
backend/cron/service_test.go
charts/ftl/templates/cron-deployment.yaml
cmd/ftl/cmd_serve.go

fix: remove cron raft config from ftl dev

---

cmd/ftl/cmd_interactive.go
cmd/ftl/main.go

fix: remove build and deploy commands in dev cli

---

common/schema/metadatasqlcolumn.go
common/schema/schema_test.go

chore: cleaner column names in SQL column definitions

---

go-runtime/compile/build.go

closes https://github.com/block/ftl/issues/4901

fix: check for changes in queries.ftl.go before using optimistic compilation

---

internal/buildengine/build.go
internal/buildengine/engine.go
internal/buildengine/module.go

fixes https://github.com/block/ftl/issues/4919

fix: sql errors persist and overrule auto rebuilds

---

jvm-runtime/jvm_hot_reload_test.go
jvm-runtime/plugin/common/jvmcommon.go

fix: SQL errors cause dev mode hang

---

internal/terminal/interactive.go

Users type messages to goose conversationally like this:
`goose there seem to be errors. I'd like to know why`
Or use quotation marks which should not be lost
`goose please make the verb log out "some example text"`
We now take everything after goose as a single argument we pass to goose.

fix: messages to goose do not get parsed as CLI args

---

cmd/ftl/cmd_goose.go

Goose would keep making up functions/types in FTL, like `ftl.UUID`. We now pass in the go runtime interfaces to goose, failing gracefully if it does not succeed.

fix: teach goose the ftl runtime interface

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/JVMCodeGenerator.java
jvm-runtime/ftl-runtime/common/hotreload/src/main/java/xyz/block/ftl/hotreload/CodeGenNotification.java

Sometimes the code gen for SQL verbs would be missed

fix: flakey JVM test

---

backend/provisioner/service.go
charts/ftl-k3d/Chart.lock
charts/ftl-k3d/templates/ingress.yaml
charts/ftl-k3d/templates/redpanda.yaml
charts/ftl-k3d/values.yaml
charts/ftl/templates/provisioner-deployment.yaml
charts/ftl/values.yaml
deployment/Justfile
deployment/values-release.yaml

This will allow us to test both the sandbox provisioner and pubsub in kube

chore: redpanda k3d support

---

examples/go/mysql/types.ftl.go
frontend/console/src/features/graph/graph-utils.ts
frontend/console/src/features/modules/ModuleGraph.tsx

fix: bad data links and remove enums

---

go-runtime/compile/build.go

fix: generated imports

---

internal/container/container.go

fix: CLI spacing

---

internal/mcp/readwrite.go

Problem:
- Goose can update db migrations or queries by changing SQL files
- Goose then tries to update code to use the generated queries but consistently makes mistakes because:
- It can't reliably guess struct names or field names
- It can't reliably guess what each field type will be (eg Decimal is mapped to float64 in go)
Solution:
- This PR maps files being written to files they affect.
- This allows the MCP to return the generated file content when writing the original files. This greatly improves FTL/Goose performance when writing DB code.
- It is hardcoded for Go + SQL files at the moment.
- To make this generic we probably want to do this first: https://github.com/block/ftl/issues/4793
- We wouldn't want to load up a whole plugin just to check if a file path affects other files.

feat: MCP auto-reads queries.ftl.go after writing sql files

---

internal/log/plain.go

fix: color logs with multiple lines together

---

internal/terminal/interactive.go
internal/terminal/status.go

fix: update terminal status section styles

---

backend/cron/service.go

chore: change log level for verbose logs

---

backend/controller/sql/database_integration_test.go
backend/controller/sql/testdata/go/database/database.go
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/Database.java
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/InsertRequest.java
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/TransactionRequest.java
backend/controller/sql/testdata/java/database/src/main/java/xyz/block/ftl/java/test/database/TransactionResponse.java
backend/controller/sql/testdata/java/database/src/main/resources/db/postgres/testdb/queries/queries.sql
backend/controller/sql/testdata/kotlin/database/src/main/kotlin/ftl/database/Database.kt
backend/controller/sql/testdata/kotlin/database/src/main/resources/db/postgres/testdb/queries/queries.sql
common/schema/validate.go
common/schema/verb.go
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/FTLDotNames.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HTTPProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/SubscriptionProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/VerbProcessor.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/Transactional.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/CurrentTransaction.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRecorder.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRunnerConnection.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLRunnerConnectionImpl.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/MockRunnerConnection.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/SQLQueryVerbInvoker.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/VerbClientHelper.java
jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/VerbRegistry.java

fixes #3970
fixes #3967
fixes #4970

feat: support transactions in JVM

---

.github/workflows/createnewrelease.yml

chore: make release label consistent with other labels

---

jvm-runtime/plugin/common/service.go

We don't really want a timeout here, 100m is basically long enough that we will never hit it

fix: JVM startup timeout

---

internal/log/debug.go

Uses the correct file extension for its actual contents.

fix: logs use jsonl extension

---

go-runtime/goplugin/commands.go
go-runtime/goplugin/commands_test.go

fix: go version for new go modules

---

jvm-runtime/ftl-runtime/common/runtime/src/main/java/xyz/block/ftl/runtime/FTLController.java

This happens pretty regularly during frequent hot reloads
fixes: #5070

fix: reduce log level

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java

fix: add pos for JVM metadata

---

backend/goose/goose.go
cmd/ftl/cmd_dev.go
cmd/ftl/cmd_goose.go

chore: reset goose context on new dev runs

---

backend/goose/goose.go
frontend/console/src/features/ai-agent/AIAgent.tsx
internal/mcp/readwrite.go
package.json
pnpm-lock.yaml

- filter out some more unwanted lines
- support markdown formatting
- improve formatting for code blocks
https://github.com/user-attachments/assets/f532f748-3f5b-4faa-8719-8dd95cd23091

chore: improve formatting in goose panel

---

.github/workflows/ci.yml

Reverts block/ftl#5129
Reverting for now, as the blockoss user seems to be rate limited as well.

revert: "chore: login to docker also in integration tests"

---

backend/schemaservice/changesetstate_test.go
backend/schemaservice/eventextractor_test.go
backend/schemaservice/events.go
backend/schemaservice/state.go
internal/iterops/coiunt.go
internal/iterops/filter.go
internal/iterops/len.go

Writes realm information to schema state and validates that there is at most one internal realm at any given time.
Deleting realms is not supported yet.

feat(Juho): realms in state

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/HTTPProcessor.java
jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java

fix: validate HTTP methods don't have other annotations

---

frontend/console/src/features/timeline/TimelineEventList.tsx

fix: module name in console now that we have realms

---

frontend/console/src/features/ai-agent/AIAgent.tsx
frontend/console/tailwind.config.js

Ignore the errors at the end of the video, just doing some testing :)
https://github.com/user-attachments/assets/c2dedd90-2b94-4b1e-80fe-08285625fcde

feat: add goose animation when busy

---

cmd/ftl/goose_instructions.txt

This is now handled for goose by FTL MCP

fix: simplify db instructions for goose

---

backend/schemaservice/schemaservice.go
backend/schemaservice/state.go
common/schema/schema.go
internal/key/deployment_key.go
internal/schema/schemaeventsource/schemaeventsource.go
jvm-runtime/plugin/common/service.go

Non functional change, we are still writing the "default" realm

chore: fetch the realm name from server

---

frontend/console/src/shared/layout/navigation/Navigation.tsx
frontend/console/src/shared/layout/navigation/SearchInput.tsx

fix: nav bar layouts and add FTL name

---

frontend/console/src/features/graph/GraphPage.tsx

chore: add flag to show/hide timeline on graph page

---

cmd/ftl/cmd_goose.go

Fixes #5056
With `ftl goose`:
```
❯ ftl goose chat "what is the schema?"
ftl: error: ftl dev is not running. Please start ftl dev first with 'ftl dev' before using Goose
```
With `ftl` then, `goose`:
```
❯ ftl
❯ goose chat "what modules are running?"
👤 chat "what modules are running?"
ftl dev is not running. Please start ftl dev first with 'ftl dev' before using Goose
❯ 
```

fix: goose error message when ftl dev is not active

---

backend/runner/pubsub/integration_test.go

Failed here: https://github.com/block/ftl/actions/runs/14584252814/job/40906864124?pr=5180

chore: increase time allowed for consumer to leave group

---

jvm-runtime/ftl-runtime/kotlin/build-parent/pom.xml
jvm-runtime/plugin/common/commands.go
jvm-runtime/plugin/common/java_plugin_test.go

The Java build does not have this profile so this fixes a warning

fix: activate profile via property

---

examples/go/echo/types.ftl.go
internal/buildengine/engine.go

revert: "fix: reload and rebuild modules when configuration changes"

---

internal/buildengine/engine.go

Fixes #5196
```
❯ ftl dev
info:http-ingress: HTTP ingress server listening on: http://127.0.0.1:8891
info:console: Building console...
info:console: Web console available at: http://127.0.0.1:8892
info: Controller started in 0.05s
info: FTL startup command ⚡️
info: Modules waiting to build: echo, types, pubsub, mysql, cron, postgres, http
error: Initial build and deploy failed: module "echo" requires dependency "time": module "time" not found. does the module exist and is the ftl.toml file correct?
◌ cron       ◌ echo       ◌ http       ◌ mysql      ◌ postgres   ◌ pubsub     ◌ types
```

fix: improve error message to make resolving the issue more obvious

---

cmd/ftl/cmd_deploy.go

@stuartwdouglas does this fix #5229? Or is there more to it?

fix: sync schema before deploying

---

frontend/console/src/features/modules/decls/topic/TopicRightPanels.tsx

fix: topic event link in console

---

backend/provisioner/registry.go
backend/provisioner/runner_scaling_provisioner.go
cmd/ftl-provisioner/main.go
cmd/ftl/cmd_serve.go

This can mess with JVM dev mode

fix: always create local runners

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/Circular1.kt
jvm-runtime/testdata/kotlin/kotlinmodule/src/main/kotlin/xyz/block/ftl/test/Circular2.kt

fix: Handle circular references

---

frontend/console/src/features/modules/ModuleGraph.tsx

fix: Parent node echo not found.

---

jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java

fix: preserve field order

---

jvm-runtime/ftl-runtime/kotlin/deployment/src/main/java/xyz/block/ftl/kotlin/deployment/KotlinCodeGenerator.java
jvm-runtime/plugin/common/integration_test.go

feat: default to null for nullable fields

---

frontend/console/src/features/modules/decls/EditDeclButton.tsx
internal/editor/editor.go

`ftl edit echo.EchoRequest github`

feat: add github option to ftl edit command and console

---

internal/editor/editor.go

Will still need to update the editor and friends to use the git metadata in the schema.
See #5312

fix: opening decl refs in github

---

backend/console/console.go
backend/schemaservice/schemaservice.go
common/schema/schema.go
common/schema/schema_test.go
internal/schema/schemaeventsource/schemaeventsource.go
internal/schema/schemaeventsource/schemaeventsource_test.go

chore: deepcopy whole schema every time we add builtin module

---

common/schema/typeresolver.go
common/schema/validate.go
common/schema/verb.go

Moves module validation from Schema to Realm. For now, all Realms are validated independently, this will change once we have inter realm references.

chore: validate realms

---

Justfile
bin/hermit.hcl
internal/zip_relative.go
internal/zip_relative_test.go

fix: revert -fullpath

---

frontend/console/src/features/modules/decls/verb/VerbRequestForm.tsx

fix: make sure we report call errors to the user

---

frontend/console/src/features/modules/ModulesPanel.tsx

fix: empty language field and show additional runtime info

---

backend/console/console.go
backend/protos/xyz/block/ftl/console/v1/console.pb.go
backend/protos/xyz/block/ftl/console/v1/console.proto
cmd/ftl-console/main.go
common/schema/go2proto.to.go
frontend/console/src/features/modules/decls/secret/SecretPanel.tsx
frontend/console/src/protos/xyz/block/ftl/console/v1/console_pb.ts
frontend/console/src/shared/providers/info-provider.tsx
internal/app/cmd_serve.go

Until we have user access controls, also make sure we hide secrets on the console so they are not viewable.
Also hide goose and local editors

fix: add flag for local dev to show/hide on console

---

frontend/console/src/features/modules/decls/verb/VerbFormInput.tsx
frontend/console/src/features/modules/decls/verb/VerbRequestForm.tsx
frontend/console/src/shared/components/Loader.tsx

feat: add a loading spinner when calling ftl verbs

---

.cursor/rules/typescript.mdc
frontend/console/src/features/graph/GraphPage.tsx
frontend/console/src/features/graph/GraphPane.tsx
frontend/console/src/features/graph/RightPanelHeader.tsx
frontend/console/src/features/graph/graph-utils.ts
frontend/console/src/features/modules/ModulePanel.tsx
frontend/console/src/features/modules/decls/DeclDefaultPanels.tsx
frontend/console/src/features/modules/decls/RightPanelHeader.tsx
frontend/console/src/features/modules/decls/config/ConfigPanel.tsx
frontend/console/src/features/modules/decls/database/DatabasePanel.tsx
frontend/console/src/features/modules/decls/secret/SecretPanel.tsx
frontend/console/src/features/modules/decls/topic/TopicPanel.tsx
frontend/console/src/features/modules/decls/verb/VerbPage.tsx
frontend/console/src/features/modules/module.utils.ts
frontend/console/src/shared/components/HoverPopup.tsx
frontend/console/src/shared/providers/routing-provider.tsx

- Add links to go between modules and graph view
- Add url path parameters to graph page to navigate to a specific decl via URL
- Fix hover popup showing outside of the browser window

feat: make console link between modules and graph pages

---

frontend/console/src/features/graph/graph-utils.ts

Updated `kitchen.go` to have this:
```go
//ftl:verb
//ftl:subscribe newOrderTopic from=beginning
func CookPizza(ctx context.Context, pizza Pizza, topic PizzaReadyTopic, another NewOrderTopic) error {
ftl.LoggerFromContext(ctx).Infof("Cooking pizza: %v", pizza)
another.Publish(ctx, pizza)
return errors.WithStack(topic.Publish(ctx, pizza))
}
```
Which results in this graph:

fix: graph to show subscribers that publish back to same topic

---

frontend/console/src/features/graph/graph-utils.ts

Fixes verb to verb references:
Also cleaned up the code/logic for handing subscribers that publish back to the same topic.

fix: refactor and fix graph node edges

---

charts/ftl/templates/_helpers.tpl
charts/ftl/templates/runner.yaml

At some point we will use these to set Xmx etc

chore: add env vars for container memory

---

frontend/console/src/features/graph/GraphPane.tsx

feat: add decl type filter to graph view

---

frontend/console/vite.config.ts

BEFORE:
```
vite v6.2.2 building for production...
✓ 7207 modules transformed.
dist/index.html                                       1.45 kB │ gzip:   0.57 kB
dist/assets/favicon-jjzVXmZJ.ico                     15.41 kB
dist/assets/index-DeGfjByM.css                       77.36 kB │ gzip:  12.77 kB
dist/assets/vendor-fuse-Ch1WBRTM.js                  18.24 kB │ gzip:   6.61 kB
dist/assets/vendor-lodash-BCwzBnj6.js                46.96 kB │ gzip:  17.02 kB
dist/assets/vendor-json-schema-library-DwAStZul.js   95.01 kB │ gzip:  27.34 kB
dist/assets/vendor-yaml-Luz2TmpT.js                 104.82 kB │ gzip:  32.36 kB
dist/assets/vendor-protos-BENQK6j-.js               174.04 kB │ gzip:  28.68 kB
dist/assets/vendor-ui-Dm9Jva_B.js                   202.76 kB │ gzip:  62.92 kB …
```

chore: reduce bundled chunk sizes for console warnings

---

.github/workflows/release.yml
jvm-runtime/ftl-runtime/.maven_settings.xml
jvm-runtime/ftl-runtime/pom.xml

Java publishing will fail until you merge this PR. It should have all the changes you need.

build: Migrate jar publishing to Sonatype Central Publishing

---

frontend/console/src/features/graph/GraphPane.tsx

fix: graph filter dropdown options

---

cmd/ftl/app.go
internal/rpc/rpc.go

This is primarily for use in mTLS environments.

feat: add --client-cert flag for loading client certificate key pair

---

examples/go/mysql/queries.ftl.go
frontend/console/src/features/graph/GraphPane.tsx
frontend/console/src/features/graph/graph-utils.ts
frontend/console/src/features/modules/ModulesTree.tsx
frontend/console/src/features/modules/ModulesTreeHeader.tsx
frontend/console/src/shared/components/Button.tsx

feat: add show/hide exported option to graph view

---

internal/sql/sql.go
internal/sql/sql_test.go

fix: sql queries path to be project root relative

---

backend/ingress/handler.go

Ingress was generating a request key but only using it for the ingress timeline event.
Now it actually uses that key when calling the verb.

fix: ingress passes along request key

---

Justfile

This is spectacularly idiotic, but this now uses `git ls-files` to avoid searching `node_modules`, `.hermit`, etc.
Before:
```
~/dev/ftl $ time find . -type f -name '*_test.go' -print0 | xargs -0 grep -r -l TestConfigImportExport | xargs grep -l '//go:build integration'
./cmd/ftl/integration_test.go
find . -type f -name '*_test.go' -print0  0.34s user 5.03s system 47% cpu 11.298 total
xargs -0 grep -r -l TestConfigImportExport  0.00s user 0.01s system 0% cpu 11.314 total
xargs grep -l '//go:build integration'  0.00s user 0.00s system 0% cpu 11.318 total
```
After:
```
~/dev/ftl $ time git ls-files | grep '_test\.go$' | xargs grep -r -l TestConfigImportExport | xargs grep -l '//go:build integration'
cmd/ftl/integration_test.go
git ls-files  0.00s user 0.00s system 54% cpu 0.016 total
grep …
```

chore: speed up integration tests

---

backend/admin/service.go
backend/provisioner/oci_image_provisioner.go
backend/provisioner/registry.go
backend/provisioner/scaling/localscaling/local_scaling.go
backend/provisioner/service.go
backend/provisioner/sql_migration_provisioner.go
cmd/ftl-provisioner/main.go
cmd/ftl/cmd_buildimage.go
cmd/ftl/cmd_serve.go
internal/download/download.go
internal/oci/artefact_service.go
internal/oci/image_service.go
internal/oci/key_chain.go

Image service uses ArtefactService to pull build files, but is responsible for pushing any images

chore: separate artefact and image services

---

.github/actions/build-cache/action.yml
.github/workflows/ci.yml
.github/workflows/writecache.yml
Justfile
go.mod

- use cache for docs
- also cache Go modules in cmd/*

chore(ci): more CI tweaks

---

.github/workflows/ci.yml
Justfile
frontend/console/playwright.config.ts

chore(ci): only run playwright against chromium-headless

---

backend/provisioner/registry.go

fix: spawn only one provisioner plugin process even if it is used multiple times in the config
